Export data that on screen
betagouv/rdv-solidarites.fr pull request #1064
Opened 2021-01-04 09:37 UTC by yaf

- Lien vers Trello Sentry
- (Description de la fonctionnalité ou du bug)
- (Description du code de la PR)
- checklist avant review: 
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touched inutilement, debug logs qui trainent...).
- [ ] Attendre que les tests soient verts sur la CI

2021-01-05 15:23 UTC, adipasquale reviewed
Je crois que je serais parti dans une autre direction : garder un unique exporteur qui aurait éventuellement pris une option `anonymize_users` (ou pas du tout et toujours retourné les infos usagers). Je pense que ca aurait été un poil plus simple à implémenter et à maintenir et que le résultat aurait convenu aux besoins.

La solution à deux exporteurs permet d'avoir plus de différences, donc pourquoi pas. 

Sur les tests, je pense que ça serait cool qu'on ait (yet another) une discussion, je suis pas fan des tests de méthodes privées (ou qui devraient l'etre). par exemple tu testes `StatRdvExporter.majeur_ou_mineur`. A mon avis c'est un bon exemple : cette méthode devrait ici être privée, parce que personne ne l'appelle de l'extérieur `StatRdvExporter`. Ici il me semble que ca souleve que cette méthode est mal positionnée : elle devrait appartenir à `User` et donc être publique et testée.

Je ne suis pas du tout figé sur ces questions et les tests sont très lisibles ici donc ça me va aussi. Mais je pense qu'il faut qu'on trouve un terrain d'entente pour ne pas se retrouver à ré-écrire dans un sens ou dans l'autre à chaque fois qu'on passe sur le code de l'autre :) (tu as fait le refacto de cet exporter d'un service avec une unique méthode publique vers un module avec plusieurs méthodes statiques publiques dans une PR précédente il me semble).

2021-01-05 15:23 UTC, adipasquale commented on app/service_functions/stat_rdv_exporter.rb
> +    ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor < 18
je pense que cette méthode devrait être dans `User` plutot qu'ici (meme si ce n'est pas cette PR qui l'introduit)

2021-01-05 15:23 UTC, adipasquale commented on app/service_functions/stat_rdv_exporter.rb
> +    ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor < 18
et est-ce que tu ne peux pas simplement faire `birth_date < 18.years.ago` ?

2021-01-05 15:23 UTC, adipasquale commented on app/service_functions/rdv_exporter.rb
> +  def self.lieu(rdv)
pareil je pense que cette méthode aurait plus sa place dans le modèle Rdv (ou un presenter/helper de Rdv). 
Il y a déjà une méthode très proche `address_complete_without_personnal_details` dans le `Rdv::address_concern`, on pourrait ajouter celle la a coté ?

2021-01-05 15:23 UTC, adipasquale commented on app/controllers/admin/organisations/stats_controller.rb
> +      format.xls { send_data(StatRdvExporter.export(policy_scope(Rdv), StringIO.new), filename: "rdvs.xls", type: "application/xls") }
je crois que ce `policy_scope(Rdv)` n'est pas iso avec l'existant : 
- aujourd'hui on filtre sur l'organisation, j'ai un petit doute que ce policy_scope le fasse aussi, il faut peut etre rajouter un where. tu as testé ?
- on fait plein d'includes pour les perfs, ca serait probablement bien de les faire ici aussi

2021-01-06 08:34 UTC, yaf commented on app/service_functions/rdv_exporter.rb
> +    extract_string_from build_excel_workbook_from rdvs
Comme la première option. Je peux ajouter des parenthèses, ça sera plus clair sans doute

2021-01-06 08:35 UTC, yaf commented on app/service_functions/stat_rdv_exporter.rb
> +    ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor < 18
Il y a moyen de simplifier avec ce que tu proposes oui. Pour la mise dans User, effectivement, c'est peut-être mieux.

2021-01-06 12:10 UTC, yaf commented on app/controllers/admin/organisations/stats_controller.rb
> +      format.xls { send_data(StatRdvExporter.export(policy_scope(Rdv), StringIO.new), filename: "rdvs.xls", type: "application/xls") }
En fait, si tu regardes quelques lignes au-dessus, on utilise `policy_scope(Rdv)` pour le reste des statistiques. Je pourrais faire en sorte qu'on utilise la même base. Mais je suis parti du principe que ça fonctionne pour les statistiques et donc que ça serait ok pour l'export.

J'imagine qu'on pourra traiter les perfs dans une autre PR, voir étoffer les tests si nécessaires.

2021-01-06 13:13 UTC, adipasquale commented on app/controllers/admin/organisations/stats_controller.rb
> +      format.xls { send_data(StatRdvExporter.export(policy_scope(Rdv), StringIO.new), filename: "rdvs.xls", type: "application/xls") }
ok en effet `policy_scope(Rdv)` filtre bien par defaut sur l'orga courante dans ce cas. 

pour les perfs j'ai fait un test sur l'orga avec le plus de RDVs (orga 106 Meaux) sur un dump de prod c'est deja mega lent sur master, donc ok pour ignorer les perfs pour l'instant, on verra ce qu'il se passe a l'usage

2021-01-06 13:25 UTC, adipasquale requested changes
merci pour les changements @yaf , dernière chose avant d'approuver : je pense qu'il manque des `travel_back` dans les specs

2021-01-06 13:25 UTC, adipasquale commented on spec/models/user_spec.rb
> +      travel_to(now)
si tu fais travel_to je crois qu'il faut faire `travel_back` a la fin sinon tu laisses les tests dans un etat bizarre potentiellement

2021-01-12 15:09 UTC, adipasquale requested changes
désolé je refuse encore une fois mais je crois avoir vu une erreur dans l'algo pour décider s'il y a au moins un usager mineur.

Les autres commentaires sont bonus, à part peut-être le travel_back, il me semble que c'est important

2021-01-12 15:09 UTC, adipasquale commented on app/service_functions/rdv_exporter.rb
> +      rdv.users.map(&:minor?).uniq.compact == [true] ? "oui" : "non"
je pense que ça teste que tous les usagers sont mineurs ici, et pas qu'il y en ait au moins un. J'ai fait un test (1 rdv avec juste un mineur et l'autre avec deux rdvs) et ça me paraît erroné :

<img width="418" alt="Screenshot 2021-01-12 at 16 08 02" src="https://user-images.githubusercontent.com/883348/104332330-5a5f2080-54f0-11eb-92dc-ae8ddc00a830.png">

je pense que tu peux faire `rdv.users.any?(&:minor?)`

2021-01-12 15:17 UTC, yaf commented on Makefile
> -	bundle exec rubocop -a && bundle exec rspec --profile 3 && bundle exec brakeman
Ah non, je n’ai pas fait gaffe, j'ai vu truc pas « auto corrigée » et ça me disait d'utiliser `-A` pour que ça le soit. J'ai cru à une modification de l'outil (vu que tu as mis Rubocop à jour). Je supprime.

2021-01-12 15:23 UTC, yaf commented
> désolé je refuse encore une fois mais je crois avoir vu une erreur dans l'algo pour décider s'il y a au moins un usager mineur.

C'est à se demander si tu ne préfèrerais pas coder seul sur cette appli :trollface: 

Est-ce que tu peux me parler un peu de l'erreur ? Est-ce que c'est uniquement l'histoire de la forme sur le `any?(&:minor?)`

> Les autres commentaires sont bonus, à part peut-être le travel_back, il me semble que c'est important

Je ne suis pas sûr que le `travel_back` soit nécessaire, je pense qu'il est joué à la fin de chaque test, ou qu'il est remis à zéro au début de chaque... mais je veux bien en mettre. Ceci étant, je ne vois pas où il en manque là ?

2021-01-12 15:33 UTC, adipasquale commented
sorry 😬 

pour l'erreur, ce n'est pas sur la forme, non, il me semble que c'est un bug dans l'implem. tu n'as pas vu le screenshot de l'export que j'ai fait ? 

![image](https://user-images.githubusercontent.com/883348/104335107-63052600-54f3-11eb-8c72-7775208b6efd.png)

- Le 2e RDV avec josephine seule est marqué avec mineur
- Le 1er RDV avec josephine + 1 est marqué sans mineur

ca me parait incohérent.

Je suggérais juste un moyen de corriger avec le `any?(&:minor)`, pas un refacto de forme.

-- 

pour le sujet `travel_back` si tu regardes dans la codebase des specs existantes il me semble qu'on n'utilise jamais `travel_to` sans appeller `travel_back` après. je n'ai pas vu de mention que ca soit fait automatiquement par RSpec, mais c'est peut etre le cas. 

Tu peux aussi utiliser la forme `travel_to do block end` si tu préfères
et si tu penses que c'est fait par RSpec automatiquemetn, ok ca me va, on verra si on a des nouvelles flaky specs un jour il faudra suspecter ca

2021-01-12 15:39 UTC, yaf commented
Merci !

Je n’ai pas pris le temps de regarder la copie d'écran ! Merci. Et merci pour la précision, je n’ai pas regardé dans ce fichier là

2021-01-12 15:48 UTC, yaf commented
En fait c'est un cas de test qui n'était pas correct sur le majeur / mineur. J'avais fait un usager que je pensais majeur, alors qu'il n'avait que 8 ans (et pas 18  :D) révolue. Merci !

2021-01-12 17:13 UTC, adipasquale approved these changes
🚀 merci de supporter mes retours

2021-01-14 13:04 UTC, merged