Filtre et recherche dans la page des motifs
betagouv/rdv-solidarites.fr pull request #1151
Opened 2021-01-26 16:33 UTC by yaf

fix #1054

Pour faciliter la consultation des motifs (liste longue parfois), ajout
- d'un champ de recherche (basé sur le nom pour le moment)
- de filtres sur les colonnes « Réservable en ligne », « Service » et « Type de rendez-vous »

2021-01-28 15:33 UTC, adipasquale requested changes
tres cool comme nouvelle fonctionnalité ca manquait ! 
le seul truc que je note bloquant c'est la combinaison de filtres qui ne marche pas
le reste c'est de la discussion / du nitpicking

2021-01-28 15:33 UTC, adipasquale commented on Makefile
> +	bundle exec rubocop -a && bundle exec brakeman --no-pager && bundle exec rspec --profile 3
je pense que tu peux retirer ça de cette PR

2021-01-28 15:33 UTC, adipasquale commented on app/controllers/admin/motifs_controller.rb
> +    motifs = service_filtered(@motifs, params[:service_filter]) if params[:service_filter].present?
@yaf j'ai un doute ici, est-ce que tu ne devrais pas plutot appeler `service_filtered(motifs` plutot que sur @motifs ? 

ca marche peut etre parce qu'en fait au dessus `motifs = ` assigne a `@motifs` car la fonction est impure et reassigne le parametre mais j'ai un doute.

je pense que ça serait mieux d'éviter de réassigner `motifs =` pour garder la methode pure, par exemple en introduisant un nouveau `new_motifs = `

2021-01-28 15:33 UTC, adipasquale commented on app/controllers/admin/motifs_controller.rb
> +    motifs.where(service_id: service_filter)
je ne suis pas mega convaincu de l'opportunité de séparer ces méthodes aussi compliquées que leur noms, même si je comprends le souci de symétrie avec online_filtered. Je pense que je rapatrierais tout dans `filtered` a ta place

2021-01-28 15:33 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +          = f.input :service_filter, as: :hidden, value: params[:service_filter]
pourquoi utiliser des champs cachés et copier la valeur du champ select dedans plutôt qu'utiliser le select directement ? ça éviterait un peu de JS et ça simplifierait ce code

2021-01-28 15:33 UTC, adipasquale commented on app/controllers/admin/motifs_controller.rb
> +    motifs = service_filtered(@motifs, params[:service_filter]) if params[:service_filter].present?
en effet après test ca ne fonctionne pas de combiner : 
<img width="401" alt="Screenshot 2021-01-28 at 16 26 44" src="https://user-images.githubusercontent.com/883348/106160030-b202ba80-6185-11eb-8ab8-f9ec736c1f53.png">

2021-01-28 15:33 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
ca pourrait etre cool de rajouter `.select2-input` par coherence avec le reste du site. 

Le fait d'avoir glissé ces selects dans les noms de colonnes est interessant en termes d'UX ca marche assez bien. par contre : 
- ca ne sera pas super responsive (la page ne l'est deja pas bcp donc c'est pas pire)
- ca risque de conflicter avec le tri si on le rajoute un jour
- c'est assez unique par rapport au reste du site
- quand on clique sur reinitialiser on ne comprend pas bien que ca s'applique a l'ensemble des filtres et pas qu'au champ de recherche, car ils sont distants

mais ca me va d'essayer ca et voir comment ca evolue ca ne coutera pas cher de les ressortir un jour si jamais

2021-01-28 16:32 UTC, yaf commented on Makefile
> +	bundle exec rubocop -a && bundle exec brakeman --no-pager && bundle exec rspec --profile 3
oui, et en même temps, ça serait bien de le faire. Je le propose dans une autre PR

2021-01-28 16:33 UTC, yaf commented on app/controllers/admin/motifs_controller.rb
> +    motifs = service_filtered(@motifs, params[:service_filter]) if params[:service_filter].present?
Merci, je n’avais pas refait le test après avoir déplacé le code.... Et tu as raison, je vais revoir pour que la fonction reste propre !

2021-01-28 16:34 UTC, yaf commented on app/controllers/admin/motifs_controller.rb
> +    motifs.where(service_id: service_filter)
J'ai créé filtered après coup (le linter disais que c'était trop complexe la méthode index). C'est vrai qu'une fois extrait, ça a moins de sens de couper si petit, ou alors, en poussant dans un scope... Je vais revoir ça.

2021-01-28 16:35 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +          = f.input :service_filter, as: :hidden, value: params[:service_filter]
Effectivement, je n'y avais pas pensé :) Merci.

2021-01-28 16:37 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
Je pense que ça n'a pas beaucoup de sens de combiner tri et filtre. Pour moi, c'est l'un ou l'autres.

Je m'attends à ce que la config ne se fasse pas sur mobile. Je n’ai pas regardé Matomo pour vérifier si cet écran est consulté depuis des mobiles.

Je peux faire en sorte que « reinitialiser » remette aussi les filtre à zéro. Je n'y avais pas pensé. Merci !

2021-01-28 17:01 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +          = f.input :service_filter, as: :hidden, value: params[:service_filter]
Ça fait de la bricole en fait, le champ de recherche est en dehors du table#header contrairement aux filtres.

Je vais voir comment élargir le formulaire, mais ça va créer de la confusion dans la page je crois

2021-01-28 17:52 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
Bon, j'ai essayé, mais je trouve le résultat vraiment pas satisfaisant.

Le JavaScript permet de déclencher le filtre sans avoir à appuyer sur un bouton. S'il y a du JS, je peux me permettre d'utiliser des champs hidden histoire de pas avoir un formulaire qui englobe tout le tableau.

Je crois que c'est mieux comme ça. Merci de m'avoir fait la suggestion, ça m'a permis d'explorer une autre voie, mais je la trouve vraiment pas top.

J'ai ajouter les class `select2-input` par contre. Ça fait un peut bizarre d'avoir un champ de filtre dans une select de filtre (_inception_), mais en dehors de cette zone de saisi, le reste est effectivement plus cohérent.

Ça sera intéressant d'avoir un select2 sans la zone de saisi si c'est possible à un moment. J'ai l'impression qu'il faudrait qu'on utilise une autre classe pour définir le select sans recherche : https://select2.org/searching#single-select

2021-02-01 09:05 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
> je peux me permettre d'utiliser des champs hidden histoire de pas avoir un formulaire qui englobe tout le tableau

Pourquoi tu penses que le formulaire ne doit pas englober tout le tableau ? je n'y vois pas d'inconvénient, ni techniquement ni sémantiquement, ça se fait assez souvent qu'un form englobe une page entière parce que les champs sont répartis de haut en bas. 

ça devient problématique s'il y a des formulaires imbriqués mais je ne crois pas que ce soit le cas

2021-02-01 09:28 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
C'est pas le cas. Et je ne trouve vraiment pas ça très propre sémantiquement parlant. Même en lisibilité ça perd.

Encore un aspect sur lequel nous ne sommes pas accordé :smile: 

Ceci étant, je vais faire ce méga-formulaire histoire de réduire le JavaScript.

2021-02-01 09:30 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
Pardon, ça pose un autre soucis : après avoir modifié une dropdown pour filtrer une colonne, il faut que j'aille appuyer sur un bouton « rechercher » qui est au-dessus. En terme d'UX, c'est vraiment pas top. Tu as une suggestion pour ça ?

2021-02-01 09:34 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
non non mais laisse c'était pas bloquant c'était pour comprendre ton choix. j'attendais juste le deploy de la review app pour tester et approuver.

Je pense que le JS est en effet nécessaire pour soumettre automatiquement le formulaire. à moins de faire des trucs à l'ancienne dans le html genre "onChange=document.querySelector(form).submit"

2021-02-01 09:42 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
Oui. Par contre, c'est vrai qu'on pourrait, en englobant le tout dans le formulaire, se passer des champs hidden.

Mais du coup, ça à moins de sens pour moi. Si c'est uniquement pour les champs hidden. Pour virer le JS, j'aurais été partant. Merci pour ces échanges :)

2021-02-01 09:53 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +                = select_tag("online_filter_select", options_for_select(["En ligne", "Hors ligne"], params[:online_filter]), include_blank: "Tous", class: "motif-filters")
pas bloquant mais juste pour la discussion : 

je continue à penser que ça serait mieux de faire un seul champ visible que gérer la syncho de champs cachés en JS, j'ai peur que ça se désynchronise par exemple après rechargement de la page, je vais tester sur la review app

2021-02-01 09:54 UTC, adipasquale commented
@yaf ca n'a plus l'air de soumettre automatiquement le formulaire lors du changement de filtre, ca fonctionne pour toi ? https://demo-rdv-solidarites-pr1151.osc-secnum-fr1.scalingo.io/admin/organisations/1/motifs

2021-02-01 09:57 UTC, yaf commented
Ah non effectivement. J'ai dû casser un truc en faisant les corrections / tests d'un formulaire englobant.

J"apprécie ton dernier argument. Je vais refaire un essai pour supprimer les champs cachés en gardant le JS.

2021-02-01 11:00 UTC, adipasquale approved these changes
👍 merci d'avoir survécu à mes retours ça marche nickel maintenant, pas de pb de synchros, le refresh, les combinaison, l'interaction avec la recherche texte et la réinitialisation.

J'ai noté un point pas forcément bloquant sur la liste de services visibles.

Aussi, pour la discussion, je pense que dans ce cas j'aurais introduit un "form model", c'est à dire un modèle qui ne sert qu'à modéliser les champs de ce formulaire. ça permet d'utiliser plus facilement les helpers de simple form, sans avoir besoin de passer les values, ni définir les noms des champs et faire le mapping pour hydrater. Et ça permet ensuite de rajouter des validaitons facilement si besoin - il n'y en a pas ici, mais on pourrait imaginer vouloir valider que les options sélectionnées sont valides et autorisées selon le rôle de l'agent

2021-02-01 11:01 UTC, adipasquale commented on app/views/admin/motifs/index.html.slim
> +                  = select_tag("service_filter", options_from_collection_for_select(Service.all, "id", "short_name", params[:service_filter]), include_blank: "Tous", class: "motif-filters select2-inp
d'ailleurs maintenant que j'y pense ça serait intéressant de tester sur un dump de la prod pour voir la taille du select de service, ça risque d'être bien gros et de casser un peu le layout

2021-02-01 13:53 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> += simple_form_for '', url: admin_organisation_motifs_path(current_organisation), html: { method: :get, class: 'form-inline search-and-filter-form' }, wrapper: :inline_form do |f|
C'est une convention qui me va. Je vais essayer de l'adopter. Au moins pour ce projet :smile:

2021-02-01 13:59 UTC, yaf commented on app/views/admin/motifs/index.html.slim
> +                  = select_tag("service_filter", options_from_collection_for_select(Service.all, "id", "short_name", params[:service_filter]), include_blank: "Tous", class: "motif-filters select2-inp
Très juste remarque. J'ai repris le code pour lister les services des motifs de la liste, ça me semble plus approprié

2021-02-01 16:41 UTC, merged