Notification avec ICS pour les modifications et suppressions de plages d'ouverture
betagouv/rdv-solidarites.fr pull request #1177
Opened 2021-02-09 09:32 UTC by yaf

Notification avec ICS pour les modifications et suppressions de plages d'ouverture.

fix #1166

2021-02-26 18:11 UTC, yaf commented
Je n'arrive pas à résoudre le souci de la base de test existante :-/ Faut-il que je reprenne le code de cette PR sur une nouvelle branche pour tout reprendre de zéro ?

Je suis preneur de piste.

2021-03-01 11:04 UTC, adipasquale reviewed
Comme dit dans le Slack je ne suis pas convaincu par la direction du refacto fonctionnel de cet objet. 

Ceci dit, le code est quand même plus propre qu'avant, et c'est tout à fait acceptable donc je ne m'opposerai pas à ce changement. ça serait peut-être cool qu'on en discute cependant, pour que les directions ne divergent pas trop. Si tu as des arguments à partager ici pour aller dans la direciton fonctionnelle pour ce cas, je suis preneur, ou bien se faire un petit échange oral avec plaisir.

Je n'ai pas encore approuvé, mais rien de bloquant, 'ai mis quelques questions/commentaires dans le code. je dois encore tester un peu plus en détail sur la review app mais ça a l'air de fonctionner parfaitement 👍

2021-03-01 11:04 UTC, adipasquale commented on app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_destroyed.html.slim
> +p Vous pouvez synchroniser cette plage sur votre calendrier en ouvrant la pièce-jointe de cet email.
que penserais-tu de  : 

> Vous pouvez supprimer l'événement correspondant de votre logiciel de calendrier externe (Outlook, Zimbra, Thunderbird etc) en ouvrant la pièce jointe

2021-03-01 11:07 UTC, adipasquale commented
ah et une question que je me pose : est-ce que tu comptes refacto la classe paralelle `Rdv::Ics` ? je pense que ca peut etre fait dans une PR successive si tu ne souhaites pas polluer celle-ci, mais par contre je serais d'avis qu'on le fasse rapidement pour garder un peu de coherence dans le code si on merge cette PR avec ce refacto

2021-03-01 14:34 UTC, yaf commented on app/service_functions/ics.rb
> +    event.last_modified = Time.zone.now
Le `last_modified` n'est peut-être pas nécessaire... :thinking: C'est issue des multiples tests que j'ai fait « à la main » avec google agenda. Il met toujours un `last_motified`

2021-03-01 14:36 UTC, yaf commented on app/service_functions/ics.rb
> +    attendee_params = { "CUTYPE" => "INDIVIDUAL",
Le status est nécessaire pour la « suppression » d'une plage d'ouverture. J'ai également ajouté l'organizer. J'ai découvert ça lors des tests à la main. Je trouve que c'est assez intéressant d'avoir cette info. Les personnes attendue n'était pas reconnu proprement avec ce qu'il y avait avant. J'ai fini par trouver ce qu'il faut faire.

2021-03-01 14:37 UTC, yaf commented on app/service_functions/ics.rb
> +                        "RSVP" => "TRUE",
Je crois que c'est lié au fait que la personne ait acceptée ou pas le rendez-vous.

2021-03-01 14:38 UTC, yaf commented on app/service_functions/ics.rb
> +module Ics
Ah oui, pourquoi pas. Nous n'avions pas encore fait de « scope » dans le répertoire `service_function`. Mais oui, nous pouvons

2021-03-01 14:42 UTC, yaf commented on app/views/mailers/agents/plage_ouverture_mailer/plage_ouverture_destroyed.html.slim
> +p Vous pouvez synchroniser cette plage sur votre calendrier en ouvrant la pièce-jointe de cet email.
Oui, ça me convient

2021-03-01 14:53 UTC, adipasquale commented on app/service_functions/ics.rb
> +    attendee_params = { "CUTYPE" => "INDIVIDUAL",
Merci ! dans le cas d'une PO, qui est l'organisateur ? Celui qui créé la PO ? dans ton code c'est toujours l'agent qui va réaliser la PO il me semble. 
Je trouve ça très cool que tu aies pris le temps de creuser et comprendre le fonctionnement de l'ICS pour l'implémenter correctement mais je me demande l'intérêt de rajouter ces champs pour les POs si on a toujours 1 seul attendee qui est le même que l'organisateur et le même que le destinataire de l'ICS envoyé par email. ça change quelque chose dans ton logiciel de calendrier pour toi ?

2021-03-01 14:56 UTC, adipasquale commented on app/service_functions/ics.rb
> +                        "RSVP" => "TRUE",
alors dans la RFC : 
```
   Purpose:  To specify whether there is an expectation of a favor of a
      reply from the calendar user specified by the property value.
      ```
      
ici il n'y a pas d'attente de reponse a l'ICS (au contraire on prefere que les logiciels de calendrier ne nous repondent pas, on recoit les emails de reponse sur contact@rdv-solidarites.fr et on les met a la poubelle)

2021-03-01 15:01 UTC, yaf commented
Je commence par répondre à ta dernière question, puis je poserais quelques éléments qui m'amènent aux choix que je fais en ce moment sur l'architecture (objets, fonctions).

Oui, je pense que ça serait chouette de reprendre `Rdv::Ics` dans le même esprit, et oui, plutôt dans une autre PR, et oui, assez rapidement.


Sur les éléments qui m'amènent à choisir de transformer l'objet ICS en fonction :
- Ics est plutôt un format qu'un objet
- Nous voulons que PlageOuverture soit « transformé » en fichier ICS
- Une transformation est plutôt une fonction qu'un objet
- Je trouve plus clair est lisible d'utiliser les objets comme des structures de données qui permettent de préciser des objets « métiers » et des fonctions extérieures pour les transformer. Avec quelques exceptions pour lesquelles il est intéressant d'avoir des fonctions dans les objets, comme « save ». Encore que ce soit discutable, mais je n'ai pas envie de pousser jusqu'à là pour le moment :)
- les tests unitaires me semble plus facile à écrire comme ça


J'imagine que nous pourrions :
- avoir un objet payload (où on le range ?) avec les fonctions liées à la création d'un payload.
- faire en sorte que seule les fonctions d'appel à `ical` et `rrule` soit publique, le reste en privée.


Est-e que ça te convient si j'essaie de faire ça ?

2021-03-01 15:12 UTC, adipasquale commented on app/service_functions/ics.rb
> +    event.last_modified = Time.zone.now
merci ! j'aurais tendance à l'enlever dans ce cas, ou alors s'il se révèle être nécessaire plutôt donner le plage_ouverture.updated_at . Tel quel c'est assez artificiel/incorrect de donner l'heure d'execution du job

2021-03-01 15:24 UTC, adipasquale commented
merci pour les détails ! tout me va, même tel quel la PR est quasiment OK pour moi - après discussion des nouveaux champs rajoutés dans les ICS. 

je note mes réactions à tes points en faveur du fonctionnel :

- je trouve ça personnellement plus agréable et lisible d'utiliser des objets, même s'ils sont un peu artificiels. j'aime bien utiliser les attributs d'instances pour ne pas avoir à les passer entre chaque appel de fonction, ça évite un peu de "tuyauterie". 
- "Une transformation est plutôt une fonction qu'un objet" > du coup je suis d'accord mais j'aurais quand même tendance à en faire un "Service Object" ou "service model", une vraie classe instanciée avec une seule méthode publique "perform", ou "transform" ou "to_ics" ou quoi que ce soit.
- J'adhère plus à la pratique de ne pas tester les méthodes qui ne sont pas appellées de l'extérieur donc ça ne me dérange pas d'avoir des vraies méthodes privées dures à tester car elles dépendent des attributs. (un des conseils de POODR de sandi metz)
- Je trouve que ruby-rails se prête plus naturellement à l'écriture OO

2021-03-01 16:01 UTC, yaf commented on app/service_functions/ics.rb
> +    attendee_params = { "CUTYPE" => "INDIVIDUAL",
Non pas vraiment, d'autant que c'est sur les plages d'ouvertures. Peut-être pas super pertinent. Sur les RDV ça sera différent.

2021-03-01 18:52 UTC, yaf commented on app/service_functions/ics.rb
> +                        "RSVP" => "TRUE",
C'est très lié au test que j'ai fait. Je vais supprimer le RSVP :)
Merci !

2021-03-01 19:13 UTC, yaf commented on app/service_functions/ics.rb
> +module Ics
Je note ça pour plus tard...

2021-03-01 19:16 UTC, yaf commented on app/service_functions/ics.rb
> +    attendee_params = { "CUTYPE" => "INDIVIDUAL",
J'ai viré pas mal de truc sur les ATTENDEE et ORGANIZER. Je vais vérifier si ça fonctionne bien.

2021-03-01 19:42 UTC, yaf commented
Je suis prêt à envisager de faire des objets plutôt que du fonctionnel. C'est ce que je faisais avant après tout. Ceci étant, j'ai du mal à « penser » l'architecture du coup.

Et là, un souci m'a poussé au réfactoring : difficulté à introduire la gestion du status dans le fichier ICS + serialisation de la plage d'ouverture au moment de la suppression.

Un truc important pour moi dans le code, c'est de faire en sorte que ce soit facile à modifier... Les histoires de clean code et de principes SOLID vont dans ce sens.

Je pense que pour garder une structure avec des objets, j'aurais besoin d'avoir des discussions avec toi pour penser le design avant de faire. Ça nous fera peut-être un peu trop de point de synchro, et peut-être que ça sera ok...

2021-03-04 08:47 UTC, adipasquale commented on app/service_functions/ics.rb
> +    event.append_attendee(attendee_value)
désolé d'insister là dessus mais es-tu sûr que c'est nécessaire de rajouter les attendees pour que l'annulation du RDV soit prise en compte ? ça me paraît bizarre.

2021-03-04 08:48 UTC, adipasquale commented on spec/mailers/agents/plage_ouverture_mailer_spec.rb
> +          name: "plage-ouverture--.ics",
drole de nom de fichier non ? il ne manque pas le prefixe rdv-solidarites et un suffixe d'ID ?

2021-03-04 08:51 UTC, yaf commented on app/service_functions/ics.rb
> +    event.append_attendee(attendee_value)
Tu as raisons, surtout dans le cadre d'une annulation de plage d'ouverture.

Je verrais au moment des RDV si c'est nécessaire et comment le re-introduire correctement.

Merci !

2021-03-04 08:52 UTC, yaf commented on spec/mailers/agents/plage_ouverture_mailer_spec.rb
> +          name: "plage-ouverture--.ics",
Je crois qu'il n'y a aucun test sur le nom du fichier. Je pourrais mettre un peu n'importe quoi ici.

2021-03-04 09:28 UTC, yaf commented
Je réalise que la notion de `private` dans un module est inutile. Je pourrais mettre une `class` à la place pour « faire semblant » et rendre privée une partie des fonctions. Ça ne me dérange pas trop de le faire. Le principale étant de scoper les functions « ouvertes ».

2021-03-04 14:59 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +      title: object.title.parameterize,
je ne pense pas que `parameterize` devrait être fait à ce niveau. le `title` est appelé pour le `summary` qui est une valeur qui doit être lisible par un humain il me semble. Je pense que c'est une régression que tu introduis avec ce changement

2021-03-04 15:00 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +    event.summary = "#{BRAND} #{payload[:title]}"
je note que tu as enlevé `event.description="'`
ca me va effectivement il y a peu de chances pour que ça fasse planter la compatibilité quand même, je le note pour plus tard au cas où

2021-03-04 15:03 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +    payload_for(object).merge(event: :create)
le choix de `event` ici pour designer le lifecycle event entre un peu en conflit avec l'événement au sens `Icalendar` aussi appelé `event`, c'est un poil ambigu à mon avis j'aurais peut-être mis `ar_event` ou `crud_event` ou `lifecycle_event` ou `object_event` .. (rien de bloquant, c'est une suggestion)

2021-03-04 15:09 UTC, adipasquale requested changes
je mets en bloquant pour : 

- le parameterize title au mauvais endroit
- un bug lorsque je créé une PO recurrente : https://sentry.io/organizations/rdv-solidarites/issues/2252134591

2021-03-04 15:11 UTC, yaf commented on app/service_functions/admin/ics.rb
> +      title: object.title.parameterize,
J'ai trimballé le truc qui était utilisé avant... ça me convient de l'enlever !

2021-03-04 15:12 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +      title: object.title.parameterize,
non, le parameterize est utile, mais uniquement dans le `name` de la PO, pas le `summary` c'est ca que je voulais dire

2021-03-04 15:13 UTC, yaf commented on app/service_functions/admin/ics.rb
> +    payload_for(object).merge(event: :create)
Est-ce que `:action` conviendrait ?

2021-03-04 15:13 UTC, yaf commented on app/service_functions/admin/ics.rb
> +    payload_for(object).merge(event: :create)
voir Status puisque c'est le paramètre dans lequel il est utilisé ensuite dans le fichier ICS

2021-03-04 15:15 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +    payload_for(object).merge(event: :create)
`status: :create` ca n'a pas trop de sens sémantiquement ça devrait plutôt être `status: :created` etc

`action` pourquoi pas oui si tu preferes a `event` prefixé  ou suffixé ça me va bien. Tant que ça n'entre pas en conflit avec l'event c'est cool

2021-03-04 16:11 UTC, adipasquale requested changes
désolé mais l'erreur se produit toujours sur la review app https://sentry.io/organizations/rdv-solidarites/issues/2252134591

2021-03-04 17:09 UTC, adipasquale commented on app/service_functions/admin/ics.rb
> +  def self.rrule(plage_ouverture)
en termes de signature c'est perturbant que cette méthode prenne un objet AR plage_ouverture alors que celle au dessus attend un payload.

2021-03-04 17:14 UTC, adipasquale approved these changes
👍 ca marche bien, a vrai dire je suis meme surpris que les logiciels de calendrier supportent aussi bien les opérations d'update et de destroy, c'est cool. Pas du tout naturel pour moi mais j'imagine que quand ton client mail et calendrier sont bien intégrés ensemble comme c'est le cas pour les agents utilisant Outlook c'est pratique.

Je note une différence opérationnelle dans ton code : une grosse partie de la transformation PO -> ICS est faite inline dans le controlleur alors qu'avant c'etait fait dans le job. C'est du au fait que tu doives serialiser avant d'enqueue le job pour gerer le cas de la suppression. Ca peut introduire deux legers pbs : 

- ralentir l'action du controlleur (probablement tres negligeable)
- s'il y a une erreur ca fait une 500 pour l'agent alors qu'avant ca faisait "juste" pas de mail et on avait une erreur sentry a traiter et eventuellement re-enqueue le job apres

2021-03-04 17:18 UTC, yaf commented on app/service_functions/admin/ics.rb
> +  def self.rrule(plage_ouverture)
Je suis bien conscient de ça. C'est lié aux histoires de sérialisation. Un autre option serait de récupérer `rrule` via le payload peut-être. Cette méthode est exposée dans le blueprint plage_ouverture.

Je peut faire une autre proposition si tu as la patience :)

2021-03-04 17:23 UTC, yaf commented on app/service_functions/admin/ics.rb
> +  def self.rrule(plage_ouverture)
Je suis en train de penser que ça ne changera pas grand-chose, en dehors de pouvoir considérer la méthode « rrule » comme privée.

Je laisse comme ça. J'aurais sans doute l'opportunité de reprendre cette partie en faisant les ics pour les absences et en reprenant ceux des rendez-vous

2021-03-04 17:23 UTC, merged