Limiter la création d'organisation par une personne non authentifiée
betagouv/rdv-solidarites.fr pull request #1193
Opened 2021-02-12 17:42 UTC by yaf

fix #1192

2021-03-01 10:02 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      redirect_to action: :new
pourquoi ne pas faire `render :new` ici comme c'était le cas avant ? ca devrait t'eviter d'avoir a désérialiser les erreurs dans un flash

2021-03-01 14:32 UTC, yaf commented on app/controllers/organisations_controller.rb
> +      redirect_to action: :new
Pour avoir une url « valable ». Ça me semble plus « railsish » de faire un redirect.

2021-03-01 14:40 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      redirect_to action: :new
hum je dirais justement l'opposé que c'est plus rails-compliant de faire render :new . Si tu désérialises les erreurs dans une chaine de caractères dans un cookie flash tu perds le lien avec les champs, il ne peuvent plus s'afficher selon leur statut d'erreur par exemple.

2021-03-01 19:45 UTC, yaf commented on app/controllers/organisations_controller.rb
> +      redirect_to action: :new
Ah oui. Mais l'url est naze du coup... Je peux faire un render :new, pas de soucis

2021-03-02 07:43 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      redirect_to action: :new
les urls par défaut rails après un post ne sont pas rafraichissables si c'est ce que tu veux dire oui

2021-03-02 07:45 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      flash[:error] = @organisation.errors.full_messages.join(", ")
ce flash manuel n'est pas necessaire normalement quand tu fais un `render :new` classique : @organisation.errors est bien rempli dans la vue et les erreurs s'affichent naturellement

2021-03-02 07:46 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      flash[:error] = I18n.t("activerecord.errors.models.organisation.existing_orga_with_dep_need_connected_agent_html")
tu pourrais aussi faire un `@organisation.errors.add(:base, ...)` pour rentrer dans le cadre des validations plus classiques Rails - AR. 
C'est la direction des form models : des validations différentes par chemin, ici depuis ce chemin public il y a une validation supplémentaire par rapport au modèle Organisation. 

(c'est juste une suggestion, pas du tout bloquant)

2021-03-02 14:17 UTC, yaf commented on app/controllers/organisations_controller.rb
> +      flash[:error] = I18n.t("activerecord.errors.models.organisation.existing_orga_with_dep_need_connected_agent_html")
J'aime bien. Je vais intégrer l'aspect `errors.base` mais pas `form_model`. Ça me semble un peu overkill pour le formulaire en question, il me semble.

2021-03-03 09:02 UTC, adipasquale requested changes

2021-03-03 09:02 UTC, adipasquale commented on config/locales/models/organisation.fr.yml
> +          existing_orga_with_dep_need_connected_agent_html: "Au moins une organisation, avec au moins un agent existe déjà pour ce département. Merci de prendre contact avec cette personnes pour ajou
En bloquant, je me permets de noter deux fautes : 
- cette personnes => cette personne
- oranisation => organisation

En suggestions non-bloquantes :
- je pense qu'on pourrait extraire le lien vers la doc pour qu'il apparaisse tout le temps, pas juste dans le message d'erreur. (d'ailleurs la doc est très cool, merci d'avoir fait ça ! je vais faire une petite PR pour corriger quelques fautes ^^)
- je pense qu'on pourrait condenser le message, par ex "Il y a déjà des organisations et des agents créés dans ce département, veuillez entrer en contact avec eux"

2021-03-03 09:12 UTC, adipasquale commented
@yaf j'ai fait une petite passe sur la doc je sais pas si ce lien marche pour toi :  https://app.gitbook.com/@rdv-solidarites/s/rdv-solidarites/~/diff/drafts/-MUrKNm8L8B7O2rNDw9s/revisions/-MUrKFHrI-lm4vrURSoB/tutoriels/creer-une-organisation/@activity/-MUrLSgZMCuP_CFbf7Ll 

sinon il faut aller la https://app.gitbook.com/@rdv-solidarites/s/rdv-solidarites/@drafts

la vue diff de gitbook est pas ouf du tout :/

2021-03-03 15:22 UTC, adipasquale commented
@yaf je n'y avais pas pensé mais l'introduction des "Territoires" va m'obliger à refacto ce code juste après que tu l'aies déployé car ça va changer la position de l'unicité du département. C'est plutôt un changement qui simplifie

2021-03-03 20:33 UTC, yaf commented on config/locales/models/organisation.fr.yml
> +          existing_orga_with_dep_need_connected_agent_html: "Au moins une organisation, avec au moins un agent existe déjà pour ce département. Merci de prendre contact avec cette personnes pour ajou
Ah oui, merci. C'est effectivement une bonne idée.

Je ne sais pas trop où la mettre (je crois que cette page mériterais d'être reprise de fond en comble !). Je vais pas l'ajouter pour le moment.

Merci

2021-03-03 21:08 UTC, yaf commented
Yep, j'ai bien conscience que le refacto va un peu changer la donne.

Merci pour les corrections sur la doc !

Et merci pour ta relecture. Je pense avoir fait ce qu'il faut. Il restera à reprendre cette page et faire un lien vers la documentation.

2021-03-04 08:42 UTC, adipasquale commented on app/controllers/organisations_controller.rb
> +      @organisation.errors.add(:base, I18n.t("activerecord.errors.models.organisation.existing_orga_with_dep_need_connected_agent_html").html_safe)
no need anymore for `_html` suffix nor `html_safe`

2021-03-04 08:45 UTC, adipasquale approved these changes
👍

2021-03-04 09:12 UTC, merged