cors gem to allow cross origin calls to api
betagouv/rdv-solidarites.fr pull request #1238
Opened 2021-03-15 11:43 UTC by qblanc

- [Issue 1236](https://github.com/betagouv/rdv-solidarites.fr/issues/1236)
- Permettre les requêtes cross-origins depuis les navigateurs
- Ajout de la gem rack-cors
- Ajout (bonus) d'un lien de contributing.md vers Install.md (vu avec Thomas; j'avais raté ce fichier au moment de mon install, ce qui m'a posé des difficultés avec le .env.sample qui ne s'était pas dupliqué en .env)

2021-03-15 15:07 UTC, adipasquale requested changes
test

2021-03-15 15:07 UTC, adipasquale approved these changes
test 2

2021-03-19 14:48 UTC, yaf commented
Tout me semble ok sur cette PR. Est-ce que je peux la fusionner avec main ?

2021-03-19 17:04 UTC, qblanc commented
Hello Yannick ! Pour les domaines autorisés, j'ai remplacé le * par une variable d'env. Il faudrait donc renseigner la variable d'env dans votre environnement de prod (Scalingo je crois ?). A minima il faudrait autoriser https://betagouv.github.io/analyse-flux-insertion/, ou ne pas filtrer, comme vous préférez.

Je ne sais pas pourquoi les tests ont échoué cette fois, peut-être à cause de l'absence de cette variable d'env ?
En dehors de ce souci, la PR peut être mergée.

2021-03-22 16:46 UTC, adipasquale commented
est-ce qu'on peut scoper cette règle CORS uniquement sur les routes de l'API @qblanc ? je ne suis pas super chaud d'élargir à toutes les routes de l'appli rails

2021-03-22 18:00 UTC, qblanc commented
J'ai ajouté le scope pour n'exposer que les routes de l'API, dis moi si ça te convient @adipasquale .
Si vous rajoutez la variable d'env dans Scalingo les tests devraient passer correctement je pense.

2021-03-23 09:01 UTC, adipasquale requested changes
j'ai encore plusieurs remarques désolé @qblanc : 

1. es-tu sur que ca fonctionne ? J'ai fait un test rapide en local et je ne vois pas le response header CORS sur la route de sign in : 

<img width="695" alt="Screenshot 2021-03-23 at 09 59 25" src="https://user-images.githubusercontent.com/883348/112120571-ae584680-8bbe-11eb-9c7c-16359732ec32.png">

2. je pense que pour une API, le allowed origins doit toujours etre `*`. A mon avis, on peut supprimer la variable d'env et le hardcoder. ca reparera les specs en passant.

2021-03-23 09:25 UTC, qblanc commented
Hello Adrien,

pas de souci pour les remarques, l'important est de faire un truc robuste et secure :) Je suis d'accord avec toi pour les origins, j'ai remis la wildcard.
Pour ton test ça me paraît logique puisque tu l'as fait depuis ton terminal, et que le souci des cors intervient lorsque tu passes par un navigateur, que ta requête est envoyée depuis un autre domaine.

2021-03-23 09:38 UTC, adipasquale commented
bien vu merci, ça n'arrive pas à rentrer dans ma tête que ça ne se produit que depuis le navigateur ! 

j'ai réussi à reproduire avec ce mini script https://gist.github.com/exAspArk/07bbbafa2a9171b6c260989780cc0955 : 

<img width="708" alt="Screenshot 2021-03-23 at 10 36 20" src="https://user-images.githubusercontent.com/883348/112125480-c54d6780-8bc3-11eb-9391-124ee30f5e84.png">

c'est presque bon donc, il faudrait juste merger master ici (ou rebase comme tu préfères) pour que les specs passent je pense

2021-03-23 09:52 UTC, qblanc commented
Done

2021-03-23 11:07 UTC, adipasquale approved these changes
👍 testé rapidement depuis curl sur la review app, les headers sont bien présents uniquement sur les routes d'API mais en minuscules, je ne sais pas si ca change qqch. Je n'ai pas testé en détail si l'exposition des headers sélectionnés est suffisante, on verra avec ton intégration @qblanc . Merci pour cette PR !

2021-03-23 14:15 UTC, merged

2021-03-23 14:36 UTC, adipasquale commented
@qblanc c'est déployé 🚀