affiche le  mois complet dans les notifications SMS
betagouv/rdv-solidarites.fr pull request #1251
Opened 2021-03-19 21:30 UTC by yaf

fix #1209

2021-03-22 13:33 UTC, adipasquale requested changes
il me semble que ca ne respecte pas ce qu'on avait évoqué comme format de dates dans le ticket : https://github.com/betagouv/rdv-solidarites.fr/issues/1209 à savoir " mardi 16/03 à 10h00". Tu as fait différement pour une raison précise @yaf ?

Aussi, pourquoi introduire des nouveaux formats plutôt que changer les existants ? Là ça va créer des incohérences dans la manière d'afficher les dates dans les différents SMS.

2021-03-22 14:02 UTC, yaf commented
J'avais préféré de nouveau format pour ne pas perturber l'existant. Mais c'est vrai que c'est peut-être plus gênant qu'autre chose de garder ce format peu lisible :)

Et j'avais oublié de lire le ticket avant de commencer. Je ne me souvenais plus que nous avions défini un format. Merci d'avoir pris le temps de vérifié (ou d'avoir eu la mémoire :))

2021-03-22 18:16 UTC, yaf commented
Le commit https://github.com/betagouv/rdv-solidarites.fr/pull/1251/commits/442c2e82ddfeb4351e6f9a8d1110bdb9e27ca492 a vocation à réduire la variabilité d'un test sur une spec qui n'est pas en lien avec cette PR.

Je peux la `cherry-picker` à l'extérieur si c'est plus confortable.

2021-03-23 08:50 UTC, adipasquale approved these changes
👍 top !

2021-03-23 10:53 UTC, merged