Ajout de rails-erd et d’une version actuelle du modèle
betagouv/rdv-solidarites.fr pull request #1258
Opened 2021-03-22 15:02 UTC by n-b

Ajoute [domain_model.pdf](https://github.com/betagouv/rdv-solidarites.fr/files/6183165/domain_model.pdf) au dossier docs. Il est tenu à jour automatiquement à chaque rails db:migrate.

Dans le même style, j’aime bien [annotate](https://github.com/ctran/annotate_models), qu’en pensez-vous?

2021-03-22 15:04 UTC, adipasquale commented
bonne initiative 👍 j'avais fait ca en arrivant aussi mais jamais mergé : https://github.com/adipasquale/rdv-solidarites.fr/pull/1/files#diff-79192d96d0e8df302dc87ef73524be54

2021-03-22 15:26 UTC, n-b commented
J’ai ajouté annotate, pendant que j’y étais. Je vous laisse juger si c’est pertinent, en général j’aime bien avoir le rappel du modèle dans les fichiers concernés.

2021-03-22 15:33 UTC, adipasquale reviewed
je trouve ca un peu violent en nombre de lignes et "pollution visuelle" annotate perso, je serais plus d'avis d'avoir une extension IDE pour faire ce genre de choses je ne sais pas si ça existe.

Mais je vous laisse décider :)

2021-03-22 16:17 UTC, n-b commented
ok, on pourra toujours reparler de annotate plus tard; c’est pas difficile à remettre.

2021-03-22 16:39 UTC, adipasquale reviewed
par rapport a ma version qui date d'un an (https://github.com/adipasquale/rdv-solidarites.fr/pull/1/files#diff-79192d96d0e8df302dc87ef73524be54) 
- que penses-tu d'exclure les tables "non-metier" ?
- que penses-tu d'utiliser png plutot que PDF pour l'output ?

2021-03-22 16:53 UTC, n-b commented
:+1: pour le png et pour exclure les tables non-métier (dans d’autres projets, `disconnected: false` suffisait de fait à supprimer les tables non métier)

2021-03-23 08:43 UTC, adipasquale requested changes
peux tu rajouter dans `INSTALL.md` qu'il faut installer graphviz stp ? peut etre avec un lien vers https://voormedia.github.io/rails-erd/install.html

2021-03-23 16:24 UTC, adipasquale approved these changes

2021-03-23 16:57 UTC, merged