WIP refacto DuplicateUserFinder
betagouv/rdv-solidarites.fr pull request #1284
Opened 2021-03-29 14:30 UTC by adipasquale

WIP

2021-04-08 11:49 UTC, adipasquale commented on app/controllers/admin/users_controller.rb
> +    @user.invite! if user_persisted && @user.email.present? && params[:invite_on_create] == "1"
ces changements qui n'ont rien a voir avec la PR sont des petits hacks pour que ce fichier tienne dans la limite acceptée par le linter ... ce n'est pas beau, je sais. je n'ai pas de très bonne piste pour réduire la taille de ce controleur pour l'instant.

2021-04-08 11:49 UTC, adipasquale commented on app/models/user.rb
> -  def user_is_not_duplicate
goodbye forever 👋

2021-04-08 11:49 UTC, adipasquale commented on app/views/admin/users/_form.html.slim
> +    = render partial: 'layouts/model_errors', locals: { model: user_form, f: f }
il y a en fait assez peu de changements dans cette vue, mais GH ne l'affiche pas très clairement : 

- on enlève le bazar qui existait pour rendre les warnings custom de duplicate users
- on wrappe la plupart des champs dans `collapsible_form_fields_for_warnings` pour avoir le comportement de transparence / disable lorsqu'il y a des warnings
- on enlève le checkbox custom qui apparaissait en bas pour ignorer les avertissements - c'est maintenant générique dans le model_errors

2021-04-12 12:50 UTC, n-b reviewed
(notes pour moi)

2021-04-12 13:44 UTC, n-b commented on app/controllers/admin/users_controller.rb
> +    @user.invite! if user_persisted && @user.email.present? && params[:invite_on_create] == "1"
Je suis revenu à invite_user?, je ne sais pas si c’est le nombre de lignes ou de méthodes qui coinçaient, mais là ça semble aller.

2021-04-12 13:46 UTC, n-b commented on app/controllers/admin/users_controller.rb
> +      @user.tap { _1.assign_attributes(user_params) },
J’ai ajouté une méthode `def user_form_object` qui crée que UserForm pour toutes les méthodes. A priori, on pouvait se contenter de faire toujours le même appel à partir de @user, et de prendre `:active_warnings_confirm_decision` uniquement si elle est présente.

2021-04-12 13:47 UTC, n-b commented on app/form_models/admin/user_form.rb
> +      .each { user.errors.add(:base, render_message(_1)) }
… parce qu’on veut afficher ce message en en-tête du formulaire, pas au niveau du champ concerné.

2021-04-12 13:57 UTC, n-b commented on app/form_models/admin/user_form.rb
> +    ApplicationController.render(
J’ai l’impression que `from_modal?` et `add_query_string_params_to_url(modal_return_location`, c’est effectivement un peu tricky. Ça sera pour la prochaine fois quand on réécrira tout avec hotwire :D

2021-04-12 14:19 UTC, n-b approved these changes
@yaf Sinon c’est bon pour moi. J’ai l’impression que la modale nous coûte assez cher en complexité du code, mais c’est pas l’objet ici.

Je veux bien que tu jettes un coup d’œil rapide :)

2021-04-12 14:19 UTC, n-b commented on app/controllers/admin/users_controller.rb
> +
@yaf le seul changement significatif que j’ai fait est l’ajout de cette méthode.

2021-04-12 15:42 UTC, yaf commented
J'ai une erreur 500 sur la pose de rendez-vous dans l'agenda :-/  https://sentry.io/organizations/rdv-solidarites/issues/2178934294/?project=1811205&referrer=RegressionActivityEmail

2021-04-12 15:43 UTC, yaf requested changes
Il y a une erreur 500 lorsque je pose un rendez-vous depuis l'agenda
https://sentry.io/organizations/rdv-solidarites/issues/2178934294/?project=1811205&referrer=RegressionActivityEmail


Bizarre d'ailleurs de ne pas avoir un test qui claque ici du coup :thinking: S'il y a bien un truc qui est sur le chemin critique, c'est bien poser un rendez-vous sur l'agenda :)

2021-04-13 08:37 UTC, n-b commented
Mm, je vois la 500 sur la review app mais pas en local. (Au moins ça explique pourquoi les tests n’échouent pas.)

2021-04-13 08:46 UTC, yaf commented
Ah oui. Ok, c'est peut-être lié à une migration ou une donnée inconsistante alors :thinking:

2021-04-13 13:20 UTC, yaf approved these changes
Ça fait du bien ce petit nettoyage.

Je ne suis pas à l'aise avec cette histoire de modal. Mais je crois que pour s'en passer nous avons besoin de réfléchir un peu en termes de design

Pour l'usage des FormObjects, je ne suis pas encore pleinement convaincu, mais je n'ai pas non plus d'argument contre. Je suis prêt à essayer encore un peu :)

2021-04-13 13:45 UTC, merged