Ajout d’une colonne “Actions” à admin/organisations/:id/agents
betagouv/rdv-solidarites.fr pull request #1314
Opened 2021-04-07 10:39 UTC by n-b

fixes #1267

Avec un design plus ou moins inspiré de Lieux#index.
* Ajout d’une colonne Actions, avec les boutons edit et delete
* Redesign pour déplacer les invitations en dessous, plutôt qu’à droite.
* Je n’ai pas réussi à utiliser les policies dans les vues, je me suis résolu à utiliser `current_agent_role.admin?`. C’est probablement faisable, mais je veux bien en parler, j’ai l’impression que c’est lié à des travaux en cours.

Ça permet aussi de répondre à  https://rdv-solidarites.zammad.com/#ticket/zoom/61, puisqu’on peut modifier les agents sans nom (voir aussi #1313)

2021-04-07 12:47 UTC, adipasquale commented
@n-b les tests ont l'air d'avoir planté j'attends que tu corriges pour review !

2021-04-07 13:37 UTC, adipasquale requested changes

2021-04-07 13:37 UTC, adipasquale commented on app/views/admin/agents/_agent.html.slim
> +  td.wo rd-break-all
je pense que c'est une typo

<img width="352" alt="Screenshot 2021-04-07 at 15 36 59" src="https://user-images.githubusercontent.com/883348/113875522-245fce80-97b7-11eb-8f14-e2711f2fcf7f.png">

2021-04-07 13:37 UTC, adipasquale commented on app/views/admin/agents/index.html.slim
> +    = link_to 'Inviter un agent', new_admin_agent_organisation_invitation_path(current_organisation), class:"btn btn-outline-white"
👍 pour harmoniser Professionnel -> Agent

2021-04-07 13:39 UTC, adipasquale commented
nitpick mais si tu as envie d'améliorer l'UI c'est cool de faire en sorte que les tableaux aillent jusqu'aux bords lateraux des cards : 

<img width="1006" alt="Screenshot 2021-04-07 at 15 39 07" src="https://user-images.githubusercontent.com/883348/113875864-79034980-97b7-11eb-8bbf-f524d0f5c6be.png">

2021-04-07 13:57 UTC, adipasquale commented on app/views/admin/agents/_agent.html.slim
> +      - if current_agent_role.admin?
`policy([:agent, agent_role]).destroy?` a l'air de bien fonctionner si tu rajoutes la methode correspondante dans la policy AgentRolePolicy. tu peux détailler ce que tu essayais de faire mais qui ne marchait pas pour toi ? je n'ai pas bien compris

2021-04-07 14:04 UTC, n-b commented on app/views/admin/agents/_agent.html.slim
> +      - if current_agent_role.admin?
Si, je pense que c’est ça. En fait, je suis un peu surpris que la policy n’existe pas déjà, vu qu’on ne rajoute pas d’action :-/

2021-04-07 14:04 UTC, n-b commented on app/views/admin/agents/_agent.html.slim
> +  td.wo rd-break-all
😱

2021-04-07 14:15 UTC, n-b commented
Sur les tables sans bordures, je veux bien, mais c’est pas le cas actuellement sur `admin/organisations/:id/lieux` et `admin/organisations/:id/motifs`. Je vais faire un test pour voir.

2021-04-07 14:16 UTC, n-b commented
D’ailleurs, c’est pas une card, c’est un container 😄

2021-04-07 14:33 UTC, adipasquale commented on app/views/admin/agents/_agent.html.slim
> +      - if current_agent_role.admin?
alors oui ca m'a surpris aussi mais je m'en souviens maintenant : 
- lorsque tu cliques sur supprimer en fait la route est `admin/agents#destroy` donc la policy probablement `AgentPolicy#destroy`
- c'est en partie correct : si tu cliques sur supprimer sur un agent qui n'appartient qu'a une orga, ca va supprimer d'abord le agentrole, puis l'agent lui meme
- par contre si tu cliques sur un agent qui appartient a d'autres orgas ca va seulement supprimer le AgentRole ... cette subtilité n'est pas prise en compte dans le check actuel des policies c'est pour ca qu'il faut la rajouter ici

je me souviens avoir changé a un moment pour ne supprimer QUE le agent role et jamais le compte agent automatiquemetn. ca pose un souci lorsque les agents veulent supprimer un compte agent et recréer le compte juste apres avec le meme email (par ex pour changer un agent de service)

2021-04-07 16:06 UTC, n-b commented on app/views/admin/agents/_agent.html.slim
> +        = link_to path, title: agent_removal_presenter.button_value, data: { confirm: agent_removal_presenter.confirm_message }, method: :delete do
Je le fais aussi pour le bouton [supprimer] dans `admin/organisations/1/agent_roles/1/edit`, du coup.

2021-04-07 16:19 UTC, n-b commented on app/views/admin/agents/index.html.slim
> +          th Actions
À vrai dire, il faudrait aussi que le lien du nom ne soit pas cliquable dans ce cas, ça essaye de nous emmener vers la page d’édition.

Pour la colonne d’actions, j’aurais tendance à vouloir la garder quel que soit le contexte. En fait, je me dis que je laisserais bien les icônes d’actions mais grisées, mais c’est pas vraiment le sujet.

2021-04-07 16:33 UTC, n-b commented
A priori, j’ai pris en compte les remarques, mais je passe en draft le temps de refaire une passe de test demain matin.

2021-04-08 08:06 UTC, adipasquale commented
@n-b je lance le re-deploy de la review app pour qu'elle soit a jour puis je review (c'est manuel depuis les GH actions) !

2021-04-08 08:16 UTC, n-b commented on app/helpers/admin_helper.rb
> +    end
Ça mérite peut-être un peu de discussion, ça. Si je dis pas de bêtise, `current_agent_can?` est utilisé dans les cas où il n’y a pas d’objet courant, c’est à dire, en gros, pour `#new?` `#create?` et `#index?`. J’ai cru comprendre dans d’autres apps que ce qui était courant c’était de passer la classe à la policy, ce qui donnerait quelque chose comme `policy([:agent, Lieu]).create?` dans notre example. Ça ne marche pas aujourd’hui, mais peut-être qu’on pourrait simplement déporter le mécanisme de `current_agent_can?` dans les policies pour les actions concernées.

2021-04-08 08:16 UTC, n-b commented on app/policies/agent/agent_policy.rb
> +    # Even admins cannot destroy themselves
Attention, changement de comportement! Je crois que c’est raisonnable.

Par contre, il reste un trou, que je n’ai pas voulu tirer dans cette PR: un admin peut se changer lui-même en `basic`. J‘ai arrêté là, parce que `current_agent_or_admin_in_record_organisation` ou des méthodes similaires existent dans plusieurs policies, et j’ai l’impression qu’il y a un refactor en cours avec `CurrentAgentInPolicyConcern`.

2021-04-08 08:16 UTC, adipasquale approved these changes
👍 works perfectly

2021-04-08 08:16 UTC, adipasquale commented on app/policies/agent/agent_policy.rb
> +    # Even admins cannot destroy themselves
👍

2021-04-08 08:16 UTC, adipasquale commented on app/helpers/admin_helper.rb
> +      mock = klass.new(organisations: [current_organisation])
j'admire ton Rails-fu :) mais je me demande si ça ne fait pas un peu trop de magie ce helper maintenant ... il faudra voir comment ça évolue et peut-être le supprimer ou le simplifier pour inliner les instanciations des mock objects

2021-04-08 08:17 UTC, adipasquale commented on app/policies/agent/agent_policy.rb
> +    # Even admins cannot destroy themselves
j'ai vu ça, mais ça n'est pas très gênant qu'un admin s'auto-dégrade je pense. Il y a normalement une validation pour empêcher qu'une orga se retrouve sans aucun admin par contre

2021-04-08 08:25 UTC, merged