ajout du endpoint pour les référents
betagouv/rdv-solidarites.fr pull request #1324
Opened 2021-04-09 13:48 UTC by qblanc

- Issue #1322 
- Fonctionnalité nécessaire dans le cadre de notre expérimentation avec les Ardennes.
- put /users/id/update avec un array d'id d'agents dans la requête pour assigner des agents à un usager

2021-04-09 16:51 UTC, yaf approved these changes
Vous n'écrivez pas de test de requête sur l'API ? Ça pourrait être pas mal je pense. On peut regarder ensemble si besoin.

2021-04-09 16:52 UTC, yaf commented
Dites-moi si vous voulez prendre le temps d'ajouter des tests. Sinon, je peux fusionner cette branche avec master.

2021-04-12 08:31 UTC, n-b requested changes

2021-04-12 08:31 UTC, n-b commented on app/controllers/api/v1/users_controller.rb
> +    if user.update(agents: agents)
Ce qui m’embête un peu, c’est que ce n’est pas vraiment une action `#update`, au sens REST: on ne peut pas mettre à jour les autres paramètres de l’utilisateur. Soit on fait une véritable action update, qui permet _aussi_ de modifier les agents; soit on faite une action spécifique pour ça, quelque chose comme `GET/PUT /api/v1/users/:id/agents_list`.

Par ailleurs, j’ai l’impression qu’il n’y a aucun moyen dans l’api de connaître les agents actuellement associés à un utilisateur, non?

2021-04-12 08:31 UTC, n-b commented on app/controllers/api/v1/users_controller.rb
> +      render json: { success: false }
Je crois que dans les autres controllers d’api, on utilise les codes http pour indiquer les erreurs, comme ceci:
`render( status: :unprocessable_entity, json: { success: false, … } )`.

2021-04-12 08:32 UTC, aminedhobb commented
> Vous n'écrivez pas de test de requête sur l'API ? Ça pourrait être pas mal je pense. On peut regarder ensemble si besoin.

Je suis d'accord qu'il faudrait rajouter des tests @yaf 👍 , je pense que @qblanc va les rajouter.
D'ailleurs est-ce que l'on pourrait être rajouté comme collaborateurs au projet pour que l'on puisse être désigné comme reviewer ? Dans un premier temps on ne mergera pas tant que ce n'est pas approuvé par un membre de votre équipe.

2021-04-12 11:22 UTC, qblanc commented on app/controllers/api/v1/users_controller.rb
> +    if user.update(agents: agents)
Il n'y a effectivement aucun moyen de connaître les agents actuellement associés à un utilisateur, mais est-ce qu'on en a besoin ?
Pour l'action à la base j'avais fait un put de ce genre, avec une route /referents, mais j'avais opté pour l'update dans l'idée qu'on pourrait y ajouter progressivement des éléments pour en faire un vrai update.
Dites moi ce que vous préférez, pas de souci pour changer

2021-04-12 12:49 UTC, n-b commented on app/controllers/api/v1/users_controller.rb
> +    if user.update(agents: agents)
Si #update existe, autant qu’il fasse ce à quoi on s’attend :)

Le truc qui me chiffonne, c’est que “les agents d‘un usagers” ne sont pas un attribut de usager, mais une association;
* soit on décide que c’est pas grave, et on gère agents_ids dans #show et #update, 
* soit on considère que c’est une sub-resource d’un user, et on fait une autre route.

Je sais pas si c’est clair, on peut prendre 5 minutes pour en discuter.

2021-04-13 10:18 UTC, aminedhobb commented
@qblanc du coup après notre réunion avec les Ardennes je ne suis pas sûr que cette fonctionnalité soit nécessaire pour le moment non ?

2021-04-13 12:32 UTC, qblanc commented
yes pour l'instant ce n'est plus nécessaire. Est-ce que vous voulez que je ferme la PR ?

2021-04-13 12:55 UTC, yaf commented
Je vais la supprimer oui. Merci !

2021-04-13 12:55 UTC, closed without merging