SMS-Configuration #1 configure les notifications SMS en DB territoire
betagouv/rdv-solidarites.fr pull request #1441
Opened 2021-05-10 11:02 UTC by yaf

Première PR à livrer pour le ticket #1408 

Ajout de deux colonnes à la table de territoire ;
Ajoute un Enum et une gem lié https://github.com/bibendi/activerecord-postgres_enum

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-05-10 15:48 UTC, n-b reviewed
👍 À part ça c’est cool

2021-05-10 15:48 UTC, n-b commented on app/models/territory.rb
> +  }.freeze
Tout ça fonctionne main dans la main avec `SendTransactionalSmsService` qui doit implémenter une méthode `send_with<provider>`. Ça mérite un petit commentaire, non?

2021-05-10 15:58 UTC, yaf commented on app/models/territory.rb
> +  }.freeze
C'est aussi (surtout ?) très lié à une vue : https://github.com/betagouv/rdv-solidarites.fr/pull/1411/files#diff-9d0de39b3a7ddfb63b276fd535b20cc1256e3c5a9e0c16c55419df5c53d85b7bR14 
Je pourrais le déplacer là-bas, ou lui donner un autre nom. :thinking: Voir, faire une vue spécifique par `provider`. J'avais commencé comme ça... Et puis j'ai exploré une autre voie.

Je vais reprendre pour utiliser une vue partiel par `provider` pour l'édition, et supprimer ce point. Merci !

2021-05-10 16:23 UTC, yaf commented on app/models/territory.rb
> +  }.freeze
Bon, finalement je l'ai laissé, mais c'est dans la 3ᵉ PR. Pas besoin de l'avoir ici. Je l'ai renommé et ajouté un commentaire.

2021-05-10 17:25 UTC, yaf commented on app/models/territory.rb
> +  }.freeze
Comme tu le suggères sur l'autre PR, j'ai ajouté des validations qui s'appuie sur cette structure. Je l'ai donc renommé en espérant que ça suffise. Sinon, j'ajouterais un commentaire

2021-05-11 07:49 UTC, n-b requested changes
À part ça 👍

2021-05-11 07:49 UTC, n-b commented on app/models/territory.rb
> +    FIELDS_FOR_SMS_CONFIGURATION[sms_provider.to_sym] - (sms_configuration.keys || [])
Ici ça crashe si `sms_provider` est nil (idem pour `sms_configuration`, d’ailleurs). La CI échoue sur les seeds à cause de ça.

2021-05-11 08:49 UTC, yaf commented on app/models/territory.rb
> +    FIELDS_FOR_SMS_CONFIGURATION[sms_provider.to_sym] - (sms_configuration.keys || [])
Ah, mais oui, il manque une garde. merci

2021-05-11 14:18 UTC, merged