DO NOT MERGE/Landing page d'invitation pour emailless users
betagouv/rdv-solidarites.fr pull request #1452
Opened 2021-05-12 16:37 UTC by qblanc

Dans cette PR, j'introduis la logique permettant aux utilisateurs sans email de créer leur profil en se reliant au compte créé pour eux par un tiers (les départements, par exemple) grâce à un code envoyé par courrier.

Ce qu'il reste à faire :
- simplifier le token d'invitation : pour l'instant, il ressemble à quelque chose comme "JhHnH6zo81xRiUfp-z8", cela me paraît trop effrayant/compliqué/risqué à recopier au clavier pour des publics peu à l'aise avec le numérique.
- s'accorder sur le ou les champs réclamés à l'utilisateur pour accéder à la page edit (qui permet de "prendre possession" du compte contenant des infos personnelles). On pourrait imaginer se passer du code envoyé par courrier en demandant une combinaison numéro d'affiliation + date de naissance ou nom, par exemple, mais est-ce que cela serait suffisamment sécurisé ? Et quid si le nom ou la date de naissance a été mal renseigné par l'utilisateur, et que son compte a été créé avec des informations qu'il ne parviendra pas à répliquer correctement ? Les seuls infos que l'administration connaît de manière 100% fiable sur lui, qui ne relèvent pas du déclaratif, me paraissent le numéro d'affiliation et un éventuel code envoyé par courrier (mais je me trompe peut-être). Pour l'instant, c'est pour cette raison que j'ai choisi ces deux champs.
- rajouter des tests

2021-05-17 07:22 UTC, yaf approved these changes

2021-05-17 07:23 UTC, yaf commented
Ça me semble très bien. Merci pour cette PR :)

2021-05-17 14:59 UTC, n-b requested changes
Je crois qu’on peut customiser Devise pour rentrer dans le mode normal sans avoir à bypasser la sécurité. Il faut faire un generateur de token custom, qui créée un “raw token” de 8 caractères, et la suite devrait se faire toute seule.

À vue de nez, on peut remplacer Devise::TokenGenerator par notre version custom, mais continuer d’utiliser le générateur de base si le compte à inviter a un email. Est-ce que c’est le critère?

2021-05-17 14:59 UTC, n-b commented on app/views/users/invitations/new.html.slim
> +        .col-md-12= f.input :affiliation_number, label: 'Identifiant CAF', placeholder: '123456'
`affiliation_number` est traduit comme “Numéro d'allocataire”, est-ce qu’on peut le garder tel quel? En fait, si ça peut être différent, autant faire un nouvel attribut.

2021-05-17 14:59 UTC, n-b commented on config/routes.rb
> +    post "invitation", to: "users/invitations#redirect", as: "invitations_landing_redirection"
En principe, on peut donc se passer de routes custom (et de noms personnalisés pour les helpers)

2021-05-25 11:09 UTC, n-b reviewed
👍 sinon je crois que c’est bon, ça m’a l’air correct. @qblanc tu as encore des modifs en cours à part les corrections pour la CI?

2021-05-25 11:09 UTC, n-b commented on app/models/user.rb
> +        break [raw, enc] unless User.where(invitation_token: enc).size > 0
Est-ce que tu peux mettre tout le `else` dans une autre méthode, du genre `generate_short_invitation_token`, avec des commentaires pour expliquer pourquoi on fait ça?

Ça vaut peut-être aussi le coup de créer une issue sur le sujet, histoire de pouvoir la référencer depuis le code et par la suite quand on va rediscuter d’authentification.

2021-05-25 11:09 UTC, n-b commented on app/views/users/invitations/landing.html.slim
> +- content_for :title, "Inscription"
Est-ce que tu peux mettre les textes d’interface dans des fichiers .yml? Tu sais comment faire pour réferencer les clés i18n avec le nom de la vue courante?

(on est loin d’être au clair sur l’internationalisation, mais j’essaie de le faire au moins sur les nouvelles vues.)

2021-05-25 11:09 UTC, n-b commented on config/routes.rb
> +    get "invitation", to: "users/invitations#landing", as: "invitations_landing"
Ça nous fait une page publique `rdv-solidarites.fr/invitation`? j’aime bien 👍 

Si vous avez besoin d’un nom de domaine raccourci, on peut peut-être acheter un truc du genre rdvsoli.fr.

2021-05-25 11:09 UTC, n-b commented on config/locales/models/user.fr.yml
> +        invitation_token: "Code d'invitation"
```suggestion
        invitation_token: "Code d’invitation"
```

👋 J’aime bien les apostrophes courbes.

2021-05-25 11:09 UTC, n-b commented on config/routes.rb
> +    get "invitation", to: "users/invitations#landing", as: "invitations_landing"
Ah d’ailleurs, si ça ne fait pas de conflit, on peut aussi bien appeler l’action `invitation` au lieu de `landing`? Je suis partagé parce que ça serait un peu bizarre comme nom pour le helper, mais j’aime bien quand l’action et le path ont le même nom.

2021-05-26 07:30 UTC, n-b reviewed
Je crois qu’on est presque bon, j’ai bientôt fini de t’embêter 🙇 

Pour user.rb qui est trop longue, tu peux rajouter une exception dans rubocop.yml. Elle est effectivement trop longue, mais les méthodes que tu y rajoutes sont pertinentes à cet endroit 🤷.

2021-05-26 07:30 UTC, n-b commented on app/controllers/users/invitations_controller.rb
> +      request.referer.end_with?("/invitation") ? (redirect_to invitations_landing_url) : (redirect_to after_sign_out_path_for(resource_name))
(Ah ok, c’est pas super lisible le style de Devise 😓)
Si je lis bien, la seule différence c’est le redirect? Je _pense_ que tu pourrais juste override  `after_sign_out_path_for`.

2021-05-26 08:46 UTC, aminedhobb reviewed
Ça me paraît good dans l'ensemble, good job @qblanc 👏  !
Je t'ai laissé une petite question pour être sûr de bien comprendre.

2021-05-26 08:49 UTC, qblanc commented on app/controllers/users/invitations_controller.rb
> +    unless params[:invitation_token] && self.resource = resource_class.find_by_invitation_token(params[:invitation_token], true)
Je suis en train de virer cet override, mais j'avais repris le code de Devise ici, sinon je suis d'accord sur le `unless` qui peut vite être tricky

2021-05-26 08:51 UTC, qblanc commented on config/routes.rb
> +    get "invitation", to: "users/invitations#invitation", as: "invitations_landing"
on l'avait appellée `landing` avant, mais @n-b préfère que le nom de l'action corresponde au nom du path. Perso tout me va :)

2021-05-26 09:18 UTC, aminedhobb commented on app/controllers/users/invitations_controller.rb
> +  def resource_from_invitation_token
Ah ok

2021-05-26 11:15 UTC, qblanc commented
Normalement tout devrait être ok maintenant, si ça vous va est-ce qu'on peut le merge ? Le deploy en prod se fait automatiquement ? On aimerait pouvoir commencer à tester demain avec un département.

2021-05-26 14:52 UTC, n-b commented on app/controllers/users/invitations_controller.rb
> +    root_url
Ah, appelle `super` plutôt: on fait un truc un peu tricky dans `ApplicationController` pour FranceConnect, je suis pas sûr de ce que ça implique 😅 

Oh, et c’est `after_sign_out_path_for(resource)`. Même si ce controller n’est pas appelé avec autre chose que des User. Devise ne se plaint pas pour le paramètre manquant ?

2021-05-26 14:58 UTC, qblanc commented on app/controllers/users/invitations_controller.rb
> +    root_url
Non, mais je l'avais mis à la base, et Rubocop se plaint quand je le met car il n'est pas utilisé :)

2021-05-26 19:17 UTC, n-b approved these changes
👍 👏 

Pour le token transmis au usagers: en testant j’ai eu par exemple `sA32s_RV`, ce qui n’est peut-être pas très simple à taper pour des _gens normaux_.

Utiliser `SecureRandom.choose` à la place de `friendly_token` vous permettrait peut-être de limiter à des chiffres ou à des lettres; si vous mettez des lettres, pensez aussi à ne choisir que des minuscules (ou des majuscules).

2021-05-27 06:36 UTC, merged