1405 modif referents sans supprimer
betagouv/rdv-solidarites.fr pull request #1511
Opened 2021-06-11 17:40 UTC by yaf

close #1405 

Comme nous l'avions évoqué, j'ai modifié la façon d'interagir avec les référents.
- L'agent ne vois que les référents pour lesquels il est habilité
- L'agent peut supprimer un référent à la fois
- L'agent peut ajouter un référent à la fois.

J'ai ajouté un lien « retiré X » à côté des noms de référents.

![Screenshot_2021-06-11 Léa DUPONT - RDV Solidarités](https://user-images.githubusercontent.com/42057/121727878-c91ac700-caec-11eb-9ea6-b06bc0338d29.png)

Le bouton modifié (remis en bas de la carte, comme pour les autres) amène à une page listant les agents disponibles pour être référent. 
Un bouton sur chaque carte d'agent permet de l'ajouter comme référent.

![Screenshot_2021-06-11 Ajouter un référent à Léa DUPONT - RDV Solidarités](https://user-images.githubusercontent.com/42057/121727899-cfa93e80-caec-11eb-9967-7f3f15b1617a.png)

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-06-14 13:53 UTC, n-b requested changes
J’ai des remarques de design ! 😬  

1. sur la liste des référents, j’aimerais bien qu’on commence à utiliser un style cohérent. Par exemple pour la liste des agents, c’est une table avec une colonne “Actions”, je crois qu’on pourrait faire pareil ici, même si c’est plus étroit.

2. Au final c’est un peu lourd, la page intermédiaire pour “new”, non? Je sais que c’est pas ce qu’on avait dit, mais est-ce qu’un bête `select` et un bouton “ajouter” dans la liste des référents existants ne suffirait pas ?

2021-06-14 13:53 UTC, n-b commented on app/models/agent.rb
> +    where.not(id: [user.agents.map(&:id)])
```suggestion
    where.not(id: user.agents.ids)
```
c’est un poil moins cher que `map(&:id)` 😄 . Il y avait aussi des `[]` en trop ou c’est moi qui n’ai pas bien compris?

2021-06-14 13:53 UTC, n-b commented on app/views/admin/referents/new.html.slim
> +
Je vais ajouter un linter pour les fichiers slim, les lignes vides comme ça ça risque de couiner 🤔

2021-06-14 13:53 UTC, n-b commented on app/views/admin/referents/new.html.slim
> +          p.card-text = agent.service.name
Il y a un form par agent, c’est bien ça? Pas la peine de faire un `simple_form`, non? À la limite, un `link_to … method: :post` pourrait suffire, je crois.

2021-06-14 15:56 UTC, yaf commented
Yep, effectivement, ça paraît un peu lourd. Et je me dis que c'est malgré tout peut-être plus simple pour les utilisateurs. Ces listes déroulantes ne sont pas pratiques à manipuler, surtout quand il y a 10 agents dans ton service... Et c'est encore pour les personnes du secrétariat ou de l'admin qui ont tous les services.

Alors oui, il y a la zone de recherche, et j'ai l'impression que c'est un outil de poweruser. Pas du tout adapté à des personnes qui ne serait pas très à l'aise avec le numérique.

La liste en carte me semble plus adapté qu'une liste en tableau. Par contre, c'est vrai que ça fait un écart avec ce qui existe... Je ne sais pas comment nous pourrions définir ce qui est le plus simple à utiliser pour les agents : les listes en tableau ou bien les listes en cartes ?

Peut-être que pour l'instant je peux faire une liste en tableau afin de garder la cohérence, et que si un jour on décide de changer, on changera toutes les listes en quelques jours ?

2021-06-14 16:36 UTC, n-b commented
Effectivement, j’ai testé en local avec 3 agents, je me rendais pas compte que dans la réalité il y en a des dizaines. Par contre, je préfère clairement une table plutôt que des cartes, ça permet de chercher plus facilement. D’ailleurs, peut-être qu’ici, un layout étroit se justifie?

2021-06-14 18:13 UTC, yaf commented
Yep, peut-être. J'essaie de trouver un icon font-awsome qui va bien pour la sélection d'un agent et je pousse une nouvelle version en tableau.

2021-06-15 11:50 UTC, yaf commented
Pas très inspiré sur l'icône à utiliser.

![Screenshot_2021-06-15 Ajouter un référent à Léa DUPONT - RDV Solidarités](https://user-images.githubusercontent.com/42057/122047591-9ae50200-cde0-11eb-8ff3-ab40c971a926.png)

2021-06-23 13:39 UTC, n-b approved these changes
👍 à part la majuscule (et le tri?)

Peut-être que dans la page des référents, il faudra ajouter un champ de recherche: je sais pas combien de référents il y a au maximum dans les organisations en prod.

2021-06-23 13:39 UTC, n-b commented on app/views/admin/referents/index.html.slim
> +                      span> ajouter
A majuscule comme sur Retirer
```suggestion
                      span> Ajouter
```

2021-06-23 13:39 UTC, n-b commented on app/controllers/admin/referents_controller.rb
> +    @referents = policy_scope(@user.agents).distinct
Tiens justement, on pourrait les trier par nom-prénom?

2021-06-23 14:42 UTC, yaf commented on app/controllers/admin/referents_controller.rb
> +    @referents = policy_scope(@user.agents).distinct
Ah oui tiens.

2021-06-23 14:46 UTC, yaf commented
Pour la recherche, je pense qu'on ne passera pas une autre PR.

2021-06-23 21:16 UTC, yaf commented on app/controllers/admin/referents_controller.rb
> +    @referents = policy_scope(@user.agents).distinct
J'ai préféré rassembler les agents, les trier par nom de famille, plutôt que d'afficher les référents en haut et les autres en bas. Ça perturbais ce tri assez bizarre je trouve.

2021-06-23 21:19 UTC, yaf commented on app/controllers/admin/referents_controller.rb
> +    @referents = policy_scope(@user.agents).distinct
Ça sera intéressant d'ajouter un champ de filtre / recherche.

2021-06-24 07:18 UTC, merged