affiche la durée du rendez-vous coté usager
betagouv/rdv-solidarites.fr pull request #1559
Opened 2021-07-05 06:49 UTC by yaf

close #1555 

J'ai ajouté la durée dans le rendez-vous à partir du FormObject pour faire court.

Ceci dit, j'ai l'impression que tout ce « rdv wizard » pourrait être nettoyé. La prochaine fois sans doute.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-07-05 09:32 UTC, n-b commented
(fermé-réouvert pour redémarrer proprement le déploiement de la review app scalingo)

2021-07-05 13:19 UTC, n-b requested changes

2021-07-05 13:19 UTC, n-b commented on app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
> +        = rdv_time_and_duration(rdv_wizard.rdv)
Ça donne ça: 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/139391/124476564-44e1f980-dda3-11eb-89e5-5f1ad6a832c1.png">

Du coup il faudrait afficher le jour quelque part quand même 😬

2021-07-05 13:19 UTC, n-b commented
À un moment il faudra discuter du critères selon lequel on écrit “13h46” ou “13:46”. En général, on préfère “13:46” dans une table, et “13h46” dans une phrase.

2021-07-07 06:42 UTC, yaf commented on app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
> +        = rdv_time_and_duration(rdv_wizard.rdv)
Effectivement ! Je vais peut-être faire un autre format.

2021-07-07 06:53 UTC, yaf commented on app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
> +        = rdv_time_and_duration(rdv_wizard.rdv)
Voilà, c'est réparé !

![Screenshot_2021-07-07 Inscription - RDV Solidarités](https://user-images.githubusercontent.com/42057/124713425-d6b34900-df00-11eb-843b-6481a2c0f28a.png)

2021-07-07 08:07 UTC, n-b approved these changes

2021-07-07 08:13 UTC, merged