expire les absences selon la récurrence
betagouv/rdv-solidarites.fr pull request #1631
Opened 2021-08-13 12:37 UTC by yaf

Close #1613 

Affiche dans les présents les absences dont la date de fin est passé, mais pour lesquelles la récurrence est encore valable.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-08-13 14:36 UTC, n-b requested changes
👍 Sinon c’est très cool, simple et efficace. Dans PlageOuverture, la colonne s’appelle `expired_cached`, est-ce qu’on en profiterait pas pour s’assurer que c’est cohérent? Sans factoriser le code, hein, mais au moins pour que ça soit la même solution.

2021-08-13 14:36 UTC, n-b commented on app/models/absence.rb
> +  def expired?
Mmm, il me semble que ActiveRecord, par défaut, génère des accesseurs avec un `?` pour les attributs booléens, donc ça fait confusion ici: sans cette implémentation `absence.expired?` retournerait simplement la valeur de la colonne. Il faudrait un nom plus explicite: quelque chose comme `def recurrence_is_expired?` ?

2021-08-13 14:36 UTC, n-b commented on db/migrate/20210813115346_add_expire_to_absence.rb
> +    add_column :absences, :expired, :boolean
C’est un peu un réflexe pavlovien, mais j’aime bien les colonnes nonnull :)
```suggestion
    add_column :absences, :expired, :boolean, null: false, default: false
```

2021-08-13 14:36 UTC, n-b commented on spec/models/absence_spec.rb
> +      today = Time.zone.parse("20210323 13:45")
J’adore `Time.zone.parse`, ça mange vraiment tous les formats qu’on peut lui donner 😅

2021-08-13 16:11 UTC, yaf commented on app/models/absence.rb
> +  def expired?
J'ai changé le nom de la colonne pour correspondre à ce qu'il y a dans plage d'ouverture (expired_cached) et du coup, j'ai laissé le nom `expired?` comme dans les plages d'ouvertures.

Je pense que nous pourrions sans doute factoriser ce code... Ça me dérange un peu un concern, mais là, c'est sans doute le truc adapté :-/

2021-08-16 14:56 UTC, n-b commented on app/models/concerns/expiration.rb
> +
Ça me parait cool comme concern. Dans une autre vie, un CTO avait donné comme conseil pour “quand factoriser” d’attendre la troisième occurence, et pour la deuxième de se contenter de copier-coller. Dans le cas présent, ça me parait suffisamment général pour valoir le coût tout de suite, donc 👍 .

Par contre ça serait bien de mettre un peu de doc, notamment les attributes nécessaires dans la classe de base pour que ça fonctionne. Ici, si je comprends bien, `expired_cached (bool)` et `recurrence (Montrose-formatted string)`?

2021-08-17 07:18 UTC, yaf commented on app/models/concerns/expiration.rb
> +
Tiens je ne connaissais pas ce « conseil » :) Je ne sais pas si je vais le suivre tout le temps, mais merci pour le partage ! :)


Pour la doc, oui, pourquoi pas. J'ajoute.

2021-08-19 07:53 UTC, n-b approved these changes

2021-08-19 08:09 UTC, n-b requested changes
Il y a un petit souci sur le badge “Passée”: je crois que `AbsencesHelper::absence_tag` ne prend pas en compte la récurrence.

<img width="1124" alt="Capture d’écran 2021-08-19 à 10 05 32" src="https://user-images.githubusercontent.com/139391/130031793-73e03e7e-1c5c-4b4f-8775-34758ecb1026.png">


D’ailleurs, je suis pas sûr de comprendre la gestion de la date de fin dans Absence.rb. Pourquoi est-ce que dans `set_end_day` on met la date de fin à la date de début? C’est bizarre, et à l’affichage d’une absence récurrente sans fin, c’est étrange.

2021-08-20 15:22 UTC, yaf commented
> D’ailleurs, je suis pas sûr de comprendre la gestion de la date de fin dans Absence.rb. Pourquoi est-ce que dans set_end_day on met la date de fin à la date de début? C’est bizarre, et à l’affichage d’une absence récurrente sans fin, c’est étrange.

C'est un sujet qui a trainé longtemps dans les tickets par ici : la confusion entre la date de fin de récurrence et la date de fin...

Ce que je vois à l'usage, c'est que souvent, il y a une date de début, et, 
- quand on ne précise pas la date de fin, c'est que c'est juste pour cette journée (ce qui a été fait pour le moment, pour ce cas-là, c'est de copier la date de début dans la date de fin)
- quand on précise la date de fin, c'est que c'est sur une période donnée, qui en général ne se répète pas (donc souvent, pas de récurrence, mais ce n’est pas toujours vrai je pense, il faudrait vérifier)
- Quand c'est une seule journée, elle est parfois répétée. C'est un peu comme moi qui ne suis jamais là le mercredi par exemple. Si on devait gérer un agenda de l'équipe RDV-Solidarités pour afficher nos disponibilités pour que des personnes puisse prendre rendez-vous avec nous au tel, et bien je poserais sans doute une absence d'une journée un mercredi, puis je placerais une récurrence tout les mercredi.

Bon, je me doute que tu avais compris tout ça, et effectivement, je trouve que ce n'est pas clair. Ceci étant, je n'ai pas trouvé d'autres propositions pour le moment.

2021-08-20 15:43 UTC, yaf commented
J'ai repris tout les commits pour reprendre la migration... Cette PR à trop trainé et ça posait un problème avec les PR qui étaient passées entre temps.

J'ai également ajouté un test pour AbsencesHelper et fait quelque correction dedans. Je pense que c'est tout bon maintenant :)

2021-08-23 08:55 UTC, n-b commented on app/helpers/absences_helper.rb
> +      absence.recurrence.lazy.map(&:to_date).select { |d| d > Time.zone.now }.take(1).any?
Bizarre de devoir chainer tout ça. `.any?` ne prend pas un block? On pourrait faire `absence.recurrence.any?{ |r| r.to_date > today }`

2021-08-23 08:57 UTC, n-b commented on app/helpers/absences_helper.rb
> +      absence.recurrence.lazy.map(&:to_date).select { |d| d > Time.zone.now }.take(1).any?
D’ailleurs attends, ça sert pas à la même chose justement que la nouvelle méthode `expired?` du concern?

2021-08-23 09:25 UTC, yaf commented on app/helpers/absences_helper.rb
> +      absence.recurrence.lazy.map(&:to_date).select { |d| d > Time.zone.now }.take(1).any?
Ce n’est pas tout à fait la même chose. Là, nous cherchons une absence qui n'a pas expirée ET qui a commencée. D'où le fait de tester d'abord le «today » pour celles qui ne sont pas récurrente, puis, pour les récurrentes, de vérifier que c'est une date de début dans le passé, avec une récurrence toujours en cours.

Il y a sans doute moyen de faire plus simple, mais là, je ne vois pas :thinking:

2021-08-23 09:27 UTC, yaf commented on app/helpers/absences_helper.rb
> +      absence.recurrence.lazy.map(&:to_date).select { |d| d > Time.zone.now }.take(1).any?
Enfin, si, comme `any?` prend un bloc, il y a moyen de faire ça mieux... Mais je ne vois pas comment utiliser le `expired?`

2021-08-23 10:02 UTC, n-b approved these changes

2021-08-23 10:02 UTC, merged