Bump to ruby 3 (encore une fois)
betagouv/rdv-solidarites.fr pull request #1712
Opened 2021-09-13 16:14 UTC by n-b

Résumé des épisodes précédents:

* #1648
* #1688

For some reason in Ruby 3, encoding ActiveRecord objects in JSON takes a different path.
I tracked it down to ActiveSupport::ToJsonWithActiveSupportEncoder:
In ruby 3, options.is_a?(::JSON::State), in ruby 2.7 it uses ActiveSupport::JSON regularly.

The best source I can find is this SO discussion: https://stackoverflow.com/questions/66871265/to-json-on-activerecord-object-ruby-3-0

The workaround is to manually convert to json.

2021-09-13 20:55 UTC, yaf submitted a review, later dismissed

2021-09-13 20:58 UTC, yaf requested changes
J'ai une erreur 500 quand j'essaie de créer un RDV

https://sentry.io/organizations/rdv-solidarites/issues/2646393480/?referrer=alert_email&environment=staging

2021-09-14 07:21 UTC, n-b commented
Mmm, je crois que c’est une erreur de chargement bizarre au premier déploiement, un truc qu’on voit depuis un moment et qu’on n’arrive pas à reproduire en local. Y’a régulièrement la même chose sur les review apps, souvent il faut déployer une deuxième fois. Je crois que Adrien avait des notes sur le sujet 🤔

2021-09-14 13:31 UTC, yaf approved these changes
:rocket:

2021-09-20 10:38 UTC, merged