stock et affiche la commune de l'usager
betagouv/rdv-solidarites.fr pull request #1715
Opened 2021-09-13 22:37 UTC by yaf

close #1638

2021-09-14 07:09 UTC, n-b requested changes
🚀 yeah, super que ça avance. Par contre je pense qu’on va se faire [rate-limiter](https://geo.api.gouv.fr/faq) assez rapidement. On peut utiliser l’api de geocodage de masse par csv, ça me parait nettement plus fiable. Il y a 63930 users avec des adresses en base, avec des batch de 100 ou de 1000 ça devrait aller vite.

2021-09-14 07:14 UTC, yaf commented
Ah oui, je n'y avais pas pensé, c'est beaucoup mieux.

Je vais remettre cette PR en draft le temps de m'en occuper.

2021-09-20 10:18 UTC, n-b requested changes
Oui, autant utiliser Typhoeus qu’on a déjà en dépendance, non? Ou alors RestClient a un avantage particulier?

2021-09-20 10:18 UTC, n-b commented on scripts/update_city_name_from_address.rb
> +      next if user.address.blank?
`User.where.not(address: nil).pluck(:id, :address)`, non?

Il y 150000 usagers en base, la limite de taille du csv d’après la doc (https://geo.api.gouv.fr/adresse) est 50 Mo, je crois qu’on est large. J’ai un peu peur de tout faire d’un seul coup plutôt qu’en batches, mais ça devrait quand même passer.

2021-09-20 10:18 UTC, n-b commented on scripts/update_city_name_from_address.rb
> +puts "mise à jour du nom de vile de l'usager à partir de son adresse"
```suggestion
puts "mise à jour du nom de ville de l'usager à partir de son adresse"
```

2021-09-20 10:18 UTC, n-b commented on scripts/update_city_name_from_address.rb
> +  result_lines = CSV.parse(response.body, encoding: response.encoding)[1..]
Là, tu stockes en mémoire l’intégralité du csv, et on en fait un tableau à côté. Ça va faire un gros gros pic mémoire, c’est dans un script donc même si ça passe pas, ça n’aura pas d’impact sur la prod, mais quand même 😅 .

Si je me souviens bien, tu peux passer un block à `CSV.parse`, ce qui permet au CSV de ne pas être entièrement lu en un seul coup. Il y a aussi une option pour utiliser le premier row comme noms de colonnes et ensuite obtenir un hash (plutôt qu’un array) pour chaque row.

2021-09-20 10:18 UTC, n-b commented on scripts/update_city_name_from_address.rb
> +    User.find(id).update(
On va faire plusieurs dizaines de milliers de `update`, c’est un peu violent 😅. Je crois qu’on peut bypasser les validations et les hooks de ActiveRecord (avec `update_column`): ça ira beaucoup plus vite, et en plus ça évitera de mettre à jour `updated_at`.

Je crois aussi qu’on peut utiliser `update_all` en passant un array d’id, mais je sais plus exactement comment on fait. Ça, ça permettrait de ne faire qu’une requête sql 🚀 .

2021-09-20 23:04 UTC, yaf commented on scripts/update_city_name_from_address.rb
> +    User.find(id).update(
Je me suis battu;
j'ai même fini par essayé d'écrire une requête SQL un peu tordu...

Je n'ai pas réussi.
Retour donc à un parcour du talbeau avec un `User.find` et un`update_columns` histoire de ne pas déclencher les validations.

Le `update_all` ne permet pas vraiment d'avoir des valeurs différentes pour chaque objet ;
Le `update` est plutôt intéressant, mais fait une requête SQL à chaque objet (pour déclencher les validations)

2021-09-20 23:07 UTC, yaf commented
:tired_face: dur PR :smile:

2021-09-21 09:24 UTC, n-b approved these changes
🚀 Ça m’a l’air ok: juste, je ne suis pas certain de comprendre le but des champs hidden?

2021-09-21 09:24 UTC, n-b commented on app/views/admin/users/_responsible_form_fields.html.slim
> +
Ah, j’avais raté ça à la précédente lecture: ça sert à quoi de mettre ces champs dans le formulaire?

2021-09-21 09:24 UTC, merged

2021-09-21 16:57 UTC, yaf commented on app/views/admin/users/_responsible_form_fields.html.slim
> +
Pour que l'appel JS qui autocomplete l'adresse à partir de l'appel à la BAN remplisse ces champs pour les nouveaux usagers.