Add recette/deployment tasks to the Makefile
betagouv/rdv-solidarites.fr pull request #1722
Opened 2021-09-15 09:34 UTC by n-b

Je me demande si ça devrait être un script, mais j’ai envie de garder les choses les plus basiques possible.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-09-15 21:38 UTC, yaf requested changes
J'aurais besoin d'ajouter le `--rebase` pour que ça puisse fonctionner sur mon environnement...

Pour le reste, je trouve que ce n’est pas si mal ici.
Peut-être que l'appel d'un script externe permettrait d'avoir moins d'entrée dans ce fichier, mais est-ce bien gênant ?

2021-09-15 21:38 UTC, yaf commented on Makefile
> +	git checkout production && git pull origin production:production
Pourquoi tu parles de `fetch` alors que tu `pull` ?

J'ajouterais `--rebase` pour être sûr que ça fasse un `rebase` :)

_Sans aucune option dans le `.gitconfig` tu es obligé de préciser au moment de faire le `git rebase`_

2021-09-15 21:38 UTC, yaf commented on Makefile
> +recette_deploy_to_production: recette_fetch recette_rebase_onto_production recette_merge_in_production ## Deploy the current status of recette to production
:+1:

2021-09-20 11:12 UTC, n-b commented on Makefile
> +	git checkout production && git pull origin production:production
Mmm en principe, dans le cas de `recette` et `production`, si tu as des commits en local qui ne sont pas présents sur le remote, c’est probablement une erreur, donc je ne voudrais ni rebaser, ni merger. Je me demande si j’oublie quelque chose, sinon on peut mettre `--ff-only` ici aussi.

2021-09-20 20:53 UTC, yaf commented on Makefile
> +	git checkout production && git pull origin production:production
Je pensais que c'était nécessaire de préciser le « mode » de `pull` mais sans doute pas dans tout les cas.

2021-09-20 20:54 UTC, yaf approved these changes

2021-09-21 09:27 UTC, n-b commented on Makefile
> +	git checkout production && git pull origin production:production
Si si, je voulais juste dire qu’on ne veut pas faire un rebase, justement, parce qu’en principe il n'y a pas de commits à rebaser.

2021-09-22 08:20 UTC, merged