Ajoute zone de pagination en bas de page motifs
betagouv/rdv-solidarites.fr pull request #1727
Opened 2021-09-17 11:59 UTC by yaf

Close #1726 

Ajoute une zone de pagination en bas de la page des motifs

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-09-22 08:11 UTC, n-b requested changes
À part ça c'est cool. Est-ce qu’on ne veut pas le faire sur toutes les vues paginées?

2021-09-22 08:11 UTC, n-b commented on app/views/admin/motifs/index.html.slim
> +      .d-flex.justify-content-center id="users-pagination"
Attention, ça fait deux éléments avec l'id `users-pagination`. J’ai pas l’impression que cet id ne soit référencé nulle part cela dit, je crois qu’on peut ne pas le mettre :)

2021-09-22 08:11 UTC, n-b commented on app/controllers/super_admins/application_controller.rb
> -    # end
Ah, en fait j’aurais bien dé-commenté cette méthode, j’aime bien pouvoir customiser le `per_page` à la main. (Mais effectivement, soit on l'active soit on la supprime. J’ai pas d’avis fort.)

2021-09-22 21:37 UTC, yaf commented on app/controllers/super_admins/application_controller.rb
> -    # end
ça ne fonctionne que dans le super admin. Pour le faire ailleurs, il faudrait la mettre ailleurs :)

2021-09-22 21:42 UTC, yaf commented
Sans doute. Vu la pile de truc à faire, je n'ai pas pris le temps de me balader dans chaque page où l'on pagine pour doubler ce bout de code. :-/

C'est peut-être pas si long...

2021-09-23 09:08 UTC, n-b approved these changes

2021-09-23 09:08 UTC, merged