ajoute des éléments de doc technique
betagouv/rdv-solidarites.fr pull request #1738
Opened 2021-09-21 19:43 UTC by yaf

En nettoyant la doc du gitbook, j'ai rapatrié quelques éléments ici.

2021-09-22 09:10 UTC, n-b requested changes
🤔 dans #1699 j’avais justement sorti une partie de ce texte du fichier contributing pour tout réunir dans /docs; en gros, la plupart de ce contenu existe déjà dans 1-installation et 2-contributions, non?

2021-09-22 22:07 UTC, yaf commented
Effectivement, je n'avais pas fait attention au `2-contributions.md`.

2021-09-23 16:58 UTC, n-b approved these changes

2021-09-23 16:58 UTC, n-b commented on INSTALL.md
> +[Cf docs/1-installation.md](docs/1-installation.md)
Haha merci de corriger mes liens. C’est donc à ça que servent les cms 😓

2021-09-23 16:58 UTC, merged