Ne pas permettre l'invitation depuis l'app web des utilisateurs de certaines organisations
betagouv/rdv-solidarites.fr pull request #1740
Opened 2021-09-22 17:36 UTC by qblanc

[Issue 66 de RDV-Insertion](https://github.com/betagouv/rdv-insertion/issues/62)

Lorsque l'on invite un usager à s'inscrire sur RDV-Solidarités depuis rdv-insertion (processus d'invitation géré en autonomie de celui de rdv-solidarités), il est toujours possible de l'inviter depuis sa fiche usager dans RDV-Solidarités.
On ne souhaite pas permettre cela car une invitation par l'agent via l'interface RDV-Solidarités invaliderait le token envoyé dans le SMS de RDV-Insertion.

- Création d'une colonne `source` sur la table `organisations`
- Création d'une méthode `users_invitable?` liée à l'organisation, qui dépend de la source (liste des sources implémentées en dur dans le code ; pour l'instant limitée à rdv-insertion)
- L'affichage du bouton "Inviter" dans le show du User pour les agents est désormais dépendante de la méthode `users_invitable?`, en plus d'être dépendante de la méthode `invitable`, liée à l'user

2021-09-23 16:43 UTC, aminedhobb reviewed
Merci pour la PR @qblanc , je l'ai parcouru et j'ai quelques petits retours à chaud: 

- La colonne source doit être un `enum` et pas un string à mon avis. Sur ce projet les enum sont des enum au sens de Postgres (et pas des integers comme sur notre projet, qui peut se permettre d'être plus basique car pas la même charge). La gem activerecord postgres_enum te permet d'en créer avec `create_enum` comme [ici](https://github.com/betagouv/rdv-solidarites.fr/blob/92f0c92733dd8441866fdc8aa71aec23e9b8ed6d/db/migrate/20210506164841_add_sms_configuration_to_territory.rb#L5). 

- Je pense qu'il faut garder la logique de `invitable?` dans le modèle `user` et pas par rapport à l'orga. Peut-être qu'on peut rajouter une méthode `from_external_source?` dans le modèle et rajouter la condition `!from_external_source?` dans la méthode `invitable?`, WDYT?

2021-09-23 16:56 UTC, n-b requested changes

2021-09-23 16:56 UTC, n-b commented on app/models/organisation.rb
> +  # Users invited by organisations within the array are not invitable in the web app
Je serais plutôt pour mettre un commentaire plus explicite vis-à-vis de rdv-insertion (vraiment, j’ai pas compris le nom de vos projets). Quelque chose du style:
```suggestion
# Users created by rdv-insertion are invited externally (using the token obtained via the api, see /api/v1/users/invite), and we should not try to re-invite them from rdv-solidarités. See https://github.com/betagouv/rdv-insertion/issues/62```

2021-09-23 16:56 UTC, n-b commented on db/migrate/20210922172831_add_source_to_organisations.rb
> +    add_column :organisations, :source, :string
Je ne comprenais pas le commentaire de Quentin sur l’emplacement des méthodes, et en fait je n’avais pas réalisé que vous vouliez mettre `source` sur `Organisation`.

Pour moi, `source` est un attribut de `User`, et ça indique “cet user a été invité par un process externe”. De toute façon, les usagers peuvent avoir plusieurs organisations! Si on met l’attribut sur organisation, rien n’empêche les agents d’une autre organisation de réinviter les usagers créés par rdv-insertion.

2021-09-23 16:56 UTC, n-b commented on db/migrate/20210922172831_add_source_to_organisations.rb
> +    add_column :organisations, :source, :string
Le complément de ça, c’est qu’il faut que source soit passé à la création, effectivement: et peut-être qu’on veut le configurer automatiquement par organisation, ou peut-être qu’on veut le passer à l’api?

2021-09-23 20:46 UTC, yaf commented on db/migrate/20210922172831_add_source_to_organisations.rb
> +    add_column :organisations, :source, :string
Je rappelle aussi qu'à relativement court terme, je pense que nous allons supprimer le champ « organisation » des usagers. Peut-être seront-ils attachés à un territoire pour éviter la surcharge d'information usager dans les territoires, mais la séparation par organisation semble inutile.

2021-09-24 08:52 UTC, n-b commented
ℹ️ on a rebasé la branche `recette` sur `production`, comme on fait des fois. Le mieux pour mettre celle-ci (`not_invitable`) à jour, c’est de faire un `git checkout not_invitable; git rebase recette`, plutôt que d’utiliser le bouton Update de github.

2021-09-29 08:40 UTC, n-b commented
Je viens de remarquer qu’il existe déjà un attribut `User#created_through`, qui aujourd’hui peut avoir ces valeurs:

```
agent_creation
user_sign_up
franceconnect_sign_up
user_relative_creation unknown
agent_creation_api
```

Ce n’est pas exactement le même usage, mais serait bien d’être un peu cohérent avec l’existant: du coup, je propose d’appeler le nouvel attribut `invited_through` qui aurait comme valeurs, disons
```
devise_email
external
```
?

Au passage, si vous voulez ajouter un index à `created_through`, et en faire un enum, c’est sympa :)

2021-10-04 08:26 UTC, n-b commented on app/views/admin/users/show.html.slim
> +              | Cet usager ne s'est pas encore créé de compte RDV-Solidarités mais a déjà reçu une invitation de la part d'une autre organisation
Mmm, j’ai oublié un truc: pourquoi finalement ne pas mettre ce comportement dans `User#invitable?` (Mon réflexe, c’est qu’on essaye d’empêcher un comportement, et que ce blocage ne devrait pas être dans la vue, ou en tout cas pas uniquement.)

Sur la formulation: “une autre organisation” c’est pas forcément exact, je me trompe? Est-ce que ça serait mieux de dire quelque chose comme 
```suggestion
              | Cet usager a reçu une invitation via un partenaire de RDV-Solidarités: en envoyant une nouvelle invitation, l’ancienne deviendra invalide.
```
J’hésite sur les détails, mais vous voyez l’idée.

Ah, et attention aux apostrophes courbes (`'` vs `’`) et au point final. 🕵️

2021-10-04 08:26 UTC, n-b commented on db/migrate/20210930100857_add_invited_through_to_users_change_created_through_to_enum_and_add_index.rb
> +    rename_column :users, :created_through, :old_created_through
OK pour laisser trainer `:old_created_through` un moment, c’est plus simple que de la supprimer tout de suite et de devoir gérer la migration inverse. Peut-être une note en commentaire?

2021-10-05 18:51 UTC, qblanc commented on db/migrate/20210930100857_add_invited_through_to_users_change_created_through_to_enum_and_add_index.rb
> +    rename_column :users, :created_through, :old_created_through
Il n'y avait pas de point final pour le texte du cartouche quand l'option "Inviter" est dispo, mais ça me va :)

2021-10-06 07:20 UTC, qblanc commented on app/views/admin/users/show.html.slim
> +              | Cet usager a reçu une invitation via un partenaire de RDV-Solidarités, mais il ne l’a pas encore acceptée.
J'ai opté pour un message moins détaillé, car je pense que la notion d'invalidation de l'invitation risque plus d'embrouiller les agents qu'autre chose. De toute façon, ils n'ont pas la possibilité d'inviter, donc j'ai juste mis un message pour les informer de pourquoi ils ne peuvent pas.
J'ai suivi tes recommandations pour les apostrophes courbes et le point final, mais je m'étais calé sur le reste du fichier ; si c'est important, il n'y a pas beaucoup de views qui respectent ces règles chez vous :)

2021-10-06 08:03 UTC, n-b commented on app/views/admin/users/show.html.slim
> +              | Cet usager a reçu une invitation via un partenaire de RDV-Solidarités, mais il ne l’a pas encore acceptée.
Je suis pas repassé sur toutes les vues pour mettre le texte dans du yml et nettoyer la typo, même si c’est pas l’envie qui manque!

2021-10-06 08:17 UTC, merged