rdv statuts responsive
betagouv/rdv-solidarites.fr pull request #1841
Opened 2021-11-02 14:20 UTC by rebeccadumazert

Close #1823

rendre statuts responsive 

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-11-02 14:52 UTC, n-b requested changes

2021-11-02 14:52 UTC, n-b commented on app/webpacker/stylesheets/components/_dropdown.scss
> +    display: contents !important;
Je crois que ce qui pose problème dans `_rdv_status_dropdown.html.slim`, c’est 
```
dropdown-menu[style="min-width: 30rem"]
```
En fait, ça ne devrait pas être un style inline. Ça serait mieux de rajouter une classe, d’ajouter le style dans ce fichier, et de faire une media-query si besoin. (Plutôt que de faire `!important`. Les styles inline et les !important, c’est le mal.) (C’est moi qui ai mis le `min-width: 30rem` en question, je crois.)

2021-11-02 14:52 UTC, n-b commented on app/views/admin/rdvs/show.html.slim
> +      .card-header[style="text-align: center"]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/139391/139871111-25e33ee4-7dbc-4a42-9ea1-36f197dc984c.png">


Ça me fait bizarre, surtout en vue desktop. Ça mérite peut-être là aussi une classe custom et une media-query?

(Sinon, il y a une classe bootstrap qui s’appelle `text-center`, qui fait la même chose. C’est un peu ridicule, soit, mais bon, j’ai déjà dit le mal que je pensais de bootstrap?)

2021-11-02 17:31 UTC, rebeccadumazert commented on app/views/admin/rdvs/show.html.slim
> +      .card-header[style="text-align: center"]
Finalement j'ai enlevé ça, car en effet c'était assez étrange et nous avons réglé le problème avec un petit flex-wrap

2021-11-02 17:33 UTC, rebeccadumazert commented on app/webpacker/stylesheets/components/_dropdown.scss
> +    display: contents !important;
j'ai essayé de jouer avec le min-width, de l'enlever ou de le remplacer par des class mais c'est vrai que je n'ai pas trouvé de résultats aussi propres qu'avec ce display: contents !important

2021-11-03 10:20 UTC, n-b approved these changes
Ça m’a l’air assez cool!

Pour ce genre de PR vraiment visuelle, n’hésite pas à mettre deux petits screenshots avant-après dans la description, comme ça on sait où regarder.

Sinon, [dans la doc](https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-alignment), j’avais vu `.dropdown-menu-right` qui permet ,d’aligner le menu sur le bord droit du bouton (plutôt qu’à gauche), je me demande s’il n’y aurait pas un truc à jouer avec ça.

2021-11-03 10:20 UTC, n-b commented on app/webpacker/stylesheets/components/_dropdown.scss
> +  min-width: 30rem;
Ça permet de se passer du style inline dans `_rdv_status_dropdown.html.slim`, non?

2021-11-03 10:20 UTC, n-b commented on app/views/admin/rdvs/_rdv_status_dropdown.html.slim
>    .dropdown-menu[style="min-width: 30rem"]
(ce style inline ici)

2021-11-08 16:16 UTC, rebeccadumazert commented on app/views/admin/rdvs/_rdv_status_dropdown.html.slim
>    .dropdown-menu[style="min-width: 30rem"]
en effet

2021-11-09 15:34 UTC, merged