feat(api): Filter motifs on services
betagouv/rdv-solidarites.fr pull request #1851
Opened 2021-11-04 10:45 UTC by aminedhobb

Dans cette PR j'ajoute la possibilité de filtrer les motifs par service quand on récupère les motifs par l'API. 
En effet nous nous ne voulons récupérer que les motifs liés aux RSA.
J'ajoute également le `service_id` au blueprint qui pourrait nous être utile.

2021-11-04 15:11 UTC, n-b requested changes
Ça m’a l’air assez cool, mais je suis toujours un peu frileux à l’idée de passer des id dans l’API. Le `Service#short_name` a l’air de servir d’identifiant de fait dans certaines parties du code, et son unicité est garantie en base (et il est indexé). Ça vous irait d’utiliser ça à la place de `service_id`?

2021-11-05 13:25 UTC, yaf approved these changes
J'approuve, et je trouve la réflexion de @n-b très juste. Et quand c'est vers l'extérieur, ça ne me semble pas bloquant...

2021-11-08 16:01 UTC, aminedhobb commented
Merci pour le retour @n-b 🙌 .
Ce qui t'embête c'est de renvoyer le `service_id` dans la réponse ou de le passer en params pour filtrer les motifs ?

En vrai on a besoin soit de l'un soit de l'autre (pour que le filtre sur l'ID se fasse chez vous ou bien chez nous), sinon ça nous obligerait à sauver le `short_name` en plus de l'ID, puisque l'ID on est de ttes façons obligé de l'avoir pour rediriger la personne vers le bon service dans le lien d'invitation (puisque c'est l'ID qui est pris en compte dans les paramètres de l'URL à ce moment-là).

2021-11-08 16:10 UTC, n-b commented
Ah, j’avais pas complètement pris conscience qu’on mettait le service_id dans le lien d’invitation. Ce qui m’embête en règle plus générale, c’est que les ids de base se retrouvent dehors :) Donc en fait, il faudrait utiliser le `short_name` comme identifiant public, dans l’api et dans le lien d’invitation. Ça parait raisonnable?

2021-11-08 16:24 UTC, aminedhobb commented
> Donc en fait, il faudrait utiliser le `short_name` comme identifiant public, dans l’api et dans le lien d’invitation. Ça parait raisonnable?

Ça impliquerait de toucher au [`WelcomeController`](https://github.com/betagouv/rdv-solidarites.fr/blob/83c92edcc592dee07d2f658fd11572a79c49d20f/app/controllers/welcome_controller.rb#L60) et au [`LieuxController`](https://github.com/betagouv/rdv-solidarites.fr/blob/83c92edcc592dee07d2f658fd11572a79c49d20f/app/controllers/lieux_controller.rb#L92) et potentiellement d'autres que j'oublie, sans compter le fait que ça rendrait les liens envoyés jusqu'à présent caduques 😬 . 

Ça t'irait si on laissait pour l'instant l'id du service dans le blueprint et qu'on enlève la possibilité de l'envoyer en params de l'API ?

2021-11-08 17:03 UTC, n-b approved these changes

2021-11-09 10:43 UTC, merged