Notifications fines par rendez-vous (1/N)
betagouv/rdv-solidarites.fr pull request #1870
Opened 2021-11-17 13:08 UTC by n-b

refs #1617, reprise de #1742

Fait dans cette PR:
* [x] Renommage et refactor des “services” de notification. C’est sans lien direct avec le problème, si ce n’est que ce sont les mêmes fichiers. Au passage, je transforme `Notifications::Rdv::BaseServiceConcern` en véritable classe intermédiaire; je ne tiens pas à l’héritage, mais on avait déjà cette hiérarchie dans les faits, sans le dire. Pour cette raison, la PR est un peu grosse, mais ça se lit bien commit par commit.
* [x] Nouveaux flags `send_lifecycle_notifications` et `send_reminder_notification` sur RdvUser, avec migration des anciennes données. Ces flags sont non-null en base.
* [x] Affectation automatique de la valeur des flags à la création d’un Rdv à partir du `visibility_type` du Motif.
* [x] Prise en compte des flags dans les services de notification.

Reste à faire dans les PR suivantes:
1. Choix par l’agent à la création du Rdv
2. Affichage des valeurs des flags dans rdv#show et rdv#edit

Et éventuellement:
* Je renommerais bien `RdvUser` en `Participation` ou `UserParticipation`, qu’en pensez-vous?
* Ça simplifierait l’évolution à venir sur les notifications multiples et les usagers simples “observateurs” d’un Rdv (#1670) On rajouterait alors un flag à `UserParticipation` pour indiquer si l’usager est convoqué au Rdv, et on n’aurait plus besoin de se baser sur la relation de responsable.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-11-17 16:25 UTC, yaf requested changes
Je mets `request changes` parce que j'ai besoin d'une revue en direct avec toi je pense pour comprendre comment on va faire pour notifier les bons `usagers` ici. La table `rdvs`users` ne contenant que les bénéficiaires du RDV.

2021-11-17 16:25 UTC, yaf commented on app/services/notifications/rdv/base_service.rb
> +class Notifications::Rdv::BaseService < ::BaseService
J'ai l'impression qu'il n'y a qu'une classe qui hérite de celle-ci. Si c'est le cas, pourquoi maintenir le code dans deux classes ?

2021-11-17 16:25 UTC, yaf commented on app/services/notifiers/rdv_cancelled.rb
> +class Notifiers::RdvCancelled < Notifiers::RdvBase
J'avais oublié que nous avons ce genre d'empilage d'héritage :cry:. J'espère que nous aurons l'occasion de faire un bon changement là-dedans plus tard.

En attendant, merci pour le renommage, au moins, c'est un peu plus simple et plus clair.

2021-11-17 16:25 UTC, yaf commented on app/services/notifiers/rdv_cancelled.rb
> +    @rdv.rdvs_users.where(send_lifecycle_notifications: true)
Ma crainte ici, c'est que les `rdvs_users` ne sont pas forcément ceux à notifier. Je me demande si une autre tableau n'aurait pas été plus clair et simple à utiliser :thinking:

2021-11-17 16:25 UTC, yaf commented on db/migrate/20211109141613_add_rdvs_users_notifications_flags.rb
> +class AddRdvsUsersNotificationsFlags < ActiveRecord::Migration[6.0]
Je constate que tu as opté pour l'ajout sur la table existante. Je continue de craindre la complexité de code et la forêt de `if` pour faire la distinction entre les `users` bénéficiant du RDV et les `users` à notifier qui ne sont pas les mêmes...

Et peut-être que tu as un plan en tête et que ça sera très clair, compréhensible et lisible :shrug:

2021-11-17 17:28 UTC, n-b commented on app/services/notifications/rdv/base_service.rb
> +class Notifications::Rdv::BaseService < ::BaseService
Avant, on avait les services concrets (`Notifications::Rdv::Rdv[Created|Cancelled|Updated|UpcomingReminder]Service`) qui héritait directement de la classe `::BaseService`, et qui incluaient le module `Notifications::Rdv::BaseServiceConcern`. Maintenant, les services concrets héritent de la classe `Notifications::Rdv::BaseService`, qui lui même hérite de la classe `::BaseService`. 

`::BaseService` est utilisé un peu partout, c’est le truc qui donne `perform_with(...)` 🤷

2021-11-17 17:29 UTC, n-b commented on app/services/notifiers/rdv_cancelled.rb
> +class Notifiers::RdvCancelled < Notifiers::RdvBase
D’accord avec toi :) Justement quitte à avoir de l’héritage, autant le faire vraiment et ne pas essayer de le camoufler avec des modules.

2021-11-17 17:30 UTC, n-b commented on app/services/notifiers/rdv_cancelled.rb
> +    @rdv.rdvs_users.where(send_lifecycle_notifications: true)
C’est un peu mon plan machiavélique en 3 bandes, en renommant RdvUser en “Participation”, on peu indiquer que c’est la personne directement concernée par le Rdv, ou bien une personne qui veut juste être notifiée.

2021-11-19 10:02 UTC, yaf commented on app/services/notifiers/rdv_cancelled.rb
> +    @rdv.rdvs_users.where(send_lifecycle_notifications: true)
Tu veux dire que tu ajoute une colone pour préciser le niveau de participation : notification seulement ou bien présent au rdv ?

Je crois que j'ai besoin d'en parler avec toi :)

2021-11-19 10:08 UTC, n-b commented on app/services/notifiers/rdv_cancelled.rb
> +    @rdv.rdvs_users.where(send_lifecycle_notifications: true)
Oui, quelque chose de ce genre! En gros, la table “Participation” serait là juste pour indiquer qu’un usager est concerné, d’une façon ou d’une autre, par ce Rdv. Ensuite, les flags permettent de dire si c’est le Rdv est _pour cet usager_, s’il veut être tenu au courant, etc.

2021-11-19 15:12 UTC, yaf approved these changes
:+1:

2021-11-24 17:12 UTC, yaf commented
Je vote plutôt pour `UserParticipation` afin d'être bien explicite. Et ça me fait bizarre de dire participation pour les personnes qui seront notifiés. Mais je n'ai pas de meilleure idée pour le moment. Ça pourra sans doute être atténué par un choix de nom de colonne / méthode judicieux permettant de bien clarifier le type de participation :thinking:

2021-11-24 17:16 UTC, yaf commented on app/models/rdvs_user.rb
> +    # rubocop:enable Style/GuardClause
Le `disable` ici c'est parce que Rubocop demande à ce que ce soit sous la forme 
```ruby
self.send_lifecycle_notifications = rdv.motif.visible_and_notified? if send_lifecycle_notifications.nil? 
self.send_reminder_notification = rdv.motif.visible_and_notified? if send_reminder_notification.nil?
```

2021-11-25 15:41 UTC, yaf commented on app/models/rdvs_user.rb
> +    self.send_reminder_notification = rdv.motif.visible_and_notified? if send_reminder_notification.nil?
:+1:

2021-12-23 15:47 UTC, merged