Notifications fines par rendez-vous (2/N)
betagouv/rdv-solidarites.fr pull request #1889
Opened 2021-11-25 15:14 UTC by n-b

refs #1617, suite de #1870

WIP: 
* [ ] merger #1870 d’abord
* [ ] merger #1888, les changements sont en principe cohérents

Fait dans cette PR
* [x] Affichage des valeurs des flags dans rdv#show 

À suivre :
* Choix dans rdv#edit
* Choix par l’agent à la création du Rdv 

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-12-07 14:45 UTC, n-b commented
Fermeture/réouverture pour relancer la review app.

2021-12-07 19:43 UTC, yaf requested changes
Un bug étrange sur mobile (et peut-être que c'est du fait que je regarde avec firefox en faisant semblant ?
J'ai en tête que nous voulons faire en sorte que ça fonctionne mieux sur mobile, au fur et à mesure... 

En dehors de ça, c'est top. 

Ah, j'oubliais, il y a une erreur 500 quand on tente de poser un RDV sur la review-app. J'ai récupéré la branche en local pour faire des tests :)

2021-12-07 19:43 UTC, yaf commented on app/models/user.rb
> +  end
:heart_eyes:

2021-12-07 19:43 UTC, yaf commented on app/services/notifiers/rdv_base.rb
> +  # :notify_agent(agent)
:sob:

2021-12-07 19:43 UTC, yaf commented on app/views/admin/rdvs/_rdv_user_notifications.html.slim
> +  = user_soft_deleted_tag(user, current_organisation)
Tellement de `if` est-ce qu'il n'y a pas moyen de mettre tout ça dans un helper pour pouvoir le tester ?

2021-12-07 19:43 UTC, yaf commented on app/views/admin/rdvs/_rdv_user_notifications.html.slim
> +  = user_soft_deleted_tag(user, current_organisation)
Même chose pour en dessous

2021-12-07 19:43 UTC, yaf commented on app/views/admin/rdvs/_rdv_user_notifications.html.slim
> +        .ml-2= boolean_attribute_tag rdv.motif, :visible_and_notified?
:heart_eyes:

2021-12-07 19:43 UTC, yaf commented on app/webpacker/components/popover.js
> +
J'ai un bug sur mobile (je n'arrive pas vraiment à faire film) quand je passe au-dessus du lien, la popover se met à clignoter.

2021-12-08 10:26 UTC, n-b commented on app/services/notifiers/rdv_base.rb
> +  # :notify_agent(agent)
C’était déjà dans #1870 ça! (et c’était en fait déjà comme ça avant, je change que les noms)

2021-12-08 10:28 UTC, n-b commented on app/views/admin/rdvs/_rdv_user_notifications.html.slim
> +  = user_soft_deleted_tag(user, current_organisation)
En fait, j’hésite encore sur ce que je veux, aux deux endroits! Dans la PR suivante, je divise ce partial en plusieurs.

2021-12-09 11:33 UTC, yaf commented on app/views/admin/rdvs/_rdv_user_notifications.html.slim
> +  = user_soft_deleted_tag(user, current_organisation)
ah ok, cool.

2021-12-15 09:03 UTC, n-b commented on app/webpacker/components/popover.js
> +
Ah oui, donc: dans la version révisée, j’ai finalement retiré les popovers (et mis des collapse à la place)

2021-12-15 22:12 UTC, yaf approved these changes

2021-12-23 15:48 UTC, merged