Créer des équipes de professionnels
betagouv/rdv-solidarites.fr pull request #1904
Opened 2021-12-03 13:28 UTC by yaf

Close #1731 

- Ajout d'une table `Teams` pour y créer des noms d'équipe
- Ajout d'une table de jointure `AgentTeams` pour faire la liaison entre des agents et des équipes.
- 2 interfaces : un CRUD pour gérer les équipes, un CRUD pour les agents.

Pour les agents, ça sera surtout ajouté et supprimer des équipes. Mais j'imagine que ça pourrait devenir l'endroit d'où on gère tout pour les agents : droits d'accès, invitation, ...

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2021-12-14 15:03 UTC, n-b commented on app/views/admin/territories/agents/edit.html.slim
> +    = form.input :team_ids, collection: current_territory.teams, label: "Team (s)", label_method: :name, input_html: { multiple: true, class: "select2-input" }
C’est un peu bizarre, cette liste d’agents du territoire en plus de la liste d’agents de l’organisation. Ça multiplie les points de configuration. Est-ce que ça veut dire que seuls les admins de territoires peuvent définir des équipes?

2021-12-14 15:03 UTC, n-b commented on app/views/admin/territories/agents/index.html.slim
> +      div= link_to "Réinitialiser", admin_territory_agents_path(current_territory), class: "btn btn-link #{search}"
(Je crois qu’il y a des clés i18n pour ça, non?)

2021-12-14 15:03 UTC, n-b commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.input :agent_ids, collection: current_territory.organisations.flat_map(&:agents), label: "Agent(s)", label_method: :full_name, input_html: { multiple: true, class: "select2-input" }
En fait, on pourrait ajouter et supprimer les agents (avec un select2 qui fait peur) directement depuis le `edit` d’une équipe. Il y a un moyen de voir tous les membres d’une équipe aujourd’hui?

2021-12-14 15:03 UTC, n-b commented on app/views/admin/territories/teams/new.html.slim
> +  = render "form", team: @team, url: admin_territory_teams_path(current_territory)
👍

2021-12-21 21:20 UTC, yaf commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +    params[ids_key]&.reject(&:blank?)&.presence
Effectivement, j'y ai pensé, et je me suis dit que ça serait pas mal de ne pas ajouter de code dans le `form_object`

2021-12-21 21:22 UTC, yaf commented on app/controllers/admin/territories/agents_controller.rb
> +    @agents = Agent.joins(:roles).where(agents_organisations: { organisation_id: Territory.first.organisations || [] }).page(params[:page])
Je n'en suis pas sûr. Pour moi l'accès à une organisation n'a rien à voir avec un rôle dans le département...
C'est éventuellement dans le lien à la table `Territory` que nous pourrions ajouter une qualification, mais est-ce vraiment très utile ? 
_Je parle là de la cible, une fois que nous aurons changé la façon de gérer les autorisations_

2021-12-21 21:30 UTC, yaf commented on app/models/team.rb
> +                  ignoring: :accents)
Je pense qu'il pourrait y en avoir pas mal à terme. 

J'ai l'impression d'avoir mis un index :thinking:  https://github.com/betagouv/rdv-solidarites.fr/pull/1904/files#diff-cbf8b25d6d853acf58fa9057841f407d29ffe90649c75cf9e3f51b2d6e3aa1d3R404 J'ai rété un truc ?

2021-12-22 08:42 UTC, yaf commented on app/form_models/agent_creneaux_search_form.rb
> +    (organisation.agents.where(id: agent_ids) + teams.flat_map(&:agents)).uniq
Je ne suis pas sûr de voir comment la faire celle-là :thinking: Si tu as un moment pour que nous regardions ensemble ça serais pas mal :)

2021-12-22 08:50 UTC, yaf commented on app/views/admin/territories/agents/edit.html.slim
> +    = form.input :team_ids, collection: current_territory.teams, label: "Team (s)", label_method: :name, input_html: { multiple: true, class: "select2-input" }
Dans un premier temps oui.
J'imagine plus tard que les « fonctionnalités » (de configuration principalement) seront présenté sous forme d'une liste avec « j'ai accès ou pas » (plutôt que d'avoir un profil admin de territoire et un d'organisation).
Tout ça pour dire que j'imagine que plus tard, les équipes puissent être créées par d'autres agents

Pour la liste, comme je l'ai mis dans le texte de la PR, j'envisage que nous pourrions déplacer toute la configuration dans cette zone, pour clairement séparer la config de l'utilisation de RDV. 

Ça nécessite de modifier par mal de chose, surtout au niveau des accès. L'idée serait d'avoir une petite poignée d'agents ayant des capacités de configuration large, et notamment celle de modifier les capacités de chaque agent. Ça fait partie de mes devoirs de « vacances » de faire une première liste de ces capacités pour engager les travaux.

**C'est le thème que j'appelais incorrectement « décloisonnement » que je tente de renommer « affinage des autorisations » dans le [pad de roadmap](https://pad.incubateur.net/jftuVsrKTsKbn3ay8AoL0Q?edit)**

J'aimerais ramener TOUT ce qui concerne la configuration, l'invitation & co des agents dans cette page/vue.

2021-12-22 09:12 UTC, yaf commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.input :agent_ids, collection: current_territory.organisations.flat_map(&:agents), label: "Agent(s)", label_method: :full_name, input_html: { multiple: true, class: "select2-input" }
Ce n'est pas ce qu'il y a justement ?

![Screenshot 2021-12-22 at 10-11-36 RDV Solidarités](https://user-images.githubusercontent.com/42057/147067345-dea67756-da27-4640-a96b-def475a79435.png)

C'est par contre qu'il n'y a pas de « visualisation ». Peut-être ajouter un show ?

2021-12-22 09:15 UTC, yaf commented on app/views/admin/territories/agents/edit.html.slim
> +    = form.input :team_ids, collection: current_territory.teams, label: "Team (s)", label_method: :name, input_html: { multiple: true, class: "select2-input" }
L'idée, comme évoqué dans le texte de la pr, c'est de ramener ici tous les éléments de configuration des agents.

La difficulté que j'ai, c'est dans quel ordre faire les choses ?

Et là, je pense qu'il faut entamer le thème appelé incorrectement décloisonnement en commençant par les autorisations d'agent. Et plutôt que d'écrire ici tout ce que j'envisage, nous pouvons en parler à l'occasion. C'est très lié à la roadmap je pense... Les tickets ne sont pas encore tous créés.

Pour le moment, effectivement, seul les agents admin territoriaux pourront créer des équipes.

2021-12-22 09:16 UTC, yaf commented on app/form_models/agent_creneaux_search_form.rb
> +    (organisation.agents.where(id: agent_ids) + teams.flat_map(&:agents)).uniq
J'ai quelques difficultés à trouver comme m'y prendre pour ce `or`. Est-ce que tu as une suggestion ou un peu de temps pour que nous en parlions ?

2021-12-22 09:45 UTC, n-b commented on app/form_models/agent_creneaux_search_form.rb
> +    (organisation.agents.where(id: agent_ids) + teams.flat_map(&:agents)).uniq
Mmm, on veut les agents dont on a les id (et qui sont dans `organisation`), et les agents des teams dont on a les id. Ça revient à 
```
Organisation.find_by(id: organisation_id).agents.where(id: agent_ids) + organisation.territory.teams.where(id: team_ids).flat_map(&:agents)).uniq
```

En décomposant, ça devrait faire un truc de ce genre:
```
organisation_agents = Agent
  .where(id: agent_ids)
  .joins(:agent_roles)
  .where(organisation_id: organisation_id)
teams_agents = Agent
  .joins(:teams)
  .where(team: Team
    .where(id: team_ids)
    .joins(territory: :organisations)
    .where(organisations: {id: organisation_id}
  )

organisation_agents.or teams_agents
```

(j’ai pas testé)

2021-12-22 09:50 UTC, n-b commented on app/models/team.rb
> +                  ignoring: :accents)
Souviens-toi de #1772 and #1833: avec `ignoring: :accents`, ça utilise la fonction `unaccent` de PG, qui donc n’utilise pas cet index, mais qui n’est pas utilisable dans un index (parce que non immutable), raison pour laquelle on a des colonnes distinctes pour les `search_terms`.

2021-12-22 09:55 UTC, n-b commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.input :agent_ids, collection: current_territory.organisations.flat_map(&:agents), label: "Agent(s)", label_method: :full_name, input_html: { multiple: true, class: "select2-input" }
🤔 Mmm je sais pas exactement ce que je voulais dire, en fait c’est bien.

2021-12-22 14:59 UTC, yaf commented on app/models/team.rb
> +                  ignoring: :accents)
Mais oui :facepalm:

2021-12-22 16:43 UTC, yaf commented on app/form_models/agent_creneaux_search_form.rb
> +    (organisation.agents.where(id: agent_ids) + teams.flat_map(&:agents)).uniq
En fait je crois que cette méthode n'est jamais appelée :sweat_smile:  J'ai cherché comment la tester dans l'interface et je n'ai pas trouvé !

2022-01-03 15:13 UTC, n-b requested changes
À chaque fois qu’on a des formulaires avec des collections c’est compliqué, mais on avance :)

Et puis à force, c’est souvent le même problème, on va finir par réussir à normaliser/génériser ça.

2022-01-03 15:13 UTC, n-b commented on app/models/agent.rb
> +    "#{last_name} #{first_name}"
Maaaais pourquoi “nom prénom” au lieu de “prénom nom”?

```suggestion
    "#{first_name} #{last_name}"
```

2022-01-03 15:13 UTC, n-b commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.input :agent_ids, collection: current_territory.organisations.flat_map(&:agents), label: "Agent(s)", label_method: :full_name, input_html: { multiple: true, class: "select2-input" }
Ah, j’ai retrouvé ce que je voulais dire: avec la collection comme ça, ça met tous les agents des orgas du territoire dans le DOM: 

<img width="391" alt="image" src="https://user-images.githubusercontent.com/139391/147946478-d7fc2e84-f543-4e49-bcf5-4d4daae584d9.png">

Il faudrait utiliser `search_admin_organisation_agents_path(current_organisation)`; le problème justement c’est qu’on a pas de `current_organisation`. Je crois qu’on a besoin d’une autre route pour retourner en json tous les agents d’un territoire! Mais d’un autre côté, on vient d’ajouter un `admin/territories/agents_controller#index`, alors ça va 😅

2022-01-03 15:13 UTC, n-b commented on app/views/admin/territories/agents/edit.html.slim
> +    = form.input :team_ids, collection: current_territory.teams, label: "Team (s)", label_method: :name, input_html: { multiple: true, class: "select2-input" }
En réalité, ici aussi il faudrait remplir la collection dynamiquement avec du json. Le nombre d’équipe va être moindre que le nombre d’agents, mais c’est quand même plus raisonnable.

2022-01-05 16:55 UTC, yaf commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.input :agent_ids, collection: current_territory.organisations.flat_map(&:agents), label: "Agent(s)", label_method: :full_name, input_html: { multiple: true, class: "select2-input" }
Super. Merci. Je viens de faire l'ajout, c'est mieux effectivement. 

J'ai dupliqué la méthode. Nous pourrons sans doute supprimer cette qui est dans l'organisation dans quelques temps.

2022-01-05 16:58 UTC, yaf commented on app/models/agent.rb
> +    "#{last_name} #{first_name}"
Ah oui, pour le tri dans les colonnes et liste de recherche, c'est mieux. Et je ne sais plus où est utilisé ce `to_s` alors je vais accepter ta proposition et on verra bien :)

2022-01-05 18:06 UTC, yaf commented
Les commits sont un peu empilés n'importe comment. Si c'est trop pénible je pourrais prendre le temps de ranger un peu tout ça, n'hésitez pas à me le demander.

Je pense avoir fait le tour de chaque remarque (merci !) et fait les évolutions nécessaire.

2022-01-06 15:10 UTC, n-b commented on app/models/team.rb
> +                  using: { tsearch: { prefix: true, any_word: true } })
Dans #1973, j’ai un refactor pour DRY la recherche texte. Peut-être que ça vaudrait le coup de l’utiliser, mais il faut juste une colonne `:search_terms` distincte.

2022-01-06 15:10 UTC, n-b commented on spec/models/team_spec.rb
> +  end
Est-ce que c’est vraiment utile, ce genre de tests?

2022-01-06 15:10 UTC, n-b commented on db/migrate/20211220210821_create_teams.rb
> +      t.belongs_to :territory
Vu que les agents et les teams ont tous deux une relation avec le territoire, est-ce qu’on devrait valider que les agents d’une même team sont tous du territoire de la team?

2022-01-07 11:35 UTC, yaf commented on app/models/team.rb
> +                  using: { tsearch: { prefix: true, any_word: true } })
Ça fait bizarre d'ajouter une colonne spécifique ici ? Ou bien peut-êrtre pour gérer les accents du coup ?

2022-01-07 11:36 UTC, yaf commented on spec/models/team_spec.rb
> +  end
Ça justifie de mettre une validation dans le model... Je n'écris pas de ligne de code si un test ne me le demande pas en général (sauf pour la vue).

C'est utile tant que nous avons besoin de la validation à mon sens :)

2022-01-07 11:36 UTC, yaf commented on db/migrate/20211220210821_create_teams.rb
> +      t.belongs_to :territory
ça serait pas mal oui.

2022-01-10 11:12 UTC, n-b reviewed
Ça m’a l’air de rouler, à part l’histoire de la recherche texte :)

2022-01-10 11:12 UTC, n-b commented on app/models/team.rb
> +                  using: { tsearch: { prefix: true, any_word: true } })
Ah mais oui, c’est nécessaire pour ça !

2022-01-10 11:12 UTC, n-b commented on app/controllers/admin/territories/agents_controller.rb
> +    @agents = Agent.joins(:roles).where(agents_organisations: { organisation_id: Territory.first.organisations || [] }).page(params[:page])
poke

2022-01-11 10:36 UTC, n-b requested changes
🙈 j’ai encore des changements! (Mais j’aime!)

2022-01-11 10:36 UTC, n-b commented on app/controllers/admin/territories/teams_controller.rb
> +  end
Ah, avec `TextSearch` ceci n’est plus nécessaire. (C’était aussi le but de ce module)

2022-01-11 10:36 UTC, n-b commented on spec/models/concerns/text_search_spec.rb
> +  # Peut-être difficile sans activerecord ?
Ah cool, merci d’avoir fait ça :)

`TextSearch` n’est pas vraiment un module indépendant, il n’a d’intérêt que pour être inclus dans un Model. C’est un peu la différence que je faisais avec le module `PhoneNumberValidation` dont les méthodes peuvent exister hors de ActiveModel (et c’est pour ça qu’il est dans `lib`plutôt que dans `concerns`)

2022-01-11 10:36 UTC, n-b commented on spec/models/concerns/text_search_spec.rb
> +  # Test sur qui inclue ce concerns
Les tests d’avant le refactor sont encore dans `user_spec`, je peux les rassembler ici si tu veux. Je crois que ça se fait bien :)

2022-01-11 10:36 UTC, n-b commented on app/views/admin/creneaux/agent_searches/index.html.slim
> +                    delay: 250\
Bon, je vais faire un helper pour ça, c’est plus possible de répéter ces lignes à chaque fois. 🙈

2022-01-11 10:36 UTC, n-b commented on app/models/team.rb
> +  scope :ordered_by_name, -> { order(Arel.sql("unaccent(LOWER(teams.name))")) }
Attention, ce tri n’est pas indexé, si on a beaucoup de teams ça va être un peu cher.

2022-01-11 10:36 UTC, n-b commented on app/services/search_creneaux_for_agents_service.rb
> +    creneaux = SlotBuilder.available_slots(@form.motif, lieu, @form.date_range, OffDays.all_in_date_range(@form.date_range), @form.agent_ids)
Rappelle-moi pourquoi on met `agent_ids` au lieu de `agents`?

2022-01-11 21:18 UTC, yaf commented on spec/models/concerns/text_search_spec.rb
> +  # Peut-être difficile sans activerecord ?
Je comprends oui.

2022-01-11 21:26 UTC, yaf commented on app/models/team.rb
> +  scope :ordered_by_name, -> { order(Arel.sql("unaccent(LOWER(teams.name))")) }
Est-ce que c'est mieux de trier sur le « search_term » du coup ?

2022-01-11 21:31 UTC, yaf commented on app/services/search_creneaux_for_agents_service.rb
> +    creneaux = SlotBuilder.available_slots(@form.motif, lieu, @form.date_range, OffDays.all_in_date_range(@form.date_range), @form.agent_ids)
Je ne me souviens plus ... Je crois que c'est parce que ça viens comme ça du formulaire, et qu'au lieu de lui demander de charger la liste des agents, on transporte les id qui serviront dans la requête de recherche de créneau.

Et en écrivant ça je ne suis pas super convaincu et j'ai un gros doute sur le pourquoi on fait ça :thinking:

2022-01-12 11:28 UTC, yaf commented on app/models/team.rb
> +  scope :ordered_by_name, -> { order(Arel.sql("unaccent(LOWER(teams.name))")) }
Bon, j'ai supprimé ce `scope` et j'en ai mis un dans le `text_search` qui propose un tri par `search_terms` historie d'être explicite. Je ne sais pas si c'est mieux. Au moins, ça sera indexé :sweat_smile:

2022-01-13 09:25 UTC, n-b commented on app/models/concerns/text_search.rb
> +    scope :ordered_by_search_terms, -> { order(:search_terms) }
```
irb(main):002:0> Agent.ordered_by_search_terms.explain
=> 
EXPLAIN for: SELECT "agents".* FROM "agents" ORDER BY "agents"."search_terms" ASC
                            QUERY PLAN
------------------------------------------------------------------
 Sort  (cost=82.23..84.75 rows=1006 width=457)
   Sort Key: search_terms
   ->  Seq Scan on agents  (cost=0.00..32.06 rows=1006 width=457)
```

Ça ne fonctionne pas, ce qui est logique: l’index n’est pas sur `search_terms` mais sur `to_tsvector('simple'::regconfig, COALESCE(search_terms, ''::text))`. Mais de toute façon, ça n‘aurait pas forcément de sens de trier sur la concaténation des termes de recherche. Si on veut trier les équipes par nom, il faut juste un index spécifique sur le nom des équipes 🤷

2022-01-13 09:26 UTC, n-b commented on db/schema.rb
> +    t.index "to_tsvector('simple'::regconfig, (COALESCE(name, (''::text)::character varying))::text)", name: "index_teams_name_vector", using: :gin
Ah mais d’ailleurs il y a cet index qui n’est plus utilisé, si on a search_terms.

2022-01-13 09:33 UTC, n-b commented on app/views/admin/territories/teams/_form.html.slim
> +  = form.submit
un petit `"btn btn-primary"` ici?
```suggestion
  = form.submit, class: "btn btn-primary"
```

2022-01-13 09:35 UTC, n-b commented on app/views/admin/territories/agents/edit.html.slim
> +    = form.submit
Ah, ici aussi, c’est tout gris: 

```suggestion
    = form.submit, class: "btn btn-primary"
```

2022-01-17 10:00 UTC, n-b commented on db/migrate/20211220210821_create_teams.rb
> +    add_index :teams, :name, unique: true
Ça veut dire qu’on ne peut pas avoir deux équipes du même nom, même dans deux territoires différents?

2022-01-17 10:01 UTC, n-b approved these changes
À part l’histoire de l’unicité du nom de l’équipe, c’est bon pour moi 👍

2022-01-17 23:05 UTC, yaf commented on db/migrate/20211220210821_create_teams.rb
> +    add_index :teams, :name, unique: true
Effectivement, pas malin. Je vais laisser la validation dans le modèle avec un scope sur le territoire.

2022-01-17 23:27 UTC, merged