envoie un email avec le fichier de donnée de RDV
betagouv/rdv-solidarites.fr pull request #1958
Opened 2021-12-28 21:37 UTC by yaf

Close #issue_number

// Description de la fonctionnalité ou du bug

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2022-01-03 14:25 UTC, n-b requested changes
Yeah, c’est carrément cool. Deux remarques principalement, sur le fait de passer les données excel à un second job, et sur l’implémentation de la nouvelle policy. (Par ailleurs, si je comprends bien, le but est de ne plus dépendre de `current_organisation` ici, et 👍 à ça.)

2022-01-03 14:25 UTC, n-b commented on app/controllers/admin/rdvs_controller.rb
> +    return nil if date_param.blank? || date_param == "__/__/____"
Oh wow, on peut vraiment se retrouver dans une situation ou le front nous envoie `"__/__/____"`? Bigre.

👍 👍 pour le refactor

2022-01-03 14:25 UTC, n-b commented on app/jobs/send_export_job.rb
> +  queue_as :send_export
👍 pour le mettre tout seul dans sa queue

2022-01-03 14:25 UTC, n-b commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
`data` va être en général assez gros. Si on fait l’envoi de mail dans un second job, on va passer tout `data` en paramètre de ce job. Ça me parait assez dangereux :)

(Je ne sais plus exactement si `.deliver_now` fait vraiment un appel inline, mais je crois que oui.)

2022-01-03 14:25 UTC, n-b commented on app/form_models/admin/rdv_search_form.rb
> -
Ah, donc `RdvSearchForm` ne s’occupe plus du résultat de la requête. 👍 👏 à ça

2022-01-03 14:25 UTC, n-b commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
Note, on aurait déjà configuré ActiveStorage, on l’utiliserait pour ça.

2022-01-03 14:25 UTC, n-b commented on db/seeds.rb
> +               end_time: Tod::TimeOfDay.new(18))
👍  à ça, mais ça n’est pas directement lié?

2022-01-03 14:25 UTC, n-b commented on app/policies/agent/agent_policy.rb
> +  alias export? current_agent_or_admin_in_record_organisation?
On veut exporter les agents aussi? Je suis pour, mais j’ai l’impression que c’est pas encore là 😄

2022-01-03 14:25 UTC, n-b commented on app/policies/agent/rdv_policy.rb
> +      if @agent.roles.map(&:can_access_others_planning?).uniq == [true]
Mmm, on ne devrait s‘intéresser qu’au role de `@agent` dans `@organization`, ou bien je rate quelque chose?

2022-01-03 14:25 UTC, n-b commented on spec/jobs/send_export_job_spec.rb
> +    it "calls send_notifications" do
J’ai l’impression que ce titre de test est copié-collé d’ailleurs 😄

2022-01-03 14:25 UTC, n-b commented on spec/jobs/send_export_job_spec.rb
> +      described_class.perform_now(agent.id, agent.organisations.first.id, params)
Je crois que ce test ne teste rien, il n’y a pas de `expect` 🤔

2022-01-03 14:25 UTC, n-b commented on spec/policies/agent/rdv_policy_spec.rb
> +    it "returns all organisation's rdv with admin agent" do
```suggestion
    it "returns all organisations rdv with admin agent" do
```

2022-01-06 21:14 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    return nil if date_param.blank? || date_param == "__/__/____"
Oui #tristesse Encore un truc à nettoyer. Je crois que c'est un truc avec du JS en plus dans les filtres de RDV :-/

2022-01-06 21:16 UTC, yaf commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
Ah oui, je n'y avais pas pensé. On pourrait aussi passer la construction de l'Excel (l'appel à la méthode) dans une `proc` aussi.

2022-01-06 21:18 UTC, yaf commented on app/form_models/admin/rdv_search_form.rb
> -
J'avais même tenté de le virer, mais ça coince. Je ne sais pas encore trop comment on fait avec `simple_form` lorsque l'on n'a pas vraiment un objet `activerecord` dans le formulaire. Du coup je pense que
- soit on garde un `form_object` pour ça
- soit on fait un `form_tag` à la rails

2022-01-06 21:18 UTC, yaf commented on app/form_models/admin/rdv_search_form.rb
> -
J'ai opté pour ne rien faire de plus pour l'instant dans cette PR

2022-01-06 21:19 UTC, yaf commented on db/seeds.rb
> +               end_time: Tod::TimeOfDay.new(18))
Pas tout à fait. Je ne me souviens plus vraiment, mais je crois que ça me facilitait la vérification sur la `review_app`

2022-01-06 21:20 UTC, yaf commented on app/policies/agent/agent_policy.rb
> +  alias export? current_agent_or_admin_in_record_organisation?
Ah ah ! Boulette oui.

2022-01-07 15:19 UTC, yaf commented on app/policies/agent/agent_policy.rb
> +  alias export? current_agent_or_admin_in_record_organisation?
Ah, mais non. En fait dans le contrôler j'utilise `authorize(current_agent)` dans la méthode export. Pour moi l'idée, c'est de vérifier qu'un agent a le droit d'exporter un fichier.

2022-01-07 15:30 UTC, yaf commented on spec/jobs/send_export_job_spec.rb
> +    it "calls send_notifications" do
:sweat_smile:

2022-01-07 15:45 UTC, yaf commented on spec/jobs/send_export_job_spec.rb
> +      described_class.perform_now(agent.id, agent.organisations.first.id, params)
Je crois que c'est Rubocop qui m'ennuie là-dessus et me dire d'utiliser `allow` plutôt que `expect` :-/

2022-01-07 16:29 UTC, yaf commented on app/policies/agent/agent_policy.rb
> +  alias export? current_agent_or_admin_in_record_organisation?
Ok, en fait non, effectivement, c'est mieux de l'avoir coté RDV. Mais c'est bizarre, car, si je comprends bien comment ça fonctionne, le `authorize` de pundit est utilisé sur un objet en particulier, ici, ça devrait être sur un RDV : « est-ce que l'agent a le droit d'exporter CES rendez-vous là », sauf que dans ce cas il faut passer par le mécanisme de `scope`. Ce que j'ai fait dans le `SendExportJob` (et qui pourrait se retrouver exécuté dans le `Agents::ExportMailer`). 

Du coup, je pense que je vais nettoyer en mettant un `skip_authentification` dans `Admin::RdvsController`.

2022-01-07 17:01 UTC, yaf commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
Bon, le type Proc est bloqué dans ActiveMailer :angry: 

Je l'ai déjà dit que ce framework me fatigue parfois avec toute sa magie ?

2022-01-07 17:06 UTC, yaf commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
ActiveStorage ne semble pas configuré pour la prod. Ça va se passer comment sur scalingo ?

2022-01-07 17:08 UTC, yaf commented on app/jobs/send_export_job.rb
> +    Agents::ExportMailer.rdv_export(agent.email, data).deliver_later
Ah, mais le hic, c'est que `Agents::ExportMailer` passe aussi par un _background job_, et donc on ne peut pas sérialiser une relation _ActiveRecord_ (et effectivement, ce n'est pas super de sérialiser un gros tableau). Je vais ainsi virer le _job_ qui ne faisait que le passe plat et envoyer les id à `Agents::ExportMailer` qui s'occupera d'appeler le service d'export de RDV.

2022-01-10 10:22 UTC, n-b commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization # RDV will be scoped in SendExportJob
En fait je pense qu’on devrait utiliser le scope normal ici, et dans `search_for` restreindre à ce qui nous intéresse.

2022-01-11 12:30 UTC, yaf commented on app/mailers/agents/export_mailer.rb
> +    agent = Agent.find(agent_id)
Pour la sérialisation, c'est plus facile avec un id. J'imagine que de toute façon, `Active Record`, pour `rehydrater` les données va faire un `Agent.find` ...

2022-01-11 12:30 UTC, yaf commented on app/mailers/agents/export_mailer.rb
> +      subject: "Export RDV du #{now.strftime('%d/%m/%Y')}"
Ah, mais oui ! J'ai copié collé un bout de truc sans regarder le contenu vraiment... Merci !

2022-01-11 15:39 UTC, yaf commented on app/policies/agent/rdv_policy.rb
> +  class ScopeByOrganisation
Oui, je pense aussi...

Et en même temps, je crois que Pundi force à utiliser un `policy_scope` dans les `index` des contrôleurs, et des `authorize` dans les autres méthodes.

Alors c'est vrai que là, j'ai fait un `skip_authorization` dans le contrôleur, alors on pourrait se demander pourquoi je me force à utiliser un `Scope` plus loin :thinking:

J'ai l'impression que quitte à utiliser `Pundit` autant le faire aussi sur cet aspect. Et je n'ai pas une opinion forte là-dessus. Tu souhaites que nous en discutions ou alors c'est très clair pour toi que ce n'est vraiment pas nécessaire de les utiliser ? Voir qu'il ne faut surtout pas les utiliser (ça va nécessiter de faire un truc dans les index sans doute, comme un `skip_authorisation`)?

2022-01-11 16:48 UTC, yaf commented on spec/controllers/admin/rdvs_controller_spec.rb
> +  render_views
Oui, tu as raison. Je vais le remettre en haut, voir l'enlever :)

2022-01-11 16:54 UTC, yaf commented on app/policies/agent/rdv_policy.rb
> +  class ScopeByOrganisation
https://github.com/varvet/pundit#ensuring-policies-and-scopes-are-used

2022-01-11 17:00 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization # RDV will be scoped in SendExportJob
Ici, ce n'est pas un scope, c'est une authorisation. Le scope est demandé sur l'index uniquement. Ok pour le virer du `search_for` par contre.

2022-01-11 17:02 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization # RDV will be scoped in SendExportJob
Ah, mais non, c'est bizarre. Car dans le `search_for` il faut que je reproduise le code qui est dans la police pour savoir si l'agent qui faire la recherche peut voir les RDV de toute l'organisation ou bien seulement de son service (comme liste de RDV de base)

2022-01-12 17:10 UTC, yaf commented on app/mailers/agents/export_mailer.rb
> +    agent = Agent.find(agent_id)
Bon, il semble que rails protège surtout le passage d'une liste (qui pourrait être trop grosse), mais sur un simple objet, c'est ok. Je vais donc faire la modification pour l'agent et l'organisation

https://stackoverflow.com/questions/32154220/cant-pass-collectionproxy-object-to-activejob

2022-01-12 17:15 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization # RDV will be scoped in SendExportJob
Peut-être qu'il faut l'injecter dans le `model` par contre, pour que ce soit un peu plus propre (et avoir les appels `pundit` uniquement dans les contrôleurs)

2022-01-12 17:16 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization # RDV will be scoped in SendExportJob
Ah non, pas possible puisque les collections ne sont pas _sérialisable_ ...

2022-01-12 17:37 UTC, yaf commented
En dehors d'une discussion autour de notre utilisation de Pundit, ça me semble plutôt bon là. Peut-être que nous pouvons prendre un temps de discussion en live au sujet de Pundit ?

2022-01-13 14:47 UTC, yaf commented on app/policies/agent/rdv_policy.rb
> +  class ScopeByOrganisation
Suite à notre discussion, j'écris ici que notre conclusion, c'est de ne pas bricoler des scopes en plus. Il y a aussi un truc en transition pour le passage des changements de droits d'accès…

2022-01-17 10:51 UTC, n-b approved these changes

2022-01-18 08:11 UTC, merged