bump ruby to 3.0.3
betagouv/rdv-solidarites.fr pull request #1965
Opened 2022-01-03 17:32 UTC by n-b

On est un peu en retard, y’a eu ruby 3.1 à noël, mais autant avancer pas à pas.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2022-01-03 21:01 UTC, yaf requested changes
J'ai l'impression qu'il y a un invité surprise :thinking:

2022-01-03 21:01 UTC, yaf commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_12_20_210821) do
tiens, pourquoi ces modif sont ici ?

2022-01-04 07:56 UTC, n-b commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2021_12_20_210821) do
oups, en effet, j’ai glissé.

2022-01-04 10:41 UTC, yaf approved these changes

2022-01-04 13:06 UTC, merged