affiche le lien d'invitation
betagouv/rdv-solidarites.fr pull request #2000
Opened 2022-01-13 12:19 UTC by yaf

Close #1721 

![Screenshot 2022-01-13 at 13-18-16 Invitations en cours pour MDS Paris Nord - RDV Solidarités](https://user-images.githubusercontent.com/42057/149329038-dbf123f8-f669-4405-8df0-e1680f48aa4f.png)

J'aurais aimé avoir un bouton pour copier le lien dans le clipboard, mais l'API javscript autour du clipboard semble très instable. Je ne trouve pas une information fiable.

Checklist avant review:
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touchés inutilement, debug logs qui trainent…).
- [ ] Tester la fonctionnalité sur la review app

2022-01-13 13:20 UTC, yaf commented
Merci @n-b pour le partage de la bonne doc https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText je vais reprendre pour ajouter un bouton de copy du lien

2022-01-13 14:25 UTC, yaf commented
Je crois que c'est bon. Je ne suis pas forcément très satisfait d'avoir ajouté l'évènement à la fois sur l'icône de _font awesome_ ET sur le lien. Mais si je mets l'icône dans le lien, c'est lui qui capte l'évènement « clic », ça devient ensuite un peu tordu de récupérer la donner à copier...

2022-01-13 15:04 UTC, n-b commented
![image](https://user-images.githubusercontent.com/139391/149354922-f8696419-b312-496e-89f0-b4e096649dd7.png)

2022-01-13 15:48 UTC, n-b requested changes
En fait ça marche pas 😅 

Enfin, ça peut pas marcher comme ça. Les liens d’invitations contiennent le `raw_invitation_token`, celui qu’on ne garde pas en base. On est incapable de regénérer un lien d’invitation a posteriori, et c’est _normal_.

Le seul endroit où on peut faire quelque chose, c’est dans la même action que celle du `invite!`. C’est le seul moment où `agent.raw_invitation_token` vaut quelque chose. Le problème c’est que pour le moment, ces actions (`Admin::InvitationsController#reinvite` et `Admin::InvitationsDeviseController#create`) se concluent par un `redirect_to`, donc entretemps on a oublié le `raw_invitation_token`.

À vue de nez, je serais plutôt partant pour ne gérer que le cas de `#reinvite` pour le moment. Dans ce cas, `#reinvite` pourrait renvoyer un bout de js et le fragment de html avec l’url à copier.

D’un point de vue de design, ça veut dire aussi qu’on ne peut avoir qu’un lien d’invitation à la fois à l’écran, donc on n’a sans doute pas besoin d’une colonne dédiée.

2022-01-13 15:48 UTC, n-b commented on config/locales/fr.yml
> +        copy_invitation_link: Copie l'invitation
```suggestion
        copy_invitation_link: Copier l’invitation
```

2022-01-13 15:48 UTC, n-b commented on app/webpacker/components/copytoclipboard.js
> +        console.log(event)
```suggestion
```
🙊

2022-01-13 15:48 UTC, n-b commented on app/webpacker/components/copytoclipboard.js
> +      }, {capture : true})
Ça me perturbe, `capture: true`. C’est parce qu’on met un listener sur un `a`?

2022-01-13 15:48 UTC, n-b commented on app/views/admin/agents/_agent.html.slim
> +    button.btn.fa.fa-clone.js-copy-to-clipboard(data-tocopy="#{accept_agent_invitation_url(invitation_token: agent.invitation_token)}")
👍 👌 le composant générique pour copier un item en data

2022-01-13 15:48 UTC, n-b commented on app/views/admin/invitations/index.html.slim
> +          th= Agent.human_attribute_name(:invitation_token)
En fait on pourrait mettre “copier le lien d’invitation” dans la colonne action, et mettre toutes les actions dans un menu `.dropdown`. (Mais ça dépend même de si ça fonctionne 😅)

2022-01-13 15:52 UTC, yaf commented on app/webpacker/components/copytoclipboard.js
> +      }, {capture : true})
Ah non, j'avais fait un test, mais je peux l'enlever... Merci pour ta vigilance

2022-01-13 15:54 UTC, yaf commented
Ok, je regarde ce qui peut être fait.

Il ne peut y avoir qu'un token valide à un instant T n'est-ce pas ? Nous pourrions enregistrer le `raw_invitation_token` dans la table ou bien c'ets dangereux ?

2022-01-14 09:50 UTC, n-b commented
C’est le principe même du token, on ne stocke en base que le hash de ce qui est envoyé par email. Ainsi, on ne peut pas regénérer un lien d’invitation a posteriori, et personne ne peut usurper l’identité d’un autre utilisateur.

L’idée à la base de 1721, c’est que _de façon exceptionnelle_, un admin peut, au moment où il (re)génère une invitation pour un agent, obtenir ce lien pour lui envoyer par d’autres moyens que par l’email enregistré sur RDVS. C’est un contournement pour les cas où les comptes des agents sont créés avant que leur adresse email soit fonctionnelle, par exemple parce que la DSI prend un peu de temps. Ça arrive.

Mais donc, le serveur ne connait le `raw_invitation_token` que _pendant la requête où `invite!` est appelé_. Ça veut dire que si on veut l’envoyer au client, il faut que ça soit dans la réponse à cette requête.

Je me demande si on ne devrait pas activer cette fonctionnalité au cas par cas pour chaque admin qui le demandera, en prenant le temps d’expliquer le fonctionnement. Sinon, on va avoir des admins qui vont cliquer sur le lien d’invitation sur leur propre poste au lieu de l’envoyer.

2022-01-14 10:16 UTC, yaf commented
Un truc me surprend. J'ai bricolé des liens d'invitation par email par 3 fois pour le 62 puis le 26 pour des agents qui n'arrivaient pas à recevoir le mail d'invitation... Et ça semblait fonctionner :open_mouth: 

Quand j'essaie en local, ça ne fonctionne pas... en recette non plus. Donc en fait, ce que je faisais devait régénérer un mail qui était reçu cette fois-ci sans doute ?

Je vais fermer cette PR et créer un ticket pour évoquer le problème : comment ouvrir un compte agent s'il y a un souci avec les emails ?

Voilà, j'ai posé ça dans #2003

2022-01-14 10:16 UTC, closed without merging