refactor(invitations): Link invitation matching motifs to lieu
betagouv/rdv-solidarites.fr pull request #2046
Opened 2022-01-25 17:11 UTC by aminedhobb

On va laisser la possibilité de passer un `lieu_id` dans l'url d'invitation d'un usager.
Lorsque celui-ci est présent, les motifs disponibles ne doivent correspondre qu'aux motifs qui sont rattachés à ce lieu par des plages d'ouvertures. Cette PR fait ce lien, qui était jusqu'à présent fait seulement sur l'organisation du lieu.

2022-01-25 19:19 UTC, yaf commented
Je ne sais pas si c'est lié, mais j'ai une erreur 500 une fois que j'ai choisi mon créneau (je devrais avoir la page de login / inscription il me semble ?)

https://sentry.io/organizations/rdv-solidarites/issues/2961252291/?project=1811205&query=is%3Aunresolved

(_vous avez un accès à notre Sentry ?_)

`super: no superclass method `starts_at=' for #<Rdv >`

2022-01-25 23:29 UTC, aminedhobb commented
> Je ne sais pas si c'est lié, mais j'ai une erreur 500 une fois que j'ai choisi mon créneau (je devrais avoir la page de login / inscription il me semble ?)
> 
> https://sentry.io/organizations/rdv-solidarites/issues/2961252291/?project=1811205&query=is%3Aunresolved
> 
> (_vous avez un accès à notre Sentry ?_)
> 
> `super: no superclass method 'starts_at=' for #<Rdv >`

Hmm c'est bizarre j'ai pas cette erreur en local mais je l'ai aussi sur la review app. 
A première vue l'erreur ne semble être liée à ce changement, mais j'ai pas accès à votre Sentry non 😬

2022-01-25 23:33 UTC, aminedhobb commented
Je viens de tester et j'ai la même erreur en passant par le chemin normal (et pas `/prendre_rdv`), donc je pense pas que ça vienne de ce changement. Ça vient peut-être du setup de la review app.

2022-01-26 08:33 UTC, n-b commented
Il y a parfois un bug de chargement sur les review apps, je n'ai jamais pris le temps de fouiller. En gros, il suffit de redémarrer l’instance. (Mais il y a peut-être aussi un véritable bug)

2022-01-26 09:55 UTC, aminedhobb commented
> Il y a parfois un bug de chargement sur les review apps, je n'ai jamais pris le temps de fouiller. En gros, il suffit de redémarrer l’instance. (Mais il y a peut-être aussi un véritable bug)

Yes ça a l'air de marcher maintenant 👍

2022-01-26 13:22 UTC, n-b requested changes

2022-01-26 13:22 UTC, n-b commented on app/models/motif.rb
> +  }
En fait, je suis en train de chasser ce genre de scopes 😅 . À mon avis Ça doit être modélisé par des relations `:through`. Ici, ça serait :

1. Dans motif.rb:
`
has_many :lieux, through: :plage_ouvertures
`
2. dans lieu.rb
`
has_many :motifs, through: :plage_ouvertures
`

J’ai fait le test, ça donne la même requête:
```
irb(main):014:0> lieu.motifs.to_sql
=> "SELECT \"motifs\".* FROM \"motifs\" INNER JOIN \"motifs_plage_ouvertures\" ON \"motifs\".\"id\" = \"motifs_plage_ouvertures\".\"motif_id\" INNER JOIN \"plage_ouvertures\" ON \"motifs_plage_ouvertures\".\"plage_ouverture_id\" = \"plage_ouvertures\".\"id\" WHERE \"plage_ouvertures\".\"lieu_id\" = 40"
irb(main):015:0> Motif.for_lieu(lieu).to_sql
=> "SELECT \"motifs\".* FROM \"motifs\" INNER JOIN \"motifs_plage_ouvertures\" ON \"motifs_plage_ouvertures\".\"motif_id\" = \"motifs\".\"id\" INNER JOIN \"plage_ouvertures\" ON \"plage_ouvertures\".\"id\" = \"motifs_plage_ouvertures\".\"plage_ouverture_id\" WHERE \"plage_ouvertures\".\"lieu_id\" = 40"

```

2022-01-26 13:53 UTC, aminedhobb commented on app/models/motif.rb
> +  }
T'as raison c'est bien mieux, j'étais jamais sûr de quand je peux appeler directement `has_many` mais en gros c'est pratiquement tout le temps, même quand c'est un many de many :). 
J'aurais pu garder le scope pour garder la logique de jointure dans le modèle mais je veux pas perturber ta chasse 😄 .

2022-01-27 08:57 UTC, n-b approved these changes

2022-01-27 09:01 UTC, n-b commented on app/services/search_context.rb
> +      motifs = motifs.joins(:lieux).where(lieux: lieu) if lieu.present?
D’ailleurs, `motifs.merge(lieu.motifs)`,  reviendrait au même, mais là ça devient presque une question de style.

2022-01-27 09:01 UTC, n-b approved these changes

2022-01-27 09:07 UTC, merged