Ne pas mélanger les membres des équipes au champ agents du formulaire de créneaux
betagouv/rdv-solidarites.fr pull request #2052
Opened 2022-01-26 15:29 UTC by n-b

fixes #2026

AVANT LA REVUE
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

REVUE
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-01-26 22:07 UTC, yaf commented on app/models/agent.rb
>      service.present? ? "#{reverse_full_name} (#{service.short_name})" : full_name
Ah, en fait c'est un grand rangement dans le modèle, rangement qui n'a rien à voir avec la PR ou bien la modification est masqué dans le mouvement ?

2022-01-26 22:20 UTC, yaf requested changes
Il doit manquer un truc, car le retour aux filtres ne maintient pas l'équipe sélectionnée.

![Screenshot 2022-01-26 at 23-19-02 RDV Solidarités](https://user-images.githubusercontent.com/42057/151256681-5bb4f1ed-2ef9-439e-8d7a-cbc82f49bb62.png)

![Screenshot 2022-01-26 at 23-19-12 RDV Solidarités](https://user-images.githubusercontent.com/42057/151256743-a2c6be6b-cdeb-4ca1-bc24-dffe1e3d0fe5.png)

![Screenshot 2022-01-26 at 23-19-22 RDV Solidarités](https://user-images.githubusercontent.com/42057/151256753-c2a7fff8-9b6e-4e21-b448-2c7f1be484e3.png)

2022-01-26 22:20 UTC, yaf commented on app/services/search_creneaux_for_agents_service.rb
> +    creneaux = SlotBuilder.available_slots(@form.motif, lieu, @form.date_range, OffDays.all_in_date_range(@form.date_range), all_agents)
`all_agents` ne me semble pas correspondre à ce qu'il y a dans la méthode :thinking: `selected_agents` ou `agent_for_filter`, `asked_agents`, ou un truc dans le genre me semblerait plus opportun

2022-01-27 08:53 UTC, n-b commented on app/services/search_creneaux_for_agents_service.rb
> +    creneaux = SlotBuilder.available_slots(@form.motif, lieu, @form.date_range, OffDays.all_in_date_range(@form.date_range), all_agents)
ah, je vois ce que tu veux dire, “all” est pour indiquer que c’est les agents sélectionnés individuellement et ceux des équipes. `all_selected_agents` ça t’irait?

2022-01-27 09:08 UTC, n-b commented on app/models/agent.rb
>      service.present? ? "#{reverse_full_name} (#{service.short_name})" : full_name
Je range un peu, oui :) Je peux faire passer ça dans une PR séparée si tu préfères? En fait ça va un peu avec l’idée de retirer les scopes inutiles et de se baser sur les relations `:through`, mais ça demande d’avoir un modèle propre et cohérent :)

Par exemple il y avait cette relation: `Agent.has_many :lieux, through: :organisation` qui n’a aucun sens, il n’y pas de relation `Agent#organisation` (c’est `#organisations` au pluriel).

2022-01-27 09:24 UTC, n-b commented
> Il doit manquer un truc, car le retour aux filtres ne maintient pas l'équipe sélectionnée.

Ah, en effet, je ne passais pas les team_ids correctement:
* dans la redirection s’il n’y a qu’un lieu
* dans les flèches “semaine suivante” et “semaine précédente”.

Est-ce que j’en profite pour rajouter un helper `url_params` dans `AgentCreneauxSearchForm`? Ça me semble utile, mais j’avais envie de supprimer le form object. Qu’en penses-tu?

2022-01-27 10:31 UTC, yaf commented on app/models/agent.rb
>      service.present? ? "#{reverse_full_name} (#{service.short_name})" : full_name
Non, ça me va dans cette PR. Mais je crois que ç'aurait été pas mal qu'on en parle et que l'on définisse un « modèle » en le précisant quelque part (sorte de _coding guidelines_ que nous pourrions ajouter à notre doc technique ?).

La doc peut être faite dans une autre PR

2022-01-27 10:31 UTC, yaf commented on app/services/search_creneaux_for_agents_service.rb
> +    creneaux = SlotBuilder.available_slots(@form.motif, lieu, @form.date_range, OffDays.all_in_date_range(@form.date_range), all_agents)
Ça me semble plus clair oui :) Merci :bow:

2022-01-27 10:32 UTC, yaf commented
Ça me semble une bonne idée d'avoir ce `helper`. Est-ce qu'on peut l'ajouter ailleurs que dans le `form_object` ?

2022-01-28 10:22 UTC, n-b commented
J’ai poussé un commit encore un peu WIP d’hier soir, mais pas complètement testé. Je repasse en draft, même si c’est, avec un peu de chance, fonctionnel :)

2022-01-31 15:33 UTC, yaf approved these changes

2022-01-31 15:33 UTC, yaf commented on app/helpers/creneaux_helper.rb
> +  end
:star_struck:

2022-01-31 16:21 UTC, merged