🚀 Ébauche de style de code dans la doc
betagouv/rdv-solidarites.fr pull request #2058
Opened 2022-01-27 16:17 UTC by n-b

Commentaires bienvenus :)

AVANT LA REVUE
- [x] ~~Préparer des captures de l’interface avant et après~~
- [x] Nettoyer les commits pour faciliter la relecture
- [x] Supprimer les éventuels logs de test et le code mort

REVUE
- [x] Relecture du code
- [x] ~~Test sur la review app / en local~~

2022-01-28 09:35 UTC, yaf requested changes
Merci d'avoir noté et mis en forme un minimum.

J'ai besoin d'une petite clarification sur les « classes auxiliaires » et après c'est bon pour cette première version ! :)

2022-01-28 09:35 UTC, yaf commented on docs/2-contributions.md
> +    - Par exemple, les form objects, presenters, services, etc.
Cette tournure n'est pas très claire. Il faut éviter les form_object, presenters et services je présume.

Je crois que j'aurais besoin de savoir où mettre certains bouts de code malgré tout. J'ai en tête le livre de Sandy Metz et le fait que tu utilises `app/lib`. Est-ce que tu penses qu'une partie du code qui est dans le répertoire `service` pourrait être placé dans le répertoire `app/lib` ? (ça me convient très bien d'y mettre des librairies, des fonctions utilitaires).

Pour tout dire, j'apprécie l'approche qui viserais à faire des répertoires par domaine métier et y placer les contrôler, vue et modèle et autres... Mais Rails n'est pas ainsi fait, et j'ai un peu de mal avec cette arborescence technique.

2022-01-31 10:35 UTC, n-b commented on docs/2-contributions.md
> +    - Par exemple, les form objects, presenters, services, etc.
Pour moi, dans `lib/`, il ne doit pas y avoir de code ou de ressource utilisé dans l’app. C’est d’ailleurs presque le cas aujourd’hui, il n’y a qu’un module helper pour franceconnect et un csv, qui pourraient venir dans app. Les tâches rake, par contre, y sont à leur place.

Je crois qu’on pourrait configurer le tout de façon transversale, pour mettre (par exemple) le contrôleur et ses vues et helpers au même endroit, je crois que j’aimerais bien.

(Pour les modèles ça me parait plus délicat, ils sont par définition plus interconnectés.

2022-01-31 10:41 UTC, yaf commented on docs/2-contributions.md
> +    - Par exemple, les form objects, presenters, services, etc.
Je pensais surtout à où ranger certains fichiers qui sont dans `services` parce que ce sont des « fonctions » de transformation de l'information, des bouts de code qui ne sont pas sur un objet persisté en base de données (je ne sais pas si je suis clair ?). Et notre doc ne dit pas ce que nous allons faire de ces bouts de code qui ne sont pas des modèles, pas des contrôleurs, pas des helper, pas des vues...

2022-01-31 10:41 UTC, yaf commented on docs/2-contributions.md
> +    - Par exemple, les form objects, presenters, services, etc.
(pour le `/lib` :+1: complétement ok)

2022-01-31 10:52 UTC, n-b commented
Est-ce qu’on dit qu’on fait passer ce genre de truc en prod sans attendre?

2022-01-31 11:33 UTC, yaf commented
oui :)

2022-01-31 13:06 UTC, yaf approved these changes

2022-01-31 15:15 UTC, merged