Considère le délai min et max du motif
betagouv/rdv-solidarites.fr pull request #2127
Opened 2022-02-08 22:52 UTC by yaf

Close #2005 

Nous ne prenions pas en compte les délais min et max configuré dans le motif au moment du calcul de créneau.

Il y a plusieurs façons de le prendre en compte. J'ai opté pour la modification de la période de recherche de créneau (déplacement des bornes en fonction de la configuration du motif). C'es ce qui me semble le plus optimum.

Nous pourrions imaginer que cette opération soit réalisé avant, en dehors du calcul de créneau, mais je crois le code pas assez nettoyer encre... et ça permet d'avoir une vue d'ensemble comme ça.

AVANT LA REVUE
- [x] ~~Préparer des captures de l’interface avant et après~~
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

REVUE
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-02-10 12:59 UTC, victormours requested changes

2022-02-10 12:59 UTC, victormours commented on app/services/slot_builder.rb
> +      end_range = if motif.max_booking_delay.positive?
idem, le max_booking_delay est toujours positif, donc on peut supprimer ce if, et juste garder la première branche

2022-02-10 12:59 UTC, victormours commented on spec/services/slot_builder_spec.rb
> +  describe "#motif_delay_and_range_union" do
pour mieux comprendre les règles métiers, et être moins couplés à l'implémentation, on pourrait faire des specs sur `SlotBuilder.available_slots`

2022-02-10 15:40 UTC, yaf commented on app/services/slot_builder.rb
> +      return date_range if motif.min_booking_delay.zero? && motif.max_booking_delay.zero?
ah oui, merci, je n'avais pas fait attention :)

2022-02-10 16:27 UTC, yaf commented on spec/models/file_attente_spec.rb
> +      let!(:plage_ouverture2) { create(:plage_ouverture, first_day: 8.days.from_now, start_time: Tod::TimeOfDay.new(9), lieu: lieu, agent: agent, motifs: [motif], organisation: organisation) }
Ça, c'est un peu à cause des changements faits sur le  `NextAVailability` la dernière fois... pourquoi ça n'avait pas cassé avant ?

2022-02-21 16:47 UTC, victormours approved these changes
👍 cool !

2022-02-22 08:24 UTC, merged