ajoute recherche par description plage d'ouverture
betagouv/rdv-solidarites.fr pull request #2166
Opened 2022-02-18 16:08 UTC by rebeccadumazert

Ref #1918 

Ajoute barre de recherche pour faciliter recherche de plage d'ouverture.
Ici nous ne prenons en compte que le label description de la plage d'ouverture.
Il faudrait ouvrir une autre PR afin de faire des recherches sur dates/motifs/lieu...

![image](https://user-images.githubusercontent.com/44778533/154718913-cdae51fd-9a9d-41b1-85c6-3dd1376c545b.png)

AVANT LA REVUE
- [x] Préparer des captures de l’interface avant et après
- [x] Nettoyer les commits pour faciliter la relecture
- [x] Supprimer les éventuels logs de test et le code mort

REVUE
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-02-21 08:54 UTC, n-b reviewed
Il faut que tu commites le `schema.rb` mis à jour pour que la CI passe. Pour brakeman, je sais pas trop exactement pourquoi ça pose problème ici, je sais plus comment on fait pour les autres cas, mais ça doit se résoudre :)

(On fait `rake db:setup` dans `.github/ci.yml`, ce qui charge le schema plutôt que de faire les migrations. Je garde [cette cheat sheet](https://jacopretorius.net/2014/02/all-rails-db-rake-tasks-and-what-they-do.html) sous le coude.)

2022-02-21 08:54 UTC, n-b commented on app/views/admin/plage_ouvertures/index.html.slim
> +    | Vos plages d'ouvertureeee
👀

2022-02-21 08:54 UTC, n-b commented on app/views/admin/plage_ouvertures/index.html.slim
> +            | Il n'y a pas de résultat correspondant à votre recherche.
i18n au passage?

2022-02-21 09:36 UTC, rebeccadumazert commented on app/views/admin/plage_ouvertures/index.html.slim
> +    | Vos plages d'ouvertureeee
oups

2022-02-22 09:18 UTC, n-b requested changes
Petit retour sur le lien Reset et pinaillages sur i18n, mais sinon je crois qu‘on est bon.

2022-02-22 09:18 UTC, n-b commented on app/views/admin/plage_ouvertures/index.html.slim
> +    div= link_to t(".reset"), admin_organisation_agent_plage_ouvertures_path(current_organisation, @agent.id), class: "btn btn-link"
En fait ici, la variable `search` sert à masquer le lien reset si le champ est vide. C’est le cas sur la recherche d’agents ou de motifs, par exemple. C’est fait comme ça dans les autres vues:
```
      - search = params[:search].blank? ? "d-none" : ""
      div= link_to "Réinitialiser", admin_organisation_motifs_path(current_organisation), class: "btn btn-link #{search}"
```

Comme on utilise rails 6.1, on peut maintenant utiliser `class_names`, donc on peut écrire
```suggestion
    div= link_to t("helpers.reset"), admin_organisation_agent_plage_ouvertures_path(current_organisation, @agent.id), class: class_names("btn", "btn-link", "d-none": params[:search].blank?)
```

(avec au passage la clé `helpers.reset` pour mettre i18n en commun.)

2022-02-22 10:13 UTC, rebeccadumazert commented on app/views/admin/plage_ouvertures/index.html.slim
> +    = t(".your_aperture_range")
rah j'ai hésité en plus ! merci

2022-02-24 08:48 UTC, n-b approved these changes

2022-02-24 08:56 UTC, merged