Rdv Collectifs v0
betagouv/rdv-solidarites.fr pull request #2171
Opened 2022-02-21 17:01 UTC by victormours

Close #2163 

AVANT LA REVUE
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

REVUE
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-02-21 20:00 UTC, n-b requested changes
Ça m’a l’air très très cool! Hormis la discussion sur les notifiers, j’ai surtout des remarques de style surtout et du pinaillage sur i18n.

2022-02-22 14:48 UTC, victormours commented on app/controllers/admin/motifs_controller.rb
> +  before_action :set_available_services, only: %i[new edit update]
c'est dans le cas où il y a une erreur de validation et qu'on render edit. Finalement j'ai ajouté un appel explicite à `set_available_services` dans cette branche de code, c'est plus simple à comprendre.

2022-02-22 14:51 UTC, victormours commented on app/views/admin/rdv_wizard_steps/step1.html.slim
> += render "admin/rdv_wizard_steps/card", rdv_wizard_form: @rdv_wizard, next_steps: [{step: 2}, {step: 3}, {step: 4}], step_title: t(".step_title") do
au début c'est parce que je me retrouvais à render ce step depuis une autre vue (j'ai eu un `RDVCollectifController#new` à un moment), mais c'est plus utilisé. Je l'enlève.

2022-02-22 17:40 UTC, n-b reviewed
Ça m’a l’air ok, je fais quelques tests et 🚀

2022-02-22 17:40 UTC, n-b commented on app/services/notifiers/rdv_collectif_participations.rb
> +end
Ça me va très bien. Je me demande s’il y aurait un moyen de faire remonter cette notion de “participation” dans le cas général, c’est-à-dire de faire en sorte de n’appeler `Notifiers::RdvCreated` et `Notifiers::RdvCancelled` qu’à un seul endroit. Peut-être qu’il faudrait se baser sur un `RdvsUserUpdater` plutôt que sur `RdvUpdater`. Ça pousse pour renommer `RdvsUser` en `Participation`, en tout cas.

2022-02-22 17:40 UTC, n-b commented on app/services/notifiers/rdv_base.rb
> +    @users = users || rdvs_users_to_notify.map(&:user)
Ça mérite peut-être un petit commentaire.

2022-02-22 17:49 UTC, n-b commented on app/services/rdv_updater.rb
> +      previous_participant_ids = rdv.participants_with_life_cycle_notification_ids
Ah, il y avait encore cette affaire que j’ai peut-être pas comprise https://github.com/betagouv/rdv-solidarites.fr/pull/2171#discussion_r811396177

Pourquoi filtrer ici les participants selon `send_lifecycle_notifications`? On pourrait le faire tout à la fin, dans `new_participants` et `deleted_participants`, non?

2022-02-22 18:01 UTC, n-b approved these changes
ok donc à part [cette discussion](https://github.com/betagouv/rdv-solidarites.fr/pull/2171#discussion_r812207733) qui peut attendre, ça m’a l’air 🚀

2022-02-23 08:56 UTC, victormours commented on app/services/rdv_updater.rb
> +      previous_participant_ids = rdv.participants_with_life_cycle_notification_ids
La colonne lifecycle_notifications est sur rdvs_users, donc pour les participations supprimées on ne peut pas les retrouver avec juste les ids des users.

2022-02-23 08:58 UTC, victormours commented on app/services/notifiers/rdv_collectif_participations.rb
> +end
Oui, je pense que la notion de participations va apparaitre de plus en plus, et que dans l'ui aussi on va se mettre à parler de "participants" plutôt que d'"usagers" pour les rdv collectifs

2022-02-23 09:30 UTC, n-b commented on app/services/rdv_updater.rb
> +      previous_participant_ids = rdv.participants_with_life_cycle_notification_ids
Arf, évidemment. Mmmmmm, J’ai vaguement envie de fouiller si je trouve une gem qui permettent d’étendre les `previous_changes` aux relations, mais en vrai, là aussi on veut parler de Participations. Peut-être un petit commentaire là aussi?

2022-02-23 13:28 UTC, merged