refactor(invitations): Revamp invited user journey[4/4]
betagouv/rdv-solidarites.fr pull request #2197
Opened 2022-03-01 11:54 UTC by aminedhobb

Vient après #2164 .

## Contexte 
Cette PR est la dernière d'un set de 4 PRs dont le but est de changer la manière dont un utilisateur invité prend RDV.

Dans cette PR je change tous les liens envoyés dans les sms et les mails envoyés aux utilisateurs lorsqu'un rdv est créé, changé, annulé ou rappelé pour y insérer le lien du rdv avec un token d'invitation. Ceci permet à l'utilisateur d'accéder aux détails de ce rdv et éventuellement le modifier sans se connecter mais juste en rentrant les 3 premières lettres de son nom de famille (voir #2164 ) à la manière de doctolib.
Cette PR ne concerne pas seulement les utilisateurs invités mais tous les utilisateurs de RDV-Solidarités.

## Mécanisme

Pour se faire je rajoute `devise_invitable` et les colonnes correspondantes à la table `RdvsUser`, pour pouvoir permettre à un utilisateur d'être invité dans le contexte d'un rdv.

Lorsque l'on va notifier l'utilisateur (`Notifiers::RdvBase`), on va d'abord générer des tokens sur tous les `rdvs_users` à notifier soit les utilisateurs liés au rdv en question. Cet endroit me parait propice pour la génération car c'est ici qu'on décide qui doit être notifié.

On va ensuite passer ce token dans tous les sms/mails envoyés à partir de ce service et les rajouter dans les urls envoyés.
Les notifiers doivent aussi renvoyer ces tokens en sortie pour pouvoir les récupérer les nouveaux tokens au moment de la redirection après création/modification/annulation d'un rdv.

Aussi, lorsqu'un token lié à un `rdvs_user` est passé en paramètre, on marque l'utilisateur comme invité dans le contexte de ce rdv précis. Il ne pourra pas accéder à d'autres rdvs avec ce token.

## Développements annexes

Certains développements annexes ont été faits dans le cadre de cette PR:

* On ne laisse pas la possibilité à l'utilisateur de modifier l'horaire d'un rdv créé par un agent
* Lorsqu'on invite un utilisateur à reprendre un rdv (annulation d'un rdv précédent ou créneau indispo au moment de la prise du rdv) on redirige maintenant toujours vers `/prendre_rdv`. La logique est la même que pour `/lieux` mais prend en + en compte les invitations, et il est de toutes façons prévu qu'à terme il n'y ait plus que ce chemin qui soit utilisé.

## Remarques

* 2 noms de paramètres peuvent être maintenant passés pour les tokens d'invitations: `invitation_token` et `tkn`. On pourrait trouver des noms + descriptifs mais on doit garder le premier pour l'instant qui est envoyé actuellement dans les liens d'invitations depuis RDV-I et le deuxième sert à avoir un sms le + court possible.
* Les personnes qui prennent rdv pour un proche n'ont pas pour l'instant de token dans leur lien vers le rdv car elles ne sont pas liées directement au rdv (l'utilisateur notifié est différent de l'utilisateur lié au rdv). Ça me parait acceptable vu qu'il faut dans tous les cas créer un compte avec mdp pour prendre rdv à un proche.
* De nouveaux tokens sont générés à chaque fois pour notifier la personne et donc invalident les précédents. Du coup si par exemple une notification de rappel n'est pas correctement envoyée, le lien reçu dans le message précédent (de création de rdv) ne marcherait plus. 
* Au moment de rebaser la branche `refactor/invited-user-journey` avec `production` j'ajouterai la classe `RdvsUser` comme étant une classe pour laquelle on veut utiliser notre custom token generator.

2022-03-08 15:34 UTC, n-b reviewed
Il y a encore des points à éclaircir sur la nécessité de recréer le token de rdv dans le notifier.

2022-03-08 15:34 UTC, n-b commented on spec/services/notifiers/rdv_cancelled_spec.rb
> +        expect(subject.rdv_tokens_by_user_id).to eq({ user.id => token })
C’est dommage de devoir répéter ce test à chaque notifier alors que c'est dans rdv_base 🤔  (j'ai pas de suggestion)

2022-03-08 15:34 UTC, n-b commented on spec/features/users/user_can_search_rdv_spec.rb
> +      expect(page).to have_content(motif.name)
Est-ce que c’est lié au reste de la PR?

2022-03-08 15:34 UTC, n-b commented on app/controllers/users/rdvs_controller.rb
> +      notifier = Notifiers::RdvCreated.perform_with(@rdv, current_user)
En tout cas, le nom de variable n'est pas descriptif: ce qu’on a “dedans”, c'est les tokens des rdvs_users a qui on a envoyé des notifs.

2022-03-08 15:34 UTC, n-b commented on app/controllers/users/rdvs_controller.rb
> +      notifier = Notifiers::RdvCreated.perform_with(@rdv, current_user)
À terme en tout cas, ça aurait plus de sens que les notifiers/mailers soient construits sur les “Participations” (les rdvs_users) plutôt que sur les Rdv.

2022-03-09 17:08 UTC, aminedhobb commented on spec/features/users/user_can_search_rdv_spec.rb
> +      expect(page).to have_content(motif.name)
En fait c'est lié à ce que j'avais fait sur la PR précédente et que j'avais oublié de rajouter: un utilisateur loggé peut voir le motif du rdv (contrairement à l'utilisateur du rdv).
Si ça t'embête de le laisser ici je peux l'enlever et je l'ajouterai sur la branche principale une fois qu'on aura mergé les 4 PRs.

2022-03-09 17:09 UTC, aminedhobb commented
J'ai appliqué tes suggestions @n-b .
Pour l'instant je renvoie directement les tokens en sortie des notifiers (sans OpenStruct), c'est un peu + clair déjà je trouve.
Pour la création des tokens, je vois au moins 3 cas où on est obligé d'en créer: pour le reminder, pour la file d'attente, et pour la création du rdv.

2022-03-09 17:10 UTC, aminedhobb commented on app/policies/user/rdv_policy.rb
> +    cancel? && !record.created_by_agent?
du coup j'ai ajouté une méthode `editable_by_user?` sur un rdv qui empêche l'édition d'un RDV si le motif n'est pas réservable en ligne et s'il a été créé par un agent (ce point est peut-être + discutable).

2022-03-21 21:32 UTC, yaf commented
Merci pour tout ce boulot !

Pour faire une démo demain, avant de faire le merge, je faisais un petit tour pour voir ce qui est visible sans invitation (en attendant qu'elles arrivent :p) et je ne suis pas sûr de ce que je peux faire/montrer.

- J'ai un bouton pour modifier mon RDV qui est dispo 
- Quand je clique dans le mail, je peux annuler mon RDV et le déplacer sans m'authentifier (même pas en saisissant les 3 lettres de mon nom). Est-ce que c'est bien ce que l'on attend ici ?

Je ne vois rien d'autres d'accessible. J'ai raté un truc ?

Pour l'annulation / déplacement, je trouve ça trop bien. C'est peut-être mieux s'il y a une double vérification, avec les lettres du nom, mais en même temps, nous les affichons dans le mail, ça n'apporte pas une grande sécurité en plus :facepalm: 

J'avais l'impression que ça permettait de traiter la vieille issue #1805. Mais je ne reçois pas de notification SMS pour m'en assurer. C'est surprenant, je pensais que sur les review apps, les SMS partaient :thinking:

2022-03-24 10:36 UTC, n-b requested changes
“Suggest changes” plutôt que “Request changes”, parce que c’est très très cool cette histoire. Je crois qu’on est quasiment bon.

(J’ai un peu peur pour le rebase sur `main`)

2022-03-24 10:36 UTC, n-b commented on config/routes.rb
> +  end), as: "rdv_shorten"
Je pinaille sur le nommage, et d’ailleurs c’est déjà comme ça dans le code existant, mais ça serait plutôt “short_url” que “shorten_url”. (ou à la limite “shorter_url”. Enfin bref, shorten c’est un verbe.)

2022-03-24 10:36 UTC, n-b commented on config/routes.rb
> +    "users/rdvs/#{path_params[:id]}#{params.values.any? ? "?#{params.to_query}" : ''}"
ou sinon, faire le “to_query” dans le helper “format_redirect_params”?

2022-03-24 10:36 UTC, n-b commented on db/migrate/20220309133231_add_show_token_in_sms_to_organisations.rb
> +    add_column :organisations, :show_token_in_sms, :boolean, default: false
poke @yaf Est-ce qu’on veut pas plutôt mettre cette configuration au niveau des territoires?

Il s’agit d’afficher le token (la version courte, 8 caractères) dans le lien d’accès au rdv dans le sms.

2022-03-24 10:36 UTC, n-b commented on spec/controllers/concerns/token_invitable_spec.rb
> +    def fake_action
👌 

Tiens, tout ce test aurait pu être dans la PR précédente, non? Je me demande si TokenInvitable ne mériterait pas un paragraphe explicatif, le pourquoi, le comment, etc.

2022-03-24 10:36 UTC, n-b commented on app/models/rdv.rb
> +    cancellable? && motif.reservable_online && !created_by_agent?
OK, moi ça me va, mais il faut le noter pour la présentation aux référentes. Aujourd’hui, de toutes façons, les Rdv ne sont pas éditables du tout par les usagers. 

Poke @yaf et @victormours, ça a bougé récemment, non?

2022-03-24 10:36 UTC, n-b commented on app/controllers/concerns/token_invitable.rb
>      # rubocop:disable Rails/DynamicFindBy
Pinaillage de style: plutôt que de disable/enable dans deux méthodes, ce qui est un peu fragile si on les réordonne, autant faire un disable à la fin de chacune des deux lignes.

2022-03-24 10:36 UTC, n-b commented on app/services/rdv_updater.rb
> +      )
Autant définir une petite classe `RdvUpdater::Result`? Les OpenStruct, ça fait un peu bricolage, et on est quand même dans un truc central.

2022-03-24 10:36 UTC, n-b commented on app/services/rdv_updater.rb
> +    def notifier_for_rdv(rdv)
```suggestion
    def notifier_for_changes(rdv)
``` 
?

2022-03-29 08:53 UTC, aminedhobb commented on app/controllers/concerns/token_invitable.rb
> +    @user_by_token ||= User.find_by_invitation_token(session[:invitation_token], true)
Ah ok j'avais pas compris ça my bad! Fait ici : https://github.com/betagouv/rdv-solidarites.fr/pull/2197/commits/659169f4138e748835c6b8360ef41e773a06c72a

2022-03-29 15:42 UTC, yaf approved these changes

2022-03-29 16:22 UTC, merged