Rendre certains champs optionnels pour les fiches usagers
betagouv/rdv-solidarites.fr pull request #2204
Opened 2022-03-02 09:39 UTC by victormours

Close #2192

<img width="580" alt="Capture d’écran 2022-03-02 à 10 30 56" src="https://user-images.githubusercontent.com/1840367/156334822-0398416a-e0c7-4a80-aa74-d32609c340ed.png">
<img width="1088" alt="Capture d’écran 2022-03-02 à 10 31 04" src="https://user-images.githubusercontent.com/1840367/156334818-dc06e3c2-8029-4cf9-934b-1d53be748fc5.png">
<img width="837" alt="Capture d’écran 2022-03-02 à 10 34 03" src="https://user-images.githubusercontent.com/1840367/156334810-1b9c9572-663d-4d68-a39a-dbb2e2ca12fe.png">

On ajoute une option de configuration pour cacher ou afficher certains champs des fiches usagers.
Cette PR répond à deux besoins : 
- limiter les champs inutiles pour les cnfs (et pour d'autres services)
- limiter les risques sur les données personnelles en évitant d'avoir un champs "Remarques"

Vu le temps limité par les autres sujets cnfs (onboarding et rdv collectifs entre autres), il y a plusieurs points qui ne sont pas abordés dans cette pr :
- les champs "logement" et "notes" ne sont pas déplacés de user_profiles vers users
- le champs "numéro de dossier" évoqué avec les référentes n'est pas ajouté
- les api continuent de donner accès à ces champs

Je pense que ces différents points peuvent être traités plus tard dans le cadre d'une autre issue.

REVUE
- [x] Relecture du code
- [x] Test sur la review app / en local

2022-03-02 20:48 UTC, yaf requested changes
Très cool d'avoir fait ça :tada: 

J'ai malgré tout deux petites demandes d'ajustement. Si tu souhaites en discuter, fais-moi signe.

2022-03-02 20:48 UTC, yaf commented on spec/features/agents/users/agent_can_update_user_spec.rb
> +  describe "optional fields" do
Ah je ne pensais pas que tu étais du genre test de features ; je te croyais plutôt test unitaire, TDD :grinning:

2022-03-02 20:48 UTC, yaf commented on db/migrate/20220301100400_add_fields_display_to_territories.rb
> +    add_column :territories, :enable_logement_field, :boolean, default: false
C'est cool que ça soit désactivé par défaut, mais pour que chaque département puisse faire la bascule qu'il souhaite, de la manière qu'il le souhaite, je crois qu'il faudrait mettre à `true` au moins pour les territoires du médico-social (ceux qui ont un numéro comme valeur du `territory.departement_number` ?).

2022-03-02 20:48 UTC, yaf commented on app/views/admin/territories/show.html.slim
> +  .col.col-md-4.p-2.rounded.settings-box
J'ai oublié de mettre un commentaire sur l'icône de liste des organisations, mais je crois que ça serait mieux si la liste des orgas étaient placée toujours à la fin. Plus facile à repérer, et pour le moment, c'est LE moyen de sortir de la configuration pour retourner à l'écran métier. C'est pour ça que je l'avais mis en dernier.

2022-03-03 09:09 UTC, victormours commented on app/controllers/admin/territories/user_fields_controller.rb
> +class Admin::Territories::UserFieldsController < Admin::Territories::BaseController
J'ai oublié de le mettre, et il n'y a pas les after_actions de pundit sur ces controllers. 🤔 En regardant ça de plus près, je me rend compte qu'on a un trou dans la raquette, et qu'il manque des authorize sur d'autres controllers de la configuration. Je suis en train de préparer une pr séparée pour les ajouter

2022-03-03 10:00 UTC, yaf commented on app/controllers/admin/territories/user_fields_controller.rb
> +class Admin::Territories::UserFieldsController < Admin::Territories::BaseController
C'est déjà plus ou moins ma PR en cours #2184

2022-03-03 10:26 UTC, victormours commented on app/controllers/admin/territories/user_fields_controller.rb
> +class Admin::Territories::UserFieldsController < Admin::Territories::BaseController
cool, du coup j'ajoute juste les authorize qui vont bien sur ce controller

2022-03-03 10:31 UTC, victormours commented on db/migrate/20220301100400_add_fields_display_to_territories.rb
> +    add_column :territories, :enable_logement_field, :boolean, default: false
oui, c'est le but du update_all qu'il y a dans la suite du fichier : par défaut tous les champs pour les territoires existants continueront d'être affichés, et on peut les désactiver au cas par cas.
Pour les territories qui seront créés dans le futur par contre, les `default_false` éviteront que ces champs soient affichés, pour éviter que les nouveaux utilisateurs commencent avec des mauvaise habitures

2022-03-03 10:33 UTC, victormours commented on app/views/admin/territories/show.html.slim
> +  .col.col-md-4.p-2.rounded.settings-box
aah, c'est bon à savoir. J'ai changé l'ordre et ajouté un commentaire

2022-03-03 12:47 UTC, yaf approved these changes
Merci ! :shipit:

2022-03-03 12:47 UTC, yaf commented on db/migrate/20220301100400_add_fields_display_to_territories.rb
> +    add_column :territories, :enable_logement_field, :boolean, default: false
Ah, mais ok, pardon, j'avais mal lu ou lu trop vite, ce qui est équivalent... ⁣:bow: 

Merci pour ta compréhension et l'explication !

2022-03-03 14:31 UTC, merged