RDV Collectifs : limite du nombre de participants
betagouv/rdv-solidarites.fr pull request #2315
Opened 2022-03-29 16:10 UTC by victormours

Close #2188

Cette PR ajoute la possibilité de gérer les participants à un rdv collectif.

<img width="1405" alt="Capture d’écran 2022-03-29 à 17 46 08" src="https://user-images.githubusercontent.com/1840367/160655064-2c46d7cc-f936-49fb-9bc1-01b77526bf33.png">

Dans l'index des rdv collectifs, on a un aperçu du nombre de participants
<img width="1131" alt="Capture d’écran 2022-03-29 à 17 45 31" src="https://user-images.githubusercontent.com/1840367/160655083-92fe16c4-c209-4886-82b8-92c25ec38699.png">

<img width="1123" alt="Capture d’écran 2022-03-29 à 17 46 14" src="https://user-images.githubusercontent.com/1840367/160655059-e2090e7b-800a-40a6-88d0-e5ba265a5b6f.png">

<img width="1124" alt="Capture d’écran 2022-03-29 à 18 00 13" src="https://user-images.githubusercontent.com/1840367/160655049-6d34463c-3639-42c4-949d-89d7702c1aed.png">

<img width="1146" alt="Capture d’écran 2022-03-29 à 17 59 52" src="https://user-images.githubusercontent.com/1840367/160655056-731e8454-54f9-417d-9bb5-815073ee71a8.png">

Comme montré lors de la réunion référente il y a quelques semaines, il est possible de faire de la sur-réservation.

### Implémentation

Pour éviter de surcharger la base, cette PR ajoute un counter cache sur le nombre de participants. Pour éviter de faire trop d'écritures, ce counter cache n'est activé que pour les rdv collectifs (il n'est pas mis à jour pour les autres rdvs). Cette option n'étant pas disponible avec les counter-cache classiques de rails, ça a motivé l'ajout de la gem counter-culture.
Pour clarifier que ce counter cache n'est que pour les rdv collectifs, j'ai préfixé son nom, mais je ne suis pas sûr que ça soit l'option la plus élégante.

Pour le moment, cette fonctionnalité est encore cachée. Une fois qu'elle sera mergée, je vais voir comment je peux l'intégrer à la recherche par créneaux.

REVUE
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-03-30 08:59 UTC, n-b requested changes
Ça m’a l’air assez cool. 🌮 

Deux remarques principales: 
* Autant activer le counter_cache pour tous les rdvs, à long terme ça sera plus simple, je pense.
* Est-ce qu’on essaie d’unifier l’édition des rdv normaux et collectifs? Si on continue à les distinguer, ça va coûter de plus en plus cher. (et en plus, ce que j’ai fait pour l’ajout de participants à un Rdv est un peu cracra.)

2022-03-30 08:59 UTC, n-b commented on app/controllers/admin/rdvs_collectifs_controller.rb
> +      rdvs_users_attributes: %i[user_id send_lifecycle_notifications send_reminder_notification id _destroy]
👍

2022-03-30 08:59 UTC, n-b commented on app/form_models/admin/rdv_collectif_search_form.rb
> +      rdvs = rdvs.where("rdv_collectif_users_count < max_participants_count OR max_participants_count IS NULL")
Ça vaudrait pas le coup de définir ça comme scope dans `rdv.rb`?

2022-03-30 08:59 UTC, n-b commented on app/controllers/admin/rdvs_collectifs_controller.rb
> +    authorize(@rdv, :edit?)
Pinaillage: on peut mettre le authorize juste après la ligne `@rdv =`? J’ai l’impression que c’est là que je m’attends à la trouver.
```suggestion
    authorize(@rdv, :edit?)

    @add_user_ids = params[:add_user].to_a + params[:user_ids].to_a
    users_to_add = User.where(id: @add_user_ids)
    @rdv_users_to_add = users_to_add.ids.map { @rdv.rdvs_users.build(user_id: _1) }
```

2022-03-30 08:59 UTC, n-b commented on app/models/rdvs_user.rb
> +  counter_culture :rdv, column_name: proc { |rdv_user| rdv_user.rdv.collectif? ? "rdv_collectif_users_count" : nil }
1. Pourquoi a-t-on besoin de `counter_culture` ? On ne peut pas faire un `counter_cache` normal ?
2. Est-ce que c’est pour ne compter que les rdv collectifs? Est-ce que ça serait un vrai problème de garder un `counter_cache` de pour tous les rdvs? Dans les faits, on modifie rarement les participants à un rdv.

2022-03-30 08:59 UTC, n-b commented on app/views/admin/rdvs/edit.html.slim
> +              = f.input :max_participants_count, label: "Nombre de places", input_html: { min: 1 }
i18n please :)

(en plus dans les formulaires, l’existence de la clé dans le fichier yml ajoute le label automatiquement)

2022-03-30 08:59 UTC, n-b commented on config/routes.rb
> +          end
Est-ce que ça ne serait pas simplement `:edit` et `:update` ?

2022-03-30 08:59 UTC, n-b commented on db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
> +    add_column :rdvs, :max_participants_count, :integer
J’aime bien participant. Je pensais renommer `RdvsUser` en `Participation` un jour ou l’autre, mais Participant c’est bien aussi. Est-ce que ça irait comme nouveau nom pour `RdvsUser`?

2022-03-30 08:59 UTC, n-b commented on db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
> +      end
Il y a probablement moyen de faire une seule grosse requête SQL, sans doute un poil complexe. Je sais pas si ça vaut le coup: en tout cas, là, on fait N queries, avec N = le nombre de Rdv collectifs. C’est pour ça que tu ne veux mettre le counter cache que sur les rendez-vous collectifs? 😬

2022-03-30 08:59 UTC, n-b commented on spec/spec_helper.rb
> +  # options.add_argument("--headless")
🤨

2022-03-30 08:59 UTC, n-b commented on spec/support/select2_spec_helper.rb
> +    # This is to make sure we wait for the user to be added before doing the next action
```suggestion
    # Wait for the user to be added before doing the next action
```

2022-03-30 09:27 UTC, victormours commented on spec/spec_helper.rb
> +  # options.add_argument("--headless")
wooops, p'tit bricolage de débuggage commité par erreur

2022-03-30 16:49 UTC, victormours commented on app/form_models/admin/rdv_collectif_search_form.rb
> +      rdvs = rdvs.where("rdv_collectif_users_count < max_participants_count OR max_participants_count IS NULL")
yep, c'est fait !

2022-03-30 16:50 UTC, victormours commented on app/models/rdvs_user.rb
> +  counter_culture :rdv, column_name: proc { |rdv_user| rdv_user.rdv.collectif? ? "rdv_collectif_users_count" : nil }
Yep, c'est effectivement plus simple avec un counter_cache normal. Comme discuté en visio, j'ai changé ça, et mis à jour la migration pour backfill la colonne simplement

2022-03-30 16:51 UTC, victormours commented on db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
> +    add_column :rdvs, :max_participants_count, :integer
Yep, ça pourrait être bien. Je suis tenté de reporter ça à une pr plus tardive ceci dit :)

2022-03-30 16:51 UTC, victormours commented on db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
> +      end
au final la requête est assez simple :-)

2022-03-31 09:55 UTC, victormours commented on config/routes.rb
> +          end
yes, c'est plus simple

2022-03-31 13:35 UTC, n-b commented on db/migrate/20220321103957_add_rdvs_max_participants_count_and_users_count.rb
> +    add_column :rdvs, :max_participants_count, :integer
oui oui, c’est juste pour discussion

2022-03-31 13:47 UTC, n-b approved these changes
👍

2022-03-31 13:47 UTC, n-b commented on app/models/rdv.rb
> +  scope :with_remaining_seats, -> { where("users_count < max_participants_count OR max_participants_count IS NULL") }
Au fait, ça vaudrait le coût d’indexer les deux nouvelles colonnes? Si on fait une requête dessus?

2022-03-31 13:59 UTC, victormours commented on app/models/rdv.rb
> +  scope :with_remaining_seats, -> { where("users_count < max_participants_count OR max_participants_count IS NULL") }
yep, bonne idée. C'est ajouté

2022-03-31 16:43 UTC, merged