feat(rdv): add categories to motif
betagouv/rdv-solidarites.fr pull request #2328
Opened 2022-04-04 15:00 UTC by qblanc

Dans cette PR, j'ajoute la possibilité d'appliquer une catégorie aux motifs. Cette feature nous est nécessaire pour récupérer des rdvs en fonction de leurs motifs sans dépendre du nom du motif.

Cette liste est pour l'instant constituée sous forme d'enum, hardcodée, et devra être éditée à la main en fonction des remontées terrain. Un dropdown de sélection de la catégorie, pour l'instant optionnel et limité à un faible nombre de catégories, a été ajouté au formulaire de création comme l'avait suggéré Yannick pour "tester" les réactions.

![image](https://user-images.githubusercontent.com/46218316/161570229-46c0303e-c643-4116-922a-7708a29a7d05.png)

P.S.: je n'arrive pas à faire un commit propre par rapport au schema et au domain model, sorry 😕

2022-04-05 08:44 UTC, aminedhobb reviewed
Moi ça me va, à voir avec @yaf et @n-b ce qu'ils en pensent. 
On pourrait éventuellement décider au niveau du territoire si on veut afficher cette option de catégorie ou non si on veut éviter que les différentes orgas soient perturbés par ces catégories. Mais l'idée de @yaf de l'afficher à tout le monde pour faire réagir les départements me va aussi !

2022-04-05 08:44 UTC, aminedhobb commented on config/locales/models/motif.fr.yml
> +        rsa_orientation_phone_platform: RSA - Orientation sur une plateforme téléphonique
Pour info pour l'équipe RDV-S: Il ne s'agit pas là d'un RDV d'orientation avec un agent par téléphone, ici c'est le bRSA qui appelle une plateforme téléphonique qui gèrera son orientation. D'où la catégorie à part, même si ça peut être confusant.

2022-04-05 10:10 UTC, victormours requested changes
Est-ce que vous avez discuté de la possibilité de considérer ce champs supplémentaire comme un label plutôt qu'une catégorie ? J'ai l'impression que ça pourrait être plus générique et donc utilisable plus facilement pour le médico-social et/ou les cnfs

2022-04-05 10:10 UTC, victormours commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
J'ai un gros doute sur le fait de hardcoder ces catégories spécifiques au RSA et de les afficher à tout le monde. Il n'y a aucun cas où les cnfs ou les gens du médico-social vont ce servir de ces catégories (si j'ai bien compris), qui vont pourtant s'afficher. Ça ajoute du bruit dans une interface qui est déjà compliquée.

De manière générale, pour gérer nos trois domaines différents (médico-social, rsa, cnfs) je pense que c'est bien d'appliquer le principe "Un élément spécifique à un domaine ne doit pas apparaître pour les autres domaines". C'était l'idée derrière le fait de rendre les champs du médico-social facultatifs dans la fiche usager par exemple (voir https://github.com/betagouv/rdv-solidarites.fr/pull/2204).

Ici, ce système de catégories pourrait être utile pour tout le monde, mais il ne faut pas que les catégories d'un seul domaine soit appliquées à tout le monde.

2022-04-05 17:05 UTC, qblanc commented
Est-ce que c'est le nom qui te paraît poser problème @victormours ? (outre l'affichage sur la page new, qui peut se discuter) On avait hésité à appeler ça un `tag` sinon, mais `label` me paraît pas mal aussi

2022-04-05 17:14 UTC, qblanc commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
Pour le côté hardcodé, notre contrainte a nous, c'est de pouvoir récupérer ce label directement sur la table motif, pour pouvoir filtrer les motifs sur leur valeur. Mais si on veut éviter d'hardcoder les valeurs, on pourrait penser à une table `tags` qui `has_many` motifs, avec des champs `name` et `human_name`, par exemple, et un champ `tag_name` dans la table motif qui serait écrit automatiquement lorsque/si l'association change

Pour le côté "ne pas les montrer à tout le monde", il me semble que c'est déjà le cas des services : quand tu crées un motif, tu peux choisir "service social", "PMI", etc., donc il me paraît difficile de filtrer l'affichage par rapport à cette donnée. Mais on peut faire un select2 avec des labels/tags/catégories regroupées par sous-catégories pour faciliter la recherche/sélection. Et en précisant bien en hint que c'est un champ optionnel et non display à l'utilisateur.

2022-04-05 20:44 UTC, yaf commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
Nous avons discuté sur le sujet @victormours et l'idée, c'était d'avoir un truc le plus simple possible le temps d'explorer.

L'énum semble une bonne solution. L'idée, ce n'est clairement pas d'en ajouter tous les jours, et de faire en sorte que ce soit nous qui définissions les catégories.

Ça rejoint une discussion plus large que nous avions eu cet hiver avec @qblanc @aminedhobb @n-b et @rebeccadumazert à propos de la refonte de l'interface usager. Le plan étant de faire des groupements thématiques plutôt que d'utiliser le service.
C'est aussi lié à un échange que j'avais eu en septembre dernier avec les designers transverse lors d'une session de « docteur design ».

D'ailleurs, dans la gestion des droits d'accès, quand nous aurons fini, il n'y aura plus de lien d'un motif sur un service. La notion de service pourra « disparaitre » à terme.

Mon hypothèse, c'est que ces catégories seront alors un outil à notre main pour « ranger » les motifs.

Peut-être que nous aurons besoin de mettre ces catégories dans une table à un moment donnée, mais en attendant, c'est plus simple comme ça, et je crois que c'est plus efficace en perf aussi :)

2022-04-05 20:52 UTC, yaf commented
Lors de la discussion sur cette fonctionnalité, il y avait aussi eu peu de temps avant un échange avec les référentes où nous avions parlé de ne plus afficher les motifs dans les notifications. La catégorie me semblait être une piste intéressante pour malgré tout afficher une information
- plus fine que le service
- plus large et compréhensible (?) que le motif

Mais je n'avais pas de certitude.

J'ai donc proposé à @qblanc et @aminedhobb de l'afficher dans la configuration de motif, sans la rendre obligatoire. Eux pourront informer les agents qui configure des motifs RSA de les utiliser, et nous, nous pourrons questionner ou laisser venir les référentes pour savoir si ça les intéresse, les ennuis ou autres. Il sera alors temps de faire des modifications dessus.

Pour l'histoire des champs médico-sociaux optionnelle, ce n'est pas vraiment ça la raison, même si finalement, l'explication fonctionne aussi. C'est surtout que niveau RGPD il ne faudrait pas avoir ces champs. Mais les supprimer totalement sur l'ensemble des 250 000 fiche usager d'un coup, c'était un peu violent. On passe donc par cette étape pour permettre aux départements de préparer une transition en étape...

Ici, les catégories de motifs, je pense que c'est intéressant pour tout le monde. C'est un outil « d'éditorialisation » des motifs. C'était un truc qui avait été tenté avant en bloquant la création de libellé de motif. C'était l'équipe qui pouvait créer des libelles de motif, au moment de créer un motif, les agents pouvait taper dans la liste. Le hic, c'est que chaque département nous demandait un libellé presque pareil à l'autre, mais nous trouvaient toujours une bonne excuse pour avoir quand même le leur... Alors nous avons « libéré » les libellés de motif. Cette catégorie pourrait nous permettre de refaire des groupements...

Bref. Possible aussi que nous en discutions jeudi si besoin.

2022-04-06 12:52 UTC, victormours commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
L'énum n'est effectivement pas un problème en soit, le point gênant est surtout qu'on afficheraits des infos spécifique à un domaine aux autres domaines.
Une solution simple qui me conviendrait tout à fait serait de ne pas afficher ce champs aux conseillers numériques avec un simple `if !current_agent.conseiller_numerique?`.

On a un produit assez compliqué, que les conseillers numériques ont du mal à prendre en main, donc si on peut éviter de le compliquer encore plus avec des catégories du rsa, c'est mieux. :)

2022-04-06 12:52 UTC, victormours commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
Par ailleurs, il y a souvent un flou pour les agents sur quelles infos sont visibles par les utilisateurs, et quelles infos ne le sont pas, et parfois aussi sur ce à quoi servent certains champs. Comme on le fait pour les autres champs des motifs, peut-être que la catégorie pourrait être dans un encart séparé, avec un bref texte explicatif.

2022-04-06 13:00 UTC, victormours commented
> Est-ce que c'est le nom qui te paraît poser problème @victormours ? (outre l'affichage sur la page new, qui peut se discuter) On avait hésité à appeler ça un tag sinon, mais label me paraît pas mal aussi

Je me demandais si un nom plus générique que catégorie pouvait par la suite permettre plus d'usages différents, mais si vous en avez discuté et que vous êtes tombés d'accord sur catégories, ça me va complètement 👍

2022-04-06 20:27 UTC, yaf commented on app/models/motif.rb
> +                   rsa_orientation_phone_platform: "rsa_orientation_phone_platform" }
Tu as raison sur le point troublant d'afficher des trucs qui ne sont pas du domaine. Un filtre à partir du territoire semble légitime.

Je crois que les catégories pourrons remplacer les services, mais en attendant, les services sont là. Alors peut-être faut-il « masque » ce champ pour l'instant ? Ou effectivement, ajouter une couche de configuration au niveau du territoire...

Qu'est-ce qui vous parait le mieux pour vous @aminedhobb @qblanc  ?

Nous pourrions avoir une rapide discussion sur le sujet tous ensemble afin de nous accorder.

2022-04-07 14:52 UTC, yaf reviewed
En dehors d'une question sur la migration, ça me semble pas mal

2022-04-07 14:52 UTC, yaf commented on db/migrate/20220401150352_add_category_to_motifs.rb
> +    end
Est-ce bien nécessaire puisque c'est la valeur par défaut ?

2022-04-07 14:54 UTC, qblanc commented on db/migrate/20220401150352_add_category_to_motifs.rb
> +    end
Il me semble que postgress ne fait pas cette opération tout seul si on ne lui dit pas, si on ne met pas ça la valeur resterait à `nil` pour les territoires existants (ce qui ne serait pas très gênant mais c'est plus propre comme ça je trouve)

2022-04-07 14:54 UTC, yaf commented
Je ne sais pas à quoi c'est due, mais j'ai une erreur 500 quand je veux aller configurer les motifs sur la review app.

2022-04-07 14:56 UTC, qblanc commented
>> Je ne sais pas à quoi c'est due, mais j'ai une erreur 500 quand je veux aller configurer les motifs sur la review app.

Je suis en train de fix les tests mais a priori ça ne devrait pas poser de souci à ce niveau là. Je vais essayer de comprendre pourquoi, merci pour le retour.

2022-04-07 15:19 UTC, yaf commented on db/migrate/20220401150352_add_category_to_motifs.rb
> +    end
Je viens de faire un test et la valeur retournée est bien `false` 

Et 

```
lapin_development=# select field_with_default_value from "territories";
 field_with_default_value 
--------------------------
 f
 f
 f
(3 lignes)
```

Tu peux donc supprimer ce bout de boucle d'initialisation :)

2022-04-08 15:03 UTC, yaf commented
Ça me semble très bien. @victormours tu peux faire une petite revue pour faire avancer cette PR ?

2022-04-11 17:03 UTC, aminedhobb approved these changes
ça m'a l'air ok 👍

2022-04-11 17:03 UTC, aminedhobb commented on app/models/motif.rb
> +  enum category: { rsa_orientation: "rsa_orientation",
On pourrait peut-être ajouter un commentaire pour dire que c'est amené à être étoffé

2022-04-11 20:58 UTC, yaf approved these changes

2022-04-12 11:12 UTC, merged