Permettre aux super admin de migrer un agent d'une organisation à une autre
betagouv/rdv-solidarites.fr pull request #2502
Opened 2022-05-23 16:02 UTC by victormours

Suite aux invitations des CNFS, on a souvent eu besoin de migrer des agents d'une organisation à l'autre, en réutilisant ce vieux script (quitte à parfois éditer le script dans un container scalingo avant de le lancer 🙈 ).
Pour mieux outiller l'équipe support, cette PR ajoute cette fonctionnalité dans le super admin. Voilà à quoi ça ressemble :

<img width="1548" alt="Capture d’écran 2022-05-23 à 17 40 18" src="https://user-images.githubusercontent.com/1840367/169860341-ed833d12-326c-4558-b3c0-5bbada8c83b5.png">

<img width="1314" alt="Capture d’écran 2022-05-23 à 17 40 35" src="https://user-images.githubusercontent.com/1840367/169860286-5ba69cfe-d2f8-4e42-9549-b426810bbb53.png">

J'ai laissé la PR en deux commits pour faciliter la relecture, mais je squasherai avant de merger.

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-05-23 16:04 UTC, victormours commented on app/controllers/super_admins/migrations_controller.rb
> +    def create
toute cette action est tirée du script qui est supprimé

2022-05-23 16:04 UTC, victormours commented on app/models/motifs_plage_ouverture.rb
> +end
On a besoin de donner un nom à cette table de jointure pour pouvoir la modifier.

2022-05-23 16:04 UTC, victormours commented on app/views/super_admins/migrations/new.html.slim
> +    = f.input :new_organisation_id, type: :number, label: "ID de la nouvelle organisation"
pour éviter de charger toute la base dans un select, on propose juste d'indiquer l'id ici. Ça me semblait acceptable comme interface pour l'équipe support.

2022-05-23 16:15 UTC, n-b commented on app/views/super_admins/migrations/new.html.slim
> +  p Tous les rdvs et usagers de l'agents seront déplacés dans la nouvelle organisation.
```suggestion
  p Tous les rdvs et usagers de l’agent seront déplacés dans la nouvelle organisation.
```

2022-05-23 16:18 UTC, yaf commented
Une chose m'échappe... 

C'est déjà possible d'inviter un agent dans une autre organisation. Pourquoi construire tout ça du coup ?

2022-05-24 07:30 UTC, victormours commented
> Une chose m'échappe...
> 
> C'est déjà possible d'inviter un agent dans une autre organisation. Pourquoi construire tout ça du coup ?

Cette fonctionnalité fait plus qu'inviter un agent dans une autre organisation : elle déplace les rdv, plages d'ouvertures, motifs et lieux utilisés par cet agent dans la nouvelle organisation.
On s'en sert beaucoup dans le cadre des conseillers numériques parce que certains conseillers ont été mis dans la même organisation, alors qu'en fait ils ne bossent pas ensemble (parfois par maladresse dans le script d'import, parfois parce que les données de l'espace coop ne sont pas bonnes). On veut donc pouvoir les séparer dans des organisations différentes sans qu'ils ne perdent leurs données.

2022-05-24 07:37 UTC, victormours commented on app/controllers/super_admins/migrations_controller.rb
> +    include SuperAdminConcern
Oh, oui c'était une erreur de ma part : j'avais pas fait attention au namespace, et je pensais que j'étais en train d'hériter de `::ApplicationController` (dans le namespace racine), alors qu'en fait c'est bien le super admin. Et finalement on a effectivement besoin d'hériter de `SuperAdmins::ApplicationController`, donc j'ai supprimé le concern. Merci d'avoir remarqué ça !

2022-05-25 12:21 UTC, yaf requested changes
Je serais rassuré s'il y avait quelque point de contrôle supplémentaire
- sur les organisations cible et source (pour qu'elles soient du même territoire)
- sur le comportement en cas de RDV avec plusieurs agents

2022-05-25 12:21 UTC, yaf commented on app/views/super_admins/migrations/new.html.slim
> +    = f.input :new_organisation_id, type: :number, label: "ID de la nouvelle organisation"
Ça pourrait aussi être les organisations d'un territoire... Il n'y a pas de raison de déplacer une personne d'une orga d'un territoire à une orga d'un autre territoire.

Et les id, ça me va aussi. En espérant qu'il n'y ait pas de boulette... (un petit contrôle serait peut-être nécessaire ?)

2022-05-27 12:09 UTC, victormours commented on app/views/super_admins/migrations/new.html.slim
> +    = f.input :new_organisation_id, type: :number, label: "ID de la nouvelle organisation"
Pour les cnfs, on a 2183 organisations dans leur territoire, donc même si on ne scope pas comme, ça fait quand même beaucoup de monde.

2022-05-27 12:11 UTC, victormours commented on spec/features/super_admin/migrating_an_agent_spec.rb
> +describe "Migrating an agent from one organisation to another" do
Le cas ne s'était pas encore présenté, vu que généralement on sépare des gens qui ne bossent pas ensemble, mais c'est effectivement une bonne idée de le prévoir. Le plus simple serait sans doute de lever une erreur, et de rollback la transaction. Je vais ajouter ça

2022-05-27 12:11 UTC, victormours commented on app/views/super_admins/migrations/new.html.slim
> +    = f.input :new_organisation_id, type: :number, label: "ID de la nouvelle organisation"
mais c'est quand même bien d'ajouter cette vérification. Je vais faire ça

2022-05-27 12:28 UTC, yaf commented on spec/features/super_admin/migrating_an_agent_spec.rb
> +describe "Migrating an agent from one organisation to another" do
Oui, ça me semble clairement suffisant pour le moment. C'est un cas (rdv en binôme), à priori assez rare, qui s'additionne à un autre cas (agent qui n'est pas dans la bonne organisation) à priori assez rare aussi (et qui nécessite d'envisager aussi que ces deux agents qui sont sur le même RDV ne devrait en fait pas être dans la même organisation). :).

Une erreur sera parfaite :)

2022-05-27 12:54 UTC, victormours commented
> Je serais rassuré s'il y avait quelque point de contrôle supplémentaire
> - sur les organisations cible et source (pour qu'elles soient du même territoire)
> - sur le comportement en cas de RDV avec plusieurs agents

C'est ajouté dans le dernier commit :)

2022-05-30 07:23 UTC, yaf approved these changes
Merci !

2022-05-30 08:06 UTC, merged