Bloque le changement depuis un status annulé
betagouv/rdv-solidarites.fr pull request #2613
Opened 2022-06-28 21:54 UTC by yaf

Lorsqu'un RDV a été annulé, l'usager a reçu une notification. Plutôt que de gérer des tournures étranges et des cas bizarres en laissant la possibilité de « re-ouvrir » un RDV annulé, nous préférons bloquer le changement de statut à partir du statut annulé.

C'est un statut final d'un RDV.

J'ai opté pour mettre une validation ET faire en sorte que l'option ne soit pas possible dans l'écran.

Si la validation est déclenchée depuis le `rdvs_controller`, la redirection nous amène au formulaire de modification d'un RDV, alors que le changement de statut se faire depuis la visualisation d'un RDV...

Prendre en compte d'où viens l'appel et comment afficher l'erreur (liste des RDV, affichage d'un RDV, ...) ne semble pas trivial, et c'est un cas qui ne devrait pas se produire. Je préfère donc faire l'impasse. Ce n'est peut-être pas si grave, au pire, si on se retrouve sur le formulaire du RDV.

![Screenshot 2022-06-28 at 23-54-24 Votre agendaRDV Joséphine DUROY 🏠 - RDV Solidarités](https://user-images.githubusercontent.com/42057/176306904-84786064-bd26-4dd6-a82b-e5f428560dc2.png)
![Screenshot 2022-06-28 at 23-54-15 Votre agendaRDV Joséphine DUROY 🏠 - RDV Solidarités](https://user-images.githubusercontent.com/42057/176306907-7ad9b176-eb2f-4f6e-9fe5-0bb7436ebca8.png)
![Screenshot 2022-06-28 at 23-54-03 Liste des RDV - RDV Solidarités](https://user-images.githubusercontent.com/42057/176306908-5d4fbac7-4e4e-4f0e-a16d-25303fa76f2b.png)
![Screenshot 2022-06-28 at 23-53-54 Liste des RDV - RDV Solidarités](https://user-images.githubusercontent.com/42057/176306911-50d16f7b-df1c-474e-a4a2-8549f742e39e.png)

Closes #2538

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-07-07 08:38 UTC, victormours requested changes
On est en train d'enlever une fonctionnalité existante et utilisée, et il faut vraiment avoir une bonne raison de faire ça. Il y aurait une autre solution possible : https://github.com/betagouv/rdv-solidarites.fr/issues/2538#issuecomment-1177256097

2022-07-11 17:31 UTC, yaf commented on app/services/rdv_updater.rb
> +    def update_and_notify!(author, rdv, previous_participant_ids)
Oui, clairement.

2022-07-11 17:33 UTC, yaf commented on app/services/rdv_updater.rb
> +        rdv_users_tokens_by_user_id = update_and_notify!(author, rdv, previous_participant_ids)
Ah si, effectivement. Il y a eu des hésitations dans le refactoring... Et un oubli de retour sur le nom ! Merci

2022-07-12 14:27 UTC, francois-ferrandis approved these changes
Bonne initiative cette division en petites méthodes !

J'ai deux suggestions, à prendre ou à laisser car je ne veux pas bloquer la PR pour des préférences peut-être subjectives. :wink:

2022-07-12 14:27 UTC, francois-ferrandis commented on spec/services/rdv_updater_spec.rb
> +  end
Après relecture, je me demande pourquoi faire un test de cette méthode "privée" (et donc tester l'implémentation), plutôt que de faire un test du comportement du service (tester la boite noire). Question de performances ?

On pourrait imaginer un segment comme ça, qui pourrait remplacer aussi le test que tu as ajouté ligne 120 : 

```ruby

describe 'resetting the RDV (setting the status to "unknown")' do
  Rdv::CANCELLED_STATUSES.each do |cancelled_status|
    it "calls Notifiers::RdvCreated when rdv status from #{cancelled_status} to unknown" do
      rdv = create(:rdv, status: cancelled_status)
      author = rdv.agents.first
      expect(Notifiers::RdvCreated).to receive(:perform_with).with(rdv, author)
      described_class.update(rdv.agents.first, rdv, { status: "unknown" })
    end
  end

  Rdv::NOT_CANCELLED_STATUSES.each do |not_cancelled_status|
    # From unknown to unknown permet de tester le cas où il n'y a pas de changement sur le status
    it "does not call Notifiers::RdvCreated when rdv status from #{not_cancelled_status} to unknown" do
      rdv = create(:rdv, status: not_cancelled_status)
      author = rdv.agents.first
      expect(Notifiers::RdvCreated).not_to receive(:perform_with)
      described_class.update(author, rdv, { status: "unknown" })
    end
  end
end
```

2022-07-12 14:33 UTC, yaf commented on app/services/rdv_updater.rb
> +    end
Merci, c'est une bonne idée !

2022-07-12 16:14 UTC, francois-ferrandis commented on spec/services/rdv_updater_spec.rb
> +  end
C'est toujours l'équilibre entre le test très unitaire qui vérifie un logique en isolation et les tests plus larges qui vont aussi vérifier le câblage. Les seconds sont plus fragiles mais évitent davantage de régressions. Imaginons par exemple que le `RdvUpdater` soit modifié à l'avenir, et que la méthode `#rdv_status_reloaded_from_cancelled?` ne soit plus utilisée. Le test passera toujours alors qu'il ne vérifiera rien d'utile.

Ceci étant dit, je réalise que ton premier test (ligne 120) vérifier bien le câblage, et que cette seconde section vérifier les variantes de cas métier. On est donc bien dans l'approche conseillée : 1 test "d'intégration" + plusieurs tests unitaires pour les variantes. Donc ça me va bien comme ça. :hand_over_mouth: :pray:

2022-07-15 08:01 UTC, merged