Ajout de statistique d'activation des agents
betagouv/rdv-solidarites.fr pull request #2620
Opened 2022-07-01 16:46 UTC by victormours

Cette PR ajoute de la visibilité sur les indicateurs utilisés par l'équipe CNFS pour mesurer l'adoption de RDV Solidarités par les agents

![Capture d’écran 2022-07-01 à 18 43 13](https://user-images.githubusercontent.com/1840367/176936457-4374e8c3-d095-4a58-ac2b-12f6890c83c6.png)

Pour faire un vrai graphe avec ces quatre pourcentages en stacked bar chart, ça commençait à faire du sql un peu compliqué, donc pour le moment on peut se contenter d'un indicateur qui nous donne les chiffres maintenant, et il y a 30 jours.

# Checklist

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-07-01 21:43 UTC, yaf requested changes
Pour les agents du médico-social, ces stats sont très bizarres. 

J'imagine que c'est hyper pertinent vis-à-vis du mode de déploiement pour les CNFS par contre.

Est-ce que ça ne serait pas mieux d'envisager cette partie uniquement sur les CNFS ? Ça sera sans doute plus parlant en plus... Enfin, il me semble.

Il y a aussi une PR en cours pour supprimer le cumul de fiche usager, d'agent et d'orga. A minima, ça serait cool de décaler ce bloc pour qu'il ne soit pas au milieu des graph qui vont disparaitre (ça sera plus simple sur le rebase ;-))

2022-07-01 21:43 UTC, yaf commented on app/helpers/stats_helper.rb
> +module StatsHelper
:+1:

2022-07-04 09:51 UTC, victormours commented
Ça marche, je vais mettre ça dans une page séparée dédiée aux cnfs, ça sera mieux

2022-07-04 09:57 UTC, yaf commented
Je crois que ça pourrait rester dans cette page, mais peut-être faut-il que nous fassions des « blocs ». Un général, un CNFS, un médico social (à venir peut-être ? :))

2022-07-04 10:07 UTC, victormours commented
> Je crois que ça pourrait rester dans cette page, mais peut-être faut-il que nous fassions des « blocs ». Un général, un CNFS, un médico social (à venir peut-être ? :))

De toutes façons cette page peut être filtrée par territoire, et ces stats sont dans une carte séparée. Du coup est-ce que la version avec juste le premier commit fonctionne ? Comme ça on évite du code spécifique 🤔 

Sinon j'ai fait le deuxième commit si on veut bouger ça dans une autre page, et l'avoir uniquement pour les CNFS. C'est peut-être mieux dans un premier temps, et ça permet de mettre ça en ligne sans perturber le médico-social.

2022-07-04 10:46 UTC, yaf commented
Ah oui, je comprend mieux ce que tu veux dire. Nous pourrions laisser ce cadre dans la page principal, et bien qu'il n'ai pas beaucoup d'intérêt sur la dimension « global » de RDV-Solidarités, ni sur le médico-social, ça ne perturbe pas non plus. Et ça permet de laisser les stats sur la même page. Pour les CNFS (pour qui c'est intéressant), une sélection du territoire CN fera le job.

Ok, le premier commit suffit sans doute. Désolé pour les aller/retour.

2022-07-04 12:15 UTC, victormours commented
Ça marche, je suis revenu au premier commit (et j'en ai profité pour faire un rebase pour éviter les conflits)

2022-07-05 07:31 UTC, merged