1762 message erreur merge franceconnect
betagouv/rdv-solidarites.fr pull request #2702
Opened 2022-08-04 16:02 UTC by NFontelle

Closes #1762

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-08-08 14:00 UTC, francois-ferrandis requested changes

2022-08-08 14:00 UTC, francois-ferrandis commented on app/form_models/merge_users_form.rb
> +  def dont_destroy_franceconnected_values
On se retrouve ici à réimplémenter la validation qui est déjà faite plus bas dans `User::FranceconnectFrozenFieldsConcern` : 

https://github.com/betagouv/rdv-solidarites.fr/blob/7ed1d92f0ad776db3541dcba8dda369abc9da846/app/models/concerns/user/franceconnect_frozen_fields_concern.rb#L14

J'ai cherché un moyen de faire remonter les erreurs de validation de `User` au niveau de `MergeUsersForm`, mais notre architecture de classes actuelle ne permet pas de faire ça facilement (à ce que je vois), donc j'ai pas de meilleure solution que la tienne ! :hand_over_mouth: 

J'ai l'impression que le `MergeUsersForm` et `MergeUsersService` pourraient fusionner pour simplifier les choses. :thinking:

2022-08-08 14:00 UTC, francois-ferrandis commented on app/form_models/merge_users_form.rb
> +  include BenignErrors
Cet import me semble inutile puisque l'on utilise aucune des méthodes qu'il inclue, il me semble !

2022-08-08 14:15 UTC, NFontelle commented on app/form_models/merge_users_form.rb
> +  include BenignErrors
J'ai justement du le rajouter, son absence provoquait une erreur.

2022-08-08 14:15 UTC, NFontelle commented on app/form_models/merge_users_form.rb
> +        errors.add(frozen_field, "ne peut être modifier car un des usagers utilise FranceConnect")
Bien vu ! Merci :)

2022-08-08 14:17 UTC, NFontelle commented on app/form_models/merge_users_form.rb
> +  def dont_destroy_franceconnected_values
on peut y regarder oui :)

2022-08-08 16:31 UTC, francois-ferrandis commented on app/form_models/merge_users_form.rb
> +  include BenignErrors
Ça me semble bizarre, saurais-tu me dire quelle erreur ? :slightly_smiling_face:

2022-08-09 08:25 UTC, NFontelle commented on app/form_models/merge_users_form.rb
> +  include BenignErrors
![image](https://user-images.githubusercontent.com/60173782/183601406-676174b3-0930-4dc9-a93e-0f96a800897e.png)

2022-08-09 14:03 UTC, francois-ferrandis commented on app/form_models/merge_users_form.rb
> +  include BenignErrors
Ah oui en effet, c'est la méthode `errors_full_messages` qui ne fonctionne qu'avec des formulaires qui incluent `BenignErrors` ! On peut en discuter rapido voir si il y a une façon de faire ça plus maintenable. :wink:

2022-08-10 09:42 UTC, francois-ferrandis approved these changes
C'est bon pour moi (vu ensemble en pairing). :wink:

2022-08-10 13:11 UTC, merged