Motif: Affichage conditionné pour les prises de RDV en ligne
betagouv/rdv-solidarites.fr pull request #2848
Opened 2022-09-26 14:13 UTC by DanteZ5

Closes #issue_number

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-09-27 09:47 UTC, sebastiencarceles commented
Je trouve ça intéressant quand tu dis qu'on pourrait laisser les champs visibles à l'utilisateur·rice, même quand le motif n'est pas réservable en ligne, à la manière du bloc "RDV Secrétariat".

Pour l'édition, on pourrait, lorsque la case "Réservable en ligne" est **dé**cochée, afficher le reste de la card en `translucent` : 

![image](https://user-images.githubusercontent.com/1193334/192493407-2811cda6-51ab-47aa-a2df-9c11e62dd469.png)

Pour le show, je trouve ça très bien de ne rien montrer du tout quand le motif n'est pas réservable en ligne.

2022-09-27 09:56 UTC, DanteZ5 commented
@sebastiencarceles 

> Pour l'édition, on pourrait, lorsque la case "Réservable en ligne" est décochée, afficher le reste de la card en translucent :

Yes c'était ma première option, j'ai une préférence pour une approche plus lean des forms et je suis partie d'une logique : si c'est un bloc, il est translucent. Si c'est champs dans le bloc, ils sont hidden. Mais je laisse qui voudra trancher ^^ @yaf peut etre ? ^^

2022-09-27 12:29 UTC, sebastiencarceles approved these changes
C'est tout bon pour moi ! 

J'ai quand même envie de faire quelques suggestions visuelles sur le `show`. Ce n'est pas obligatoire ni bloquant, j'ai plutôt envie d'avoir ton avis dessus.

![image](https://user-images.githubusercontent.com/1193334/192525375-cb30a0ca-58fa-4d9c-af3a-881ef763bd31.png)

# Réservable en ligne

Est-ce qu'on ne retirerait pas le hint ? Il occupe vraiment beaucoup d'espace pour une info facilement déductible je trouve.

![image](https://user-images.githubusercontent.com/1193334/192525554-a19ce8f3-a3b0-4356-9229-7dc41d0c8741.png)

# Délai minimum

On pourrait enlever l'explication en `text-muted` ("Les premiers créneaux proposés aux usagers ne commenceront pas avant ce délai minimum") et la mettre en tooltip d'un petit picto info : 

![image](https://user-images.githubusercontent.com/1193334/192525956-ea06dba0-ff3f-4ea4-b877-a4e9ec34fb44.png)

# Délai maximum

Pareil, on pourrait utiliser un picto info pour affichher le détail.

# RDVs modifiables

Comme pour Réservable en ligne, est-ce qu'on a vraiment besoin de ce hint ?

Alternativement, est-ce qu'on pourrait avoir ces hints en version courte ? Par exemple : "Changement par l'usager max 2 jours avant le RDV", qui est une version courte de "L'horaire du RDV peut être changé par l'usager au plus tard 2 jours avant le début du RDV"

# Sectorisation au département 

Pareil, j'enlèverais le hint, au profit d'un petit picto info pour avec ces détails si besoin.

Qu'en dis-tu ? Est-ce qu'on peut parvenir à une version light du `show` ?

2022-09-27 21:18 UTC, yaf approved these changes
:+1: 

Merci !

À noter que la vidéo ne fonctionne pas sous Firefox (format plutôt chrome ?).

J'ai quelques remarques non bloquantes, aussi, j'approuve la PR, et je te laisse voir.

Je ne sais pas si c'est pertinent de garder la sectorisation en grisé, autant la masque complétement comme pour le reste de la réservation en ligne ? 

Pour la visualisation, je suis plutôt ok avec @sebastiencarceles et je me demande même si nous ne pourrions pas aller un cran plus loin : pourquoi avoir des labels ?
En fait d'avoir des labels et des hints, nous pourrions avoir des phrases courtes et explicite du genre

« ce motif n'est pas ouvert à la réservation publique » (ou « l'usager ne peut pas prendre RDV pour ce motif ») ou encore les phrases de hint existante, mais uniquement elles (ex : « Le RDV aura lieu au lieu sélectionné (MDS...) » pour un motif de type « public_office »)...

2022-09-29 06:49 UTC, DanteZ5 commented
Merci infiniment @sebastiencarceles @yaf pour le temps passé et ce niveau de détail.
Je vous fais une proposition ASAP via cette PR en tenant compte de vos remarques.
J'ai juste une réserve sur :
> En fait d'avoir des labels et des hints, nous pourrions avoir des phrases courtes et explicite du genre

ma réserve est liée à l'harmonisation globale de la structure des shows du projet. J'ai peur qu'intégrer des spécificités d'UI/UX pour chaque parcours utilisateur entraîne un risque d'adoption par les utilisateurs. Un chantier global mené par un UI/UX designer de refonte front me paraît pertinente et justifierait techniquement de faire évoluer la stack JS (avec du Hotwire par exemple).

Dans tous les cas, je vous propose une évolution de l'existant ^^

2022-09-29 07:27 UTC, sebastiencarceles commented
> J'en profite, est ce que le format vidéo vous convient ou vous préférez de loin l'écrit + screenshots ?

Petite préférence pour l'écrit et les screenshots de mon côté, mais pas c'est pas bloquant.

2022-09-29 12:04 UTC, DanteZ5 commented
Dîtes moi si cette approche par tooltip vous convient mieux : https://demo-rdv-solidarites-pr2848.osc-secnum-fr1.scalingo.io/admin/organisations/1/motifs/8

@yaf : j'ai appliqué le masquage pour la sectorisation plutôt que le grisé
s'il y a des correctifs sur l'évolution, feel free. Si vous préfériez avant, beh, je revert sans amertume ^^

![Capture d’écran 2022-09-29 à 13 52 00](https://user-images.githubusercontent.com/11738628/193026366-bf216073-c810-4e15-b32a-72c4b61db73d.png)

cc @sebastiencarceles

2022-09-29 12:36 UTC, sebastiencarceles approved these changes
J'ai une micro remarque, mais en ce qui me concerne c'est nickel !

2022-09-29 12:36 UTC, sebastiencarceles commented on app/helpers/motifs_helper.rb
> +      tag.i class: "fa fa-fw fa-circle-info"
Je mettrais volontiers un petit `ml-1` pour éloigner un poil le picto du texte, qu'en penses-tu ?

2022-09-29 12:50 UTC, DanteZ5 commented on app/helpers/motifs_helper.rb
> +      tag.i class: "fa fa-fw fa-circle-info"
ouep, on peut gratter encore un peu le fa-fw fait le début du taff, mais je suis bien d'accord

2022-09-29 15:47 UTC, yaf commented
> * j'ai appliqué le masquage pour la sectorisation plutôt que le grisé
> * j'aimais pas trop les checkbox, j'ai remplacé par des "Oui"

C'est parti là, ça me va.

Par contre, je ne suis pas fan du picto `info`. Si on cherche à rester dans ce qui se pratique aujourd'hui dans l'application (en attendant de voir l'orientation « globale » que l'ont choisi) je préfèrerais que l'on garde les `hint`. Il y en a partout et apporte souvent la clarté nécessaire aux personnes moins à l'aise avec le numérique (sans doute pas loin de 80 % des personnes utilisant RDV-Solidarités dans le médico-social). 

Je sais que vous vouliez faire plus « condensé » mais ça me semble délicat. C'est aussi pour ça que j'envisageais que seuls les hint reste finalement... Mais c'est peut-être moins clair.

En tout cas, les picto `info` c'est nouveau dans le service (il me semble ?) aussi, ça ne va pas être très simple à expliquer et justifier :-/

2022-09-29 15:48 UTC, yaf requested changes
(je fais un `request changes` pour bloquer la PR dans son état actuel, avec les picto `info`)

2022-09-29 19:16 UTC, yaf commented
Et je crois que je préfère aussi avoir du texte. La vidéo, c'est pratique pour illustrer un court enchainement, mais là, ça fait beaucoup :sweat_smile:

2022-09-30 08:16 UTC, DanteZ5 commented
J'ai mis à jour la PR avec tes remarques @yaf 
j'ai modifié la PR description avec des captures d'écrans / texte plutôt que vidéo
je conserve le commit avec les bulles infos (revert), mais si tu préfères que je les efface, tu me dis
bonne journée

2022-09-30 09:07 UTC, sebastiencarceles approved these changes
OK c'est toujours bon pour moi, on y a largement gagné en lisibilité à mon avis !

2022-09-30 09:49 UTC, yaf approved these changes
:+1: Très bien pour moi. Merci !

2022-09-30 16:32 UTC, merged

2022-09-30 16:43 UTC, yaf commented
C'est un peu le piège... Il manque la « validation »  d'au moins une personne de l'équipe support (@NesserineZarouri ou Myriam) avant de mettre en prod... Nous utilisons plutôt le tableau https://github.com/betagouv/rdv-solidarites.fr/projects/8?fullscreen=true pour savoir ce qui est ok pour la prod.

Je ne sais pas comment nous pourrions faire « vivre » ce workflow dans github :thinking: