Gestion d'un warning lorsqu'un motif dépasse la durée d'une plage d'ouverture
betagouv/rdv-solidarites.fr pull request #2857
Opened 2022-09-27 15:45 UTC by DanteZ5

Closes #2565 

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-09-30 07:46 UTC, yaf requested changes
Merci pour cette PR, c'est cool.

J'avoue me poser la question, maintenant que je le vois, sur le fait d'avoir un warning plutôt qu'un blocage. Car finalement, ça signifie qu'il ne pourra pas y avoir de RDV pris sur ce motif sur cette plage d'ouverture. C'est donc « grave ». Qu'en penses-tu ?

J'ajouterais deux éléments (et c'est tout cela qui me font opter pour un statut `demande de changement`) 

- Mon anglais est approximatif, mais il me semble qu'il y a des noms de méthodes qui ne sont pas super claires et expressives :thinking: :gb: 
- Je trouve que la méthode ` pretty_duration` dans le helper est un peu trop complexe. J'imagine que nous pourrions utiliser le nombre de minutes qui dépasse (ça sera sans doute entre 10 et 30, guère plus en général).

Fais-moi signe si tu préfères que nous travaillions ensemble un peu sur ces points, ça me fera plaisir et ça sera peut-être plus efficace :)

2022-09-30 12:43 UTC, DanteZ5 commented
- méthodes renommées
- display de la show modifié avec notion de durée qui déborde

2022-10-03 19:36 UTC, yaf approved these changes
En dehors d'une petite suggestion de changement de libellé, ça me semble très bien ! 

Merci ! :bow: :rocket:

2022-10-03 19:36 UTC, yaf commented on app/views/admin/plage_ouvertures/_motifs_duration_exceed.html.slim
> +    span> déborde de #{overflow_motif_duration(model, motif)} minutes. Il ne sera pas possible de prendre rendez-vous pour ce motif en l'état.
:ok_hand:

2022-10-03 19:36 UTC, yaf commented on app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
> +      .alert.alert-warning.py-1.px-2.mt-1 ⚠️ Certains motifs sont trop longs
Peut-être une confusion possible entre la longueur d'un titre et la durée ?
```suggestion
      .alert.alert-warning.py-1.px-2.mt-1 ⚠️ Certains motifs dépasse la durée de la plage
```

2022-10-04 14:15 UTC, merged