Permettre la prise de rdv via un lien public vers le service
betagouv/rdv-solidarites.fr pull request #2859
Opened 2022-09-28 08:33 UTC by sebastiencarceles

Closes #2856 

On ajoute une URL courte `/ser/:territory_slug/:service_id`, afin de permettre aux agent·es (notamment du médico-social) de partager un lien public de réservation auprès d'un service.

![image](https://user-images.githubusercontent.com/1193334/192729775-de055395-64b4-4d05-836e-7c7628491c0e.png)

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-09-29 15:41 UTC, yaf requested changes
Ça me semble très bien.

J'ai fait une suggestion sur le fait d'utiliser `territory_id` plutôt que `service_id` pour faire un bypass sur la saisie de l'adresse, mais ce n'est peut-être pas pertinent :shrug:. Comme évoqué dans le commentaire, tant que les services sont nationaux et non scopé au territoire, il ne permette par de déterminer un département ou une zone géographique restreinte... 

Je préfère marquer la PR comme « request changes » pour m'assurer que l'on en parle. Mais globalement ça me parait ok.

2022-09-29 15:41 UTC, yaf commented on app/services/search_context.rb
> +    if address.blank? && @organisation_id.blank? && @service_id.blank?
C'est peut-être plutôt le territoire qui est la clef (tant que nous n'avons pas « scopé » les services sur les territoires).
```suggestion
    if address.blank? && @organisation_id.blank? && @territory_id.blank?
```

Ou un truc dans le genre. L'adresse ou l'organisation servant finalement à définir un territoire (voir une zone géographique plus petite que le territoire via l'organisation ou la sectorisation)

2022-09-29 18:29 UTC, francois-ferrandis commented on app/services/search_context.rb
> +    if address.blank? && @organisation_id.blank? && @service_id.blank?
Je me suis fait la même réflexion en lisant cette ligne !

2022-10-03 17:12 UTC, francois-ferrandis approved these changes
> Closes https://github.com/betagouv/rdv-solidarites.fr/issues/2856

J'ai l'impression qu'il y a erreur sur le ticket.

Sinon côté implémentation tout me paraît bon !

Je me posais juste la question : est-ce que le médico-social a bien besoin d'un lien qui permet de prendre RDV dans tout le département ?

2022-10-04 06:10 UTC, sebastiencarceles commented
Merci pour les reviews :pray: 

Je suspens le sujet le temps d'avoir avec @yaf un point sur la prise de RDV par invitation dans le médico-social.

2022-10-10 09:21 UTC, sebastiencarceles commented
Suite à discussions, il apparaît que le besoin est mal formulé dans #2855. Donc cette PR ne sert à rien.

Le médico-social bénéficierait plutôt d'un mécanisme d'invitations. C'est synthétisé ici : https://github.com/betagouv/rdv-solidarites.fr/issues/1972

2022-10-10 09:21 UTC, closed without merging