Permettre la création de plages douverture sans lieu
betagouv/rdv-solidarites.fr pull request #2860
Opened 2022-09-28 10:05 UTC by sebastiencarceles

Closes #2770

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-11 11:57 UTC, victormours commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
Est-ce qu'il y a vraiment besoin d'un lieu pour les motifs qui sont à domicile ? J'ai l'impression que c'est juste les rdv sur place qui nécessitent un lieu (mais peut-être qu'il me manque du contexte métier et que les rdv à domicile sont quand même associés au lieu de départ de l'agent)

2022-10-11 11:57 UTC, victormours commented on app/services/slot_builder.rb
> +      end
peut-être qu'on peut simplifier ces cinq lignes en mettant juste un `scope.where(lieu: lieu)`

2022-10-11 11:57 UTC, victormours commented on app/views/admin/agents/plage_ouvertures/index.json.jbuilder
> +    json.lieu plage_ouverture.lieu&.name&.presence || "N/A"
`N/A` c'est l'abbréviation de `Not Applicable`, qu'on a dans certains champs vide parce que c'est ce que propose par défaut papertrail (je crois), mais est-ce que ça vaut vraiment le coup de se mettre à avoir ça ailleurs ? Dans le cadre d'une api j'ai l'impression qu'un `null` aurait plus de sens, non ?

2022-10-11 11:57 UTC, victormours commented on app/views/admin/plage_ouvertures/_form.html.slim
> +      = f.association :lieu, collection: policy_scope(Lieu).enabled.ordered_by_name, label_method: :full_name, include_blank: true
👍

2022-10-11 11:57 UTC, victormours commented on app/helpers/lieux_helper.rb
> +      content_tag(:span, "N/A", class: "text-muted")
Plutôt que `N/A`, qui ne donne pas vraiment d'information, est-ce qu'on ne mettrait pas plutôt "Par téléphone" et/ou "A domicile" ? Ou juste pas d'élément du tout ?

2022-10-11 16:43 UTC, damienlethiec reviewed
C'est une grosse PR, j'avoue que j'ai eu du mal à être ultra attentif jusqu'au bout. Je vais peut être chercher l'énergie d'y revenir demain ! Quelques commentaires à la marge mais globalement ça me semble bien. Même si cela me semble très complexe mais je pense que c'est lié à l'historique du projet.

2022-10-11 16:43 UTC, damienlethiec commented on app/views/mailers/agents/plage_ouverture_mailer/_plage_ouverture_overview.html.slim
> +        = plage_ouverture.lieu.name
On ne voudrait pas faire des delegate sur ces attributes là ?

2022-10-11 16:43 UTC, damienlethiec commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +    @search_results_without_lieu = search_results_without_lieu
Proposition: pour les 3 variables au début de la methode index, faire des before actions et setter les variables d'instance dans les méthodes

2022-10-11 16:43 UTC, damienlethiec commented on app/views/admin/creneaux/agent_searches/index.html.slim
> +    - if @search_results_without_lieu&.creneaux&.any?
On ne pourrait pas réutiliser la méthode creneaux_without_lieu? en la sorte du controller ? Ou au pire en settant une variable d'instance de plus :/ Pas forcément d'idée d'où la mettre mais on répète ici quelque chose qu'on fait dans le controller.

2022-10-11 16:43 UTC, damienlethiec commented on app/controllers/users/rdvs_controller.rb
> +    lieu = @lieu.present? ? Lieu.find(@lieu.id) : nil
Je ne comprends vraiment pas l'intérêt de ces lignes ? pourquoi pas directement `lieu: @lieu` ligne 103?

2022-10-12 06:45 UTC, sebastiencarceles commented on app/services/slot_builder.rb
> +      end
Sure

2022-10-12 06:46 UTC, sebastiencarceles commented on app/helpers/lieux_helper.rb
> +      content_tag(:span, "N/A", class: "text-muted")
J'ai supprimé complètement, je trouve que c'est encore ce qui est le plus logique, et c'est clair du point de vue de l'agent·e il me semble : 

![image](https://user-images.githubusercontent.com/1193334/195269698-30407239-7457-43c2-939a-7ccd45da3940.png)

2022-10-12 07:30 UTC, sebastiencarceles commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +    @search_results_without_lieu = search_results_without_lieu
:heavy_check_mark:

2022-10-12 07:39 UTC, sebastiencarceles commented on app/views/admin/creneaux/agent_searches/index.html.slim
> +    - if @search_results_without_lieu&.creneaux&.any?
Mais si, tout à fait ! J'ai fais un `helper_method` dans le contrôleur : 

```rb
class Admin::Creneaux::AgentSearchesController < AgentAuthController
  respond_to :html, :js

  before_action :set_form
  before_action :set_search_results
  before_action :set_search_results_without_lieu

  helper_method :creneaux_without_lieu?
  
  # ...
```

Ce qui permet :

```slim
    - if creneaux_without_lieu?
      .container
        p.font-weight-bold= t(".available_slots_without_lieu")
        .card
          .card-body
            = render "/admin/slots/slots", \
              lieu: nil, \
              creneaux: @search_results_without_lieu.creneaux, \
              form: @form, \
              next_availability: @search_results_without_lieu.next_availability

    - if @form.motif.present? && !@search_results&.any? && !creneaux_without_lieu?
      = t(".no_slot_available", motif_name: @form.motif.name)
```

Et c'est autrement plus sympa :pray:

2022-10-12 07:47 UTC, sebastiencarceles commented on app/controllers/users/rdvs_controller.rb
> +    lieu = @lieu.present? ? Lieu.find(@lieu.id) : nil
Oui non c'est mystérieux ça, je vais le virer

2022-10-12 07:49 UTC, sebastiencarceles commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
Je ne sais pas répondre sur ce point. Je vais demander à l'équipe.

2022-10-12 08:05 UTC, yaf commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
Non, effectivement, nous n'avons pas besoin d'un lieu pour les RDV téléphoniques.

2022-10-12 08:12 UTC, sebastiencarceles commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
Tu voulais dire pour les RDV à domicile @yaf ? 

Je vais voir si c'est facile à intégrer dans le cadre de cette PR, mais comme elle est déjà grosse, je me permettrais peut être de reporter ça dans une autre PR si ça entraîne trop de modifications.

2022-10-12 08:20 UTC, yaf requested changes
Je n'ai pas encore parcouru le code, mais je bloque sur la conception de certains écrans, en particulier ceux où l'on affiche le choix d'un lieu ET des créneaux disponibles.

Je crois que je préférerai avoir un bloc similaire à un lieu qui évoque « RDV téléphonique » et un autre « RDV à domicile » s'il y a, avec la « prochaine disponibilité affichée.

J'ajouterais qu'en fait, pour le moment, un motif ne propose qu'une modalité, donc c'est soit au téléphone, auquel cas, nous pourrions arriver directement sur la page des créneaux (sans lieux donc) doit sur place et donc il faut afficher les lieux. Il y a peu de chance que les RDV à domicile soit proposé à la réservation en ligne.

Je suis mitigé parce qu'il y a des discussions avec référentes pour sortir ces paramétrages-là pour les placer dans la plage d'ouverture voir dans le RDV. Alors, dans le futur, une interface qui affiche lieu, tel et domicile est peut-être souhaitable.

Disponible pour en parle si ce n'est pas super clair.

Je vais prendre le temps prochainement pour regarder le code. Merci

2022-10-12 08:52 UTC, sebastiencarceles commented
> Je crois que je préférerai avoir un bloc similaire à un lieu qui évoque « RDV téléphonique » et un autre « RDV à domicile » s'il y a, avec la « prochaine disponibilité affichée.

Je vais faire une proposition en ce sens, pour voir si c'est plus agréable ou plus clair à l'usage.

> J'ajouterais qu'en fait, pour le moment, un motif ne propose qu'une modalité, donc c'est soit au téléphone, auquel cas, nous pourrions arriver directement sur la page des créneaux (sans lieux donc) doit sur place et donc il faut afficher les lieux. Il y a peu de chance que les RDV à domicile soit proposé à la réservation en ligne.

C'est vrai, néanmoins c'est possible pour un motif d'avoir des créneaux avec lieu, et d'autres sans lieu, même si c'est peu probable.
Ce qu'on peut faire, du coup, c'est aller directement sur la page des créneaux lorsqu'il n'y a pas de créneau avec lieu, n'est-ce pas ?

> Je suis mitigé parce qu'il y a des discussions avec référentes pour sortir ces paramétrages-là pour les placer dans la plage d'ouverture voir dans le RDV. Alors, dans le futur, une interface qui affiche lieu, tel et domicile est peut-être souhaitable.

Est-il possible d'avancer sur ces discussions _parallèlement_ à l'ouverture de plages sans lieu, tel que proposé dans cette PR ?

2022-10-12 10:06 UTC, sebastiencarceles commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
Je  n'ai pas rencontré de problème particulier pour rendre le lieu optionnel lorsque le motif est à domicile : https://github.com/betagouv/rdv-solidarites.fr/pull/2860/commits/9c24a38dc84b83ffe92f0468f652d425e19d055d

2022-10-12 10:45 UTC, yaf commented on app/models/plage_ouverture.rb
> +  validates :lieu, presence: true, unless: -> { phone_motifs_only? }
oui, pardon, c'est bien pour les RDV à Domicile que nous n'avons pas besoin d'adresse :)

2022-10-12 10:53 UTC, yaf commented
>  >   Je crois que je préférerai avoir un bloc similaire à un lieu qui évoque « RDV téléphonique » et un autre « RDV à domicile » s'il y a, avec la « prochaine disponibilité affichée.
> 
> Je vais faire une proposition en ce sens, pour voir si c'est plus agréable ou plus clair à l'usage.
> 
> EDIT : question pour toi @yaf : est-ce que tu parles du côté agent ou usager ? Ou les deux ?

Les deux.

Il y a aussi un vague élément de performance. Bien qu'aujourd'hui, le calcul du prochain créneau disponible effectué le calcul de plusieurs créneaux, une optimisation sur ce point est souhaitable. Si dans la page, on calcule des créneaux ET le (ou les) prochains créneaux disponibles, niveau perf, il y a peut-être un point de vigilance.

---

> > J'ajouterais qu'en fait, pour le moment, un motif ne propose qu'une modalité, donc c'est soit au téléphone, auquel cas, nous pourrions arriver directement sur la page des créneaux (sans lieux donc) doit sur place et donc il faut afficher les lieux. Il y a peu de chance que les RDV à domicile soit proposé à la réservation en ligne.
> 
> C'est vrai, néanmoins c'est possible pour un motif d'avoir des créneaux avec lieu, et d'autres sans lieu, même si c'est peu probable.
> Ce qu'on peut faire, du coup, c'est aller directement sur la page des créneaux lorsqu'il n'y a pas de créneau avec lieu, n'est-ce pas ?

Non, ce n'est pas possible pour un même motif aujourd'hui. On configure un motif comme soit à domicile, soit téléphonique, soit sur place. Impossible d'avoir plusieurs options sur le même motif. Par contre, on constate que le même nom de motif est utilisé plusieurs fois pour montrer que le motif peut être téléphonique, sur place ou à domicile. Mais c'est, aujourd'hui, techniquement 3 ID différent. Et donc, sur la page des lieux, le motif choisi l'est par rapport à un ID, donc aujourd'hui, c'est impossible d'avoir les deux.

---

> > Je suis mitigé parce qu'il y a des discussions avec référentes pour sortir ces paramétrages-là pour les placer dans la plage d'ouverture voir dans le RDV. Alors, dans le futur, une interface qui affiche lieu, tel et domicile est peut-être souhaitable.
>
> Est-il possible d'avancer sur ces discussions parallèlement à l'ouverture de plages sans lieu, tel que proposé dans cette PR ?

Bien sûr. :smiley:
D'où mon point précédent qui dit : aujourd'hui, ce n'est pas possible d'avoir les trois en même temps dans cette page, et donc oui, on pourrait sauter directement à la page des créneaux (sans bricoler la page des lieux qui du coup n'a pas de sens).

2022-10-13 14:09 UTC, sebastiencarceles commented
J'ai pris en compte tous vos retours. Je n'ai pas réécrit l'historique des commits, de sorte à faciliter la lecture des commits de review. Je peux cependant synthétiser, dites-moi ce que vous préférez.

Le changement le plus important concerne la recherche et la sélection des créneaux : aller directement sur la selection d'un créneau lorsqu'on est sur un motif qui ne nécessite pas de lieu (à domicile ou par téléphone), que l'on soit usager·ère ou agent·e.

# Côté usager·ère

![image](https://user-images.githubusercontent.com/1193334/195619310-7555be1c-d0a9-47f1-b72b-899c4fb2cc53.png)

# Côté agent·e

![image](https://user-images.githubusercontent.com/1193334/195619760-d4ddb917-5f43-42e1-9a95-f0c0c88498db.png)

2022-10-13 14:18 UTC, damienlethiec reviewed
J'avoue ne pas avoir testé en local ! Mais ça me parait pas mal

2022-10-14 19:05 UTC, yaf approved these changes
Merci.

J'ai testé sur la review app, c'est ok. J'ai fait quelques commentaires, mais c'est possible d'avancer comme ça et d'en reparler plus tard.

Le truc le plus « particulier » c'est l'histoire du bouton de retour aux filtres qui en fait un tour sur lui-même... C'est bizarre. Nous avions changé un truc pour faire en sorte que ça ne fasse pas ça, mais ce n'est pas hyper satisfaisant non plus. Le mieux est peut-être de supprimer le bouton :shrug:

Le reste, c'est de la suggestion.

Merci encore !

2022-10-14 19:05 UTC, yaf commented on app/services/slot_builder.rb
> +      scope
:+1: merci, c'est beaucoup plus lisible comme ça.

Peut-on extraire la condition sur les agents de la même manière ?

2022-10-17 13:25 UTC, sebastiencarceles commented on app/services/slot_builder.rb
> +      scope
Sure!

2022-10-17 13:29 UTC, sebastiencarceles commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +    p = helpers.creneaux_search_params(@form)
C'est possible, et c'est pas cher :+1:

2022-10-17 13:39 UTC, sebastiencarceles commented on app/form_models/user_rdv_wizard.rb
> +      creneau.lieu&.full_name
All done :)

2022-10-17 18:30 UTC, yaf commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +      redirect_to admin_organisation_slots_path(current_organisation, creneaux_search_params), class: "d-block stretched-link"
Je me demande s'il y a des personnes qui clic dessus :thinking: Difficile de savoir en l'état.

Je serais assez partant pour supprimer ce bouton parce que
- je pense que peu de personne l'utilise
- que ça ne coûte pas grand-chose de cliquer sur le bouton « trouver un RDV » en haut du menu, toujours visible (il n'y était pas avant, aussi le revenir au filtre permettait d'éviter un parcours de folie pour revenir en arrière).

J'imagine qu'il serait facile de remettre quelque chose si des utilisateurs expriment un manque.

2022-10-18 06:29 UTC, sebastiencarceles commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +      redirect_to admin_organisation_slots_path(current_organisation, creneaux_search_params), class: "d-block stretched-link"
Ça marche !

2022-10-19 09:22 UTC, sebastiencarceles commented
Validé avec Myriam et Nesserine, prêt à mettre en prod

2022-10-20 07:36 UTC, merged

2022-11-02 16:54 UTC, francois-ferrandis commented on app/services/search_creneaux_without_lieu_for_agents_service.rb
> +    OpenStruct.new(lieu: nil, next_availability: next_availability, creneaux: creneaux)
Je suis curieux de savoir ce qui a motivé la duplication plutôt que l'usage direct du code déjà présent dans [`SearchCreneauxForAgentsService`](https://github.com/betagouv/rdv-solidarites.fr/blob/8c0015379aaa2aac3aaac526f2d0cab3bc373720/app/services/search_creneaux_for_agents_service.rb#L8). :upside_down_face:

2024-08-16 18:33 UTC, victormours commented on app/services/search_creneaux_without_lieu_for_agents_service.rb
> +    OpenStruct.new(lieu: nil, next_availability: next_availability, creneaux: creneaux)
On ne le saura jamais, mais on peut s'en libérer : https://github.com/betagouv/rdv-service-public/pull/4560