Changement visuel de l'index des rdv (recherche)
betagouv/rdv-solidarites.fr pull request #2861
Opened 2022-09-28 10:32 UTC by Holist

Closes #2816

Merger la pr 2805 avant celle ci.

Modification de la vue index (desktop et mobile) des RDV en fonction du figma proposé par Anne Sophie (UX) et présenté le 6 septembre aux référentes. C'est également un prérequis pour une utilisation plus générale des rdv collectifs et la mise en place de la participation individuelle.

### Avant :

![Capture d’écran 2022-09-28 à 12 30 57](https://user-images.githubusercontent.com/28594222/192757089-7b2470ae-c4c9-4cf9-8a65-281a7fe1d306.png)
![Capture d’écran 2022-09-28 à 12 31 04](https://user-images.githubusercontent.com/28594222/192757106-0bc0c746-8ffa-498d-9033-704a32589166.png)
![Capture d’écran 2022-09-28 à 12 30 30](https://user-images.githubusercontent.com/28594222/192757140-6a1b5657-b6fe-406a-bbf2-6a6311a42187.png)

### Après :

![Capture d’écran 2022-09-28 à 12 16 55](https://user-images.githubusercontent.com/28594222/192756391-bb19ec12-4511-4def-8eef-367e71232c61.png)
![Capture d’écran 2022-09-28 à 12 17 07](https://user-images.githubusercontent.com/28594222/192756400-7f25d7b5-5487-4fb9-a2fe-716be623b6d4.png)
![Capture d’écran 2022-09-28 à 12 29 09](https://user-images.githubusercontent.com/28594222/192756739-196f38ec-de35-41c7-b65b-beb3e1032975.png)

2022-09-29 15:52 UTC, yaf commented on app/views/admin/rdvs/_rdv_search_form.html.slim
> +    / En terme d'UX je trouve ca étrange, obligé de faire une recherche pour pouvoir afficher le bouton de reinit du formulaire ?
J'imagine que c'est pour éviter de « surcharger » l'interface. Le lien ne sert à rien tant qu'aucun champs n'a été modifié. En écrivant cela, je me rends compte qu'un champ modifier n'est pas la même chose qu'une recherche déclenchée... :thinking:

2022-09-29 15:52 UTC, yaf commented on app/views/admin/rdvs/index.html.slim
> +      label.custom-control-label for="show-users-switch" Afficher la liste des participants
:ok_hand:

2022-09-29 16:00 UTC, yaf requested changes
:tada: 

C'est top. Merci.

Je fais une demande de changement : faire apparaitre la date de naissance de l'usager (du proche au moins, et pourquoi pas du responsable si ça ne prend pas trop de place). 

Suite à la suppression du détail dans cette liste, nous avons reçu 2 demandes (https://zammad10.ethibox.fr/#ticket/zoom/2740 et je ne retrouve pas l'autre) pour retrouver les informations manquantes. Ce qui remonte, c'est le numéro de tel (et ça, c'est pris en compte dans le nouveau design) et la date de naissance (manquante donc).

Voir le `fullNameConcern` https://github.com/betagouv/rdv-solidarites.fr/blob/21038926e09603c5b9de03ef0bd84a222d632edf/app/models/concerns/full_name_concern.rb#L3

Merci !

2022-09-29 17:55 UTC, Holist commented on app/views/admin/users/_identity.html.slim
> -  - user_displayed_name = user.last_name == user.responsible.last_name ? user.first_name : user.full_name
Ligne inutile, la variable n'est pas utilisée

2022-09-29 18:02 UTC, Holist commented
Merci la review :) 
Au sujet du ticket Zammad, je viens d'ajouter la date de naissance de l'usager (pas du responsable) uniquement à l'impression puisque c'est ce qui est demandé car je trouve que ça surcharge le tableau quand il y a beaucoup d'usagers à l'écran. C'est ok pour le champ remarque (qui s'affiche tout le temps)
A l'affichage si les agents veulent plus d'infos (date de naissance...) sur l'usager il suffit de cliquer dessus.
Est ce contraignant pour les agents d'avoir une différence entre l'impression et l'écran ?
J'ai vu le fonctionnement avec le `FullNameConcern` mais qui traite les noms uniquement et pas les dates, il y a bien le le `UsersHelper` qui traite un peu tout concernant le user y compris les dates mais est ce utile de créer une méthode dans ce cas précis ? (surtout qu'il s'agit que d'une traduction de user.birth_date au final)

2022-09-29 19:19 UTC, yaf commented
> Au sujet du ticket Zammad, je viens d'ajouter la date de naissance de l'usager (pas du responsable) uniquement à l'impression puisque c'est ce qui est demandé car je trouve que ça surcharge le tableau quand il y a beaucoup d'usagers à l'écran. C'est ok pour le champ remarque (qui s'affiche tout le temps)

À choisir, la date de naissance prend potentiellement moins de place que les remarques :sweat_smile: mais je comprends.

Je ne pense pas que ça pose un problème en soit, mais ça créer une forme d'incohérence. Est-ce qu'en le plaçant en deuxième ligne (ou troisième ?) comme les remarques, ça ne permet pas d'avoir un truc acceptable ?

2022-09-29 20:32 UTC, Holist commented
> > Au sujet du ticket Zammad, je viens d'ajouter la date de naissance de l'usager (pas du responsable) uniquement à l'impression puisque c'est ce qui est demandé car je trouve que ça surcharge le tableau quand il y a beaucoup d'usagers à l'écran. C'est ok pour le champ remarque (qui s'affiche tout le temps)
> 
> À choisir, la date de naissance prend potentiellement moins de place que les remarques 😅 mais je comprends.
> 
> Je ne pense pas que ça pose un problème en soit, mais ça créer une forme d'incohérence. Est-ce qu'en le plaçant en deuxième ligne (ou troisième ?) comme les remarques, ça ne permet pas d'avoir un truc acceptable ?

Tu as raison pour l'incohérence, ça m'a traversé l'esprit aussi. Je regarderai demain pour faire quelque chose d'un peu plus compact et que ça s'affiche à l'écran et à l'impression.

2022-09-30 08:43 UTC, Holist commented
On affiche la date de naissance et la remarque tout le temps. J'ai un peu diminué la font.
![Capture d’écran 2022-09-30 à 10 42 11](https://user-images.githubusercontent.com/28594222/193230315-7218f78a-77f5-440c-b047-c59838fd6c22.png)

2022-09-30 12:09 UTC, yaf approved these changes
Super ! Merci beaucoup.

:rocket:

2022-10-04 13:39 UTC, merged