Téléchargement des rdvs par usager sur plusieurs organisations
betagouv/rdv-solidarites.fr pull request #2900
Opened 2022-10-06 14:23 UTC by DanteZ5

Closes #2008 

# Synthèse
- En tant qu'admin d'un territoire, je peux donner droit à un agent de télécharger toutes les données dans un nouveau format de rdvs par usager sur l'ensemble des organisations auxquelles il accède
- En tant qu'agent ayant droit de télécharger toutes les données de rdvs par usager, j'accède à cette action depuis l'interface de la liste des RDV

# Test en démo
@NesserineZarouri @MYRIAMKEDDAD : https://demo-rdv-solidarites-pr2900.osc-secnum-fr1.scalingo.io/admin/organisations/1/rdvs en tant que martine@demo.rdv-solidarites.fr

# Avant gestion de droit
![Capture d’écran 2022-10-20 à 15 46 06](https://user-images.githubusercontent.com/11738628/196970915-cf0b98e2-c2c0-463d-8749-8cdf107ccd19.png)

# Après gestion de droit
![Capture d’écran 2022-10-21 à 11 41 17](https://user-images.githubusercontent.com/11738628/197166103-2dc815f7-a0b7-4272-9e24-9b515d277bde.png)

# Avant liste des RDV
![Capture d’écran 2022-10-20 à 15 46 40](https://user-images.githubusercontent.com/11738628/196970978-df7d62d8-7685-4c12-b59e-c0d6422eafe1.png)

# Après liste des RDV pour ayant droit
![Capture d’écran 2022-10-21 à 11 41 38](https://user-images.githubusercontent.com/11738628/197166134-bad3e90d-0002-45b9-b056-e7fc90c0c732.png)

# Existant : mail reçu au téléchargement des RDV
![Capture d’écran 2022-10-20 à 15 49 01](https://user-images.githubusercontent.com/11738628/196971241-f267c7bd-d2e8-4899-8e25-21fd24e98a8f.png)

# Après : nouveau mail reçu au téléchargement des rdvs par usager 
![Capture d’écran 2022-10-21 à 11 43 20](https://user-images.githubusercontent.com/11738628/197166266-af3f9a56-1fcf-43d0-8e0f-ea3eb3ae0384.png)

# Existant : format Excel des RDVs
![Capture d’écran 2022-10-20 à 15 53 05](https://user-images.githubusercontent.com/11738628/196971282-268f1152-ad9d-4023-a02c-d2dddecf5786.png)

# Après : nouveau format Excel des RDVs par usager
![Capture d’écran 2022-10-20 à 15 54 03](https://user-images.githubusercontent.com/11738628/196971331-bdadf604-d7a9-4706-90c3-f984792e30df.png)

Avant la revue :
- [x] Préparer des captures de l’interface avant et après
- [x] Nettoyer les commits pour faciliter la relecture
- [x] Supprimer les éventuels logs de test et le code mort

Revue :
- [x] Relecture du code
- [x] Test sur la review app / en local

2022-10-21 14:29 UTC, yaf requested changes
Merci pour le boulot.

Je fais une demande de changement parce que j'ai l'impression que l'on remplace l'existant plutôt que de faire à côté, mais j'ai peut-être mal compris ?

2022-10-21 14:29 UTC, yaf commented on app/controllers/admin/territories/agent_territorial_access_rights_controller.rb
> +    params.require(:agent_territorial_access_right).permit(:allow_to_manage_teams, :allow_to_manage_access_rights, :allow_to_invite_agents, :allow_to_download_metrics)
C'est bizarre de voir ce `:allow_to_download_metrics` ici :thinking:

2022-10-21 14:29 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    skip_authorization
Est-ce qu'au lieu de `skip_authorization` nous n'aurions pas dû tester si l'utilisateur a le droit de faire l'export ?

2022-10-21 14:29 UTC, yaf commented on app/mailers/agents/export_mailer.rb
> +  def rdv_export(agent, organisation_ids, options)
Il faut garder l'ancien export, j'ai l'impression qu'ici, nous sommes en train de le remplacer. Nous avions convenu de laisser l'ancien, et de faire en sorte que plus personne ne l' utilise (leur donner envie de ne plus s'en servir) puis de le supprimer...

2022-10-21 15:07 UTC, DanteZ5 commented
Merci pour tes retours @yaf

En l'occurrence, on ne remplace pas, il y a une évolution de l'appel au job qui doit tenir compte de la nouvelle possibilité pour l'agent de scoper sur plusieurs organisations. C'est la raison pour laquelle les méthodes évoluent, mais le fonctionnement tel qu'il existait perdure (il est juste élargi pour les agents qui peuvent accéder à plusieurs organisations).

Ceci dit à réception du fix de @Holist sur `production`, je gèrerai le conflit de merge (le `search_for` ne s'appuie plus sur le `current_agent`.

2022-10-21 15:12 UTC, DanteZ5 commented on app/controllers/admin/territories/agent_territorial_access_rights_controller.rb
> +    params.require(:agent_territorial_access_right).permit(:allow_to_manage_teams, :allow_to_manage_access_rights, :allow_to_invite_agents, :allow_to_download_metrics)
hmm, peut être que je dis des bêtises, mais ça me parait nécessaire pour pouvoir changer le statut de l'agent depuis la vue d'admin. `/admin/territories/:id/agents/:agent_id/edit`

2022-10-21 19:52 UTC, yaf commented on app/controllers/admin/territories/agent_territorial_access_rights_controller.rb
> +    params.require(:agent_territorial_access_right).permit(:allow_to_manage_teams, :allow_to_manage_access_rights, :allow_to_invite_agents, :allow_to_download_metrics)
Ah, mais oui, pardon, j'ai mal regardé le contrôler sur lequel ça s'applique :)

2022-10-25 12:56 UTC, yaf approved these changes
:rocket:

Merci !

ps: pense bien à en parler avec @MYRIAMKEDDAD et @NesserineZarouri avant la mise en prod.

2022-10-25 13:41 UTC, yaf commented
Vu avec @NesserineZarouri et @MYRIAMKEDDAD le 25 octobre après-midi.

2022-10-25 13:50 UTC, merged