Ajouter le lien 'créer un usager' dans le formulaire d'édition d'un rdv
betagouv/rdv-solidarites.fr pull request #2904
Opened 2022-10-06 16:05 UTC by Holist

Closes #2903

# Avant :

![Capture d’écran 2022-10-06 à 18 03 55](https://user-images.githubusercontent.com/28594222/194363106-9f87eeba-37b9-4d14-9266-af5fce27f1db.png)

# Aprés :

![Capture d’écran 2022-10-06 à 18 03 27](https://user-images.githubusercontent.com/28594222/194363113-b0d5638e-0ce7-4640-b4bb-752e9d829ccf.png)

2022-10-10 09:35 UTC, francois-ferrandis requested changes
Il y a un petit bug, je pense qu'on peut le corriger sans prendre trop de risque.

Je ne connaissait pas cette partie du code, merci pour la découverte !

2022-10-10 09:35 UTC, francois-ferrandis commented on app/controllers/admin/rdvs_controller.rb
> +    add_user_ids = params[:add_user].to_a + params[:user_ids].to_a
Je viens de faire un tour, on dirait qu'il y a des pratiques hétérogènes autour des méthodes d'ajout de User à un RDV, ça mériterait peut-être un petit refactor (séparé bien sûr) pour rendre ça plus cohérent.

2022-10-10 09:35 UTC, francois-ferrandis commented on app/views/admin/rdvs/edit.html.slim
> +                  current_organisation, modal: true, return_location: edit_admin_organisation_rdv_path(current_organisation, @rdv), role: default_service_selection_from(@rdv.motif.service) \
Avec le système de redirect actuel, on a un bug lorsqu'on essaye d'ajouter plusieurs users via le formulaire de création : seul le dernier usager créé apparaît dans la liste.

La raison c'est que l'[on redirige vers `params[:return_location]`](https://github.com/betagouv/rdv-solidarites.fr/blob/aeb4d080aaf8edfbd678d25ae593b14e9107d7d4/app/controllers/admin/users_controller.rb#L128) et que la valeur que l'on passe ici ne conserve pas les queryparams déjà utilisés.

Encore une fois, il y aurait un petit boulot de refacto pour clarifier ces mécanismes, mais en attendant on peut définir `return_location: request.url` ici

```suggestion
                  current_organisation, modal: true, return_location: request.url, role: default_service_selection_from(@rdv.motif.service) \
```

ou simplement omettre le paramètre, ce qui fera en sorte d'[utiliser le referrer](https://github.com/betagouv/rdv-solidarites.fr/blob/aeb4d080aaf8edfbd678d25ae593b14e9107d7d4/app/controllers/admin/users_controller.rb#L128).

```suggestion
                  current_organisation, modal: true, role: default_service_selection_from(@rdv.motif.service) \
```

2022-10-10 18:08 UTC, Holist reviewed
Merci :)

2022-10-11 07:06 UTC, francois-ferrandis approved these changes
C'est top, ça fait plaisir d'ajouter une feature en si peu de lignes de code ! :ok_hand:

2022-10-11 07:52 UTC, merged