Rappatrie les champs `notes` et `logement` dans la table  `users`
betagouv/rdv-solidarites.fr pull request #2909
Opened 2022-10-07 13:08 UTC by NFontelle

Closes #2219

# Checklist

- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-11-02 16:16 UTC, yaf commented
Le champ `notes` peut être migré en cumulant les données des divers profiles. Pour le champ logement, c'est plus délicat. Nous pourrions peut-être regarder qui se sert vraiment de ce champ ?

Il y a encore pas mal de département qui utilise le champ `logement`:

```
irb(main):011:0> Territory.where(enable_logement_field: true).pluck(:name)
=> 
["Manche", 
"Yonne",
"Finistère",
"Aisne",
"Meuse",
"Seine-et-Marne",
"Lot",
"Maine et Loire",
"Seine-Saint-Denis",
"Meurthe-et-Moselle",
"Var",
"Côtes d'Armor",
"Vienne",
"Conseil Départemental des Bouches du Rhône",
"Savoie",
 "Aveyron",
 "Ardennes"]
```

_À voir avec Myriam pour lancer une action là-dessus_

Nous devons faire la migration...

```ruby
irb(main):021:0> User.joins(:user_profiles).group(:id).having("count(user_profiles.id) > 1").select {|u| u.user_profiles.pluck(:logement).uniq.compact.count > 1}.count
=> 34
```

C'est plus simple à traiter.

```
irb(main):023:0> User.joins(:user_profiles).group(:id).having("count(user_profiles.id) > 1").select {|u| u.user_profiles.pluck(:logement).uniq.compact.count > 1}.flat_map(&:organisations).uniq.flat_map(&:territo
ry).flat_map(&:name).uniq
=> ["Pas-de-Calais", "Pyrénées-Atlantiques", "Seine-et-Marne"]
```

Voilà qui devrait pouvoir réduire les questions. Si ces départements souhaitent arrêter d'utiliser ce champ, nous pouvons faire la migration simplement, en écrasant les valeurs.

2022-11-02 16:38 UTC, yaf commented
Les départements du Pas-de-Calais et des Pyrénées-Atlantique ont désactivé ce champ, donc nous pouvons l'écraser (voir le mettre à `nil`).

Un email viens d'être envoyé à la Seine-et-Marne pour voir comment faciliter cette migration.

2022-11-14 10:07 UTC, yaf commented
Le 77 ne répondant pas, nous allons faire un email pour annoncer la migration comme un fait, et pour le choix de la valeur, nous prendrons « au hasard » (peut-être voir si une des deux valeurs est la valeur par défaut, c'est sans doute l'autre qui est la bonne).

2022-12-02 18:16 UTC, yaf commented
Mise à jour des données

```
User.joins(:user_profiles).group(:id).having("count(user_profiles.id) > 1").select {|u| u.user_profiles.pluck(:logement).uniq.compact
.count > 1}.count

=> 36            
```

```
User.joins(:user_profiles).group(:id).having("count(user_profiles.id) > 1").select {|u| u.user_profiles.pluck(:logement).uniq.compact
.count > 1}.flat_map(&:organisations).uniq.flat_map(&:territory).flat_map(&:name).uniq
=> ["Pas-de-Calais", "Pyrénées-Atlantiques", "Seine-et-Marne", "Ardennes"]

```

2022-12-02 18:22 UTC, yaf commented
Où `ids` contient la liste des `id` d'organisations du 77

```
irb(main):011:0> User.joins(:user_profiles).where("user_profiles.organisation_id": ids).group(:id).having("count(user_profiles.id) > 1").select {|u| u
.user_profiles.pluck(:logement).uniq.compact.count > 1}.count
=> 11
```

2022-12-02 18:23 UTC, yaf commented
Pour les Ardennes, il n'y en a qu'un 

```
=> [250, 237, 156, 155, 154, 157, 158, 325, 329, 330, 326, 335, 327, 328, 334, 332, 331, 333, 336, 3385, 3386, 3387, 3388, 3389, 3390, 249]
irb(main):014:0> User.joins(:user_profiles).where("user_profiles.organisation_id": ids).group(:id).having("count(user_profiles.id) > 1").select {|u| u
.user_profiles.pluck(:logement).uniq.compact.count > 1}.count
=> 1
```

2023-01-09 10:42 UTC, victormours reviewed
Je crois qu'on peut supprimer le `docs/domain_model.svg`, et il manque peut-être une condition sur l'affichage des notes (mais qui était déjà manquante avant cette PR), mais sinon ça a l'air bien

2023-01-09 10:42 UTC, victormours commented on app/views/admin/rdvs_users/_user_card.html.slim
> +      - notes = rdvs_user.user.notes
est-ce qu'il ne manque pas un `- if current_territory.enable_notes_field?` ici ?

2023-01-09 20:23 UTC, aminedhobb reviewed
J'ai laissé un commentaire sur la migration mais sinon ça m'a l'air ok, merci 🙌 !

2023-01-09 20:23 UTC, aminedhobb commented on app/views/admin/rdvs_users/_user_details.html.slim
> +    - if current_territory.enable_notes_field
micro detail: ce serait peut-être mieux niveau lisibilité d'utiliser la méthode `enable_notes_field?` comme dans les autres vues

2023-01-12 09:52 UTC, yaf approved these changes
:warning: à déployer au moment d'une faible utilisation de RDV Solidarités

2023-01-12 11:20 UTC, aminedhobb requested changes

2023-01-12 11:20 UTC, aminedhobb commented on db/migrate/20221007122950_add_logement_and_note_to_users.rb
> +  def up_only
⚠️ c'est pas le nom de la méthode qui doit être `up_only`, ici ça va pas marcher. 
Je proposais  dans mon commentaire précédent de mettre seulement la partie où on update les `user` existants dans un bloc que  l'on passe à la méthode `up_only`.  Ça permet  de ne pas prendre ce code (qui n'est pas réversible) en compte lorsque l'on veut rollback la migration. 
Du coup on garderait `change` comme nom de méthode et on aurait
```ruby 
up_only do 
   profile_with_notes = UserProfile.where.not(notes: ["", nil])
   profile_with_logement = UserProfile.where.not(logement: ["", nil])

   UserProfile.where(id: profile_with_notes + profile_with_logement).distinct.find_each do |profile|
    ...
   end
end
 ```

2023-01-12 13:22 UTC, yaf commented on db/migrate/20221007122950_add_logement_and_note_to_users.rb
> +  def up_only
:facepalm: je suis allé un peu vite. Merci !

2023-01-17 11:07 UTC, aminedhobb approved these changes
👍

2023-01-24 19:49 UTC, merged