2901 notification salle attente
betagouv/rdv-solidarites.fr pull request #2911
Opened 2022-10-11 09:30 UTC by NFontelle

Closes #2901

mise en place de la notification des agents lors de l'arrivée d'un usagé en salle d'attente

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-12-14 11:38 UTC, francois-ferrandis requested changes
Désolé pour les pinaillages, je suis dispo pour qu'on regarde tout ça ensemble quand tu veux ! :call_me_hand:

2022-12-14 11:38 UTC, francois-ferrandis commented on app/models/territory.rb
> +
Je ne suis pas sûr de comprendre l'intérêt de ce choix de structure de données pour `OPTIONAL_RDV_WAITING_ROOM_FIELD_TOGGLES`. Pourquoi ne pas ajouter des valeurs dans `config/locales/models/territory.fr.yml` plutôt que `config/locales/models/rdv.fr.yml` ? Ces champs sont bien dans la table `territories` donc je ne comprends pas pourquoi on passe à traver le modèle `Rdv`.

2022-12-14 11:38 UTC, francois-ferrandis commented on app/views/admin/rdvs/_rdv.html.slim
> +      = render "admin/rdvs/waiting_room", rdv: rdv, remote: true
J'ai l'impression que ce `remote: true` n'a aucun effet (le paramètre est interprété comme un passage de variable locale à la partial).

2022-12-14 11:38 UTC, francois-ferrandis commented on app/models/concerns/rdv/using_waiting_room.rb
> +require "redis"
Je me pose la question de l'avantage de Redis par rapport à une table Postgres `WaitingRoomUsers`, dont la manipulation serait plus familière que celle de Redis. Quelles ont été les raisons de ce choix ?

2022-12-14 11:38 UTC, francois-ferrandis commented on app/views/admin/rdvs/_waiting_room.html.slim
> +  #waiting_room_button
Ce template étant utilisé sur l'index des RDV, il va y avoir plusieurs occurrences de cet élément HTML, et donc il faudrait utiliser une classe HTML (différente pour chaque RDV) plutôt qu'un ID HTML.

2022-12-14 11:38 UTC, francois-ferrandis commented on app/views/admin/rdvs/_waiting_room.html.slim
> +      = link_to "Salle d'attente", admin_organisation_rdv_user_in_waiting_room_path(rdv.organisation, rdv), method: :post, class: "btn btn-primary", remote: true
Top cet usage de `remote: true` ! :ok_hand:

2022-12-14 11:38 UTC, francois-ferrandis commented on app/views/admin/territories/rdv_fields/edit.html.slim
> +          p.text-muted.font-14= t(".hint_4")
Pourquoi utiliser des numéros plutôt qu'un nom de hint ?

2022-12-15 08:42 UTC, yaf commented on app/models/concerns/rdv/using_waiting_room.rb
> +      REDIS.del(REDIS.keys("#{Rails.env}:user_in_waiting_room_rdv_id:*"))
Nous n'avons pas vraiment besoin de clef valeur. Nous avions hésité avec l'utilisation d'une liste. Nous avons changé l'implémentation pour utiliser une liste, c'est aussi efficace (en fait, plus efficace du coup, puisqu'il n'y a plus d'utilisation de `KEYS`

2022-12-15 13:46 UTC, yaf commented on app/views/admin/territories/rdv_fields/edit.html.slim
> +          p.text-muted.font-14= t(".hint_4")
:shrug: Je vais modifier ça.

2022-12-15 13:52 UTC, yaf commented on app/views/admin/rdvs/_waiting_room.html.slim
> +  #waiting_room_button
:+1:

2022-12-15 14:17 UTC, francois-ferrandis approved these changes
Merci, beau boulot ! :sparkles:

2022-12-15 14:18 UTC, yaf commented on app/models/territory.rb
> +
Comme discuter de vive voix, nous allons repousser ce nettoyage à un autre ticket : #3185

Merci !

2022-12-15 14:20 UTC, yaf commented
@NFontelle tu présentes cette fonctionnalité à @NesserineZarouri et @MYRIAMKEDDAD  ?

2022-12-19 15:18 UTC, merged