Ajout d'une ligne responsable dans la fusion des usagers
betagouv/rdv-solidarites.fr pull request #2958
Opened 2022-10-21 08:44 UTC by NFontelle

Closes #2932

Pour permettre aux agents de choisir le maintient d'un responsable lors de la fusion usager une ligne correspondante a été ajoutée au tableau de fusion.

avant : 
![image](https://user-images.githubusercontent.com/60173782/197153387-ed2585d6-1c11-4162-a6bd-93f84b2f0e29.png)

après :
![image](https://user-images.githubusercontent.com/60173782/197153142-76c0822f-0530-4360-941c-3d6ea4ad4859.png)

# Checklist

Avant la revue :
- [x] Préparer des captures de l’interface avant et après
- [x] Nettoyer les commits pour faciliter la relecture
- [x] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-25 09:03 UTC, francois-ferrandis commented on app/views/admin/merge_users/new.html.slim
> -        - user2_presenter = DisplayableUserPresenter.new(@merge_users_form.user2, current_organisation)
Est-ce que le `DisplayableUserPresenter` était inutile ou est-ce qu"il compliquait l'implémentation, ou les deux ?  :)

2022-10-25 15:48 UTC, francois-ferrandis commented on app/views/admin/merge_users/new.html.slim
> -        - user2_presenter = DisplayableUserPresenter.new(@merge_users_form.user2, current_organisation)
En effet, si il ajoutait peu de valeur, autant faire du ménage !

2022-10-25 15:59 UTC, francois-ferrandis requested changes
L'approche globale me semble bonne (si j'ai bien compris la problématique).

Je vois en tout cas un point à corriger avant de merger, et j'ai des petites suggestions. :wink:

2022-10-25 15:59 UTC, francois-ferrandis commented on app/helpers/users_helper.rb
> +    return nil unless user
Si on a pas de `user`, le comportement correct est plutôt de prévenir le dev qui a oublié de passer un user, et donc de laisser une exception remonter. ;)

2022-10-25 15:59 UTC, francois-ferrandis commented on app/helpers/users_helper.rb
> +    return user.responsible&.full_name if attribute == :responsible_id
Il faudrait ajouter une gestion du champ `logement` pour faire passer le test `spec/features/agents/users/agent_can_merge_users_spec.rb:32`.

Ça signifie qu'il va falloir passer l'organisation aussi !

2022-10-25 15:59 UTC, francois-ferrandis commented on app/helpers/users_helper.rb
> +  def user_merge_attribute_value(user, attribute)
Je trouve ça étrange que cette méthode soit posée dans un helper généraliste, alors qu'elle n'est utilisée que dans le contexte du merge. Ça aurait plus de sens d'en faire une méthode de classe de `MergeUsersForm`.

2022-10-28 10:14 UTC, NFontelle commented on app/helpers/users_helper.rb
> +    return nil unless user
La page s'affiche sans user, avec une selection d'un premier user puis du deuxième, du coup l'absence de user est visuelle. Et il est necessaire de ne pas lever d'exception.

2022-10-28 10:34 UTC, NFontelle commented on app/helpers/users_helper.rb
> +  def user_merge_attribute_value(user, attribute)
Oui c'est juste, mais cette méthode utilise beaucoup de méthodes du Helper et la déplacer poses plusieurs questions.
On pourrait par exemple créer un concern pour le user

2022-10-28 13:02 UTC, francois-ferrandis approved these changes
C'est bon pour moi ! :ok_hand:

2022-10-28 13:02 UTC, francois-ferrandis commented on app/helpers/users_helper.rb
> +  def user_merge_attribute_value(user, attribute)
Ah oui j'avais pas vu ça ! Ça me va de laisser comme ça pour le moment. :wink:

2022-10-28 13:53 UTC, NFontelle commented on app/helpers/users_helper.rb
> +    return nil unless user
Effectivement, je n'avai pas du tout compris. Effectivement, tu as raison :)

2022-10-28 14:20 UTC, merged