Documentation Rswag motifs WIP
betagouv/rdv-solidarites.fr pull request #2973
Opened 2022-10-25 14:08 UTC by DanteZ5

Closes #issue_number

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-27 08:41 UTC, sebastiencarceles requested changes
C'est top mais j'ai une petite demande de changement ! Est-ce que tu peux ajouter la réponse 401 ? Comme c'est un endpoint qui nécessite une authentification, il me semble important de préciser ce cas.

2022-10-27 08:41 UTC, sebastiencarceles commented on spec/requests/api/v1/motifs_request_spec.rb
> +      parameter name: "access-token", in: :header, type: :string, description: "Token d'accès (authentification)", example: "SFYBngO55ImjD1HOcv-ivQ"
Bon ça ne change pas grand chose, mais ça te dirait qu'on utilise que des int pour les ID ?

```suggestion
      parameter name: "access-token", in: :header, type: :integer, description: "Token d'accès (authentification)", example: "SFYBngO55ImjD1HOcv-ivQ"
```

2022-10-27 08:41 UTC, sebastiencarceles commented on spec/requests/api/v1/motifs_request_spec.rb
> +      parameter name: :service_id, in: :query, type: :string, description: "filtre sur les services", example: "1", required: false
```suggestion
      parameter name: :service_id, in: :query, type: :integer, description: "filtre sur les services", example: "1", required: false
```

2022-10-27 08:41 UTC, sebastiencarceles commented on spec/requests/api/v1/motifs_request_spec.rb
> +          let!(:access_agent) { api_auth_headers_for_agent(agent) }
À mon avis tu peux déplacer (au moins) ces 4 lignes : 

```rb
          let!(:access_agent) { api_auth_headers_for_agent(agent) }
          let(:"access-token") { access_agent["access-token"].to_s }
          let(:uid) { access_agent["uid"].to_s }
          let(:client) { access_agent["client"].to_s }
```

à la ligne 38 pour éviter d'avoir à les répéter à chaque fois.

2022-10-31 07:42 UTC, DanteZ5 commented on spec/requests/api/v1/motifs_request_spec.rb
> +      parameter name: "access-token", in: :header, type: :string, description: "Token d'accès (authentification)", example: "SFYBngO55ImjD1HOcv-ivQ"
yes pour les ID, ça me parait sensé, dans ta suggest par contre tu as mis `access_token`.

2022-10-31 08:37 UTC, DanteZ5 commented on spec/requests/api/v1/motifs_request_spec.rb
> +          let!(:access_agent) { api_auth_headers_for_agent(agent) }
je pense que ce sont des contextes différents `agent` n'est pas le même.
Ou alors, il faudrait trouver une façon centralisée de déclarer `access_token: [], uid: [], client: []` en fonction des caractéristiques de `agent`

2022-10-31 08:49 UTC, DanteZ5 commented
ajout de la 401 et choix d'integer plutôt que strings dans le cas d'IDs.
refacto des créations de tokens non intégré.

2022-11-01 16:41 UTC, damienlethiec approved these changes

2022-11-01 16:41 UTC, merged