Feature/rate limiting api v2
betagouv/rdv-solidarites.fr pull request #2983
Opened 2022-10-26 17:46 UTC by damienlethiec

Closes #2979 

Pour pouvoir tester le comportement en développement, runnez `rails dev:cache` en console.

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-27 08:35 UTC, sebastiencarceles reviewed
Je me demande si le plus simple, ça ne serait pas de faire une nouvelle branche depuis production et de cherry-pick ce commit ? Histoire de rendre ce périmètre indépendant de l'API V2.

2022-10-27 08:35 UTC, sebastiencarceles commented on spec/requests/api/v1/rdvs_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_object"
Est-ce qu'on peut faire un schéma `error_too_many_requests` pour gérer ce cas ? On va le répéter dans chaque doc, a priori.

2022-10-27 08:46 UTC, damienlethiec commented
> Je me demande si le plus simple, ça ne serait pas de faire une nouvelle branche depuis production et de cherry-pick ce commit ? Histoire de rendre ce périmètre indépendant de l'API V2.

Agree

2022-10-27 08:48 UTC, damienlethiec commented on spec/requests/api/v1/rdvs_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_object"
Je ne pense pas que ce soir nécessaire. Le schéma vise pas à vérifier le contenu (ça c'est vérifié par l'error code) mais simplement que le format de réponse est correct. Et dans ce cas le format de réponse est le même: un hash avec une clé "errors" associée à un array de strings

2022-10-27 08:48 UTC, damienlethiec commented on spec/requests/api/v1/rdvs_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_object"
Mon but était justement de renvoyer le même type de schéma que les autres erreurs

2022-10-27 08:49 UTC, sebastiencarceles commented on spec/requests/api/v1/rdvs_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_object"
:+1:

2022-10-27 15:49 UTC, Holist requested changes

2022-10-27 15:49 UTC, Holist commented on config/initializers/rack_attack.rb
> +  throttle("requests by ip", limit: 20, period: 60) do |request|
A confirmer par @aminedhobb ou @qblanc, je pense qu'on risque d'avoir un problème  lorsque les départements vont vouloir charger les fichiers des allocataires dans rdv-insertion car rdv-insertion va utiliser à ce moment la l'api pour créer les usagers dans rdv solidarité et je me demande si on va pas dépasser cette limite. Il y a peut être d'autres cas ou cela pourrait être gênant pour rdv insertion.

2022-10-31 09:10 UTC, damienlethiec commented on config/initializers/rack_attack.rb
> +  throttle("requests by ip", limit: 20, period: 60) do |request|
Tu as une idée d'une limite qu'on pourrait mettre et qui serait safe pour nos utilisateurs existants @Holist ?

2022-10-31 17:59 UTC, damienlethiec commented
Clôturé car cherry-picked ici  #3012

2022-10-31 17:59 UTC, closed without merging