First draft pagination lieux for creneaux
betagouv/rdv-solidarites.fr pull request #2984
Opened 2022-10-26 20:22 UTC by damienlethiec

Petite tentative d'amélioration des perfs en paginant la page de recherche de créneaux.

Ca provoque une regression, que je ne trouve pas cata mais à évaluer: le nombre d'éléments par page ne sera pas toujours égale car on détermine la répartition dans les pages avant d'ignorer les éléments sans prochains créneaux. Sans ça, on aura beau paginer, on devra toujours faire le calcul de créneaux avant ça pour tous les lieux.

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-27 08:19 UTC, victormours requested changes

2022-10-27 08:19 UTC, victormours commented on app/services/search_context.rb
> +        .page(page).per(5)
avec cette implémentation, on a un risque d'avoir des pages vides, ce qui peut mener à des incompréhensions et à des usagers qui ne prennent pas de rdv alors qu'ils pourraient en avoir, et je pense pas que c'est viable.
Peut-être qu'il y a une autre implémentation qui remplace la boucle de `#next_availability_by_lieux` par un `while` pour trouver les 5 premiers lieux avec des créneaux si on demande la première page, et un peu de cache sur `Users::CreneauxSearch` pour le moment où on demande les pages suivantes.
Je suis dispo pour en parler de vive voix :)

2022-10-27 08:52 UTC, damienlethiec commented on app/services/search_context.rb
> +        .page(page).per(5)
Je serais curieux de savoir si beaucoup de lieux n'ont pas de créneaux dispo. Mais dans tous les cas ce serait plus propre oui. Je regarde dans la journée

2022-10-27 13:32 UTC, sebastiencarceles commented
Perso je trouve que c'est bien de chercher à paginer les résultats, mais comme c'est du calculé, en effet ça peut poser des problèmes de trous dans la continuité des données.

Est-ce qu'on pourrait : 
- conserver le principe de pagination
- mais aller chercher les données dans un cache, qu'on aurait préchauffé en asynchrone et qu'on maintiendrait à jour

Est-ce que c'est trop compliqué ?

2022-11-01 14:35 UTC, damienlethiec commented on app/services/search_context.rb
> +        .page(page).per(5)
Dans l'implémentation proposée, on risque quand même assez peu de page vide car on fait déjà un pré-check au niveau des lieux pour savoir s'ils ont des plages d'ouverture pour le motif donné (via le scope `with_open_slots_for_motifs`). Ca laisse assez peu de risques que de nombreux lieux n'aient au final pas de créneaux

2022-11-01 15:06 UTC, damienlethiec commented
En vrai je m'en sors pas trop ! J'arrive pas à proprement gérer l'expiration de cache ni à avoir de gains de perf importants. Si vous voulez en parler @victormours @sebastiencarceles c'est avec plaisir. Si le sujet n'a pas de sens et qu'on peut le clôturer après ce draft sans y perdre trop de temps ça me va aussi.

2022-11-02 10:53 UTC, yaf commented
La pagination ici, je ne suis pas sur que ce soit très « compréhensible » pour les usagers :thinking: 
Pour optimiser cette page, ce qu'il faudrait c'est aller cherche uniquement le premier prochain créneau disponible (actuellement, il me semble que nous calculons l'ensemble des créneaux disponible sur la semaine à venir pour n'affiche que le prochain...)

2022-11-02 10:57 UTC, damienlethiec commented
> La pagination ici, je ne suis pas sur que ce soit très « compréhensible » pour les usagers 🤔 Pour optimiser cette page, ce qu'il faudrait c'est aller cherche uniquement le premier prochain créneau disponible (actuellement, il me semble que nous calculons l'ensemble des créneaux disponible sur la semaine à venir pour n'affiche que le prochain...)

Ca pourrait s'explorer mais après avoir fait un premier tour sur ce sujet en terme de perf je ne suis pas sûr des gains. Avec la méthode de calcul en creux actuelle, on n'a pas le choix de chercher tous les créneaux pour une période donnée puis de prendre le premier. Après on a la main sur cette période. Actuellement, on itère pas semaine et on pourrait faire le choix d'itérer par jour. Faudrait faire des tests de perf avancés sur de la donnée de prod pour voir l'impact mais intuitivement je ne suis pas sûr que le gain soit vraiment là. Sur mes minis tests avec de la donnée de dev, je dégradais plutôt la perf qu'autre chose en changeant la période d'itération.

2022-11-02 11:24 UTC, yaf commented
ça pousserait pour mettre le calcul en cache pour s'en servir sur le deuxième page alors...

2022-11-03 22:49 UTC, closed without merging