Court-circuite la policy pour afficher tout les RDV
betagouv/rdv-solidarites.fr pull request #3004
Opened 2022-10-28 19:21 UTC by yaf

Nous avons ajouté la possibilité de regarder les RDV d'une des organisations dont nous avons accès dans la liste des RDV.

Le problème vient des policies en place qui limite la visualisation des RDV à ceux de l'organisation courante. Nous pourrions basculer les policies vers les RDV du territoire, mais ça n'est pas simple à faire rapidement.

Cette PR propose de ne pas utiliser les policies dans cet index. Au moins en attendant de remanier les droits d'accès.

Closes #3003

# Checklist

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-10-31 09:09 UTC, damienlethiec commented
L'autre option serait d'utiliser une policy dédiée @yaf . Je trouve ça un peu plus safe et future proof personnellement.

2022-10-31 09:48 UTC, francois-ferrandis requested changes

2022-10-31 09:48 UTC, francois-ferrandis commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
Sauf erreur de ma part, cela permet de passer des IDs arbitraires dans l'URL pour accéder à tous les RDVs de la plateforme. :warning:

2022-10-31 17:26 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
:facepalm: tu as raison.

Je vais voir comment faire évoluer la policy actuel (je ne suis pas sûr de voir l'orientation d'une policy dédié @damienlethiec ?). Après tout, je peux voir tous les RDV auxquelles j'accède (ça comprend toutes les organisations auxquelles j'ai accès)

2022-10-31 17:31 UTC, damienlethiec commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
L'intention est de ne pas créer d'exception dans un fonctionnement, mais de garder le même fonctionnement (un policy vérifie si l'accès est possible) même si c'est pour tout ouvrir. Je trouve qu'avoir le max de cohérence facilité grandement la maintenance et le debug. Aussi, de ce que je comprends il y aura quand même besoin d'un minimum de restriction. Du coup la policy a du sens pour ça je pense.

2022-10-31 17:41 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
Yep, ok. C'est sur le côté « faire une policy » spécifique que je ne suis pas certain de t'avoir compris. Mais je suis complétement d'accord avec toi sur ce que tu évoques ! :+1:

2022-10-31 17:42 UTC, damienlethiec commented on app/controllers/admin/rdvs_controller.rb
> +  skip_after_action :verify_policy_scoped, only: :index
Il me semble que tu peux faire sauter cette ligne du coup non ? Vu que tu filtre bien avec le policy scope plus bas.

2022-10-31 17:42 UTC, damienlethiec commented on app/policies/agent/rdv_policy.rb
> +      organisation_scope = scope.where(organisation: current_agent.organisations)
Je ne me rends pas trop compte des implications mais ça me parait safe. Je laisse françois confirmer.

2022-10-31 17:42 UTC, francois-ferrandis reviewed
Ça m'a l'air à part le `skip_after_action` qui traîne.

Je dois y aller et je serai absent demain, je laisse @damienlethiec valider ! :rocket:

2022-10-31 17:42 UTC, francois-ferrandis commented on app/controllers/admin/rdvs_controller.rb
> +
Tu as oublié de supprimer ce `skip_after_action`, non ?

2022-10-31 17:44 UTC, damienlethiec requested changes

2022-10-31 17:44 UTC, damienlethiec commented on app/policies/agent/rdv_policy.rb
> +      organisation_scope = scope.where(organisation: current_agent.organisations)
Il me semble que tu as un test qui pète en effet de bord !

2022-10-31 17:49 UTC, damienlethiec commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
L'idée était d'éviter les effets de bords si tu dois modifier une policy utilisée autre part. C'est ce qu'il se passe ici où en modifiant la policy tu crées une erreur des tests de l'API. Souvent j'aime bien nester mes policies dans toutes l'app pour ça, histoire de les rendre spécifique par controller et non par model (dans ce cas, l'autre policy serait probablement nestée dans un dossier API). Mais ce serait un gros taff donc déjà juste créer une policy distinct pour ce cas particulier est une première étape. N'hésite pas à me dire si je ne suis pas clair. Ce n'est pas facile à l'écrit

2022-10-31 17:49 UTC, yaf commented on app/policies/agent/rdv_policy.rb
> +      organisation_scope = scope.where(organisation: current_agent.organisations)
Je crois que le risque est complétement contrôlé. Nous ne ramenons pas de RDV auxquelles l'agent n'a pas accès.

```
app/controllers/admin/rdvs_collectifs_controller.rb:    @rdvs = policy_scope(Rdv).where(organisation: current_organisation).collectif
app/controllers/admin/rdvs_collectifs_controller.rb:      duplicated_rdv = policy_scope(Rdv).find(params[:duplicated_rdv_id])
app/controllers/admin/users_controller.rb:    @rdvs = policy_scope(Rdv).merge(@user.rdvs)
app/controllers/admin/stats_controller.rb:    policy_scope(Rdv).merge(current_agent.rdvs)
app/controllers/admin/organisations/stats_controller.rb:      rdvs: policy_scope(Rdv),
app/controllers/admin/organisations/stats_controller.rb:    stats = Stat.new(rdvs: policy_scope(Rdv))
app/controllers/admin/rdvs_controller.rb:    @rdvs = policy_scope(Rdv).search_for(@scoped_organisations, parsed_params)
app/controllers/admin/rdvs_controller.rb:    @rdv = policy_scope(Rdv).find(params[:id])
app/controllers/admin/participations_controller.rb:    @rdv = policy_scope(Rdv).find(params[:rdv_id])
app/controllers/api/v1/rdvs_controller.rb:    rdvs = policy_scope(Rdv)
app/controllers/users/rdvs_controller.rb:    @rdvs = policy_scope(Rdv).includes(:motif, :rdvs_users, :users).for_domain(current_domain)
app/controllers/users/rdvs_controller.rb:    @rdv = policy_scope(Rdv).find(params[:id])
```

2022-10-31 17:49 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +
oui :)

2022-10-31 18:01 UTC, damienlethiec approved these changes
Si on chipote il y a un saut de ligne en trop. Mais ça me va ^^

2022-10-31 18:03 UTC, damienlethiec requested changes
Problème brakeman à priori :/

2022-10-31 18:04 UTC, damienlethiec approved these changes

2022-10-31 18:07 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    @rdvs = Rdv.search_for(@scoped_organisations, parsed_params)
Je crois que je comprends l'idée. C'est sans doute un sujet à discuter en équipe effectivement. 

Après, ça fait presque 2 ans que nous avions discuté (avec mon binôme de l'équipe) d'un refactoring des policies qui aujourd'hui embarque trop de « métier » et pourraient donc être plus « simple » et compréhensible, plus ouverte... mais je n'ai pas pris le temps de faire le refactoring, et lui l'a entamé juste avant de partir sans avoir le temps de finir non plus... Comme j'ai nos vieilles discussions encore en tête, je me permets de modifier les policies dans le sens que nous avions évoqués. **Mais c'est clair que ça serait mieux de faire un point tous ensemble, un jeudi matin :)**

2022-11-01 09:13 UTC, francois-ferrandis approved these changes
Tip top ! 🚀

2022-11-02 10:18 UTC, merged