Implement rate limit for API
betagouv/rdv-solidarites.fr pull request #3012
Opened 2022-10-31 17:52 UTC by damienlethiec

closes #2979 

Remplace #2983 

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-11-02 09:59 UTC, aminedhobb requested changes
L'implémentation me parait bien, mais j'ai un peu de mal à voir pourquoi on doit faire ça :).
Je rejoins le commentaire de @guillett sur l'issue, j'ai pas l'impression que ça réponde à un problème que l'on ait actuellement. Du coup en tant que principal (même seul 😅 ) consommateur de l'API, je ne vois pas de bonnes raisons d'avoir à implémenter un système de throttling côté RDV-Insertion, ou de dégrader l'expérience utilisateur.

Si ce sont les nouveaux endpoints publics qui sont potentiellement vulnérables, on pourrait restreindre ce rate limiting pour ces endpoints non ?

2022-11-02 10:07 UTC, damienlethiec commented
> L'implémentation me parait bien, mais j'ai un peu de mal à voir pourquoi on doit faire ça :). Je rejoins le commentaire de @guillett sur l'issue, j'ai pas l'impression que ça réponde à un problème que l'on ait actuellement. Du coup en tant que principal (même seul 😅 ) consommateur de l'API, je ne vois pas de bonnes raisons d'avoir à implémenter un système de throttling côté RDV-Insertion, ou de dégrader l'expérience utilisateur.
> 
> Si ce sont les nouveaux endpoints publics qui sont potentiellement vulnérables, on pourrait restreindre ce rate limiting pour ces endpoints non ?

En effet, le besoin est surtout au niveau des nouveaux endpoints publics. Jusqu'à cette semaine je n'avais pas l'info de qui utilisait l'API actuellement. Je pose la question à la réu de jeudi pour trancher sur quels endpoints on veut limiter.

2022-11-02 10:20 UTC, aminedhobb commented
> En effet, le besoin est surtout au niveau des nouveaux endpoints publics. Jusqu'à cette semaine je n'avais pas l'info de qui utilisait l'API actuellement. Je pose la question à la réu de jeudi pour trancher sur quels endpoints on veut limiter.

Oui désolé j'étais pas là quand ces discussions ont commencé. Ça marche on voit ça jeudi merci 👍 !

2022-11-02 11:08 UTC, yaf reviewed
_Je n'avais pas mis à jour ma page, et donc pas vu vos commentaires avant de faire le mien qui n'apporte par grand-chose_

2022-11-07 09:43 UTC, damienlethiec commented
J'ai fait les changements. Vous pouvez faire un petit check @aminedhobb @Holist ?

2022-11-07 09:59 UTC, aminedhobb approved these changes
Merci pour les changements @damienlethiec !
Je t'ai posé deux petites questions non bloquantes 👍.

2022-11-07 09:59 UTC, aminedhobb commented on docs/api/v1/description_api.md
> +L'utilisation de l'API est limitée. Vous pouvez effectuer au maximum 50 appels par minutes. Si vous dépassez cette limite, une erreur 429 vous sera renvoyée et vous trouverez le temps que vous devez
On peut peut-être préciser que ça concerne que les endpoints publics du coup ?

2022-11-07 09:59 UTC, aminedhobb commented on spec/requests/api/v1/organizations_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_generic"
Je ne connais pas très bien le fonctionnement de la doc mais il ne s'agit pas d'une erreur spécifique ici ?

2022-11-07 10:11 UTC, damienlethiec commented on docs/api/v1/description_api.md
> +L'utilisation de l'API est limitée. Vous pouvez effectuer au maximum 50 appels par minutes. Si vous dépassez cette limite, une erreur 429 vous sera renvoyée et vous trouverez le temps que vous devez
Bien vu !

2022-11-07 10:14 UTC, damienlethiec commented on spec/requests/api/v1/organizations_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_generic"
Bonne question :) En effet le schéma d'erreur généric est peu précis et je peux sans doute le préciser :)

2022-11-07 10:14 UTC, damienlethiec commented on spec/requests/api/v1/organizations_request_spec.rb
> +        schema "$ref" => "#/components/schemas/errors_generic"
Je corrige ces 2 points et je merge

2022-11-07 10:49 UTC, merged