Affichage des coordonnées de prescripteur sur la page d'un RDV côté agent
betagouv/rdv-solidarites.fr pull request #3091
Opened 2022-11-16 15:15 UTC by francois-ferrandis

Pour tester : <`mettre ici l'url de la review app une fois déployé`>

Décrire le pourquoi des modifications

Closes #3034

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-11-18 07:27 UTC, francois-ferrandis commented on app/javascript/application_agent.js
> -import './components/tooltip';
Le fichier `tooltip.js` n'était plus utilisé, je l'ai supprimé.

2022-11-18 07:31 UTC, francois-ferrandis commented on db/migrate/20221116143520_add_prescripteurs.rb
> +      t.string :phone_number_formatted
Le champ `___` était requis par le concern `PhoneNumberValidation::HasPhoneNumber`, le plus simple était donc de l'ajouter en base par convention, même si nous avons douté de son utilité fonctionnelle dans ce cas précis (car nous n'envoyons pas de SMS au prescripteur).

2022-11-18 19:25 UTC, yaf approved these changes

2022-11-22 16:00 UTC, victormours requested changes

2022-11-22 16:00 UTC, victormours commented on db/schema.rb
> +    t.bigint "rdv_id", null: false
suite aux discussions sur les rdvs collectifs pour les prescripteurs, je me rends compte qu'on voudra plutôt les lier à des participations qu'à des rdvs, et qu'il faudra prévoir l'équivalent de cette PR pour le cas des rdv collectifs 🙃

2022-12-05 16:45 UTC, victormours approved these changes
Des bricoles de wordings, mais sinon c'est tout bon. Merci beaucoup ! 🙏

2022-12-05 16:45 UTC, victormours commented on app/views/admin/rdvs/_rdv_details.html.slim
> +      | pris par
Je pense que vu qu'on traite juste le cas des rdv individuels pour le moment, on peut supprimer la ligne 49 et juste mettre "Rendez-vous pris par "

2022-12-06 08:27 UTC, merged