Suppression de code non utilisé / non affiché
betagouv/rdv-solidarites.fr pull request #3102
Opened 2022-11-18 11:54 UTC by francois-ferrandis

Dans #2834, la liste des usagers a été transformée en tableau. Mais liste existante n'a pas été supprimée, c'est juste qu'elle ne s'affiche pas car elle porte la classe `.collapse`, utilisée par ce beau helper bootstrap : https://getbootstrap.com/docs/4.0/components/collapse/

Dans cette PR : 
- on supprime ce bloc qui n'est pas affiché et donc pas utile, ainsi que sa partial
- on supprime deux autres partials que j'ai trouvé en charchant les autres usages de `.collapse` et qui semblent inutilisées
- on corrige un petit souci d'indentation (j'en vois des tas avec RubyMine, mais je me retiens de les corriger en général)

# Checklist

Avant la revue :
- [X] Nettoyer les commits pour faciliter la relecture
- [X] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2022-11-18 11:54 UTC, francois-ferrandis commented on app/views/common/_contact.html.slim
> -              = link_to organisation.website, "#{organisation.website}", class: "text-white"
@yaf Peux-tu confirmer que ce code n'est plus utilisé ? J'ai un doute. :thinking:

2022-11-18 19:08 UTC, yaf requested changes
Je pense que cette PR n'est pas correct. Il y a un besoin d'afficher, dans certains cas de figure, le détail des usagers. Ça ne pouvait pas « rentrer » dans le tableau, nous avons donc décidé de faire une liste simple pour le moment. Ça mériterait d'être amélioré, mais des utilisateurs ont besoin d'accéder à ces informations qui peuvent très bien s'afficher 

copie d'écran en local :

![Screenshot 2022-11-18 at 20-02-15 Liste des RDV - RDV Solidarités](https://user-images.githubusercontent.com/42057/202783078-76388e72-5242-4c2f-840a-89ad132ca847.png)

(il faut cocher l'élément en haut de la liste à gauche)

Dans cette PR, voici ce que le bouton réalise : 

![Screenshot 2022-11-18 at 20-05-44 Liste des RDV - RDV Solidarités](https://user-images.githubusercontent.com/42057/202783242-1774d22c-9a8c-4662-864b-7e36b5b8ae2b.png)
![Screenshot 2022-11-18 at 20-05-33 Liste des RDV - RDV Solidarités](https://user-images.githubusercontent.com/42057/202783244-034e9e64-d94a-4336-9726-444c88e7068f.png)

Un « masquage » de la liste des usagers. Ça n'a pas vraiment d'intérêt et ça ne permet pas aux agents qui partent en tournée, qui ont besoin d'imprimer une liste des RDV avec de les informations usager.


Qu'est-ce qui motive cette PR ?

2022-11-19 19:19 UTC, francois-ferrandis commented
@yaf Aïe aïe aïe, merci pour ton retour ! :grimacing: J'avais en effet loupé le toggle présent sur l'index des RDV, et donc je pensais que c'était du code more ! 

> Qu'est-ce qui motive cette PR ?

En travaillant sur les prescripteur j'ai vu ce code, et je pensais supprimer du code mort. 

Je ferme la PR pour signaler clairement que la démarche est abandonnée.

Note : on vois quand-même que les tests étaient au vert malgré la suppression d'une fonctionnalité importante. Sauf erreur de ma part je ne vois aucune spec sur la liste des RDVs ! Je me note d'en rédiger une. :wink:

2022-11-19 19:20 UTC, closed without merging

2022-11-19 20:13 UTC, yaf commented
Oui, tu as raison. Merci ! :bow: