fix(user): Add organisation selection for motif without lieu
betagouv/rdv-solidarites.fr pull request #3118
Opened 2022-11-22 13:48 UTC by aminedhobb

## Contexte

Cette PR fait suite à un retour du 64, qui nous a signalé que les créneaux ne s'affichaient pas pour lorsque l'on choisissait un motif téléphonique sur leur département.

![image](https://user-images.githubusercontent.com/7602809/203328311-e863c407-ab9b-4497-bf6b-71455e8f0fa4.png)

Ce qui se passe c'est que comme nous ne choisissons plus de lieu pour ce motif, les créneaux n'étaient calculée que pour une organisation du territoire (via le `SearchContext#selected_motif`, dont le nom était trompeur puisqu'il pouvait y avoir plusieurs motifs ayant le même nom sur plusieurs organisations).
Du coup je rajoute une étape de sélection de structure avec laquelle prendre RDV lorsque le motif n'est pas sur place.

## Améliorations possibles

- @victormours suggérait qu'on pourrait ouvrir la partie "Réservation en ligne" côté admin qui est pour l'instant réservé à "RDV-aide-numérique" à tout le monde. Ça aurait l'avantage de facilement pouvoir preview le parcours usager pour les agents. Est-ce que c'est qq chose qui intéresserait le médico social aussi @yaf ?

## Previews 📷 

![image](https://user-images.githubusercontent.com/7602809/203329913-cc9ceeff-2173-48bc-b3dc-72e2f7a72bf0.png)

![image](https://user-images.githubusercontent.com/7602809/203329972-dc7c5002-26b2-4231-a2e4-3c953297c69c.png)

2022-11-22 15:30 UTC, victormours requested changes

2022-11-22 15:30 UTC, victormours commented on app/services/search_context.rb
> +  end
je suis un peu inquiet du fait qu'on a trois types d'organisations possibles dans cette classe :
- celles qui viennent du paramètre fallback_organisation_ids
- celles qui viennent du paramètre organisation_id
- celles qui correspondent aux motifs filtrés

ça pourrait être bien d'avoir des noms un peu plus spécifiques pour ces différents cas (à l'image du nom `fallback_organisations`)

2022-11-22 15:30 UTC, victormours commented on app/views/search/_creneau_selection.html.slim
> +            = link_to path_to_organisation_selection(params), class: "d-block stretched-link" do
⚠️ attention : ça casse le parcours de réservation avec les liens directs : si un agent envoie un lien vers une organisation précise (comme c'est le cas pour les cnfs et dans le cadre de notre intégration avec la carte des cnfs), la condition ici fera que l'usager pourra changer l'organisation sélectionnée. C'est le même genre de sujet que ce qu'on avait discuté il y a 10 jours, et une autre raison de distinguer les sens des organisations dans le search context : on ne veut pas le même comportement entre une organisation sélectionnée par l'agent et une organisation sélectionnée par l'usager (ou le prescripteur)

2022-11-22 16:17 UTC, aminedhobb commented on app/views/search/_creneau_selection.html.slim
> +            = link_to path_to_organisation_selection(params), class: "d-block stretched-link" do
Oui c'est vrai bien vu 👍 , d'ailleurs la partie "Réservation en ligne" demanderait quelques réajustements si on l'ouvrait à tout le monde (elle ne prend pas en compte la notion d'adresse et donc de secteur).
J'ai l'impression qu'il commence à y avoir bcp de comportement spécifique en fonction d'où vient l'usager (parcours normal, invitation avec token, invitation avec lien direct).

2022-11-22 16:51 UTC, aminedhobb commented
Merci @victormours pour ta review et ta vigilance !
J'ai appliqué tes suggestions [ici](https://github.com/betagouv/rdv-solidarites.fr/pull/3118/commits/18b7487ceb8f5f3f61c2455f2458b81a476d0de8) pour apporter un peu plus de clarté sur les organisations qu'on manipule.

2022-11-22 20:14 UTC, yaf commented
Ce qui est étrange dans la partie « réservation en ligne » pour le médico-social, c'est qu'elle fait doublon avec ce que les agents ont l'habitude de faire depuis 2 ans...

Ce qui est intéressant dans cette page, c'est le fait de résumer des informations. J'envisage que ce soit une bonne première brique pour ce que nous avions envisagé fin avril 2021 : https://github.com/betagouv/rdv-solidarites.fr/issues/1403

Le lien serait intéressant dans le cadre d'une invitation particulière à l'usager.

Et il y a un autre problème de taille : l'unité de gestion dans le médico-social c'est le département (territoire) et non l'organisation.

2022-11-22 20:21 UTC, yaf approved these changes
Ça me semble bon. :+1: Merci.

Attention aussi, car le 64 est un cas très particulier dans le paysage du médico-social. Je me demande comment ce mécanisme va être accueilli dans les autres départements...

Disons que c'est de toute façon mieux que ce qu'il y avait jusqu'à présent (où l'on n'affichait finalement pas toutes les options). Mais je pense que nous allons devoir accélérer le fait de remonter la gestion des motifs dans le territoire pour éviter ce genre de chose. Ça sera plus simple d'avoir un seul motif pour tout le territoire (quitte à l'autoriser sur certaines organisations seulement).

2022-11-23 10:25 UTC, victormours approved these changes
👍 au top ! Merci pour le correctif

2022-11-23 10:59 UTC, merged