Permet aux agents de tester les liens de prise de rdv
betagouv/rdv-solidarites.fr pull request #3121
Opened 2022-11-23 13:23 UTC by victormours

Le but de cette PR est de permettre aux agents de tester le début de la prise de rdv côté usager, en évitant la redirection vers l'agenda s'ils cliquent sur leur liens de prise de rdv.
Ils ne pourront pas aller jusqu'à la fin de prise de rdv, puisque c'est bloqué par #949, mais ça permet déjà d'avoir un aperçu des motifs et créneaux disponibles.
C'est aussi une première étape pour faciliter la prise de rdv par agent prescripteur.

Par ailleurs, d'un point de vue technique, ça a plus de sens d'utiliser explicitement une route de prise de rdv comme adresse de redirection quand on est en train de faire de la prise de rdv

2022-11-23 14:17 UTC, francois-ferrandis requested changes

2022-11-23 14:17 UTC, francois-ferrandis commented on app/controllers/search_controller.rb
> +      redirect_to prendre_rdv_short_path(
Après inspection des routes, il faudrait plutôt utiliser `prendre_rdv_path`, car `prendre_rdv_short_path` fait une redirection vers cette dernière, tout en ayant une logique impliquant les tokens.

Pour dire ça autrement, `prendre_rdv_short_path` est un lien public avec des paramètres courts, qui redirige vers `prendre_rdv_path`, qui est la route interne qui correspond explicitement à la réservation de RDV.

2022-11-23 15:34 UTC, francois-ferrandis approved these changes
Ça faisait longtemps que j'avais envie de faire ça, merci ! :pray:

2022-11-23 20:19 UTC, yaf approved these changes
:+1: 

C'était le parcours de test... Et à la fusion, on n'a pas pensé à faire comme ça, mais ce n'est pas si mal :)

2022-11-24 15:12 UTC, francois-ferrandis commented on spec/features/agents/agent_can_test_online_booking_spec.rb
> +  it "shows the online booking forms, until" do
Until Devise comes in. :boom: :hand_over_mouth:

2022-11-24 15:17 UTC, merged