Permettre aux usagers de pouvoir annuler leur participation à un RDV.
betagouv/rdv-solidarites.fr pull request #3153
Opened 2022-12-07 11:31 UTC by Holist

Permettre aux usagers de pouvoir annuler leur participation à un RDV.
J'en ai profité pour améliorer le test concernant toute la partie usager/rdv_co

Closes #3002

2022-12-07 14:07 UTC, victormours commented on app/views/users/rdvs/_rdv.html.slim
> +  confirm_message: "Oui, annuler votre participation RDV", \
j'ai un petit doute sur la formulation : parfois on parle de désinscription, parfois on parle d'annuler la participation, ça serait peut-être bien d'unifier le vocabulaire pour gagner en clarté

2022-12-07 14:10 UTC, victormours commented on app/views/users/rdvs/_rdv.html.slim
> +  body_message: rdv.motif.cancellation_warning, \
je me demande s'il y a un problème avec la modale : dans mon navigateur ce message ne s'affiche pas

2022-12-07 16:54 UTC, Holist commented on app/views/users/rdvs/_rdv.html.slim
> +  body_message: rdv.motif.cancellation_warning, \
Bizarre, je viens d'essayer avec Chrome et Firefox et j'ai bien la modale qui s'affiche. Avec le message cancellation_warning si il est renseigné et la modale de confirmation d'annulation du rdv vide si ce n'est pas le cas.

2022-12-07 16:55 UTC, Holist commented on app/views/users/rdvs/_rdv.html.slim
> +  confirm_message: "Oui, annuler votre participation RDV", \
Je m'en occupe

2022-12-12 09:37 UTC, victormours requested changes
Désolé, je suis un peu tatillon sur le nommage dans l'interface et sur les tests, mais je suis dispo pour en parler de vive voix, et évenutellement pairer un peu :)

2022-12-12 09:37 UTC, victormours commented on app/controllers/users/participations_controller.rb
> +    flash[:notice] = "Participation à l'atelier confirmée" if existing_participation.status == "unknown"
Ici on introduit une nouvelle notion : celle d'atelier, est-ce qu'on est sûres de vouloir faire ça ? J'ai l'impression que c'est un synonyme de rendez-vous collectif, mais dans ce cas, autant garder le même nom partout (et pourquoi pas se dire qu'on lance un chantier sur renommer rdv collectif en ateliers, si ça correspond aux usages). Dans le doute, on peut soit garder "rendez-vous collectif", soit juste mettre `"Participation confirmée"
Comme quoi, le nommage, c'est toujours difficile ;) (et en fait le problème du nommage des variables, c'est juste un cas particulier du problème du nommage des notions dans une interface utilisateurs).

2022-12-12 09:37 UTC, victormours commented on spec/features/users/user_can_manage_collective_rdv_spec.rb
> +          if notif_type == "without_notif"
si on commence à avoir de la logique dans nos tests, c'est qu'ils sont trop compliqués : il faut les tests soient faciles à lire, quitte à avoir un peu de duplication. On pourrait extraire les interactions avec le formulaire dans des méthodes pour limiter la duplication, et écrire en toutes lettres les différents cas de test plutôt qu'avoir des boucles et des if.

2022-12-12 09:37 UTC, victormours commented on app/models/concerns/rdvs_user/status_changeable.rb
> +      @notifier = Notifiers::RdvCreated.new(rdv, author, user_to_notify)
est-ce que ce changement permet aussi de notifier l'agent ?

2022-12-12 09:37 UTC, victormours commented on app/models/rdv.rb
> +  MIN_DELAY_FOR_CANCEL = 4.hours
👍

2022-12-12 09:37 UTC, victormours commented on app/policies/user/rdvs_user_policy.rb
> +    rdvs_user_belongs_to_user_or_relatives? && record.cancellable_by_user?
👍

2022-12-12 09:37 UTC, victormours commented on app/views/users/rdvs/_rdv.html.slim
> +        = link_to "Annuler votre participation au RDV", "#", data: { toggle: "modal", target: "#js-cancel-participation-modal-#{rdv.id}" }, class: "btn btn-outline-danger"
un bon exemple d'incohérence dans l'interface : là on parle de participation au RDV et pas de participation à l'atelier ;)

2022-12-12 15:34 UTC, Holist commented on app/views/users/rdvs/_rdv.html.slim
> +  body_message: rdv.motif.cancellation_warning, \
On s'était mal compris et effectivement, on a un bug (que je fix dans mon prochain commit).
Une partie des motifs ont `custom_cancel_warning_message` à nil et d'autres une string vide.
L'affichache est conditionné sur nil uniquement, je remplace par la méhode .presence qui va aussi tester les strings vide pour afficher le message par défaut.

2022-12-12 15:35 UTC, Holist commented on spec/features/users/user_can_manage_collective_rdv_spec.rb
> +          if notif_type == "without_notif"
Merci, je simplifie.

2022-12-12 17:26 UTC, victormours commented on app/models/motif.rb
> +    custom_cancel_warning_message.presence || Motif.human_attribute_name("default_cancel_warning_message")
🎉

2022-12-13 13:51 UTC, victormours reviewed
une dernière bricole pour éviter une régression, et promis après c'est bon

2022-12-13 13:53 UTC, victormours commented on app/views/users/rdvs/_rdv.html.slim
> +  - unless policy([:user, rdv]).cancel? || policy([:user, current_user.participation_for(rdv)]).cancel? || rdv.cancelled? || current_user.participation_for(rdv).cancelled?
Ou sinon on se fatigue pas et on met juste ça comme ça : 
```suggestion
  - unless policy([:user, rdv]).cancel? || policy([:user, current_user.participation_for(rdv)]).cancel? || rdv.cancelled? || current_user.participation_for(rdv).cancelled?  || rdv.in_the_past?
```

2022-12-13 14:05 UTC, Holist commented on app/views/users/rdvs/_rdv.html.slim
> +  - unless policy([:user, rdv]).cancel? || policy([:user, current_user.participation_for(rdv)]).cancel? || rdv.cancelled? || current_user.participation_for(rdv).cancelled?
Je dois justement prendre un petit moment pour travailler sur les droits Autorisation + Logique métier pour le point tech de jeudi. Je te propose de rajouter le || rdv.in_the_past? au "gros" (c'est le cas de le dire) unless et je vais regarder comment améliorer ca pour le point tech de jeudi.

2022-12-13 14:30 UTC, victormours commented on app/views/users/rdvs/_rdv.html.slim
> +  - unless policy([:user, rdv]).cancel? || policy([:user, current_user.participation_for(rdv)]).cancel? || rdv.cancelled? || current_user.participation_for(rdv).cancelled?
yes, c'est nickel

2022-12-13 14:31 UTC, victormours approved these changes
YEAAAAAH 🚀

2022-12-13 15:21 UTC, merged