2605 visibilite des usagers
betagouv/rdv-solidarites.fr pull request #3228
Opened 2023-01-02 19:53 UTC by yaf

Pour tester : <`mettre ici l'url de la review app une fois déployé`>

Décrire le pourquoi des modifications

Closes #issue_number

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2023-02-01 14:18 UTC, francois-ferrandis reviewed
Une PR potentiellement révolutionnaire ! :exploding_head: 

Quelques questions et remarques, mais surtout je me pose une question : est-ce que c'est OK si les agents de RDV Insertion se mettent à pouvoir accéder à tous les usagers du médico-social ? Ou alors j'ai pas bien compris et ça reste scopé par service d'une façon qui m'échappe ?

2023-02-01 14:18 UTC, francois-ferrandis commented on app/policies/agent/user_policy.rb
> +        end
Ça signifie que tous les agents du territoire peuvent aussi modifier, supprimer et inviter un usager, est-ce le comportement attendu ?

2023-02-01 14:18 UTC, francois-ferrandis commented on app/views/admin/users/index.html.slim
> +          = render partial: "admin/users/user", collection: @users.includes(:responsible).uniq, cached: ->(user) { [user, current_organisation] }
Pourquoi ne pas plutôt mettre un `.distinct` dans le contrôleur ? Ça me semble plus lisible de regrouper toutes les opérations de requête au même endroit, et surtout, les counts seront corrects et cohérents.

2023-02-01 14:18 UTC, francois-ferrandis commented on db/schema.rb
> +    t.boolean "visible_users_throughout_the_territory", default: false
Il manque une mise à jour de l'ID dans l'en-tête de ce fichier, non ? :upside_down_face:

2023-02-01 16:37 UTC, yaf commented
Nous arrivons peut-être à une limite où effectivement, il faudrait avoir une « instance » séparé pour RDV-I... Mais  peut-être que ça poserait un problème dans certains départements (je pense au 64) ?

En tout cas, c'est indispensable pour les départements aujourd'hui. Et je pense que les usagers RSA (RDV-i) sont des usagers des services sociaux, donc c'est ok. Enfin, je crois.

2023-02-01 16:38 UTC, yaf commented on app/policies/agent/user_policy.rb
> +        end
oui

2023-02-01 16:38 UTC, yaf commented on app/views/admin/users/index.html.slim
> +          = render partial: "admin/users/user", collection: @users.includes(:responsible).uniq, cached: ->(user) { [user, current_organisation] }
Oui, effectivement

2023-02-01 16:38 UTC, yaf commented on db/schema.rb
> +    t.boolean "visible_users_throughout_the_territory", default: false
ah oui.

2023-02-01 16:38 UTC, yaf commented on app/views/admin/users/search.json.jbuilder
> +json.results @users.uniq do |user|
:+1:

2023-02-02 10:03 UTC, francois-ferrandis requested changes
Je passe en "Request changes" pour que depuis le tableau on n'ai plus inscrit "Review required". :wink:

2023-02-02 11:38 UTC, yaf commented on app/views/admin/users/index.html.slim
> +          = render partial: "admin/users/user", collection: @users.includes(:responsible).uniq, cached: ->(user) { [user, current_organisation] }
Le `.distinct` dans le contrôleur pose un problème.

```
PG::InvalidColumnReference: ERREUR:  pour SELECT DISTINCT, ORDER BY, les expressions doivent apparaître dans la
liste SELECT
```
J'ai dû rater un truc quelque part.

2023-02-02 11:42 UTC, yaf commented on app/views/admin/users/index.html.slim
> +          = render partial: "admin/users/user", collection: @users.includes(:responsible).uniq, cached: ->(user) { [user, current_organisation] }
```SQL
SELECT DISTINCT "users".* FROM "users" INNER JOIN "user_profiles" ON "user_profiles"."user_id" = "users"."id" INNER JOIN "organisations" ON "organisations"."id" = "user_profiles"."organisation_id" INNER JOIN (SELECT "users"."id" AS pg_search_id, (ts_rank((setweight(to_tsvector('simple', unaccent(coalesce("users"."last_name"::text, ''))), 'A') || setweight(to_tsvector('simple', unaccent(coalesce("users"."first_name"::text, ''))), 'B') || setweight(to_tsvector('simple', unaccent(coalesce("users"."birth_name"::text, ''))), 'C') || setweight(to_tsvector('simple', unaccent(coalesce("users"."email"::text, ''))), 'D') || setweight(to_tsvector('simple', unaccent(coalesce("users"."phone_number_formatted"::text, ''))), 'D') || setweight(to_tsvector('simple', unaccent(coalesce("users"."id"::text, ''))), 'D')), (to_tsquery('simple', ''' ' || unaccent('lea') || ' ''' || ':*')), 0)) AS rank FROM "users" WHERE ((setweight(to_tsvector('simple', unaccent(coalesce("users"."last_name"::text, ''))), 'A') || setweight(to_tsvector('simple', unaccent(coalesce("users"."first_name"::text, ''))), 'B') || setweight(to_tsvector('simple', unaccent(coalesce("users"."birth_name"::text, ''))), 'C') || setweight(to_tsvector('simple', unaccent(coalesce("users"."email"::text, ''))), 'D') || setweight(to_tsvector('simple', unaccent(coalesce("users"."phone_number_formatted"::text, ''))), 'D') || setweight(to_tsvector('simple', unaccent(coalesce("users"."id"::text, ''))), 'D')) @@ (to_tsquery('simple', ''' ' || unaccent('lea') || ' ''' || ':*')))) AS pg_search_7dfb4cf67742cb0660305e ON "users"."id" = pg_search_7dfb4cf67742cb0660305e.pg_search_id WHERE "users"."deleted_at" IS NULL AND "organisations"."id" IN (4, 31) ORDER BY pg_search_7dfb4cf67742cb0660305e.rank DESC, users.updated_at desc, LOWER(last_name) LIMIT 25 OFFSET 0
```

Je veux bien regarder avec toi à l'occasion.

2023-02-02 14:59 UTC, francois-ferrandis requested changes

2023-02-02 14:59 UTC, francois-ferrandis commented on app/views/admin/territories/agents/edit.html.slim
> +          = label_tag :fake, "Administrateur du territoire"
Est-ce que tu as changé d'avis sur notre discussion ici ? https://github.com/betagouv/rdv-solidarites.fr/pull/3223#discussion_r1068256679

Ou alors c'est un bout de code obsolète qui s'est glissé dans cette PR ?

2023-02-02 14:59 UTC, francois-ferrandis commented on app/views/admin/users/index.html.slim
> +          = render partial: "admin/users/user", collection: @users.includes(:responsible).uniq, cached: ->(user) { [user, current_organisation] }
En effet, on rencontre ce problème : https://github.com/Casecommons/pg_search/issues/238

Le `uniq` est un solution qui casse parfois le décompte, mais ça paraît acceptable !

2023-02-02 14:59 UTC, francois-ferrandis commented on app/views/admin/territories/agents/edit.html.slim
> +          url = admin_territory_agent_territorial_role_path(current_territory, element)
J'ai l'erreur `undefined method `admin_territory_agent_territorial_role_path'` en chargeant la page du formulaire, est-ce qu'on se rajouterait pas une petite feature spec pour vérifier que cette page n'est pas cassée ?

2023-02-02 15:51 UTC, yaf commented on app/views/admin/territories/agents/edit.html.slim
> +          = label_tag :fake, "Administrateur du territoire"
Non, c'est une boulette de manip de rebase / merge. Merci !

2023-02-02 15:59 UTC, francois-ferrandis approved these changes
C'est bon pour moi !

Je reste méfiant sur la conséquence en termes de cloisonnement des données, est-ce que les référentes sont conscientes que les gens du RSA auront accès aux usagers médico-social ? :grimacing:

2023-02-03 21:53 UTC, merged