Clarifie 3 attributs de motif
betagouv/rdv-solidarites.fr pull request #3315
Opened 2023-02-06 10:30 UTC by yaf

Pour tester : <`mettre ici l'url de la review app une fois déployé`>

Décrire le pourquoi des modifications

Closes #issue_number

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2023-02-06 14:38 UTC, francois-ferrandis requested changes
Très bonne initiative que ce renommage ! 

J'ai juste un blocage sur les `schema.rb` sinon c'est bon pour moi. :ok_hand:

2023-02-06 14:38 UTC, francois-ferrandis commented on db/schema.rb
> +  enable_extension "pg_stat_statements"
Cette ligne, ainsi que les `precision: nil` semblent indiquer que tu as lancé le `db:migrate` sur une copie de la base démo ou prod. 

Est-ce que ces changements (sans rapport avec cette PR) disparaissent si tu fais ça ?

```bash
bundle exec rails db:drop db:setup
bundle exec rails db:migrate
```

2023-02-07 08:30 UTC, yaf commented on db/schema.rb
> +  enable_extension "pg_stat_statements"
Alors non, ça ne change rien, mais je vais faire en sorte de nettoyer

2023-02-07 08:49 UTC, francois-ferrandis requested changes

2023-02-07 08:49 UTC, francois-ferrandis commented on db/schema.rb
> +    t.integer "max_public_booking_delay", default: 7889238
Il manque encore l'en-tête avec l'ID de la migration. :grimacing:

2023-02-07 10:29 UTC, yaf commented on db/schema.rb
> +    t.integer "max_public_booking_delay", default: 7889238
Voilà qui devrait être bon

2023-02-07 10:30 UTC, francois-ferrandis approved these changes
Merci ! :rocket:

2023-02-07 12:28 UTC, merged