Ajout d'un secret partagé pour authentifié un agent inclusion connecté dans l'API
betagouv/rdv-solidarites.fr pull request #3365
Opened 2023-02-21 11:54 UTC by Holist

Closes #3364

2023-02-21 16:23 UTC, francois-ferrandis requested changes
Ça me semble très bien dans les grandes lignes, mais j'ai plein d'idées sur la forme, on peut en parler quand tu veux ! :call_me_hand:

2023-02-21 16:23 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    return false if request.headers["shared-secret-for-agents-auth"].nil?
J'ai du mal à savoir ce qu'il se passe lorsque l'on passe ce header avec une valeur vide. Je suggère que le critère soir la la présence du header, même vide, c'est à dire que si on passe le header vide, c'est comme passer un mauvais mot de passe.

Le critère deviendrait alors :

```suggestion
    return false if request.headers.include?("shared-secret-for-agents-auth")
```

2023-02-21 16:23 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +  before_action :authenticate_agent_with_shared_secret, if: :shared_secret_is_valid?
En faisant ainsi, la méthode `shared_secret_is_valid?` est appelée 2 fois, et donc potentiellement on envoie une notif 2 fois à Sentry.

Pour plus de lisibilité, je voyais plutôt un `before_action` généraliste

```ruby
before_action :authenticate_agent
```

Avec en dessous une méthode qui explicite bien la condition sur laquelle on active l'un ou l'autre des mécanisme : 

```ruby
  def authenticate_agent
    if request.headers.include?("shared-secret-for-agents-auth")
      authenticate_agent_with_shared_secret
    else
      # Use DeviseTokenAuth
      authenticate_api_v1_agent_with_token_auth!
    end
  end
```

Et ainsi on pourrait remettre la vérification du secret à l'intérieur de la méthode `authenticate_agent_with_shared_secret`, là où l'on s'attend à la trouver. :wink:

2023-02-21 16:23 UTC, francois-ferrandis commented on spec/requests/api_authentication_spec.rb
> +  let!(:absence2) { create(:absence, agent: agent, organisation: organisation2) }
J'ai peut-être manqué quelque-chose, mais ces ajouts semblent distraire du sujet du test (l'auth). 

Je suppose que c'était un moyen détourné de vérifier que c'est le bon agent qui est authentifié, mais si c'est l'intention, je pense qu'on peut définir un test particulier qui crée plusieurs agents et qui vérifier que c'est bien celui dont on passe l'email qui est considéré. Mais bon, c'est seulement si t'as envie, à mon sens y'a peu de risque qu'on se goure d'agent (quoique, dit comme ça, ça fait peur).

2023-02-21 16:23 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    @current_agent = Agent.find_by(email: request.headers["uid"])
C'est pas vraiment le sujet, mais sais-tu pourquoi on garder une colonne `agents.uid` en base ? J'ai l'impression qu'elle pourrait nous causer des soucis. J'ai l'impression qu'à travers l'appli on essaye juste de faire en sorte que cette colonne ait la même valeur que `email`, mais quel est l'intérêt ? :thinking:

2023-02-22 10:41 UTC, Holist commented on spec/requests/api_authentication_spec.rb
> +  let!(:absence2) { create(:absence, agent: agent, organisation: organisation2) }
Tu as raison, c'était une facon de m'assurer que l'agent en question n'avait pas accés à plus de choses.

2023-02-22 10:44 UTC, Holist commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    @current_agent = Agent.find_by(email: request.headers["uid"])
C'est une trés bonne question. Je n'avais même pas fait attention à ce champ en base. 
Je vais creuser la question (l'enlever et voir ce qu'il se passe) dans une autre pr, je note.

2023-02-22 10:49 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    @current_agent = Agent.find_by(email: request.headers["uid"])
Ah ben j'en demandais pas tant, c'était juste une curiosité, mais si tu peux faire ça c'est top ! :pray:

2023-02-22 10:53 UTC, Holist commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +      Digest::SHA256.hexdigest(request.headers["shared-secret-for-agents-auth"]),
Je note :)

2023-02-22 11:14 UTC, francois-ferrandis approved these changes
Nickel ~~chrome~~ firefox ! :ok_hand: 

Blague à part, c'est bon pour partir en prod. :rocket:

2023-02-22 11:14 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    if request.headers.include?("shared-secret-for-agents-auth")
On pourrait extraire ça dans une constante, mais c'est une question de goût, et je suis partagé ! :smile:

2023-02-22 11:14 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +    end
Tip top ! :ok_hand:

2023-02-22 13:23 UTC, merged

2023-02-22 13:38 UTC, aminedhobb reviewed
Merci @Holist pour cette PR, l'implémentation est top 👍 !

J'ai deux questions/suggestions qui me viennent à l'esprit en lisant le code, j'aimerais bien avoir ton avis dessus: 

* Est-ce qu'au lieu d'envoyer juste le shared secret dans les headers, on enverrait pas une signature qui serait un digest que l'on génère à l'aide du prénom, nom et email de l'agent et d'une clé secrète partagée (comme ce que l'on fait pour les webhooks par ailleurs) ? Ça ajouterait un tout petit peu plus de sécurité puisqu'il faudrait avoir ces informations également. Dans ce cas on pourrait garder un nom de header iso à celui de RDV-S, du style `X-RDVI-Signature`.
*  C'est pas directement lié à cette PR mais je me pose la question: au vu de la sensibilité de cette clé je me demande si ça vaudrait le coup de l'encrypter à l'aide des Rails credentials sur RDV-I ? Il me semble qu'on en avait abordé le sujet en réu tech mais c'était par rapport à outlook, on pourra en reparler à la prochaine :). J'ai l'impression qu'[il y a débat](https://mattermost.incubateur.net/betagouv/pl/ka19gx1yyffo8x4tu1uk7gx7sy) sur le sujet.

2023-02-22 14:13 UTC, Holist commented
> Merci @Holist pour cette PR, l'implémentation est top 👍 !
> 
> J'ai deux questions/suggestions qui me viennent à l'esprit en lisant le code, j'aimerais bien avoir ton avis dessus:
> 
> * Est-ce qu'au lieu d'envoyer juste le shared secret dans les headers, on enverrait pas une signature qui serait un digest que l'on génère à l'aide du prénom, nom et email de l'agent et d'une clé secrète partagée (comme ce que l'on fait pour les webhooks par ailleurs) ? Ça ajouterait un tout petit peu plus de sécurité puisqu'il faudrait avoir ces informations également. Dans ce cas on pourrait garder un nom de header iso à celui de RDV-S, du style `X-RDVI-Signature`.
> * C'est pas directement lié à cette PR mais je me pose la question: au vu de la sensibilité de cette clé je me demande si ça vaudrait le coup de l'encrypter à l'aide des Rails credentials sur RDV-I ? Il me semble qu'on en avait abordé le sujet en réu tech mais c'était par rapport à outlook, on pourra en reparler à la prochaine :). J'ai l'impression qu'[il y a débat](https://mattermost.incubateur.net/betagouv/pl/ka19gx1yyffo8x4tu1uk7gx7sy) sur le sujet.

Pour le premier point tu as tout à fait raison et je vais faire une PR pour mettre ça en place. 
Pour le second point c'est effectivement en discussion, il y a des avantages et inconvénients dans les 2 cas. A priori on avait mis ça en standby en statuant que l'on continuait à utiliser les variables d'environnement.