[Espace Agent] Corriger l'affichage des statuts de participations d'un usager
betagouv/rdv-solidarites.fr pull request #3550
Opened 2023-05-19 14:59 UTC by ousmanedev

# [Espace Agent] Corriger l'affichage des statuts de participations d'un usager

Fixes #3549

2023-05-19 15:13 UTC, victormours requested changes

2023-05-22 08:27 UTC, francois-ferrandis commented on spec/features/agents/agent_can_see_users_rdv_spec.rb
> +
Je suis d'accord avec toi ici : non seulement les perfs sont meilleures quand on met les `expect` dans le même `it`, mais c'est aussi bien plus lisible !

2023-05-22 10:07 UTC, francois-ferrandis commented on spec/features/agents/agent_can_see_users_rdv_spec.rb
> +        expect(page).to have_content("Non excusé\n1 ")
Et non seulement les perfs sont meilleures quand on met les `expect` dans le même `it`, mais ici ça rend aussi la spec bien plus lisible (moins de "boilerplate"). :ok_hand:

2023-05-22 10:10 UTC, victormours approved these changes
👍 nickel !

2023-05-22 10:14 UTC, merged

2023-05-22 10:33 UTC, francois-ferrandis commented on app/views/admin/users/show.html.slim
> +                count: @rdvs_users.joins(:rdv).status(temporal_status).count,
Nous faisons beaucoup de requêtes en base sur cette page, mais je suis d'avis qu'il serait prématuré de l'optimiser car ça nous coûterait en complexité.

Et donc juste pour info, je partage ici l'analyse de Skylight sur cette page : https://www.skylight.io/app/applications/RgR7i58P67xN/recent/6h/endpoints/Admin::UsersController%23show?responseType=html