Changement de wording pour les invitations
betagouv/rdv-solidarites.fr pull request #3695
Opened 2023-07-26 16:41 UTC by qblanc

Dans cette PR, je change légerement le wording de la landing page des invitations. La raison : certaines invitations sont désormais parfois envoyées par des associations non liées aux départements  (d'où les changements des lignes 7-11). J'en profite pour changer un peu le wording de la ligne 2, ce qui permet de gagner beaucoup d'espace (ce qui n'est pas négligeable sur mobile) + enlève le `(e)` (cf screenshots : avant/après)

![Capture d'écran landing invitation](https://github.com/betagouv/rdv-solidarites.fr/assets/46218316/500b9a14-8533-4332-b19b-e7e4d022bdbf)
![Screenshot 2023-07-26 at 18-27-16 RDV Solidarités](https://github.com/betagouv/rdv-solidarites.fr/assets/46218316/35191c78-04c1-464a-9fe9-dc0fcc8a62f7)

2023-07-26 16:51 UTC, qblanc commented
PI, nous avons eu le même problème pour les features tests, nous l'avons résolu via [cette PR](https://github.com/betagouv/rdv-insertion/pull/1229)

2023-07-27 12:44 UTC, victormours requested changes

2023-07-27 12:44 UTC, victormours commented on app/views/search/banners/_rdv_solidarites.html.slim
> +  | J'organise mon rendez-vous
On essaye de faire plus attention au design, et d'avoir un ton (ou "tone and voice" comme disent les design system anglophones) cohérent à travers l'appli. Ça veut dire que le changement de la deuxième à la première personne n'est pas anodin, et surtout on n'a pas du tout envie de se lancer là dedans.

Les actions faites par l'utilisateur sont soit à la deuxième personne quand on lui donne des consignes ("Choisissez un créneau"), soit à l'infinitif quand c'est des boutons qui proposent des actions ("Enregistrer").
Ici, si c'est le fait que c'est pas forcément le département qui envoie l'invitation, on pourrait tout simplement enlever l'info qui n'est plus pertinente : 
```suggestion
  | Vous avez été invité·e à prendre rendez-vous
```
(et c'est vrai que les parenthèses c'est moche, un point médian c'est un peu plus joli)

2023-07-27 13:06 UTC, aminedhobb reviewed
J'ai une préférence aussi pour la formulation "Vous avez été invité·e à prendre rendez-vous".
C'est pas ce qu'on s'était dit au daily ?

2023-07-27 13:39 UTC, qblanc commented
> (et c'est vrai que les parenthèses c'est moche, un point médian c'est un peu plus joli)

c'est plus joli et c'est plus inclusif, mais c'est aussi pas très bien accepté par un certain nombre d'administrations :-/

>  C'est pas ce qu'on s'était dit au daily ?

si si tout à fait, on avait convenu d'enlever la ref au département. Mais cela fait long et il y a cette question d'écriture inclusive. C'est pour ça que j'ai essayé de trouver quelque chose de plus compact et qui soit inclusif sans parenthèse ni point médian. En gardant le "tone and voice" de rdvs, on pourrait mettre par exemple `Organisez votre rendez-vous` ou `Vous avez reçu une invitation`. Promis si ces options ne vous conviennent pas j'arrête de vous embêter :)

2023-07-27 15:33 UTC, qblanc commented
Après discussion avec @aminedhobb, on a pas vraiment besoin du wording alternatif, donc on l'enlève carrément, ce qui est encore plus simple. Seul l'affichage du département devient conditionnel. Désolé pour le bruit autour de ce changement minime 🙏

2023-08-02 09:50 UTC, qblanc commented
up

2023-08-30 14:57 UTC, merged