Add 2 more workers for good_job
betagouv/rdv-solidarites.fr pull request #3820
Opened 2023-10-03 07:28 UTC by ousmanedev

Closes https://github.com/betagouv/rdv-solidarites.fr/issues/3805

## ℹ️ Contexte 
[Post mortem du 19 Septembre 2023](https://pad.numerique.gouv.fr/geQFlfO8R-KfZbYYmHGjMA?view)

Pour améliorer la résilience de notre infrastructure de jobs, nous avons jugé bon d'augmenter les workers au sein du Procfile, afin de mieux isoler nos différents jobs.

# Checklist

Avant la revue :
- [X] Nettoyer les commits pour faciliter la relecture
- [X] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2023-10-10 09:28 UTC, victormours requested changes

2023-10-10 09:28 UTC, victormours commented on Procfile.dev
> +jobs_3: bundle exec good_job start
Il faut que les différents processus consomment des queues différentes, sinon on n'a rien changé par rapport au fonctionnement existant forke qui plusieurs workers

2023-11-20 11:33 UTC, francois-ferrandis commented
L'auteur de `good_job` fournit ici des infos intéressantes sur l'usage des queues et des priorités : 

https://github.com/bensheldon/good_job/discussions/1091#discussioncomment-7135207

2023-11-22 08:54 UTC, ousmanedev commented
> L'auteur de `good_job` fournit ici des infos intéressantes sur l'usage des queues et des priorités :
> 
> [bensheldon/good_job#1091 (reply in thread)](https://github.com/bensheldon/good_job/discussions/1091#discussioncomment-7135207)

Merci @francois-ferrandis 
Je reprends le sujet, cette semaine.

2024-03-12 15:47 UTC, francois-ferrandis commented
J'ai l'impression qu'on a pas eu de nouveaux problèmes de congestion des queues. Il y a deux semaines j'ai enqueue quelques milliers de jobs, j'ai alors scalé à 4 containers de jobs pour que ça dépile à fond (très satisfaisant à regarder).

Bref, je pense qu'on peut fermer cette PR pour le moent.

2024-03-12 16:09 UTC, closed without merging