MotifPolicy indépendante du contexte
betagouv/rdv-solidarites.fr pull request #3898
Opened 2023-11-28 10:45 UTC by victormours

Suite aux discussions en point tech, le but de cette PR est de proposer une gestion des autorisations indépendante du contexte de navigation, et de clarifier les usages des Policy.

Cette PR est une première version de refactoring de la `Agent::MotifPolicy`. A la base j'espérais pouvoir faire ce refacto sur la `Agent::UserPolicy`, mais les règles métiers sur la visibilité des usagers sont malheureusement trop complexes pour faire ça (notamment le fait que la config de territoire détermine si on voit les agents de tout le territoire ou seulement de l'organisation courante).

Ce refacto amène plusieurs petites améliorations

### Suppression de `current_organisation` dans les policy

La nouvelle policy n'utilise plus la notion de `current_organisation`, et ce filtre est remplacé par des simples `.where(organisation: current_organisation)` là où c'est nécessaire. Il y a des endroits où c'était déjà fait par `.available_motifs_for_organisation_and_agent(current_organisation, current_agent)`.
Il y a une petite distinction métier entre ces deux scopes qui pourrait faire l'objet d'une petite pr de correctif plus tard, mais le but de la PR actuelle est de faire un refacto sans changement de comportement.

### Usage explicite de la classe plutôt que du helper `policy`

Là où c'est possible, on utilise explicitement le nom de la classe `Agent::MotifPolicy` plutôt que le helper `policy` qui fait de la métaprogrammation maligne pour trouver la bonne classe.

2023-11-28 17:56 UTC, victormours commented on app/views/admin/motifs/_visibility.html.slim
> +  span.mr-1= t(".default_html", motif: link_to(motif.name, admin_organisation_motif_path(current_organisation, motif), target: "_blank"))
il y a un tout petit changement de comportement ici : pour simplifier l'appli, on met toujours un lien vers les détails du motif (c'est à la dernière étape du wizard de prise de rdv pour agent, au moment d'expliquer les notifications).
Petite amélioration d'interface, pour éviter de perdre toutes les données du rdv à la dernière étape on ouvre ça dans un nouvel onglet (même si c'est possible de récupérer les données en navigant vers la page précédente, c'est pas forcément quelque chose que les agents savent).

2023-11-29 10:46 UTC, francois-ferrandis requested changes
Excellente démarche, je pense qu'on pourrait aller faire le travail sur les autres policies dans une PR dans les jours qui viennent, pour ne pas rester en état transitionnel trop longtemps.

J'ai un seul commentaire bloquant (régression), sinon c'est des questions ou suggestions. :wink:

2023-11-29 10:46 UTC, francois-ferrandis commented on app/policies/agent/motif_policy.rb
> +          .or(scope.where(organisation_id: current_agent.roles.where(access_level: :admin).pluck("organisation_id")))
Petit détail de cohérence : on passe plutôt un symbole à `ActiveRecord::Relation#pluck`. On peut observer à travers l'application que les usages de `pluck` avec une string sont des usages de [`Enumerable#pluck`](https://apidock.com/rails/Enumerable/pluck) (sur un `Hash` qui a des clés en string).

2023-11-29 10:46 UTC, francois-ferrandis commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +      @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).where(organisation: current_organisation).active.ordered_by_name
Si j'ai bien compris, idéalement on aimerait utiliser `policy_scope(Motif, policy_scope_class: Agent::MotifPolicy::Scope)` ici (notamment pour passer `@_pundit_policy_scoped` à `true`), mais on ne peut pas parce qu'il faudrait que tous les contrôleurs qui appellent `policy_scope(Motif, ...)` définissent un `pundit_user` de type `Agent`, ce qui est empêché par l'usage de `current_organisation` dans d'autres policies, c'est ça ?

On assume donc qu'on va être contraint d'utiliser cette notation transitionnelle jusqu'à ce qu'on vire `current_organisation` de toutes les policies utilisées dans ce contrôleur ? Pour info je pense qu'on peut très rapidement faire en sorte de toujours appeler `policy_scope` et d'avoir des `.apply` exceptionnels pour les policies qui ont besoin d'une `current_organisation`.

2023-11-29 10:46 UTC, francois-ferrandis commented on app/controllers/admin/motifs_controller.rb
> +    @motif_policy = Agent::MotifPolicy.new(current_agent, Motif.new(organisation: current_organisation))
J'allais dire qu'on aurait pu utiliser `@motifs.first` mais en fait parfois y'a pas de motif et on veut pouvoir en créer... donc très bien !

2023-11-29 10:46 UTC, francois-ferrandis commented on app/controllers/admin/motifs_controller.rb
> +    @motif = Agent::MotifPolicy::Scope.apply(current_agent, Motif)
Une raison de ne pas utiliser `policy_scope` ici ?

2023-11-29 10:46 UTC, francois-ferrandis commented on app/controllers/admin/organisations/online_bookings_controller.rb
> +    @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif)
Une raison de ne pas utiliser `policy_scope` ici ?

2023-11-29 10:46 UTC, francois-ferrandis commented on app/controllers/admin/rdv_wizard_steps_controller.rb
> +    @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).available_motifs_for_organisation_and_agent(current_organisation, @agent)
Une raison de ne pas utiliser `policy_scope` ici ?

2023-11-29 10:46 UTC, francois-ferrandis commented on app/views/admin/motifs/_visibility.html.slim
> +  span.mr-1= t(".default_html", motif: link_to(motif.name, admin_organisation_motif_path(current_organisation, motif), target: "_blank"))
Bien vu !

2023-11-29 10:46 UTC, francois-ferrandis commented on app/policies/agent/motif_policy.rb
> +    admin_of_the_motif_organisation? || @record.service.in?(current_agent.services)
Attention, il y a un régression : en tant qu'agent non-admin mais secrétaire, je dois pouvoir voir un motif peu importe son service.

2023-11-29 11:17 UTC, francois-ferrandis commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +  def policy_scope(scope, policy_scope_class: nil)
Je suis en train de me dire qu'un jour on pourra passer à 

```ruby
def policy_scope(policy_scope_class)
```

C'est pas du standard Pundit mais on s'en fiche bien.

2023-11-29 12:59 UTC, victormours commented on app/policies/agent/motif_policy.rb
> +          .or(scope.where(organisation_id: current_agent.roles.where(access_level: :admin).pluck("organisation_id")))
bien vu ! c'est corrigé

2023-11-29 14:01 UTC, victormours commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +      @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).where(organisation: current_organisation).active.ordered_by_name
tout à fait ! Je suis hésitant à passer toutes les policy au nouveau fonctionnement dans cette pr (sauf quelques exceptions), ça me semble assez gros et casse-gueule, et je préfèrerais le faire policy par policy.

2023-11-29 14:02 UTC, victormours commented on app/controllers/admin/motifs_controller.rb
> +    @motif = Agent::MotifPolicy::Scope.apply(current_agent, Motif)
non, c'était un oubli, c'est corrigé. Merci de l'avoir repéré !

2023-11-29 14:03 UTC, victormours commented on app/controllers/admin/organisations/online_bookings_controller.rb
> +    @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif)
Oui, ce controller utilise un `pundit_user` de type contexte pour la policy sur les organisations

2023-11-29 14:34 UTC, victormours commented on app/controllers/admin/rdv_wizard_steps_controller.rb
> +    @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).available_motifs_for_organisation_and_agent(current_organisation, @agent)
idem, ce controller utilise un pundit_user de type contexte pour la policy sur les rdvs

2023-11-29 14:38 UTC, victormours commented on app/controllers/api/v1/agent_auth_base_controller.rb
> +  def policy_scope(scope, policy_scope_class: nil)
oh, oui ça pourrait être intéressant

2023-11-29 14:38 UTC, victormours commented on app/policies/agent/motif_policy.rb
> +    admin_of_the_motif_organisation? || @record.service.in?(current_agent.services)
whoops, bien vu. C'est corrigé !

2023-11-29 16:17 UTC, francois-ferrandis commented on app/controllers/admin/creneaux/agent_searches_controller.rb
> +      @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).where(organisation: current_organisation).active.ordered_by_name
> policy par policy

Le problème c'est qu'on ne peut pas faire policy par policy parce que certains contrôleurs utilisent plusieurs policies, et on ne peut pas non plus faire contrôleur par contrôleur parce que plusieurs contrôleurs utilisent une même policy. Bref, je suis chaud que la prochaine PR fasse tout d'un coup, à l'exception des policies chiantes qui garderont le `#apply`. :ok_hand:

2023-11-29 16:19 UTC, francois-ferrandis commented on app/controllers/admin/rdv_wizard_steps_controller.rb
> +    @motifs = Agent::MotifPolicy::Scope.apply(current_agent, Motif).available_motifs_for_organisation_and_agent(current_organisation, @agent)
La `Agent::RdvPolicy` n'utilise pas `current_organisation` donc on pourrait lui passer un objet `Agent` en contexte, mais on retombe sur le souci des dépendances en cascades mentionné ici : 

https://github.com/betagouv/rdv-service-public/pull/3898/files#r1409534682

Vivement la prochaine PR !

2023-11-29 16:21 UTC, francois-ferrandis commented on app/policies/agent/motif_policy.rb
> +    current_agent.secretaire? || admin_of_the_motif_organisation? || @record.service.in?(current_agent.services)
Je suis content de voir les helpers génériques `admin_and_same_org? || same_agent_or_has_access?` disparaître car je les trouvais trop abstraits pour comprendre les droits au sens large. Peut-être qu'en les virant on verra d'autres abstractions émerger et que re-factorisera. :wink:

2023-11-29 16:27 UTC, francois-ferrandis approved these changes
Dans un monde parfait on prendrait 30 minutes pour créer une spec de policy sur les motifs, en s'inspirant des specs de policy existantes (j'arrive pas à savoir si je les aime ou pas). Ça me va de merger comme ça, mais je me dis qu'une spec aurait empêché la régression dans le cas des secrétaires. :wink:

2023-11-30 16:59 UTC, victormours commented
> Dans un monde parfait on prendrait 30 minutes pour créer une spec de policy sur les motifs, en s'inspirant des specs de policy existantes (j'arrive pas à savoir si je les aime ou pas). Ça me va de merger comme ça, mais je me dis qu'une spec aurait empêché la régression dans le cas des secrétaires. 😉

Tu as raison une fois de plus. J'ai ajouté la spec... et ça m'a permis de voir un autre bug 😬

2023-12-04 09:14 UTC, merged