[API] Ajout d'endpoints pour créer plusieurs référents ou user_profiles en une seule requête
betagouv/rdv-solidarites.fr pull request #3899
Opened 2023-11-28 11:49 UTC by qblanc

Dans cette PR, je crée deux endpoints `create_many` pour les `ReferentAssignation` et les `UserProfile` afin de permettre la création de records multiples pour ces deux tables de jointure. J'ajoute également la possibilité d'ajouter directement des référents au `create` d'un `user`. Ces changements permettent à rdv-insertion de recréer plus proprement les ressources nécessaires lorsque des utilisateurs supprimés pour cause RGPD (voir PR #3825) doivent être réactivés sur rdv-service-public.

2023-11-28 16:46 UTC, aminedhobb reviewed
Merci @qblanc pour l'implémentation et pour les tests 🙏 ! 
À part un détail ça m'a l'air ok 👍 , je laisse quelqu'un de l'équipe RDVS valider.

2023-11-28 16:46 UTC, aminedhobb commented on app/controllers/api/v1/referent_assignations_controller.rb
> +        referent_assignation.save
```suggestion
        referent_assignation.save!
```
On veut que ça fail je pense si l'assignation ne se fait pas ?

2023-11-28 16:46 UTC, aminedhobb commented on app/controllers/api/v1/user_profiles_controller.rb
> +        user_profile.save
```suggestion
        user_profile.save!
```
Same here

2023-11-28 17:00 UTC, aminedhobb commented on app/controllers/api/v1/referent_assignations_controller.rb
> +        referent_assignation.save
d'ailleurs on voudrait probablement s'économiser le save si l'assignation est déjà créée ?

2023-11-28 17:03 UTC, qblanc commented
@aminedhobb : 
- il me semble que le `save` ne déclenche rien si la commande ne modifie rien
- j'ai volontairement fait en sorte que ça ne fail pas, car ça ne me parraissait pas une bonne idée de tout faire fail (par exemple parce qu'une organisation n'existe plus) alors que certaines pouvaient passer

2023-11-29 16:04 UTC, qblanc commented
J'ai pris en compte tes 2 remarques écrites ici @aminedhobb, et comme discuté entre nous, j'ai finalement déplacé ces deux nouvelles méthodes dans les endpoints dédiés `rdv_insertion`. @victormours, @francois-ferrandis ou @ousmanedev si vous avez le temps d'y jeter un coup d'oeil n'hésitez pas !

2023-11-29 17:13 UTC, aminedhobb approved these changes
Ça me parait nickel merci 👌 !
Ça veut dire qu'un agent RDVI pourrait assigner des référents et des organisations rdv-i arbitrairement s'il le voulait, mais le risque me parait minime.
On pourrait faire en sorte que les controller scopé `Rdvinsertion` ne soient accessibles que si l'authentification se fait via la clé partagé, ce qui assurerait que l'appel vient du serveur RDVI. Je laisserai @Holist nous donner son avis à son retour.

2023-11-29 17:25 UTC, francois-ferrandis approved these changes
J'ai des suggestions plutôt cosmétiques, et pour ce qui est de la légitimité de la création de ce nouveau endpoint, vu que vous êtes les seuls à utiliser l'API, je pense qu'on peut dire que vous avez l'ownership sur les controller / routes. :wink:

2023-11-29 17:25 UTC, francois-ferrandis commented on app/controllers/api/rdvinsertion/user_profiles_controller.rb
> +    params.permit(:user_id, organisation_ids: []).to_h.symbolize_keys
`params.permit(...).to_h` te renvoie déjà un `ActiveSupport::HashWithIndifferentAccess` donc pas besoin de `symbolize_keys`. :wink: Mais d'ailleurs, pas besoin du `to_h` non plus, si ? :upside_down_face:

2023-11-29 17:25 UTC, francois-ferrandis commented on app/controllers/api/v1/user_profiles_controller.rb
> +    params.permit(:organisation_id, :user_id)
:broom: :+1:

2023-11-29 17:25 UTC, francois-ferrandis commented on app/controllers/api/rdvinsertion/referent_assignations_controller.rb
> +      referent_assignation.save! if referent_assignation.new_record?
```suggestion
      ReferentAssignation.find_or_create_by!(user: @user, agent: agent)
```

2023-11-29 17:25 UTC, francois-ferrandis commented on app/controllers/api/rdvinsertion/user_profiles_controller.rb
> +      user_profile.save! if user_profile.new_record?
```suggestion
      UserProfile.find_or_create_by!(user: @user, organisation: organisation)
```

2023-11-29 17:28 UTC, francois-ferrandis commented
> Ça me parait nickel merci 👌 🔥 ! Ça veut dire qu'un agent RDVI pourrait assigner des référents et des organisations rdv-i arbitrairement s'il le voulait, mais le risque me parait minime. On pourrait faire en sorte que les controllers scopés `Rdvinsertion` ne soient accessibles que si l'authentification se fait via la clé partagé, ce qui assurerait que l'appel vient du serveur RDVI. Je laisserai @Holist nous donner son avis à son retour.

Ah ouais j'ai pas pensé aux droits d'accès. :facepalm: Je suis d'avis qu'on restreigne les accès avant de merger ça !

2023-11-29 21:51 UTC, qblanc commented on app/controllers/api/rdvinsertion/user_profiles_controller.rb
> +    params.permit(:user_id, organisation_ids: []).to_h.symbolize_keys
effectivement je n'en ai plus besoin (c'est un reliquat d'un changement effacé)

2023-11-29 21:55 UTC, qblanc commented on app/controllers/api/rdvinsertion/referent_assignations_controller.rb
> +      referent_assignation.save! if referent_assignation.new_record?
ah bien vu ! du coup on peut même faire un one-liner
`@organisations.each { |organisation| UserProfile.find_or_create_by!(user: @user, organisation: organisation) }`

2023-11-29 21:56 UTC, qblanc commented on app/controllers/api/rdvinsertion/user_profiles_controller.rb
> +      user_profile.save! if user_profile.new_record?
et ici `@organisations.each { |organisation| UserProfile.find_or_create_by!(user: @user, organisation: organisation) }`

2023-11-30 10:05 UTC, francois-ferrandis requested changes
Je réalise que si on a pas de check sur les droits, on peut ajouter tous les usagers qu'on veut à son orga, donc ça craint un peu, et donc je me sens pas à l'aise de valider formellement la PR. :wink:

2023-12-06 08:59 UTC, francois-ferrandis approved these changes

2023-12-12 14:55 UTC, aminedhobb approved these changes
👍

2023-12-13 09:39 UTC, merged