feat: publishing prescripteurs
betagouv/rdv-solidarites.fr pull request #3908
Opened 2023-12-05 11:22 UTC by Michaelvilleneuve

Cette PR permet de publier les prescripteurs afin que l'on puisse les recevoir côté RDVI

Liée à https://github.com/betagouv/rdv-insertion/pull/1583

2023-12-06 08:17 UTC, Holist approved these changes
Merci !

2023-12-06 08:46 UTC, francois-ferrandis commented on app/blueprints/participation_blueprint.rb
> +  association :prescripteur, blueprint: PrescripteurBlueprint
Ça mérite une petite spec rapido dans `spec/blueprint/rdv_blueprint_spec.rb`, dans le même genre que `describe "participations contains user"` mais avec describe "participations contains prescripteur". :wink:

2023-12-06 09:02 UTC, francois-ferrandis commented on app/blueprints/participation_blueprint.rb
> +  association :prescripteur, blueprint: PrescripteurBlueprint
Ou même transformer le test pour tester les deux d'un coup : 

```ruby
  describe "participations contains user and prescripteur" do
    let(:user) { build(:user, first_name: "Jean") }
    let(:rdv) { build(:rdv, participations: [participation]) }
    let(:participation) { build(:participation, status: "seen", user: user, prescripteur: build(:prescripteur)) }

    it do
      expect(json.dig("rdv", "participations").first["status"]).to eq "seen"
      expect(json.dig("rdv", "participations").first["user"]["first_name"]).to eq "Jean"
      expect(json.dig("rdv", "participations").first["prescripteur"]["email"]).to eq participation.prescripteur.email
    end
  end
```

2023-12-06 12:57 UTC, Michaelvilleneuve commented on app/blueprints/participation_blueprint.rb
> +  association :prescripteur, blueprint: PrescripteurBlueprint
Ahhh je ne trouvais pas de spec associée donc j'ai pensé que vous ne testiez pas les blueprint (ce qui pourrait faire sens étant donné que ce n'est qu'un DSL) mais j'avais pensé à regarder dans le rdv_blueprint_spec

2023-12-06 13:13 UTC, francois-ferrandis approved these changes

2023-12-06 13:16 UTC, francois-ferrandis commented on app/blueprints/participation_blueprint.rb
> +  association :prescripteur, blueprint: PrescripteurBlueprint
Oui, c'est pas hyper "unitaire" comme façon de faire, mais au final on ne serialise jamais de `Participation` toute seule, on passe toujours par un `Rdv` ! Merci. :pray:

2023-12-06 13:32 UTC, victormours requested changes
je vois que l'objectif de cette PR est de pouvoir mettre les emails, nom et prénom des prescripteurs dans des exports csv. C'est pas anodin parce que ça fait une ouverture des données personnelles à un usage qui n'est pas prévu à la base, pas expliqué à la personne qui fournit ces données personnelles, et pas documenté dans les fiche de traitement de données. C'est malheureusement pas quelque chose qu'on peut faire 

En suivant les liens, je vois que dans l'issue de base (https://github.com/betagouv/rdv-insertion/issues/1544), le but peut-être d'obtenir l'organisation. Si c'est bien ça, il y a peut-être d'autres manières de répondre à ce besoin sans se compliquer la vie avec des données personnelles :
- si ce qui nous intéresse c'est les prescripteurs qui sont aussi agents, on pourrait imaginer faire changer le fonctionnement de la prescripteur pour les agents pour stocker l'organisation qui fait la prescription
- si c'est plutôt les prescripteurs qui n'ont pas de compte agent, on pourrait ajouter un champs dans le formulaire de prescripteur, et transmettre ce champs

Je suis dispo pour qu'on en discute plus en détails, mais dans l'immédiat on peut pas juste balader des données personnelles comme ça.

2024-01-08 11:07 UTC, victormours commented
J'ai l'impression que cette PR sera remplacée par https://github.com/betagouv/rdv-service-public/pull/3942, est-ce que c'est ok si on la ferme ?

2024-01-08 14:31 UTC, Michaelvilleneuve commented
@victormours De mon côté je ne suis pas sur, normalement Salma devait discuter avec toi Victor pour trouver une solution acceptable. Je ne sais pas de quoi relève la PR de @Holist. 
cc @aminedhobb peut-être que tu en sais plus sur la suite

2024-01-08 16:24 UTC, aminedhobb commented
Je laisserai @Holist confirmer mais oui normalement on n'a plus besoin de récupérer les infos prescripteurs sur rdvi puisqu'on ne l'utilise pas dans le csv.
Dans le cas des agents prescripteurs j'imagine qu'il y aura un moyen pour nous de le retrouver pour l'afficher dans le csv.

2024-01-09 08:30 UTC, Holist commented
A confirmer mais si coté rdvi on a besoin de récupérer via l'api les informations des agents prescripteurs (donc d'agents qui ont un compte rdvs et qui ont prescrit dans une autre orga pour un usager) on pourra imaginer récupérer via l'api le type et l'id de l'objet qui a créé le rdv/la participation une fois que la PR dont parle @victormours sera merge (et celle de la mise en place du polymorphisme sur le created_by merge également). C'est à dire avoir qqchose comme ca pour une participation par exemple : 

```
{"id"=>10012,
 "rdv_id"=>777,
 "user_id"=>50,
 "status"=>"unknown",
 "created_by_type"=>"agent_prescripteur",
  "created_by_id"=> 111}
```

L'id de `created_by_id` correspondant à un id d'agent en base et on pourra donc récupérer l'information dans rdvi sans dégrader la diffusion de données personnelles.

2024-01-09 16:40 UTC, victormours commented
Salma a confirmé qu'on ferait ça autrement au point avec RDVI

2024-01-09 16:40 UTC, closed without merging