Script d'anonymisation poru la mise en place de l'ETL
betagouv/rdv-solidarites.fr pull request #3909
Opened 2023-12-05 16:33 UTC by victormours

2023-12-13 13:03 UTC, francois-ferrandis requested changes
Superbe boulot à gros impact ! 

Un point bloquant sur `!ENV["ETL"]`, et une poignée de suggestions !

2023-12-13 13:03 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +    anonymize_table!(Rdv)
```suggestion
    anonymize_table!("users")
    anonymize_table!("receipts")
    anonymize_table!("rdvs")
```

:wink:

2023-12-13 13:03 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +    if Rails.env.production? && !ENV["ETL"] == "true"
D'après les [règles de précédence](https://ruby-doc.org/core-2.6.2/doc/syntax/precedence_rdoc.html), `!ENV["ETL"]` est résolu avant le `==`. Puisque `!ENV["ETL"]` peut valoir `true` ou `false`, il n'est jamais égal à `"true"` et on ne passe jamais dans ce if ! :hole: 

Au début j'allais juste faire un commentaire cosmétique sur ma préférence pour la forme `a != b` plutôt que `!a == b`, j'ai réalisé en suite que c'était pas du tout cosmétique ! :boom:

2023-12-13 13:03 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +  end
Ces 4 méthodes sont uniquement utilisées dans le processus d'identification des colonnes non identifiées. Je trouve qu'on révèle mieux cette réalité en faisant une seule méthode.

```suggestion
  def unidentified_column_names
    all_columns = db_connection.columns(@table_name).map(&:name)
    primary_key_columns = db_connection.primary_keys(@table_name)
    foreign_key_columns = db_connection.foreign_keys(@table_name).map { |key| key.options[:column] }
    all_columns - primary_key_columns - foreign_key_columns - anonymized_column_names - non_anonymized_column_names
  end
```

Note : j'ai aussi viré les `.map(&:to_s)` qui étaient superflus.

Note 2 : La memoization semble aussi très superflue dans ce contexte. :zap:

2023-12-13 13:03 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +  end
Plusieurs remarques : 
- On veut retourner `true` si au moins l'une des colonnes des colonnes indexées est la colonne passée, non ? Autrement dit on peut évaluer `column.name.in?(index.columns)`.
- Pour retourner un booléen, je remplacerais le `.find` par `.any?`
- Point vocabulaire : "uniqueness" e semble plus communément utilisé que "unicity"

2023-12-13 13:03 UTC, francois-ferrandis commented on config/environments/production.rb
> +  config.default_url_options = { host: ENV["HOST"]&.sub(%r{^https?://}, "") }
Je suis un peu frileux parce que ça déclare potentiellement silencieusement un `:host` à `nil`. Ça me paraît moins gênant de déclarer une variable `HOST` sur notre app d'ETL. :wink:

2023-12-13 13:03 UTC, francois-ferrandis commented on config/environments/production.rb
> +  config.default_url_options = { host: ENV["HOST"]&.sub(%r{^https?://}, "") }
Idem ci-dessous bien sûr.

2023-12-13 13:03 UTC, francois-ferrandis commented on scripts/anonymize_database.rb
> +end
Ceinture bretelles ! :safety_vest:

2023-12-13 13:03 UTC, francois-ferrandis commented on scripts/db_dump_load.sh
> +bundle exec rails runner scripts/anonymize_database.rb
Petit point de détail : je pense que ça va m'arriver de killer cet appel avec un CTRL + C quand je vais me rendre compte que j'ai besoin des données de prod. Il serait donc judicieux de déplacer cet appel après le `rm` ci-dessous, pour quand-même supprimer le fichier de dump dans ce cas.

2023-12-13 13:03 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +      raise "Les règles d'anonymisation pour les colonnes #{unidentified_column_names.join(' ')} de la table #{@table_name} n'ont pas été définies"
J'aime bien utilise `inspect` dans ce genre de cas, ça affiche des valeurs telles qu'on est habituées à les voir.

```suggestion
      raise "Les règles d'anonymisation pour les colonnes #{unidentified_column_names.inspect} de la table #{@table_name.inspect} n'ont pas été définies"
```

> RuntimeError: Les règles d'anonymisation pour les colonnes ["first_name", "last_name"] de la table "users" n'ont pas été définies

2023-12-13 15:04 UTC, victormours commented on app/lib/anonymizer.rb
> +    if Rails.env.production? && !ENV["ETL"] == "true"
Oooooh, bien vu ! J'ai corrigé ça, et j'ai ajouté d'autre "sanity checks" pour avoir une couche de sécurité en plus

2023-12-13 15:05 UTC, victormours commented on app/lib/anonymizer.rb
> +  end
niiiiice

2023-12-13 15:11 UTC, victormours commented on scripts/db_dump_load.sh
> +bundle exec rails runner scripts/anonymize_database.rb
bien vu ! Pour vraiment rien laisser au hasard j'ai remonté la suppression juste après le `pg_restore`

2023-12-13 15:12 UTC, victormours commented on app/lib/anonymizer.rb
> +      raise "Les règles d'anonymisation pour les colonnes #{unidentified_column_names.join(' ')} de la table #{@table_name} n'ont pas été définies"
oui, mais ce `join(' ')` est trèèèèès pratique pour copier coller les messages d'erreur dans le fichier de règles et constituer ce fichier en tdd

2023-12-13 15:15 UTC, victormours commented on config/environments/production.rb
> +  config.default_url_options = { host: ENV["HOST"]&.sub(%r{^https?://}, "") }
hum, je suis hésitant : sémantiquement ça me plaît pas trop d'avoir un `HOST` sur l'etl, vu que c'est une appli explicitement faite pour ne pas avoir de serveur web. 🤔  Je suis pas sûr de savoir quoi en faire

2023-12-13 15:17 UTC, francois-ferrandis approved these changes

2023-12-13 15:27 UTC, francois-ferrandis commented on config/environments/production.rb
> +  config.default_url_options = { host: ENV["HOST"]&.sub(%r{^https?://}, "") }
Oui, tout bien réfléchi le risque qu'on ait une appli web sans `HOST` est faible, donc ça me va comme ça.

2023-12-13 15:29 UTC, victormours commented on app/lib/anonymizer.rb
> +  end
- non, en fait on a un cas où la deuxième colonne de l'index n'a pas besoin d'être unique, mais uniquement la première : `t.index ["uid", "provider"], name: "index_agents_on_uid_and_provider", unique: true, where: "(uid IS NOT NULL)"`
Du coup on ne peux pas faire de `column.name.in?(index.columns)` (c'est ce que j'ai essayé d'exprimer dans le commentaire)
- grave
- yes
J'ai fais un commit pour le deuxième et troisième point

2023-12-13 17:00 UTC, francois-ferrandis commented on app/lib/anonymizer.rb
> +  end
Je vois. Mais pourquoi choisir arbitrairement la première colonne et pas la seconde ? À ce que je vois dans le `schema.rb`, en général c'est la première colonne qui est une string, mais on a un contre exemple : 

```ruby
    t.index ["organisation_id", "target_url"], name: "index_webhook_endpoints_on_organisation_id_and_target_url", unique: true
```

Bon, d'accord, `target_url` n'est pas anonymisée, mais si c'était le cas, la logique serait incorrecte, non ? Mais peut-être qu'on s'en fiche car de toute façon ça va péter si on essaye d'insérer des valeurs non uniques, donc c'est pas si grave.

2023-12-14 10:07 UTC, victormours commented on app/lib/anonymizer.rb
> +  end
hum, c'est vrai que ça marche pas pour ce cas, j'étais d'abord tombé sur les uid-providers des agents, donc j'avais pas fait gaffe à ça.
Ça ressemble bien à une amélioration possible à faire quand ça mettra à causer des erreurs

2023-12-14 10:47 UTC, merged