Script de séparation des territoires
betagouv/rdv-solidarites.fr pull request #4008
Opened 2024-01-24 16:32 UTC by victormours

2024-01-25 10:38 UTC, Holist approved these changes
Vu ensemble :) Top ! Merci Victor.
A faire : Ajouter un commentaire sur l'importance de l'agent admin de territoire vu que tout se base dessus.
Peut être spliter la ligne 154

2024-01-25 11:54 UTC, victormours commented
@Holist Merci pour la review ! C'est ajouté

2024-01-25 12:33 UTC, francois-ferrandis approved these changes
Super boulot, j'aime beaucoup l'option `dry_run` et le script affiche des infos très pertinentes.

J'ai des remarques sur la forme mais je n'ai pas détecté d'erreur de logique. :+1:

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +end
Je suis surpris qu'il nous manque encore des modèles pour certaines de nos tables, mais ma foi, pourquoi pas.

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +  attr_reader :new_territory, :main_territory_admin_id
C'était juste pour ne pas taper le `@` ? Ou aussi pour avoir une cohérence `old_territory` ? 

Je trouverais ça plus cohérent d'utiliser des variables d'instance pour toutes les références que nous avons dès le début. Pour le moment les méthodes sont des actions ou des `query?`, je pense donc qu'on peut définir nos `@` dans le constructeur :

```ruby
  def initialize(old_territory_id, main_territory_admin_id, new_territory_name, dry_run: true)
    @old_territory ||= Territory.find(old_territory_id)
    @main_territory_admin = Agent.find(main_territory_admin_id)
    @new_territory_name = new_territory_name
    @dry_run = dry_run
  end
```

Je trouve que ça fait moins d'indirection, et aussi ça permet de planter plus tôt si une référence est fausse.

Je propose également de se débarasser de la notion de `territory_id` pour `old_territory_id`. :wink:

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +    organisations_to_change.each do |organisation|
J'ai deux propositions pour améliorer la lisibilité : 

```ruby
organisations_to_change = old_territory.organisations - @main_territory_admin.organisations

organisations_to_change.order(name: :asc).each do |organisation|
```

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +      territory_ids_from_agent_organisations = agent_territorial_access_right.agent.organisations.pluck(:territory_id)
Un petit `agent = agent_territorial_access_right.agent` (comme dans `move_or_duplicate_agent_territorial_roles`) améliorerait la lisibilité. :wink:

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +      present_in_old_territory = motif_category_present_in_territory?(motif_categories_territory.motif_category_id, old_territory)
À la première lecture, je trouvais le code étrange car je supposais que `motif_category_present_in_territory?` vérifiant si la catégorie de motif était activée dans le territoire, ce qui serait absurde puisqu'on est déjà en train d'itérer sur `MotifCategoriesTerritory.where(territory: old_territory)`.

Je pense qu'on peut clarifier le nom de la méthode pour indiquer qu'elle vérifie les usages des catégories au niveau des motifs, du genre `motif_category_used_in_territory_motifs?`.

2024-01-25 12:33 UTC, francois-ferrandis commented on scripts/split_territory.rb
> +        # Cette table n'ayant pas d'id, on est obligés de passer par un update_all plutôt qu'un simple update sur le record
Je n'étais pas au courant de ces limitations sur les tables sans ID, on en apprend tous les jours !

J'ai tenté [d'ajouter une primary key](https://github.com/betagouv/rdv-service-public/compare/frf/add-primary-keys-to-join-tables?expand=1) pour voir si un `update` fonctionnerait mais en fait non. :cry:

2024-01-25 15:30 UTC, victormours commented on scripts/split_territory.rb
> +  attr_reader :new_territory, :main_territory_admin_id
très bonne idée, j'avais pas trop réfléchi en faisant ça, c'est updaté dans un nouveau commit

2024-01-25 15:32 UTC, victormours commented on scripts/split_territory.rb
> +    organisations_to_change.each do |organisation|
j'achète

2024-01-25 15:33 UTC, victormours commented on scripts/split_territory.rb
> +      territory_ids_from_agent_organisations = agent_territorial_access_right.agent.organisations.pluck(:territory_id)
c'est cadeau

2024-01-25 15:33 UTC, victormours commented on scripts/split_territory.rb
> +      present_in_old_territory = motif_category_present_in_territory?(motif_categories_territory.motif_category_id, old_territory)
nice

2024-01-25 15:53 UTC, aminedhobb reviewed
Merci @victormours !
J'ai posé une question mais à priori il n'y a pas d'implications techniques de notre côté.
@Holist si tu as un dump de la prod en local et que c'est pas trop galère ce serait peut-être bien de lancer la migration pour vérifier que ça n'implique rien côté rdv-i :). Dispo pour en discuter en tous cas. 
Je vais faire un point avec Amaury pour discuter des implications métiers toute à l'heure.

2024-01-25 15:53 UTC, aminedhobb commented on scripts/split_territory.rb
> +    organisations_to_change = old_territory.organisations - @main_territory_admin.organisations
Dans notre cas, on est sûr qu'on prend un admin de territoire qui n'est pas présent dans des organisations sur les 2 verticales ?

2024-01-25 15:53 UTC, aminedhobb commented on scripts/split_territory.rb
> +      present_in_old_territory = motif_category_used_in_territory_motifs?(motif_categories_territory.motif_category_id, @old_territory)
Là on fait quelque chose en + de la simple migration de territoire, on enlève la possibilité d'assigner des catégories de motifs qui n'ont pas encore été assignées sur ce territoire.
À priori pas de side effect, je vérifierai avec Amaury.

2024-01-25 17:23 UTC, aminedhobb commented on scripts/split_territory.rb
> +      present_in_old_territory = motif_category_used_in_territory_motifs?(motif_categories_territory.motif_category_id, @old_territory)
Je confirme que ça ne pose pas de problème, on pourra les activer le cas échéant.

2024-01-26 10:51 UTC, Holist requested changes
J'ai lancer le script en local avec un dump anonymisée de la prod et j'ai eu quelques problèmes que j'ai commenté (rien de bien méchant).

2024-01-26 10:51 UTC, Holist commented on scripts/split_territory.rb
> +    organisations_to_change = old_territory.organisations - @main_territory_admin.organisations
Il y a un soucis sur cette ligne, il manque un @ pour `old_territory` et `@main_territory_admin` n'est pas définie.

2024-01-26 10:51 UTC, Holist commented on scripts/split_territory.rb
> +    organisations_to_change.order("name asc").each do |organisation|
Ici aussi, ca ne passe pas sauf à modifier en `organisations_to_change.sort_by(&:name).each do |organisation|
`

2024-01-26 10:51 UTC, Holist commented on scripts/split_territory.rb
> +      territory_ids = [territory_ids_from_organisation_attributions + territory_ids_from_agent_attributions].uniq
la mise à jour des secteurs ne se fait pas correctement car on vérifie un tableau de tableaux avec un tableau simple pour attribuer le secteur un peu plus loin. Il faut remplacer par :
`territory_ids = (territory_ids_from_organisation_attributions + territory_ids_from_agent_attributions).uniq`
ou faire un flatten.

2024-01-26 10:51 UTC, Holist commented on scripts/split_territory.rb
> +        sector.update!(territory: @new_territory)
Un petit  `puts "Déplacement du secteur #{sector.id} dans le nouveau territoire"` serai top je pense :)

2024-01-26 10:53 UTC, Holist commented
> Merci @victormours ! J'ai posé une question mais à priori il n'y a pas d'implications techniques de notre côté. @Holist si tu as un dump de la prod en local et que c'est pas trop galère ce serait peut-être bien de lancer la migration pour vérifier que ça n'implique rien côté rdv-i :). Dispo pour en discuter en tous cas. Je vais faire un point avec Amaury pour discuter des implications métiers toute à l'heure.

J'ai lancé en local. A priori RAS coté RDVI, l'api, les invitations, les webhooks et les liens vers rdvsp continuent de fonctionner correctement. Est ce que tu vois quelque chose que je devrai tester en plus ?

2024-01-30 08:13 UTC, victormours commented on scripts/split_territory.rb
> +    organisations_to_change = old_territory.organisations - @main_territory_admin.organisations
oui, on va prendre la référente de la Drôme, qui n'est que sur le médico social (c'est l'id donné en exemple au début du script)

2024-01-30 08:51 UTC, Holist approved these changes
Merci :)

2024-01-30 12:48 UTC, merged