Ordonner les résultats de lieu par prochaine dispo
betagouv/rdv-solidarites.fr pull request #4022
Opened 2024-02-02 13:37 UTC by francois-ferrandis

Si on a une adresse, on affiche les lieu par proximité géographique, sinon on les affiche par prochaine dispo la plus proche.

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2024-02-02 13:42 UTC, victormours requested changes
Il me semble que ce qu'on cherchait à faire, c'est dans le cas d'une prise de rdv pour un rdv téléphonique, on veut trier les organisations par date de disponibilité la plus proche. C'est donc plutôt la méthode `#next_availability_by_motifs_organisations` utilisée dans `app/views/search/_organisation_selection.html.slim` qui devrait renvoyer un résultat trié par date de première dispo

2024-02-02 13:46 UTC, victormours commented on app/services/concerns/users/creneaux_wizard_concern.rb
> -        .sort_by { |lieu| lieu.distance(@latitude.to_f, @longitude.to_f) }
ah, donc en fait quand on avait pas de lat/long (ce qui arrive uniquement si on fait une réservation en ligne sans entrer d'adresse, ce qui n'est pas le cas la plupart du temps dans le médico social), on triait en fonction de la distance à `0,0`. C'est vrai que c'est un bon bug à résoudre au passage, mais pas exactement l'idée qu'on avait pour les rdv téléphoniques

2024-02-05 08:49 UTC, francois-ferrandis commented on app/services/concerns/users/creneaux_wizard_concern.rb
> -        .sort_by { |lieu| lieu.distance(@latitude.to_f, @longitude.to_f) }
Tu veux dire que c'est pas 

```ruby
if @latitude && @longitude
```

mais plutôt

```ruby
if matching_motifs.first.sur_place?
```

 ?

2024-02-06 11:33 UTC, francois-ferrandis commented on app/services/concerns/users/creneaux_wizard_concern.rb
> -        .sort_by { |lieu| lieu.distance(@latitude.to_f, @longitude.to_f) }
My bad, en fait si on appelle `next_availability_by_lieux` c'est qu'on est à l'étape `lieu_selection`, qui n'est affichée que pour les motifs "Sur place".

2024-02-07 08:36 UTC, victormours reviewed
Cool ! Ça fait plaisir de pouvoir supprimer la méthode `#lieux` au passage
ça serait fantastique d'avoir une spec pour tester ça 🙏

2024-02-12 16:49 UTC, victormours approved these changes
👍 cooooool, ça sera bien de prévenir la référente de la Drôme quand c'est en prod

2024-02-12 16:53 UTC, merged