Allow HTML in flash messages
betagouv/rdv-solidarites.fr pull request #4101
Opened 2024-02-27 14:35 UTC by francois-ferrandis

Besoin : il y a quelques cas où nous aimerions afficher des liens dans des flashes.

Risque : XSS via manipulation de la session

# Avant

![image](https://github.com/betagouv/rdv-service-public/assets/6357692/8d02aff4-9bf5-4a69-998f-0c388246e051)

# Après

![image](https://github.com/betagouv/rdv-service-public/assets/6357692/ad0c33d7-d17c-4ff6-b10d-1cab43a7f2b9)

# Checklist

Avant la revue :
- [X] Préparer des captures de l’interface avant et après
- [ ] Nettoyer les commits pour faciliter la relecture
- [ ] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2024-02-27 14:45 UTC, victormours requested changes
Ça introduirait direct plusieurs failles de sécurité : `app/controllers/users/relatives_controller.rb:20`, `app/controllers/users/relatives_controller.rb:33`, `app/controllers/admin/territories/sectors_controller.rb:27`, et ça en créerait plein de nouvelles dans les années à venir.
Je préfère qu'on ajoute au cas par cas des `html_safe` pour les moments où on a besoin d'un peu de html dans le flash (voire même qu'on trouve un équivalent de html safe mais juste pour un subset de tags. Je pense que `simple_format` pourrait au moins marcher pour éviter les `br`)

2024-02-27 14:48 UTC, francois-ferrandis commented
> Ça introduirait direct plusieurs failles de sécurité : `app/controllers/users/relatives_controller.rb:20`, `app/controllers/users/relatives_controller.rb:33`, `app/controllers/admin/territories/sectors_controller.rb:27`, et ça en créerait plein de nouvelles dans les années à venir. Je préfère qu'on ajoute au cas par cas des `html_safe` pour les moments où on a besoin d'un peu de html dans le flash (voire même qu'on trouve un équivalent de html safe mais juste pour un subset de tags. Je pense que `simple_format` pourrait au moins marcher pour éviter les `br`)

Merci beaucoup, c'est bien la réponse que j'attendais et j'en suis très heureux ! J'aimerais suggérer l'usage du markdown. J'ai déjà travaillé avec la gem [redcarpet](https://github.com/vmg/redcarpet) et je pense que son introduction dans nos outils peut inspirer des fonctionnalités (mise en forme des `instruction_for_rdv` par exemple).

Très chaud pour en discuter de vive voix !

2024-02-27 14:51 UTC, francois-ferrandis commented
Ah mais non en fait il y a bien plus léger : 

https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize

https://github.com/rails/rails-html-sanitizer

2024-02-27 16:03 UTC, victormours commented on app/views/layouts/_flash.html.slim
> +          = sanitize(flash[type], tags: %w[a br strong em])
`<a href="javascript:alert('hi');">Cliquez ici</a>` 😬

2024-02-28 13:37 UTC, Holist commented on app/views/layouts/_flash.html.slim
> +          = sanitize(flash[type], tags: %w[a br strong em])
J'ai vérifié parce qu'on utilise `sanitize` aussi dans rdvi mais ce code est bien filtré par `sanitize` (https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize). En utilisant `sanitize` cela génère bien : `<a>Cliquez ici</a>`

2024-02-28 14:25 UTC, francois-ferrandis commented on app/views/layouts/_flash.html.slim
> +          = sanitize(flash[type], tags: %w[a br strong em])
Merci pour ta vigilance @Holist ! J'avais aussi remarque ça dans la doc, mais on parlait avec @victormours  d'ajouter une spec. Je viens d'ajoute une **view spec** (eh ouais mon gars, ça existe).

2024-02-28 15:14 UTC, Holist commented on app/views/layouts/_flash.html.slim
> +          = sanitize(flash[type], tags: %w[a br strong em])
> Merci pour ta vigilance @Holist ! J'avais aussi remarque ça dans la doc, mais on parlait avec @victormours d'ajouter une spec. Je viens d'ajoute une **view spec** (eh ouais mon gars, ça existe).

🤩

2024-02-29 08:27 UTC, victormours approved these changes
🤩 trop bien ! Magnifique cette view spec

2024-02-29 11:15 UTC, merged