[Vigie] Fix Nil error on @user.referent_agents
betagouv/rdv-solidarites.fr pull request #4104
Opened 2024-02-27 16:31 UTC by ousmanedev

## Vigie: Fix Nil error on @user.referent_agents

[Sentry Issue](https://sentry.incubateur.net/organizations/betagouv/issues/87723/?project=74)

2024-02-27 16:59 UTC, victormours requested changes

2024-02-27 16:59 UTC, victormours commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
j'ai l'impression que si on met ce fix, on est en train de cacher un bug plus grave : comment est-ce qu'on a pu chercher des créneaux pour un motif de follow-up sans être connecté ? Normalement l'interface ne le permet pas

2024-02-27 21:51 UTC, ousmanedev commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
Cette ligne https://github.com/betagouv/rdv-service-public/pull/3176/files#diff-f2ad1d172c3fc9d26d6a78b1ad376d86a94012c91132d3127eb323139b53f31bR19 dans la PR https://github.com/betagouv/rdv-service-public/pull/3176  introduit la recherche de n'importe quel type de créneaux pour un usager notre connecté.

@francois-ferrandis , des idées sur la meilleure manière de gérer ce cas ?

2024-02-28 08:18 UTC, victormours commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
ah, c'est pour afficher un récap du rdv au dessus du formulaire de connexion. Mais du coup avec le fix proposé ici, si je comprends bien on transforme une erreur 500 en un bug plus difficile à détecter.
Actuellement, si je comprends bien, on a le comportement suivant :
- Un usager connecté commence une recherche de créneau pour un motif de suivi
- L'appli filtre les créneaux pour chercher uniquement les créneaux des agents référents de l'usager
- L'usager se déconnecte ou sa session expire
- Il reprend la navigation, et il a une erreur 500 au moment où on le redirige vers le formulaire de login (et d'ailleurs c'est un bug assez relou, puisqu'il ne peut pas se connecter à nouveau et ne peut pas finir sa prise de rdv)

Avec le fix proposé, la reconnexion marcherait, mais on permettrait à l'usager de prendre rendez-vous avec n'importe quel agent qui a des créneaux pour ce motif, et pas uniquement les référents de l'usager. Ça serait un bug encore plus grave parce que au lieu d'avoir juste une 500, on créerait des mauvais rdvs, et ça n'est pas détectable via Sentry.

Au final, est-ce qu'il ne vaut mieux pas que dans ce cas on trouve un moyen de rediriger l'usager vers le début de la recherche de créneaux, ou vers sa liste de rdvs ?
Ça pourrait être fait en modifiant `app/controllers/concerns/can_have_rdv_wizard_context.rb` pour gérer ce cas

2024-02-28 08:47 UTC, victormours commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
ou encore mieux : il faudrait juste ne pas afficher le récap de rdv dans ce cas

2024-02-28 08:53 UTC, ousmanedev commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
Du coup, la solution techniquement serait de supprimer ce bloc ?

```
 if rdv_wizard.creneau.blank?
   session.delete(:user_return_to)
   return
 end
```

2024-02-28 13:16 UTC, victormours commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
non, ça serait plutôt de faire un `return if rdv_wizard.motif.follow_up?` juste avant ce if, et si on veut régler plus généralement ces bugs, on pourrait même avoir un rescue en bas du block de cette méthode qui envoie l'erreur dans Sentry, pour faire que s'il y a une erreur quand on essaye de créer le rdv_wizard ça ne bloque pas le login

2024-02-28 14:48 UTC, ousmanedev commented on app/services/concerns/users/creneaux_search_concern.rb
> +    return referent_agents if motif.follow_up?
Super!

Ce commit d1516884aed0fefa8a3957f1514e9c5f9c2e3892 pour la guard clause et celui-ci pour éviter que des erreurs bloquent le flow de login ff6a37f6c3c384b6655cfd7e5eba711659193223

2024-02-29 07:55 UTC, victormours approved these changes

2024-02-29 08:06 UTC, merged