Bugfix : la case "RDVs modifiables" est re-cochée à l'édition d'un motif
betagouv/rdv-solidarites.fr pull request #4283
Opened 2024-05-22 07:31 UTC by francois-ferrandis

Le code introduit dans #4135 cause un bug : soit un motif ouvert à la résa en ligne (`bookable_by != "agents"`) et dont la case "RDVs modifiables" (`rdvs_editable_by_user`) est décochée (`false`). Lorsque j'ouvre le formulaire d'édition de ce motif, la case "RDVs modifiables" se retrouve toujours cochée automatiquement au chargement de la page.

La cause, c'est que notre système de cochage / décochage automatique est déclenché au chargement de la page, et il regarge si le motif est ouvert à la résa en ligne, et si il l'est, il coche la case.

Deux solutions possibles : 
1. ne plus manipuler les cases à cocher au chargement de la page
2. activer le cochage automatique uniquement sur le formulaire de création, et non d'édition

Je suis parti sur la seconde solution, après avoir testé la première (voir commits). J'ai constaté que la première n'était pas forcément nécessaire, donc je l'ai revert pour éviter de la complexité, mais j'aurais peut-être dû la garder pour éviter d'autres bugs de ce type. :thinking: 

# Checklist

Avant la revue :
- [ ] Préparer des captures de l’interface avant et après
- [X] Nettoyer les commits pour faciliter la relecture
- [X] Supprimer les éventuels logs de test et le code mort

Revue :
- [ ] Relecture du code
- [ ] Test sur la review app / en local

2024-05-22 14:23 UTC, victormours commented
Donc on change le comportement de l'application : cette option qui donnait de la flexibilité aux usagers se retrouve à être désactivée par défaut, et sera désactivée dans la pratique pour beaucoup de gens.
Je pense que l'option de ne pas manipuler les cases à cocher au chargement de la page serait meilleure.

C'est dommage qu'on n'ai pas eu droit à une vrai discussion sur stimulus : pour ce cas d'usage je sais pas si ça apporte grand chose par rapport à du js vanilla, et pour éviter la manipulation des cases au chargement de la page j'ai l'impression que ça complique les choses

Je ne retrouve pas de trace écrite de pourquoi on a changé le comportement par rapport à la version précédente (cacher les informations qui ne sont pas pertinentes). C'est un choix assez surprenant de préférer des disable, qui introduit ces nouveaux bugs, et du bruit dans l'interface. S'il n'y avait pas de motivation particulière à faire ça, est-ce qu'on reviendrait pas sur le fonctionnement précédent de cacher les champs qui n'ont pas de sens ?

2024-05-22 14:23 UTC, victormours requested changes
Donc on change le comportement de l'application : cette option qui donnait de la flexibilité aux usagers se retrouve à être désactivée par défaut, et sera désactivée dans la pratique pour beaucoup de gens.
Je pense que l'option de ne pas manipuler les cases à cocher au chargement de la page serait meilleure.

C'est dommage qu'on n'ai pas eu droit à une vrai discussion sur stimulus : pour ce cas d'usage je sais pas si ça apporte grand chose par rapport à du js vanilla, et pour éviter la manipulation des cases au chargement de la page j'ai l'impression que ça complique les choses

Je ne retrouve pas de trace écrite de pourquoi on a changé le comportement par rapport à la version précédente (cacher les informations qui ne sont pas pertinentes). C'est un choix assez surprenant de préférer des disable, qui introduit ces nouveaux bugs, et du bruit dans l'interface. S'il n'y avait pas de motivation particulière à faire ça, est-ce qu'on reviendrait pas sur le fonctionnement précédent de cacher les champs qui n'ont pas de sens ?

2024-05-22 14:26 UTC, victormours commented
Pour la valeur par défaut en base, vu que le champs ne s'applique que dans certains cas, je me demande si ça n'avait pas plus de sens de le garder en true par défaut, vu que c'est le comportement par défaut que ce champs soit activé (ce qui ne veut pas forcément dire que les rdv sont modifiables)

2024-05-22 14:28 UTC, victormours commented
C'est intéressant de regarder aussi l'implémentation de la méthode `Rdv#editable_by_user?` : il y a un autre décalage entre les rdv collectifs dans l'implém et dans le formulaire
Ce qui est difficile finalement c'est qu'on essaye dans le formulaire (et le motif#show) d'afficher le résultat d'une partie de l'implémentation de cette méthode (la partie côté motif) et de ce champs en base.

2024-05-22 14:58 UTC, francois-ferrandis commented
> Donc on change le comportement de l'application : cette option qui donnait de la flexibilité aux usagers se retrouve à être désactivée par défaut, et sera désactivée dans la pratique pour beaucoup de gens. Je pense que l'option de ne pas manipuler les cases à cocher au chargement de la page serait meilleure.

Oui tu as raison, dans le cas de figure où on veut rendre un motif accessible en ligne, la case ne se coche plus toute seule.

> C'est dommage qu'on n'ai pas eu droit à une vrai discussion sur stimulus : pour ce cas d'usage je sais pas si ça apporte grand chose par rapport à du js vanilla, 

Je suis aussi d'accord, au final je trouve aussi que ça n'apporte pas grand chose si ce n'est une convention de nommage sur le binding HTML <-> JS, mais c'est pas hyper important. 

> et pour éviter la manipulation des cases au chargement de la page j'ai l'impression que ça complique les choses

Je pense que ce n'est pas une conséquence de Stimulus, mais de ma tentative de refacto faite au même moment. Et je suis d'accord, elle n'est pas flexible et au final pas plus claire que la précédente.

> Je ne retrouve pas de trace écrite de pourquoi on a changé le comportement par rapport à la version précédente (cacher les informations qui ne sont pas pertinentes). C'est un choix assez surprenant de préférer des disable, qui introduit ces nouveaux bugs, et du bruit dans l'interface. S'il n'y avait pas de motivation particulière à faire ça, est-ce qu'on reviendrait pas sur le fonctionnement précédent de cacher les champs qui n'ont pas de sens ?

On avait décidé de ne pas cacher des éléments pour éviter des "sauts" dans la page, et aussi pour éviter que l'agent se dise "mais je me souviens qu'il y avait une option pour faire ça, mais je ne la vois pas sur la page". C'est ça ? @NesserineZarouri @Teodora-Stanki 

> Pour la valeur par défaut en base, vu que le champs ne s'applique que dans certains cas, je me demande si ça n'avait pas plus de sens de le garder en true par défaut, vu que c'est le comportement par défaut que ce champs soit activé (ce qui ne veut pas forcément dire que les rdv sont modifiables)

Je vois où tu veux en venir, mais je préfère avoir des règles de validation pour garder la cohérence plutôt que d'avoir dans la base un booléen `rdvs_editable_by_user` à `true` alors que le RDV n'est pas éditable par l'usager.

2024-05-23 08:37 UTC, francois-ferrandis commented
@victormours J'ai fait en sorte de ne garder dans cette PR que le fait de ne pas check la box au chargement de la page mais seulement lorsqu'on manipule la page. Ça permet de corriger le bug et de faire le reste dans d'autres PR.

Ah, j'ai oublié un test, je fais ça !

2024-05-23 13:22 UTC, francois-ferrandis commented
@victormours C'est prêt pour une review. L'implémentation à base de booléen `resetCheckbox` n'est pas la plus élégante mais ça répare le bug. Je songe à faire une autre PR de refacto car les abstractions que j'ai choisies sont e plus en plus fausses et donc le code est de moins en moins clair.

2024-05-23 14:15 UTC, victormours commented
> On avait décidé de ne pas cacher des éléments pour éviter des "sauts" dans la page, et aussi pour éviter que l'agent se dise "mais je me souviens qu'il y avait une option pour faire ça, mais je ne la vois pas sur la page". 

Je comprends ces besoin (le deuxième en particulier), et j'ai l'impression qu'on a découvert ces dernières semaines quelques problèmes avec la solution actuelle :
- les divers bugs
- on affiche en grisé des informations qui sont fausses, en les présentant comme impossible à changer (par exemple si la réservation en ligne n'est pas activée, on donne l'impression que les délais min et max s'appliquent alors que ce n'est pas le cas)

C'est peut-être le bon moment pour faire un petit ajustement : une solution possible pourrait être de garder les en-têtes des cards pour les champs inactifs, de garder le contenu des petits callouts qui expliquent pourquoi l'option ne s'applique pas (ce qui n'est pas la même chose que de ne pas pouvoir la changer), mais de cacher les inputs comme avant. Mais il y a peut-être d'autres approches :)

2024-05-23 14:22 UTC, victormours approved these changes
🙏 merci pour le fix et pour la spec !

2024-05-23 14:31 UTC, merged