[WIP] lever des exceptions pundit plutôt qu’AR lorsqu’un agent essaie d’accéder à une orga étrangère
betagouv/rdv-solidarites.fr pull request #4384
Opened 2024-07-01 07:31 UTC by adipasquale

corrige #4383

TODO: 

- [ ] écrire un test

2024-07-01 09:53 UTC, adipasquale commented on app/controllers/agent_auth_controller.rb
> +  before_action :authorize_organisation, if: -> { params[:organisation_id].present? }
ce if préserve le comportement actuel : des controleurs héritent de ce controleur mais n’ont pas toujours d’`organisation_id` dans leurs params de route, et pour autant ils ne raisent pas d’erreurs car le current_organisation n’ait jamais appelé (je suppose)

2024-07-01 13:32 UTC, francois-ferrandis approved these changes
Bonne proposition pour diminuer le bruit avec un changement minimal. :+1: 

On sent qu'on pourrait tirer le fil de la pelote avec ces questions de dépendances implicites à `current_organisation`.

2024-07-01 13:32 UTC, francois-ferrandis commented on app/controllers/agent_auth_controller.rb
> +  before_action :authorize_organisation, if: -> { params[:organisation_id].present? }
À ce que je vois, il y a 
- les controllers du namespace `Admin::` qui ont toujours besoin d'une organisation, puisqu'il y a `:organisation_id` dans le path de leur route
- les controllers du nemaspace `Agents::`, qui n'ont pas besoin d'une orga courante

Si c'est aussi simple que ça on pourra faire une autre PR où on fait en sorte que 
- on transforme `AgentAuthController` en `CurrentOrganisationController`
- les controllers de la seconde catégorie n'héritent plus de `CurrentOrganisationController`.

2024-07-01 14:43 UTC, victormours requested changes
Je suis d'accord avec l'idée qu'on améliore l'ux pour ce cas et qu'on limite le bruit dans Sentry, mais je ne comprends pas le besoin de rediriger vers la page précédente ou la home qu'une page d'erreur 404 : je pense qu'on aurait une meilleure UX en améliorant la page 404 (par exemple en rappelant à quel compte l'agent est connecté et en proposant de changer de compte).
(J'ai aussi l'impression qu'on réinvente une version moins bien et plus compliquée d'un pattern ultra classique, ce qui me rend un peu méfiant.)

Il y a un projet de mise à jour des pages 404 d'ailleurs : https://www.figma.com/design/1IITBeGk9MuYSOhBW3a8iv/Pages-statiques?node-id=1-2&t=j0JSS3uCI8xMtdEP-0 (Mehdi et Téo connaissent le sujet, mais on n'a pas encore eu le temps d'implémenter les maquettes, et je ne retrouve pas de fiche notion ni d'issue github)

J'ai aussi une petite réticence à permettre le sniffing des id d'orgas qui existent, plutôt par habitude que pour une raison précise.

2024-07-01 15:01 UTC, adipasquale commented
merci pour tes retours @victormours ! peut-être à discuter de vive voix aussi.

Je n’ai pas codé ce comportement de redirection 302 avec flash d’erreur, c’est celui par défaut qui se produit pour les `Pundit::NotAuthorizedError` cf [Admin::AuthenticatedControllerConcern](https://github.com/betagouv/rdv-service-public/blob/fix/remove-sleep-ants-sync/app/controllers/concerns/admin/authenticated_controller_concern.rb/#L31-L35)

Ce qui m’importe avec cette PR c’est effectivement de limiter le bruit sur Sentry.

Je n’ai pas d’avis fort sur ce qui devrait être le comportement dans ce cas : 

1. cacher la vraie erreur avec une 404 
2. exprimer clairement l’erreur de permissions que ce soit avec une 302 + flash ou autre chose

Mon avis faible va plutôt pour 2 : 

- Il me semble que 2. est dans tous les cas une meilleure UX que 1. malgré que le flash ne soit pas lu, l’info correcte est présente tandis qu’avec 1. l’info est cachée ou alors on pourra écrire des "il se peut que le problème vienne d’un problème de permissions" sur la 404.
- 2. est un peu plus sécurisé pour le sniffing mais on parle ici uniquement des agents loggés ce qui limite la surface « d’attaque » et effectivement l’info des IDs n’est pas très secrète (voire publique ?)
- la majeure partie des occurences semble être des redirections post sign in d’agents (potentiellement sur des ordis partagés) ou bien des liens venant de l’extérieur. On peut voir ça par [ex ici dans sentry discover avec une colonne referer](https://sentry.incubateur.net/organizations/betagouv/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&field=http.referer&name=ActiveRecord%3A%3ARecordNotFound%3A+Couldn%27t+find+Organisation+with+%27id%27%3D313+%5BWHERE+%22agent_roles%22.%22agent_id%22+%3D+%241%5D+%28ActiveRecord%3A%3ARec...&project=74&query=issue%3ALAPINS-162&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29)

@victormours Si tu as un avis fort pour 2 je peux changer cette PR dans cette direction

2024-07-02 12:56 UTC, adipasquale commented
Discuté avec @victormours : en termes d’UX le comportement actuel 404 versus le changement de cette PR avec redirection et flash générique « vous n’avez pas le droit » se valent à peu près.

Or, le rétablissement du bruit des `ActiveRecord::RecordNotFound` avait justement été fait pour être alerté de problèmes d’UX améliorables. 
Cette PR va enlever ce bruit et on n’aura plus l’info qu’il faudrait améliorer cette UX.

C’est donc le moment de le faire :) 

J’ai modifié le message du flash d’erreur pour ce cas précis : 

> Vous ne pouvez pas accéder à cette organisation

On peut itérer dessus assez facilement.

Au passage mes derniers commits : 

- utilisent de manière plus native `Pundit.authorize` plutôt que d’instancier la policy directement. Cela permet de raiser exactement la bonne erreur pundit bien chargée avec les infos et d’utiliser le bon message d’erreur i18n
- corrige le nom de la spec sur la recherche d’usager coté agent dont j’ai modifié le comportement en effet de bord de cette PR

2024-07-02 16:07 UTC, victormours approved these changes
Ça me va bien comme amélioration, merci d'avoir pris le temps de traiter les retours !

2024-07-03 09:47 UTC, merged

2024-07-04 06:47 UTC, adipasquale commented
<img width="1241" alt="image" src="https://github.com/betagouv/rdv-service-public/assets/883348/8ca88c23-ae44-4ed7-8b42-2d95f55ab659">

10 down 🚀