fix and test
betagouv/rdv-solidarites.fr pull request #4398
Opened 2024-07-02 15:42 UTC by Holist

Closes https://github.com/betagouv/rdv-insertion/issues/2122

# Contexte

Depuis https://github.com/betagouv/rdv-service-public/commit/57648fb4686163a77c2584f3c5749b38a6cd7c9d on peut spécifier si les rdvs d'un motif sont annulable ou editable par les usagers (au niveau du motif, en db uniquement, il n'y a pas de front pour ca).
Cependant quand l'usager reçoit le mail de recap du rdv le CTA lui laisse croire qu'il peut annuler/modifier le rdv en question alors que ce n'est pas le cas : 

<img width="561" alt="Capture d’écran 2024-07-02 à 17 03 39" src="https://github.com/betagouv/rdv-service-public/assets/28594222/b57775a9-6f85-49d8-b306-d789b458a5d8">
<img width="972" alt="Capture d’écran 2024-07-02 à 17 04 27" src="https://github.com/betagouv/rdv-service-public/assets/28594222/6033bcd5-cf52-4a9d-add1-a6802d1d30f6">

# Solution

J'ai conditionné l'affichage du CTA dans les mails sur les mêmes policies qui permettent ou pas de modifier/annuler le RDV.
Je n'ai pas changé la désignation du bouton (qu'on puisse uniquement editer ou annuler le rdv le bouton se nomme toujours : "Annuler ou modifier le rendez-vous"

<img width="587" alt="Capture d’écran 2024-07-02 à 17 05 55" src="https://github.com/betagouv/rdv-service-public/assets/28594222/997f1edf-7eff-4d8c-a71f-594aa389b713">

2024-07-03 07:48 UTC, victormours requested changes
J'ai l'impression que c'est un peu drastique de ne plus mettre de CTA du tout, est-ce qu'on pourrait quand même le mettre mais avec un texte du genre "Voir le RDV" ?

2024-07-03 07:53 UTC, Holist commented
> J'ai l'impression que c'est un peu drastique de ne plus mettre de CTA du tout, est-ce qu'on pourrait quand même le mettre mais avec un texte du genre "Voir le RDV" ?
> C'est vrai qu'il n'y a pas beaucoup plus d'info que dans le show, mais ça peut permettre de retrouver ses autres rdv, éventuellement de prendre un autre rdv.

yes 👍  dans ce cas quitte à modifier le texte du CTA je vais le conditionner en fonction des droits.

2024-07-03 15:43 UTC, victormours requested changes

2024-07-03 15:43 UTC, victormours commented on spec/features/users/online_booking/with_invitation_spec.rb
> +  let(:now) { Time.zone.now }
attention, il faut mieux éviter d'utiliser `Time.zone.now` dans les specs, parce que ça a une tendance à faire échouer les specs de manière imprévisible si elles tournent à une date qui est une exception dans le code, genre un jour férié, le prochain premier janvier, un lendemain de changement d'heure, etc

2024-07-03 15:43 UTC, victormours commented on app/views/mailers/common/_rdv_cancellable.html.slim
> +      = link_to "Voir le rendez-vous", users_rdv_url(rdv.id, invitation_token: @token), class:"btn btn-primary"
👍 cool, merci d'avoir géré tous les cas

2024-07-03 15:43 UTC, victormours commented on app/views/mailers/common/_rdv_cancellable.html.slim
> +      = link_to "Voir le rendez-vous", users_rdv_url(rdv.id, invitation_token: @token), class:"btn btn-primary"
Est-ce que le texte à la ligne 2 ne mériterait pas aussi d'être ajusté ?

2024-07-03 15:43 UTC, victormours commented on spec/features/users/online_booking/with_invitation_spec.rb
> +      expect(current_email).not_to have_link("Annuler ou modifier le rendez-vous")
c'est un peu intense de faire tourner toute une spec js pour de la logique dans la vue du mailer. Est-ce que ça serait possible de plutôt faire une spec unitaire sur le mailer ? (je pense que ça plairait à François aussi)

2024-07-04 14:37 UTC, Holist commented on spec/features/users/online_booking/with_invitation_spec.rb
> +  let(:now) { Time.zone.now }
Merci, vu ensemble en ajoutant le travel_to(now) pas de soucis à garder une date fixe dans ce cas effectivement.

2024-07-04 15:18 UTC, Holist commented on app/views/mailers/common/_rdv_cancellable.html.slim
> +      = link_to "Voir le rendez-vous", users_rdv_url(rdv.id, invitation_token: @token), class:"btn btn-primary"
Effectivement, bien vu. Ca donnait quelquechose de bizarre si l'orga ou le lieu n'avait pas de numéro de tel. J'ai fait les ajustements et j'ai mis quelques captures d'écran à jour.

2024-07-05 08:26 UTC, Holist commented on spec/features/users/online_booking/with_invitation_spec.rb
> +      expect(current_email).not_to have_link("Annuler ou modifier le rendez-vous")
done 👍

2024-07-05 09:42 UTC, victormours approved these changes
trop bien, merci pour les updates !
J'ai un tout petit doute sur le placement de la phrase pour contacter l'organisation par téléphone, mais c'est pas bloquant pour merger

2024-07-05 09:42 UTC, victormours commented on app/helpers/rdvs_helper.rb
> +  end
😍

2024-07-05 09:42 UTC, victormours commented on app/views/mailers/common/_rdv_cancellable.html.slim
> +        | En cas de problème vous pouvez contacter le #{link_to rdv.phone_number, "tel:#{rdv.phone_number_formatted}"}.
est-ce que pour cette branche on ne voudrait pas revenir à la ligne ? Ou alors pour se simplifier la vie on la met tout à la fin ?

2024-07-05 09:42 UTC, victormours commented on spec/features/users/online_booking/with_invitation_spec.rb
> +    travel_to(now)
👍

2024-07-05 09:42 UTC, victormours commented on spec/mailers/users/rdv_mailer_spec.rb
> +    end
👍 nickel ces specs

2024-07-05 09:51 UTC, Holist commented on app/views/mailers/common/_rdv_cancellable.html.slim
> +        | En cas de problème vous pouvez contacter le #{link_to rdv.phone_number, "tel:#{rdv.phone_number_formatted}"}.
Tu parles uniquement du cas ou on ne peut ni éditer, ni annuler le rdv ? 
Je trouve que la phrase est très courte et bien lisible dans tout les cas.

2024-07-05 12:12 UTC, merged