fix(motifs): make sure motif_category cannot be changed if motif has rdvs
betagouv/rdv-solidarites.fr pull request #4472
Opened 2024-07-22 15:35 UTC by Michaelvilleneuve

Cette PR rajoute une validation qui empêche de changer la catégorie d'un motif si celui-ci possède déjà des rdvs.

fix https://github.com/gip-inclusion/rdv-insertion/issues/2214

2024-07-22 15:51 UTC, francois-ferrandis reviewed
Que souhaitons-nous faire dans le cas où le motif n'avait pas de catégorie et qu'on souhaite lui en attribuer une ?

2024-07-22 16:18 UTC, victormours requested changes
L'issue côté RDV Insertion ne nous permettra pas de savoir pourquoi ça peut poser problème, donc dans l'état actuel on fera un rollback dans quelques mois quand on n'aura plus le contexte en tête et que quelqu'un demandera à corriger la catégorie de motif d'un rdv (on a eu un [exemple récent](https://github.com/betagouv/rdv-service-public/pull/4450#:~:text=Nous%20n%27avons%20malheureusement%20pas%20pu%20retrouv%C3%A9%20le%20contexte%20de%20la%20mise%20en%20place%20de%20cette%20exclusivit%C3%A9.) d'un douloureux manque d'explication sur une vieille issue.

Il me semble que cette évolution peut aussi casser le workflow des mairie qui utilisent les catégories de motifs qui se brancher ou débrancher du moteur de recherche de l'ants.

De manière générale, une modification du comportement de l'appli sans explication de sa motivation n'est pas possible. C'est un peu dommage qu'on ai besoin de rappeler ça.

2024-07-22 17:11 UTC, aminedhobb commented
Merci pour le feedback @victormours .
Pour info on en a discuté avec @Holist avant d'embarquer l'issue et il pensait que c'était un changement cohérent et que le fait que ça n'ait pas été fait avant était même surprenant.

> Il me semble que cette évolution peut aussi casser le workflow des mairie qui utilisent les catégories de motifs pour se brancher ou débrancher du moteur de recherche de l'ants.

Je ne le savais pas, ça peut poser question en effet.

> C'est un feedback qui s'adresse plutôt à l'équipe RDV Insertion en général qu'à Michael en particulier (qui a juste proposé une implém simple et efficace en étant de bonne volonté), mais de manière générale, une modification du comportement de l'appli sans explication de sa motivation n'est pas possible.

Pour le coup c'est vraiment pas dans nos habitudes de partir à l'abordage dans l'implémentation d'une feature sans en discuter avec vous au préalable.. 
Sur ce cas particulier, le go de notre référent rdvsp semblait suffire puisque le changement paraissait évident (ça allait également dans le sens de ce qui a été fait dans #4363), mais on s'est visiblement trompé. 

Tu recommanderais de faire un point avec l'équipe produit du coup pour voir comment les catégories sont utilisées ?

2024-07-22 17:14 UTC, aminedhobb commented
Pour info les catégories de motif présentes en prod aujourd'hui sont toutes des catégories issues de rdv-insertion

2024-07-23 08:42 UTC, victormours commented
Désolé pour le commentaire un peu sec, 🙁 je me rends compte qu'en plus c'était pas forcément très clair : c'est ok de proposer une modif sans qu'on ai eu de discussion, et il y a pas de soucis pour qu'on le fasse en asynchrone. Ce qui est embêtant, c'est d'avoir une issue qui dit juste "Les catégories de motif ne doivent pas changer s'il y a des rdv". Ça ne permet pas de savoir quels seraient les impacts négatif un changement de catégorie de motif (c'est le classique problème de parler juste d'une solution particulière et pas du problème qui est à sa racine).
Ça pourrait être utile d'avoir un exemple d'un changement de catégorie de motif qui a posé problème. 

Ça a énormément de valeur sur le long terme si dans 6 mois on a des gens qui nous disent qu'ils ont dû créer un nouveau motif parce que c'était pas possible de changer de catégorie de motif et qu'ils se sont trompés.
A court terme, ça permet aussi de mieux savoir comment on peut trouver quelque chose qui fonctionne pour les mairies aussi bien que pour l'insertion.

Est-ce que ça vous irait qu'on commence par ajouter ces infos dans l'issue, et comme ça on aura une base pour pouvoir faire une review de la PR ?

2024-07-23 08:59 UTC, aminedhobb commented
Aucun problème @victormours 🙌 , je comprends tout à fait l'utilité d'avoir ce contexte et sa valeur ajoutée, c'est pour ça que je l'ai effectivement rajouté entre temps. J'avoue que si on a pas le contexte rdv-i c'était pas si évident que ça. 
Tu me diras du coup si le contexte est assez clair ou si tu veux que je rajoute des éléments :) !

2024-07-24 08:28 UTC, Michaelvilleneuve commented
Je ferme cette PR du coup (cf https://github.com/gip-inclusion/rdv-insertion/issues/2214#issuecomment-2245474067)

2024-07-24 08:28 UTC, closed without merging

2024-09-04 14:34 UTC, Holist commented
J'ai lu les échanges. Je me permet d'intervenir. 
Cela me semblait effectivement plutôt logique qu'une catégorie de motif ne puisse plus être modifiée quand des rdvs sont pris sur un motif (l'exemple d'Amine sur la config collectif/individuel qui a déjà se comportement me semble logique).

J'aimerai bien comprendre pour l'ANTS comment ca se passe ? Ils ont des motifs avec des catégories qui peuvent changer (alors qu'il y a des rdvs de pris) ? Cela ne risque pas de poser des problèmes de cohérence des données ? Ex un RDV pris pour une 'CNI' qui se retrouve sur un motif qui a une catégorie qui a été changée pour 'Passeport' ?
@victormours