retirer select2 et jquery.datetimepicker du bundle application
betagouv/rdv-solidarites.fr pull request #4488
Opened 2024-07-25 14:49 UTC by adipasquale

Review app : https://demo-rdv-solidarites-prXXXX.osc-secnum-fr1.scalingo.io/

# Contexte

Pendant l’intégration du DSFR j’ai remarqué que ni select2 ni jquery.datetimepicker ne sont utilisés dans la partie application

# Solution

Les retirer des bundles CSS et JS `application`

Il ne devrait y avoir aucun changement fonctionnel

2024-07-29 08:18 UTC, francois-ferrandis requested changes
Il reste 2 usages de `jquery.datetimepicker` pour le champ "Date de naissance" dans 

- `app/views/users/users/_form.html.slim:15`
- `app/views/users/relatives/_form_fields.html.slim:7`

La méthode`date_input()` ajoute l'attribute `data-behaviour="datepicker"`, qui est utilisé dans notre code pour linker la lib JS (voir `datetimepicker.js`).

Je suggère de remplacer ce champ par un picker natif, qui est beaucoup plus accessible (surtout en mobile) et envoie toujours au serveur la date au format ISO `YYYY-MM-DD`. :wink: 

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

Pour info : nous avions tenté de nous débarrasser de ces date / datetime pickers dans #3217, mais ça posait des soucis niveau timezone (revert dans 0b9b5c71235651f64ab7ba1ccadf0dbec91901b3), ce qui ne concerne que les datetimes, pas les dates de naissance.

2024-07-29 08:51 UTC, adipasquale commented
bien vu @francois-ferrandis j’avais raté cet usage, je vais corriger 🙇

2024-07-29 13:58 UTC, francois-ferrandis approved these changes
Merci pour ce cleanup ! :pray:

2024-07-30 09:10 UTC, adipasquale commented
Merci @francois-ferrandis ! et validé avec Téo elle valide que c’est une bonne direction 👍

2024-07-30 09:14 UTC, merged