Suppression du layout application_dsfr
betagouv/rdv-solidarites.fr pull request #4534
Opened 2024-08-06 12:38 UTC by adipasquale

# Contexte

Dans le cadre du passage au DSFR de la partie usagers, le layout principal `application` inclut désormais tout le CSS et le JS du DSFR, ainsi qu’une partie de bootstrap.

Il reste un layout `application_dsfr` utilisé à deux endroits : la homepage de RDV Mairie ainsi que la page d’acceptation des invitations. Ce layout n’a plus beaucoup de sens et est devenu redondant.

# Solution

On utilise dorénavant le layout par défaut `application` sur les pages citées précédemment. 

On supprime le layout `application_dsfr` et les fichiers associés : 
- `app/views/dsfr/footer.html.slim` 
- `app/views/rdv_service_public.scss` 

Quelques petites adapations sont nécessaires pour pouvoir supprimer le fichier `rdv_service_public.scss` qui comprenait des règles custom qu’on n’a pas spécialement envie de garder.
Je les remplace par des class CSS utilities préfixés `.rdv-` qui seront je l’espère plus réutilisables et maintenables.

## Captures d'écran

Avant | Après
:- | -:
_mettre un screenshot ici_ | _et ici_

2024-08-07 09:07 UTC, victormours requested changes

2024-08-07 09:07 UTC, victormours commented on app/javascript/stylesheets/rdv_service_public.scss
> -}
il faut qu'on garde cette règle

2024-08-07 09:07 UTC, victormours commented on app/javascript/rdv_service_public.js
> -document.addEventListener('turbolinks:load', DsfrNewPassword)
il faut qu'on garde ça aussi pour ne pas casser le formulaire de création de compte

2024-08-07 09:08 UTC, victormours commented
est-ce qu'il serait possible de garder les boutons de la bonne couleur ? Le hover est à nouveau cassé dessus

2024-10-02 08:42 UTC, adipasquale commented
je ferme car il y avait plusieurs choses à corriger et que ce n’est pas la prio actuelle

2024-10-02 08:42 UTC, closed without merging