feat(script): add script to transfer users
betagouv/rdv-solidarites.fr pull request #4659
Opened 2024-09-24 08:58 UTC by Michaelvilleneuve

Cette PR ajoute une script permettant de transférer les usagers d'une organisation (associés à une liste de motifs en particulier) à une autre organisation. 

https://github.com/gip-inclusion/rdv-insertion/issues/2284

Cette PR fait suite à celle-ci que je vais fermer https://github.com/gip-inclusion/rdv-insertion/pull/2341#pullrequestreview-2322155605 qui faisait la même chose côté rdvi mais qui ne pouvait pas fonctionner étant donné que la donnée source est ici

2024-09-25 08:52 UTC, aminedhobb requested changes
Merci @Michaelvilleneuve 🙏 , je t'ai laissé quelques remarques en attendant un regard plus expert côté rdvsp.

2024-09-25 08:52 UTC, aminedhobb commented on scripts/transfer_users_and_rdvs_to_other_organisation.rb
> +      rdv.update!(organisation_id: target_organisation.id)
Les rdvs en question doivent également changer de lieu et de motif pour pointer vers ceux de la nouvelle orga

2024-09-25 08:52 UTC, aminedhobb commented on scripts/transfer_users_and_rdvs_to_other_organisation.rb
> +      .where(rdvs: { motif_id: motifs.ids })
donc ce script ne transfère pas les usagers n'ayant pas de rdvs (ce n'est pas ce qui est mis dans la description du script) ?

2024-09-25 08:52 UTC, aminedhobb commented on scripts/transfer_users_and_rdvs_to_other_organisation.rb
> +      participations: { user: users_to_transfer }
À mon avis il faudrait enlever cette clause aussi si l'on veut transférer tous les rdvs (dont les rdvs collectifs futures n'ayant pas encore d'usagers) sur la nouvelle orga

2024-09-25 17:15 UTC, adipasquale reviewed
Merci @Michaelvilleneuve ! est-ce que tu peux nous donner du contexte sur ce script ? Pourquoi arrive-t-il maintenant, dans quels cas et sur combien d’usagers souhaitez vous l’utiliser ?

En l’état ça me paraît un peu « dangereux », entre autres pour l’histoire des motifs à réconcilier et d’effets de bords potentiellement imprévus. 

Chez RDVS on a justement un département qui nous demande de pouvoir fusionner des orgas et on se pose des questions similaires sur la bonne manière de faire ça. 

Ça m’a l’air d’être un gros sujet qui risque d’introduire des incohérences dans la base de données qui risquent de nous embêter longtemps si on ne le fait pas de manière super exhaustive et prudente. 

Il faudrait aussi peut-être réfléchir à introduire des tests qui nous rassurent sur les effets de ce script. 
Et lancer des tests manuels sur des batches d’users, éventuellement sur des données anonymisées de prod pour avoir des cas plus proches du réel et en particulier des orgas dans lesquelles on compte lancer ces scripts.

Voilà, désolé pour ce retour assez prudent mais en l’état je ne suis pas super à l’aise avec ce script :)

Je pense qu’on peut parfois se permettre des manipulations cavalières en prod depuis la console sur des cas précis où on a identifié qu’on n’allait pas se retrouver dans des cas particuliers. 
Par exemple pour le script tel quel, si on compte le lancer sur peu d’usagers, qui n’ont aucun rdv collectif, et avec une orga cible qui est quasiment vierge, alors pourquoi pas ! Mais le risque de commiter le script sans indication ni garde-fou dans le code c’est qu’on soit tentés dans le futur de le lancer sans trop réfléchir.

2024-09-25 17:15 UTC, adipasquale commented on scripts/transfer_users_and_rdvs_to_other_organisation.rb
> +      rdv.update!(organisation_id: target_organisation.id)
C’est juste et ça pose la question de la réconciliation des motifs (et dans un moindre enjeu des lieux).

On entend par réconciliation l’algorithme qui va aller chercher des motifs existants similaires dans l’orga cible pour ne pas créer de doublon. Comment décider ce qui est un motif identique et ce qui n’en n’est pas un est loin d’être évident et doit probablement être vu au cas par cas au début.  

On en parlait récemment avec @francois-ferrandis

2024-09-26 07:43 UTC, Michaelvilleneuve commented
> Merci @Michaelvilleneuve ! est-ce que tu peux nous donner du contexte sur ce script ? Pourquoi arrive-t-il maintenant, dans quels cas et sur combien d’usagers souhaitez vous l’utiliser ?
> 
> En l’état ça me paraît un peu « dangereux », entre autres pour l’histoire des motifs à réconcilier et d’effets de bords potentiellement imprévus.
> 
> Chez RDVS on a justement un département qui nous demande de pouvoir fusionner des orgas et on se pose des questions similaires sur la bonne manière de faire ça.
> 
> Ça m’a l’air d’être un gros sujet qui risque d’introduire des incohérences dans la base de données qui risquent de nous embêter longtemps si on ne le fait pas de manière super exhaustive et prudente.
> 
> Il faudrait aussi peut-être réfléchir à introduire des tests qui nous rassurent sur les effets de ce script. Et lancer des tests manuels sur des batches d’users, éventuellement sur des données anonymisées de prod pour avoir des cas plus proches du réel et en particulier des orgas dans lesquelles on compte lancer ces scripts.
> 
> Voilà, désolé pour ce retour assez prudent mais en l’état je ne suis pas super à l’aise avec ce script :)
> 
> Je pense qu’on peut parfois se permettre des manipulations cavalières en prod depuis la console sur des cas précis où on a identifié qu’on n’allait pas se retrouver dans des cas particuliers. Par exemple pour le script tel quel, si on compte le lancer sur peu d’usagers, qui n’ont aucun rdv collectif, et avec une orga cible qui est quasiment vierge, alors pourquoi pas ! Mais le risque de commiter le script sans indication ni garde-fou dans le code c’est qu’on soit tentés dans le futur de le lancer sans trop réfléchir.

Non non t'inquiètes @adipasquale c'est presque le genre de retour que j'espérais, je suis aussi très frileux sur les manipulations de données en prod. 
Le scope me semblait relativement restreint, raison pour laquelle je l'ai mis là. 

Au départ j'avais le même script côté rdv-insertion qui était testé donc je l'ai juste déposé ici de la façon qui me semblait la plus cohérente par rapport aux autres scripts similaires, mais j'entends totalement ce que tu dis. 
Je te link pour info la PR initiale que j'avais fait côté rdvi https://github.com/gip-inclusion/rdv-insertion/pull/2341/files
Mais qui ne pouvait fonctionner car elle dépendait de données côté rdvs

Pour info le ticket chez nous semblait relativement scopé : 
> Transférer l'ensemble des usagers gérés dans la catégorie RSA Information collective de l'organisation 29 - avec leurs rendez-vous - vers la catégorie RSA Information collective de l'organisation ID 483.

Cela concerne environ 1000 usagers d'une orga en particulier.

Le besoin était le suivant : Transférer l'ensemble des usagers gérés dans la catégorie RSA Information collective de l'organisation 29 - avec leurs rendez-vous - vers la catégorie RSA Information collective de l'organisation ID 483.

En fait le problème de départ est que le département de la Haute-Savoie a créé une nouvelle organisation pour gérer toutes les informations collectives, mais qu'ils avaient commencé depuis le printemps 2024 à organiser des informations collectives sur une autre organisation.
Donc ils voudraient rapatrier ce delta.

Que préconiserais-tu ?

2024-09-26 08:50 UTC, francois-ferrandis requested changes

2024-09-26 08:50 UTC, francois-ferrandis commented on scripts/transfer_users_and_rdvs_to_other_organisation.rb
> +      rdv.update!(organisation_id: target_organisation.id)
Merci Adrien, je voulais aussi commenter en ce sens, et pour moi on ne peut pas se permettre d'avoir des RDVs liés à un motif d'une autre organisation. J'ai du mal à prédire les complications que pourraient engendrer une telle incohérence de données, mais j'ai la forte intuition qu'on risque de le regretter. J'émets donc une objection à ce que ce code soit utilisé en l'état sur des données de prod. :no_good: :slightly_smiling_face: 

Et pour l'algo de réconciliation, c'est une fonctionnalité qui nous serait peut-être utile dans d'autres cas (fusion de deux orgas lors d'une réorganisation par exemple). Ce qui rend la fonctionnalité difficile à concevoir, c'est qu'elle doit demander à l'admin de faire des choix, et ça nécessite une bonne compréhension se sa part.

2024-09-26 09:13 UTC, francois-ferrandis commented
> Que préconiserais-tu ?

Merci de poser la question, ça m'a incité à réfléchir à une première version. :pray: 

À priori je pense qu'on pourrait implémenter un script qui nous accompagne dans une démarche de transfert de motifs d'une orga à une autre. Ça permet de prendre les décisions de notre côté, mais de maîtriser les risques des opérations de transfert.

Le script prendrait les mêmes input que celui proposé ici (orga source, orga cible, liste de motifs de l'orga source), et pour chaque motif, il faudrait :
1. Détecter si il existe un motif similaire dans l'orga cible, et demander si c'est OK d'utiliser un motif déjà existant dans l'orga cible (si il est structurellement compatible, donc du même `location_type`, `service`, `collectif?`)
2. Une fois qu'on a validé la décision de réutiliser un motif distant ou de simplement déplacer le motif (changer son `organisation_id`), on va choisir ce qu'on fait des plages d'ouvertures. Faut-il supprimer les `motifs_plage_ouvertures` existants pour un motif, ou faut-il re-créer une plage d'ouverture dans l'orga distante ?
3. Concernant le déplacement de RDVs, le script pourrait demander si on veut le faire ou non, mais si dans le cas présent, on veut le faire, donc peut-être que c'est pas nécessaire.

Au vu de la complexité de la tâche (notamment le cas des plages d'ouverture), je finis par me demander si il ne vaut pas mieux faire les choses à la main pour ce besoin particulier. Mais peut-être que pour faire les choses à la main on va avoir quand-même besoin de code qui nous aide à réfléchir. :thinking: 

C'est peut-être une envie personnelle, mais j'ai l'impression que c'est une bonne occasion de pair-programmer. :brain: :brain:

2024-09-27 07:25 UTC, Michaelvilleneuve commented
Avec plaisir pour en discuter avec toi @francois-ferrandis, merci d'avoir proposé 🙏

2024-10-17 12:23 UTC, closed without merging