Limitation des requêtes de l'ants
betagouv/rdv-solidarites.fr pull request #4728
Opened 2024-10-17 15:47 UTC by victormours

Closes #XXXX

Review app : https://demo-rdv-solidarites-prXXXX.osc-secnum-fr1.scalingo.io/

# Contexte

Décrire le pourquoi des modifications

# Solution

Expliquer les choix techniques

# Checklist

- [ ] Extraire dans d'autres PRs les changements indépendants, si nécessaire
- [ ] Préparer des captures de l’interface avant et après

## Captures d'écran

Avant | Après
:- | -:
_mettre un screenshot ici_ | _et ici_

2024-10-18 07:02 UTC, adipasquale approved these changes
🙇 merci d’avoir pris le temps de faire cette PR ! je vais déployer d’ici peu

2024-10-18 07:02 UTC, adipasquale commented on app/controllers/api/ants/editor_controller.rb
> +      start_date = Date.parse(params[:start_date])
nitpick mais il n’y a pas besoin de re-parser start_date ici on pourrait faire 

`date_range = date_range[0]..(date_range[0] + 1.month)`

2024-10-18 07:02 UTC, adipasquale commented on app/controllers/api/ants/editor_controller.rb
> +      motif_creneaux = creneaux(lieu, motif, date_range)
au passage, non lié à cette PR, je réalise que la méthode `creneaux` mériterait d’être inlinée ici : 

- il y a une variable locale `creneaux` dans cette méthode qui est ambigue avec la méthode d’instance
- la méthode ne fait quasiment que passer les paramètres à `CreneauxSearch::ForUser` je pense que ce niveau d’indirection n’aide pas

je vais proposer ça dans une autre PR

2024-10-18 07:38 UTC, francois-ferrandis requested changes

2024-10-18 07:38 UTC, francois-ferrandis commented on app/controllers/api/ants/editor_controller.rb
> +    if lieux.count > 1 && (date_range.begin + 1.month > date_range.end)
Attention le comparaison est dans le mauvais sens on dirait ! 

Petite spec ? :upside_down_face:

2024-10-18 07:38 UTC, francois-ferrandis commented on app/controllers/api/ants/editor_controller.rb
> +      start_date = Date.parse(params[:start_date])
J'ai aussi un nitpick sur la lisibilité globale de ce nouveau code. Je trouve qu'on manipule surtout les date de début et de fin, plutôt qu'un range, dont on a seulement besoin à la dernière ligne.

Je pose donc ici un essai de simplification syntaxique, prends ce que tu veux. :wink: 

```ruby
start_date = Date.parse(params[:start_date])
end_date = Date.parse(params[:end_date])

# Si l'ANTS nous demande de calculer des disponibilités pour plusieurs mois pour plusieurs lieux, on risque de faire un timeout
# On limite donc au mois à venir, et on espère bientôt pouvoir se passer de cette limite
if lieux.count > 1 && end_date > 1.month.after(start_date)
  end_date = 1.month.after(start_date)
end

render json: lieux.where(id: meeting_point_ids).to_h { |lieu| [lieu.id, time_slots(lieu, params[:reason], start_date..end_date)] }
```

2024-10-18 08:01 UTC, adipasquale commented on app/controllers/api/ants/editor_controller.rb
> +    if lieux.count > 1 && (date_range.begin + 1.month > date_range.end)
wow bien vu 😓 effectivement il faut qu’on rajoute une spec.

je vais temporiser le deploy de cette PR dans tous les cas car mes tests là tout de suite pour Dammartin et Le Mesnil Amelot semblent fonctionner sur le site de l’ANTS. Peut être que les dernières améliorations ont déjà débloqué la situation

2024-10-18 08:05 UTC, adipasquale commented on app/controllers/api/ants/editor_controller.rb
> +      start_date = Date.parse(params[:start_date])
trop fort @francois-ferrandis c’est 10x plus lisible

2024-10-21 11:19 UTC, victormours commented
Merci beaucoup François pour la review ! 🙏 C'est clairement des modifs à faire si on veut merger ça.
Comme le dit Adrien, on a l'impression que les améliorations faites sur https://github.com/betagouv/rdv-service-public/pull/4729 permettent de ne pas avoir besoin de cette optimisation pour le moment, donc je vais fermer la PR, et on pourra revenir dessus si les problèmes de perfs le justifient à nouveau.

2024-10-21 11:19 UTC, closed without merging