Alternate duplicate users suggestions
betagouv/rdv-solidarites.fr pull request #844
Opened 2020-08-18 15:11 UTC by yaf

- Lien vers Trello Sentry
- (Description de la fonctionnalité ou du bug)
- (Description du code de la PR)
- checklist avant review: 
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touched inutilement, debug logs qui trainent...).
- [ ] Attendre que les tests soient verts sur la CI

2020-08-26 07:09 UTC, adipasquale requested changes
Je pense que c'est une approche intéressante de stocker dans la DB les suggestions de doublons et de les recalculer lors des updates de users mais qu'on ne peut pas l'utiliser telle quelle (avec une seule nouvelle colonne dans la table users) principalement pour une raison :
- ce n'est pas scopé par orga or on veut afficher des suggestions pour l'orga courante de l'agent

et en autres soucis moins graves avec cette solution :
- un usager peut avoir plusieurs suggestions de doublons, c'est un peu dommage de se limiter à un seul
- les suggestions ne sont pas triées par score à l'affichage
- je pense que tu peux avoir le cas `user1.potential_duplicate = user2 && user2.potential_duplicate = user1` et donc voir deux suggestions identiques juste désordonnées avec cette solution. On pourrait améliorer pour éviter ça dans la solution actuelle.

Une solution potentielle au problème de scope par orga serait de ne pas modéliser ça par une seule colonne dans la table users, mais une nouvelle table : 
```
user_duplicate_suggestions
user1_id | user2_id | organisation_id | score | created_at | updated_at (| deleted_at)
```

(le deleted_at permettrait eventuellement dans un second temps aux agents de marquer des suggestions comme fausses)

2020-08-26 07:09 UTC, adipasquale commented on app/services/mark_first_potential_duplicate_service.rb
> +    user.organisations.each do |organisation|
je pense que c'est risqué car ca va chercher dans n'importe quelle orga ou est l'utilisateur. donc si en tant qu'agent je suis connecté sur l'orga O1 je vais voir des doublons potentiels avec des usagers d'orgas O2 et O3 ... je ne pense pas que ce soit acceptable et je ne vois pas comment corriger ca en utilisant une seule colonne dans la table users malheureusement

2020-08-27 09:05 UTC, yaf commented
>  ce n'est pas scopé par orga or on veut afficher des suggestions pour l'orga courante de l'agent

C'est un oublie effectivement !


>  un usager peut avoir plusieurs suggestions de doublons, c'est un peu dommage de se limiter à un seul

Je me suis dit que c'était déjà pas mal de faire comme ça. J'ai hésité entre les deux options. Je me suis dit que de toute façon, les agents corrigeront un par un les usagers, et non en groupe. Ce qui pourrait être fait (que je n'ai pas fait il me semble), c'est déclencher la recherche de doublon après une fusion (sur l'usager mergé). Ça permettrais de le refaire apparaitre s'il y a un autre doublon potentiel.

>  les suggestions ne sont pas triées par score à l'affichage

Un oubli.

> je pense que tu peux avoir le cas user1.potential_duplicate = user2 && user2.potential_duplicate = user1 et donc voir deux suggestions identiques juste désordonnées avec cette solution. On pourrait améliorer pour éviter ça dans la solution actuelle.

Je suis preneur !

> Une solution potentielle au problème de scope par orga serait de ne pas modéliser ça par une seule colonne dans la table users, mais une nouvelle table :
> 
> user_duplicate_suggestions
> user1_id | user2_id | organisation_id | score | created_at | updated_at (| deleted_at)
> 
> (le deleted_at permettrait eventuellement dans un second temps aux agents de marquer des suggestions comme fausses)

Je voulais éviter de créer une nouvelle table, mais c'est peut-être le mieux oui. Ça permettrais aussi de faire une liste plus facilement (par rapport au point évoquer de la suggestion unique vs une liste).

Comment souhaites tu qu'on procède ?

Pour moi, cette PR est la mienne autant que la tienne :) On reprend le travail ensemble dessus ?

2020-08-27 09:27 UTC, adipasquale commented
je ne vois pas d'autres solutions au probleme de scoping à l'orga que l'introduction d'une table supplémentaire. est-ce que tu as une autre piste ? 

Et pour le tri par score comment penses-tu corriger sans une autre table ? ca implique de rajouter une colonne dans la table user a coté de ton nouveau champ j'imagine ? 

Et avec plaisir pour continuer a bosser sur cette feature mais je suis mitigé sur la bonne direction a prendre. 

## Direction 1 - stocker en DB (cette PR 844) : 

🟢 + pérenne 
🟢 + évolutif
🛑 j'ai peur qu'il reste pas mal de travail pour arriver a une solution satisfaisante : 
  - correction des pbs identifiés (avec remodelisation db)
  - verifier les edge cases pour s'assurer que les suggestions sont bien recalculées aux bons endroits
  - tester sur les données de prod
  - implementer la population initiale du champ 
🛑 risque de generer beaucoup de jobs et le delayed job actuel ne m'inspire pas du tout confiance
🛑 risque d'etre un petit poids pour les evolutions futures, il faudra s'assurer de ne pas introduire de trou dans la raquette dans le re-declenchement du calcul des suggestions

## Direction 2 - version scroll infini (autre PR): 

🟢 deployable tout de suite sans travail supplementaire (je crois)
🛑 - évolutif
🛑 scroll infini : JS un peu hacky
🛑 scroll infini : UI incoherente avec le reste de l'appli

Est-ce que tu partages cet état des lieux @yaf ? N'hésite pas a completer

Je ne me rends pas trop compte de l'importance de cette fonctionnalité mais j'aurais tendance à dire que la direction 2 si elle est effectivement deployable telle quelle suffit pour la V0 de cette feature et qu'on verra si on souhaite investir plus de temps plus tard.

2020-08-27 16:06 UTC, yaf commented
Je pense que tout y est.

Peut-être que je reformulerais les cas à travailler du point d'une autre manière

> stop_sign remodelisation db pour utiliser une table plutôt qu'un champ
> stop_sign risque de generer beaucoup de jobs et le delayed job actuel ne m'inspire pas du tout confiance

Sur ce dernier point, j'imagine que nous pourrions essayer de le faire en direct ? Après tout, c'est pas une combinatoire dans cette approche, mais uniquement un usager versus les autres de l'orga. C'est peut-être faisable sans passer par DelayedJob ?


> implementer la population initiale du champ

Je pense que pour le point il n'y a rien à faire justement. On peut laisser le temps remplir le champ (ou la table du coup). Rien ne presse.


> stop_sign risque d'etre un petit poids pour les evolutions futures, il faudra s'assurer de ne pas introduire de trou dans la raquette dans le re-declenchement du calcul des suggestions
> stop_sign verifier les edge cases pour s'assurer que les suggestions sont bien recalculées aux bons endroits
> stop_sign tester sur les données de prod

Pour moi, ces points sont valable sur tout ce qu'on fait tout le temps. 
J'essaie d'avoir des tests auxquels je fait confiance pour détecter ce genre de problème. 
Le poids sur les évolutions futures, ça fonctionne aussi pour le hacky JS ou des trucs dans le genre de toutes les features.

Je crains d'avoir écrit quelque chose qui pourrait être interprété comme « je défends ma PR ». C'est sans doute un peu le cas. Je suis très géné par :

> stop_sign scroll infini : UI incoherente avec le reste de l'appli

D'où mon insistance. Je crois que je préfèrerais qu'on ne fasse rien plutôt qu'ajouter un truc incohérent dans une appli où c'est déjà pas super top niveau ergonomie :-/

Si on trouve un moyen de rester dans l'esprit existant avec le calcul à la volé, ça me conviens.

2020-08-31 13:17 UTC, closed without merging