Authorise tous les motifs pourl'admin
betagouv/rdv-solidarites.fr pull request #881
Opened 2020-09-14 08:46 UTC by yaf

https://trello.com/c/rMGykJTv/1071-tous-les-motifs-de-lorganisation-pour-un-admin

Élargir la liste des motifs quand on est sur la prise d'un rendez-vous par une personne ayant les droit administrateur (et donc une visibilité sur tout les motifs).

2020-09-14 09:39 UTC, adipasquale requested changes
j'ai noté ce qui me semble etre une erreur et bloquant sur le scope

en non bloquant mais cool a avoir je pense que ca serait pas mal d'afficher un prefixe ou un suffixe avec le nom du service dans l'etape de selection du motif du tunnel de RDV agent, car sinon avec cette modif les agents admin risquent d'etre perdus : 

<img width="661" alt="Screenshot_2020-09-14_at_11 37 04" src="https://user-images.githubusercontent.com/883348/93070157-cdf63b80-f67e-11ea-9cf1-0ec9e2152ea0.png">

2020-09-14 09:39 UTC, adipasquale commented on app/models/motif.rb
> +                       elsif agent.admin?
je pense que cette condition devrait etre en premier car un agent secretaire peut etre admin

2020-09-14 17:03 UTC, yaf commented on app/models/motif.rb
> +                       elsif agent.admin?
J'avais oublié ce cas. Merci

2020-09-14 17:05 UTC, yaf commented
> en non bloquant mais cool a avoir je pense que ca serait pas mal d'afficher un prefixe ou un suffixe avec le nom du service dans l'etape de selection du motif du tunnel de RDV agent, car sinon avec cette modif les agents admin risquent d'etre perdus :

J'ai peur de favoriser les agents admin. Ça va polluer les autres. Et même, certains admin le sont sur des orga mono-service. Bref. C'est un point intéressant, mais je pense que nous allons attendre qu'une personne en parle pour le mettre en place.

2020-09-15 07:33 UTC, adipasquale approved these changes

2020-09-15 09:22 UTC, merged