Identification creation usager tunnel rdv
betagouv/rdv-solidarites.fr pull request #924
Opened 2020-10-15 08:06 UTC by yaf

- Lien vers Trello Sentry
- (Description de la fonctionnalité ou du bug)
- (Description du code de la PR)
- checklist avant review: 
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touched inutilement, debug logs qui trainent...).
- [ ] Attendre que les tests soient verts sur la CI

2020-10-19 10:08 UTC, adipasquale requested changes
👍 c'est top comme amélioration du tunnel

j'ai noté pas mal de petits commentaires non bloquants, je te laisse choisir ce que tu veux modifier ou non.

En bloquant je note deux choses seulement : 
- les deux `skip_before_action` dans le rdvwizardstepscontroller me semblent dangereux, il faut au moins les appeler dans la branche else
- le `resource: User.new` dans le template empeche d'afficher les erreurs dans le formulaire je pense

2020-10-19 10:08 UTC, adipasquale commented on app/controllers/users/rdv_wizard_steps_controller.rb
> +  skip_before_action :authenticate_user!, only: :new
je ne suis pas fan de ces deux skip_before_actions, ils ne sont pas rappelés dans la deuxième branche du `unless user_signed_in?`, j'ai peur que ca ait des petites implications de sécurité. 

Je te propose un petit refacto: sans modifier la methode `new` ni skipper des before actions, mais simplement en rajoutant une `before_action` en tout premiere avec `prepend_before_action`. J'ai testé et ça a l'air de se comporter pareil. 

```diff
diff --git a/app/controllers/users/rdv_wizard_steps_controller.rb b/app/controllers/users/rdv_wizard_steps_controller.rb
index 9437c1db..8ab16025 100644
--- a/app/controllers/users/rdv_wizard_steps_controller.rb
+++ b/app/controllers/users/rdv_wizard_steps_controller.rb
@@ -2,15 +2,9 @@ class Users::RdvWizardStepsController < UserAuthController
   RDV_PERMITTED_PARAMS = [:starts_at, :motif_id, :context, user_ids: []].freeze
   EXTRA_PERMITTED_PARAMS = [:lieu_id, :departement, :where, :created_user_id, :latitude, :longitude, :city_code].freeze
 
-  skip_before_action :authenticate_user!, only: :new
-  skip_before_action :set_paper_trail_whodunnit, only: :new
+  prepend_before_action :redirect_to_new_session_with_rdv_params, only: :new, if: -> { !user_signed_in? }
 
   def new
-    unless user_signed_in?
-      redirect_to session_path(User, params: params.slice(:lieu_id, :motif_id, :starts_at, :step).permit(:lieu_id, :motif_id, :starts_at, :step))
-      skip_authorization
-      return
-    end
     @rdv_wizard = rdv_wizard_for(current_user, query_params)
     @rdv = @rdv_wizard.rdv
     authorize(@rdv)
@@ -76,4 +70,8 @@ class Users::RdvWizardStepsController < UserAuthController
                     user_profiles_attributes: [:logement, :id, :organisation_id]
                   ])
   end
+
+  def redirect_to_new_session_with_rdv_params
+    redirect_to session_path(User, params: params.permit(:lieu_id, :motif_id, :starts_at, :step))
+  end
 end
```

2020-10-19 10:08 UTC, adipasquale commented on app/views/users/sessions/new.html.slim
> +        = link_to new_registration_path(resource_name, params: params.slice(:lieu_id, :motif_id, :starts_at, :step).permit!) do
pareil ici : 
- permit et slice sont redondants, on peut juste utiliser permit
- step est superflu

2020-10-19 10:08 UTC, adipasquale commented on app/views/users/sessions/new.html.slim
> +    = render "common/session_form", resource: User.new, resource_name: "user"
pourquoi ce changement ? je pense que ca casse l'affichage des erreurs car tu passes toujours un objet User.new vierge. j'ai testé en local de revert cette ligne et ca a l'air de bien se comporter.

2020-10-19 14:05 UTC, yaf commented on app/controllers/users/rdv_wizard_steps_controller.rb
> +  skip_before_action :authenticate_user!, only: :new
C'est beaucoup plus élégant. J'avais fait un essaie, mais ça ne semblait pas fonctionner. J'avais du raté un truc. Merci !

2020-10-20 08:51 UTC, adipasquale approved these changes
👍  ca aurait été cool de commiter le makefile a part. j'ai noté un test qui me parait partiel aussi. mais ce n'est pas bloquant

2020-10-20 08:51 UTC, adipasquale commented on Makefile
> -install: ## Install or update dependencies
je pense que le makefile a été commité par erreur sur cette branche

2020-10-20 08:51 UTC, adipasquale commented on spec/controllers/users/rdv_wizard_steps_controller_spec.rb
> +      it "redirect to new use session path with parameters" do
tu ne testes pas la presence des params dans la redirection il me semble

2020-10-20 08:53 UTC, yaf commented on Makefile
> -install: ## Install or update dependencies
ah oui, complétement ! Je le retire

2020-10-20 09:08 UTC, merged