retire la rightbar de l'édition de RDV
betagouv/rdv-solidarites.fr pull request #964
Opened 2020-11-13 15:08 UTC by yaf

- Lien vers Trello Sentry
- (Description de la fonctionnalité ou du bug)
- (Description du code de la PR)
- checklist avant review: 
- [ ] reparcourir le code rapidement pour voir les problèmes évidents (fichiers touched inutilement, debug logs qui trainent...).
- [ ] Attendre que les tests soient verts sur la CI

2020-11-16 12:42 UTC, adipasquale submitted a review, later dismissed

2020-11-16 12:42 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> +      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
je pense que ce n'est pas correct, il faut ici gérer le cas d'erreur. Lorsque la sauvegarde ne peut s'effectuer avec succes, il faut reafficher le formulaire edit, pas rediriger. C'est un peu le bazar dans cette action donc il faut reussir a se depatouiller. J'ai préparé un diff mais incomplet. Ce diff : 

- rajoute une erreur a tous les cas dans le modele (a enlever avant de commiter, c'est 
pratique pour tester)
- branche pour rediriger ou render edit dans cette route, mais le linter n'est plus content, a juste titre parce que la complexité de cette methode devient trop elevée, il faut refacto un peu.

```
diff --git a/app/controllers/admin/rdvs_controller.rb b/app/controllers/admin/rdvs_controller.rb
index e42b8763..36b7be7f 100644
--- a/app/controllers/admin/rdvs_controller.rb
+++ b/app/controllers/admin/rdvs_controller.rb
@@ -39,17 +39,24 @@ class Admin::RdvsController < AgentAuthController
     # association does not do it for some reason I could not figure out
     @rdv.cancelled_at = nil if params[:rdv][:status]
     if params[:rdv][:status] == "excused"
-      CancelRdvByAgentService.new(@rdv).perform
-      flash[:notice] = "Le rendez-vous a été annulé." unless request.format.json?
-    elsif @rdv.update(rdv_params)
-      flash[:notice] = "Le rendez-vous a été modifié." unless request.format.json?
+      success = CancelRdvByAgentService.new(@rdv).perform
+      flash[:notice] = "Le rendez-vous a été annulé." if request.format.html?
+    else
+      success = @rdv.update(rdv_params)
+      flash[:notice] = "Le rendez-vous a été modifié." if success && !request.format.html?
     end
     respond_to do |format|
       format.json do
         temporal_status_human = I18n.t("activerecord.attributes.rdv.statuses.#{@rdv.temporal_status}")
         render json: { rdv: @rdv.attributes.to_h.merge(temporal_status_human: temporal_status_human) }
       end
-      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
+      format.html do
+        if success
+          redirect_to admin_organisation_rdv_path(current_organisation, @rdv)
+        else
+          render :edit
+        end
+      end
     end
   end
 
diff --git a/app/models/rdv.rb b/app/models/rdv.rb
index e8bd5d33..9e034b23 100644
--- a/app/models/rdv.rb
+++ b/app/models/rdv.rb
@@ -24,6 +24,7 @@ class Rdv < ApplicationRecord
 
   validates :users, :organisation, :motif, :starts_at, :duration_in_min, :agents, presence: true
   validates :lieu, presence: true, if: :public_office?
+  validate :test_val
 
   scope :not_cancelled, -> { where(cancelled_at: nil) }
   scope :cancelled, -> { where.not(cancelled_at: nil) }
@@ -157,4 +158,8 @@ class Rdv < ApplicationRecord
     # https://github.com/rails/rails/issues/17605
     self[:uuid] = self.class.where(id: id).pluck(:uuid).first if attributes.key? "uuid"
   end
+
+  def test_val
+    errors.add(:base, "test")
+  end
 end

```

2020-11-16 12:43 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> +      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
note : ce comportement est bien pris en charge par le RightBarResponder (c'est en fait géré dans `ActionController::Responder`) donc ça serait une regression si on ne regle pas ce souci avant de merger

2020-11-16 14:21 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
Yes, merci pour ta vigilance, cette aspect m'était sorti de la tête.

Merci pour le bout de patch. Je vais regarder à partir de ce que tu as fait.

2020-11-16 15:38 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
J'aimerais essayer de fabriquer un RdvUpdater à ma manière pour voir. J'imagine que ça aménerais beaucoup de discussion entre nous, et peut-être que c'est une bonne chose ?

2020-11-17 07:24 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> +      format.html { redirect_to admin_organisation_rdv_path(current_organisation, @rdv) }
yes je pense aussi que c'est la partie à extraire ici, ce bout de logique super important n'a pas sa place dans le controlleur 👍

2020-11-20 16:44 UTC, yaf commented
Reprise du code pour extraire une partie de la logique de mise à jour du RDV dans un module RdvUpdater.

C'est aussi une proposition de structure plus light pour les services qui, bien souvent, ne sont ques des fonctions que l'on déguise à coup de [_boilerplate code_](https://en.wikipedia.org/wiki/Boilerplate_code) en objets.

2020-11-23 08:11 UTC, adipasquale requested changes
je n'ai pas testé mais je pense que tu appelles RdvUpdater au mauvais endroit

2020-11-23 08:11 UTC, adipasquale commented on .gitignore
> +.commit_template
pareil, je pense pas que ça ait sa place dans ce .gitignore mais plutôt dans ton gitignore global sur ta machine

2020-11-23 08:11 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> +        if (success_message = RdvUpdater.update(@rdv, rdv_params))
je doute très fortement qu'il faille appeler `RdvUpdater` uniquement pour le format html ? Que se passe-t-il pour le format JSON lorsqu'on update le statut depuis la liste ? probablement rien non ?

2020-11-23 08:12 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +        if (success_message = RdvUpdater.update(@rdv, rdv_params))
Ah mais oui, absoluement :) Merci

2020-11-23 08:12 UTC, yaf commented on .gitignore
> +.commit_template
un raté dans les rebases. Merci

2020-11-23 08:17 UTC, adipasquale commented
@yaf merci pour la proposition de nouveau format d'ecriture des services ! je suis pas sur de voir les avantages , tu peux préciser ce que tu y trouves de mieux ? Dans l'écriture orientée objet, je vois les avantages suivants : 

- permet de découper l'interface publique et privée et d'avoir plusieurs méthodes. ça permet de découper une méthode perform complexe en plusieurs petites méthodes privées. L'interface publique reste uniquement le perform et c'est donc elle qu'on teste, en ignorant l'implémentation interne. 
- permet de partager des variables d'instances entre la méthode publique perform et les sous-méthodes privées plutôt que les passer explicitement à chaque appel. 

et je suis d'accord que parfois c'est plus pratique d'avoir plus d'une méthode publique, pas uniquement perform. C'est pour ça que j'ai commencé les (mal-nommés) `Service Models` dans un dossier a part. Complètement preneur de nouvelles pistes mais je suis pas sûr de voir les avantages d'un module avec des fonctions indépendantes.

2020-11-23 08:35 UTC, yaf commented
Il y a plusieurs aspect qui me gratte un peu sur le style de service que nous avons.

La forme déjà, emprunté à sidekick (la méthode perform sur une instance) alors que ce n'est pas du tout nécessaire. On se retrouve donc avec de l'héritage et du boilerplate code (la méthode initialize qui met les variables dans des attributes, qui ne sont que des variables avec un scope élargi).

L'usage des attributs dans le cas de nos services, ajoute des risques d'effet de bord.  Élargir le scope d'une variable comporte toujours ce risque.

Pour moi, les services sont des fonctions dans lesquel nous passons des objets qui seront transformé (ou d'où on extrait) en un autre résultat. Conceptuellement, c'est plus clair il me semble, et niveau test c'est bien plus facile de tester une fonction qui prend des paramètres et renvoie un résultat plutôt qu'un objet avec des attributs et des paramètres.

Pour l'aspect méthode privé, c'est possible aussi dans un module... Et, j'ai fait un module là, mais nous pourrions faire une classe avec des méthodes de classe, et une zone privée.

Tu évoque bien un des points clef pour moi : c'est plus explicite comme.

Pour moi, service modèles représente, de manière plus ou moins explicite effectivement, des objets dont nous avons besoin, mais qui ne serais pas des objets ActiveRecord, ou des objets persisté. Peut-être que ces objets pourraient être rangé dans le répertoire app/models d'ailleurs ?
Ces objets ont besoin d'attribut. Et c'est la façon pour moi de savoir si je fait un nouvelle objet (non persisté) ou bien un service.

Ici, faire la mise à jour d'un modèle, c'est clairement un service pour moi, et donc une fonction plutôto qu'un objet.
ZoneImportRow est plus un objet effectivement (d'ailleur l'usage d'OpenStruct à l'intérieur est assez évocateur, nous pourrions envisager de créer un vrai objet à un moment).

Par contre, AgentRemoval serait mieux dans une fonction par exemple. 

Peut-être pourrions nous en discuter de vive voix, en regardant chacun des services pour définir ce qui est un objet non persisté ou une fonction ?

2020-11-23 09:09 UTC, adipasquale commented
merci pour la reponse ! Avec plaisir pour en discuter de vive voix.

- Je vois les service objects avec une methode unique `perform` comme des fonctions plus pratiques a manier, mais conceptuellement c'est a peu pres la meme chose : une methode unique, des arguments en entree et un seul resultat en retour. C'est pour ca que c'est important qu'ils aient une seule methode publique.
- le fait que cette methode s'appelle toujours pareil est un detail a la limite, juste pratique a l'usage je trouve. le nom `perform` est en effet peut etre une deformation de l'usage de sidekiq. je crois que l'usage le plus repandu c'est `call` en effet, pour qu'ils puissent etre utilisés comme des lambdas. 
- Le code boilerplate de l'initializer je partage tout a fait que c'est relou. je crois que tous les services font pareil (les stocker en instance vars), donc je serais plutot pour le generiser dans le BaseService
- je suis moins defavorable que toi a l'heritage, je pense qu'il se justifie ici. Rails a cette approche generalement, les controlleurs heritent d'un ApplicaitonController, les jobs d'un ActiveJob::Base etc


je n'ai pas compris en quoi ca elargit le scope de stocker les arguments en instance vars , tu peux detailler ? j'ai le sentiment que c'est pareil que les utiliser dans une fonction, juste que tu peux decouper cette fonction en plusieurs pour la rendre plus lisible. 

tu dis qu'un des points clefs c'est que c'est plus explicite, tu peux preciser ? tu veux dire plus explicite a l'appel `RdvUpdater.update(rdv_params)` versus `RdvUpdaterService.perform_with(rdv_params)` ? Ou bien plus explicite a la lecture du code d'implementation ?

2020-11-23 09:54 UTC, adipasquale submitted a review, later dismissed
👍 bien testé, et très cool le nouveau service et ses tests.

en bloquant je note juste : 
- le fichier tcr
- la suppression du service CancelRdvByAgentService

le reste est du bonus mais je serais quand même bien favorable à déplacer ce service vers un nouveau répertoire

2020-11-23 09:54 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> -      CancelRdvByAgentService.new(@rdv).perform
il me semble que tu supprimes completement l'usage de ce service, est-ce que tu pourrais supprimer le fichier et le fichier de spec?

2020-11-23 09:54 UTC, adipasquale commented on app/views/admin/rdvs/edit.html.slim
> +            = link_to "Retour", :back, class: "btn btn-link"
je pense qu'un lien explicite vers le rdv#show est plus stable et en harmonie avec l'app ici

2020-11-23 09:54 UTC, adipasquale commented on spec/services/rdv_updater_spec.rb
> +      rdv_params = attributes_for(:rdv, :future, agents: [])
je ne connaissais pas attributes_for 👍 par contre j'avoue que ca me met le doute sur ce que ca envoie au service, est-ce que ca serait pas mieux de passer explicitement les attributs ? ce qui echoue ici c'est de passer une liste d'agents vides c'est bien ca ? peut etre que rdv_params = { agents: [] } suffit pour ce cas ?

2020-11-23 09:54 UTC, adipasquale commented on spec/services/rdv_updater_spec.rb
> +      expect(rdv.reload.updated_at).to eq(now)
je crois qu'il faut eviter les comparaisons strictes de dates, une fois stockées dans la db elles perdent un peu de precision, il vaut mieux utiliser `is_within(3.seconds).of(now)` syntaxe approximative

2020-11-23 09:54 UTC, adipasquale commented on tcr
> +(bundle exec rspec spec/services/rdv_updater_spec.rb && git add -A && git commit) || git checkout .
attention je pense que ce fichier a été créé / commité par erreur

2020-11-23 09:54 UTC, adipasquale commented on app/controllers/admin/rdvs_controller.rb
> +    success_message = RdvUpdater.update(@rdv, rdv_params)
en termes de signature c'est un peu bizarre que `success_message` puisse valoir false. peut etre que le service pourrait renvoyer un tuple `success, message` ? ou une struct `{ result, message }` ?

2020-11-23 09:54 UTC, adipasquale commented on app/jobs/send_transactional_sms_job.rb
> +    SendTransactionalSmsService.perform_with(status, rdv, user, **options)
haha yes il fallait le faire les specs crient depuis un moment 👍

2020-11-23 09:54 UTC, adipasquale commented on app/services/rdv_updater.rb
> +module RdvUpdater
est-ce qu'on pourrait isoler ce service des autres ? peut etre dans un repertoire `app/service_modules` ou `app/service_functions` meme si c'est pas idéal ? je pense que ca simplifierait la lecture du code, sinon ce service dénote vraiment des autres par sa structure et son nommage (pas de suffixe Service)

2020-11-23 09:54 UTC, adipasquale commented on app/views/admin/rdvs/new.html.slim
> -- content_for :title do
good call 👍

2020-11-23 10:27 UTC, yaf commented on app/controllers/admin/rdvs_controller.rb
> +    success_message = RdvUpdater.update(@rdv, rdv_params)
à la Go. :thinking: En fait, j'ai hésité à laisser les messages à l'extérieur. Je trouverais ça plus élégant. Ceci dit, il faudrait pouvoir détecter si c'est une mise à jour de rdv ou une annulation.

Peut-être que ça serait possible on renvoie test le status du RDV ensuite ? Ça me semble plus propre, et en terme de responsabilité, ça serait aussi plus élégant.

2020-11-23 10:27 UTC, yaf commented on tcr
> +(bundle exec rspec spec/services/rdv_updater_spec.rb && git add -A && git commit) || git checkout .
ah oui, boulette. Merci pour ta vigilance.

2020-11-23 10:33 UTC, yaf commented on app/services/rdv_updater.rb
> +module RdvUpdater
J'aimerais autant qu'on arrive à trouver une orientation commune, et qu'on fasse un réfactoring (ou pas ?) pour clarifier l'ensemble. 

Si ça ne te conviens pas du tout, je reprend le code pour le mettre dans la forme habituelle avec le perfom et l'héritage. Je propose ça pour changer notre orientation, changer nos « conventions » sur le sujet. Pas pour faire des bouts de code dans mon coin :-/

2020-11-23 10:36 UTC, adipasquale commented on app/services/rdv_updater.rb
> +module RdvUpdater
ca me convient tout a fait d'introduire cette nouvelle maniere de faire les choses, meme si je suis d'accord avec toi qu'il faudrait qu'on harmonise le code a un moment. je trouve que c'est une piste exploratoire interessante, je ne suis vraiment pas contre. Je proposais ce repertoire pour clarifier les intentions, pas du tout pour dire "ca c'est les bouts de code de yannick"  !

2020-11-23 10:44 UTC, yaf commented on app/services/rdv_updater.rb
> +module RdvUpdater
Ok. Ça me conviens dans ce cas. Je note que c'est « temporaire » le temps de finir de se poser des questions et de clarifier une orientation.

Merci :bow:

2020-11-23 14:06 UTC, yaf commented
> tu dis qu'un des points clefs c'est que c'est plus explicite, tu peux preciser ? tu veux dire plus explicite a l'appel RdvUpdater.update(rdv_params) versus RdvUpdaterService.perform_with(rdv_params) ? Ou bien plus explicite a la lecture du code d'implementation ?

Il y a un des deux qui est plus verbeux que l'autre, et dans le code source, c'est un peu similaire. Le boilerplate code crée un détour non nécessaire à mon avis

2020-11-24 14:24 UTC, adipasquale approved these changes
👍 top

je note deux petits points pour le futur :

- il reste une methode `Rdv#cancel` appellée depuis la partie usager, je pense qu'elle est un peu dangereuse car on risque de l'appeler au lieu du RdvUpdater. il faudra reflechir a la supprimer je pense
- il "manque" un breadcrumb sur le rdvs#edit pour un peu d'harmonie avec le reste de l'app

2020-11-24 14:26 UTC, yaf commented
Merci, je note et je m'en occuperais sous peu.

2020-11-24 14:33 UTC, merged