filtre la listes des RDVs avec le lieu
betagouv/rdv-solidarites.fr pull request #982
Opened 2020-11-30 09:41 UTC by yaf

https://trello.com/c/JLi9wazO/581-avoir-une-vue-globale-de-la-journ%C3%A9e-dun-service

Plutôt que de construire une page spécifique, j'ai préféré enrichir la page « liste des rdvs » avec un filtre par lieu.
J'imagine modifier le lien qui est dans le menu pour propose « liste des RDV du jour par lieu » avec un pré-remplissage des filtres. Une page intermédiaire lisant les lieux si jamais l'agent conencté accède à plusieurs lieux.

2020-12-02 08:05 UTC, adipasquale requested changes
je trouve le nouveau filtre lieu sur la liste des rdvs au top
Par contre la nouvelle page intermediaire RdvByLieux#index me paraît bancale. Changer le lien principal dans la colonne de gauche casse le comportement de cet item de menu. ça me paraît un peu bizarre aussi.

Je crois qu'une piste qui me paraîtrait plus intéressante serait d'ouvrir le `lieux#index` à tous les agents (aucun souci de scope pour la lecture) et agrémenter la vue index de liens vers la liste des RDVs. On peut aussi ne pas faire ça tout de suite, et juste rajouter le filtre dans la vue liste des rdvs et voir plus tard. 

Il faudrait aussi probablement découper le ticket en plusieurs car cette PR ne répond pas aux besoins suivants : 
- pas de filtre par service sur la liste des RDVS, donc la vue est filtrée uniquement sur le lieu mais pas sur le service ce qui semble être demandé
- avoir une vue d'ensemble des plages d'ouvertures d'un service à la journée

2020-12-02 08:05 UTC, adipasquale commented on app/views/admin/rdvs/index.html.slim
> +          = f.input :lieu_id, collection: policy_scope(Lieu), label: "Lieux", label_method: :name, input_html: { class: 'select2-input' }, wrapper: "horizontal_form"
ca devrait etre "Lieu" au singulier ici dans le label

2020-12-03 14:15 UTC, yaf commented on app/views/layouts/_left_menu.html.slim
> +          span.ml-1 RDVs du jour par lieu
Est-ce que tu suggères que nous ajoutions un deuxième lien dans le menu du coup ?

2020-12-03 14:17 UTC, adipasquale commented on app/views/layouts/_left_menu.html.slim
> +          span.ml-1 RDVs du jour par lieu
non, je suggere de laisser le lien tel quel et eventuellement rajouter un lien vers lieux#index pour tout le monde avec des liens vers cette pages de liste de rdvs filtrée

2020-12-03 14:21 UTC, yaf commented
> Il faudrait aussi probablement découper le ticket en plusieurs car cette PR ne répond pas aux besoins suivants :
> 
>     pas de filtre par service sur la liste des RDVS, donc la vue est filtrée uniquement sur le lieu mais pas sur le service ce qui semble être demandé
>     avoir une vue d'ensemble des plages d'ouvertures d'un service à la journée
> 

Je pense que c'est le ticket que nous pourrions changer.

Il y a une confusion entre lieu et service. Dans certains département (22, et 14 ?), un service == un lieu. Et c'est bien pour la gestion d'un lieu physique que ce tableau est intéressant.

L'enjeu est de voir comment la journée du lieu va se passer.

Autre piste de compréhension vis à vis de ce point : le tableau suggéré par le 14 (dans la feuille Excel) évoque un service PMI, Sociale et Secrétariat (voir plusieurs sociaux et plusieurs pmi dans le découpage proposé)... C'est donc pour un lieu donnée que c'est intéressant.

Après, ce que nous ne faisons pas ici, c'est travailler le visuel effectivement. J'imagine que c'est une discussion que nous pourrions avoir avec les référentes.

Est-ce que tu souhaites que je modifie le ticket pour préciser ces points ?

Il reste par contre, notre échange sur l'entrée de menu. Je suis assez d'accord avec toi vis à vis de la vue intermédiaire qui me gène beaucoup. Ça serait plus intéressant de la ramener à la vue des lieux (avec une restriction pour l'afficahge des boutons d'action pour les admin uniquement).

Reste à savoir par quelle entrée de menu. Est-ce que l'on en fait une nouvelle ? Une entrée « lieux » ? Ou bien « vos lieux » dans le sous menu de l'agent ?

2020-12-03 14:32 UTC, adipasquale commented
je pense qu'il faut modifier le ticket oui, et eventuellement creer d'autres tickets pour ce que tu ne gardes pas dans le courant. j'ai quand meme l'impression que le pb etait plus large que juste rajouter le filtre de lieu - mais c'est une très bonne 1e étape. après on peut se dire on réduit ce ticket à ça et on verra si ça revient pour le reste ça me va, tu fais comme tu le sens 👌 

pour l'entrée de menu, oui je pense qu'il faut ouvrir la vue lieux aux agents non admin. une piste UX pourrait être de renommer l'item déroulant "paramètres" en Organisation (ou plutôt le nom de l'orga inline) et en dessous des sous items Lieux, Agents, Motifs accessibles à tout le monde. la seule diff pour l'admin c'est qu'il voit potentiellement plus de choses (cross-service) et qu'il peut modifier

2020-12-03 14:46 UTC, yaf commented
J'a intégré les modifications que tu suggère.

Pour le lien, j'ai remis l'entrée « liste des RDV » et j'ai ajouté « mes lieux » dans la zone agent. Pour l'admin, ça fait doublons, mais c'est pas trop génant je crois.
J'ai en tête de déplacer le menu de configuration d'une orga dans une autre zone, comme pour la secto.

Je vais reprendre le ticket pour que ça corresponde à ce que nous avons fait. Au moins sur lapartie solution, en disant clairement qeu c'est une première étape qui nous semble la plus simple à franchir et que si besoin, on pourra questionner l'ajout d'un autre écran plus graphique.

Merci !

2020-12-03 15:05 UTC, adipasquale requested changes

2020-12-03 15:05 UTC, adipasquale commented on app/views/layouts/_left_menu.html.slim
> +            = link_to "Mes lieux",  admin_organisation_lieux_path(current_organisation)
je pense que cet item de menu est mal placé : il concerne l'organisation courante, pas l'usager en général. il faut probablement le sortir de ce sous menu

2020-12-03 15:08 UTC, yaf commented on app/views/layouts/_left_menu.html.slim
> +            = link_to "Mes lieux",  admin_organisation_lieux_path(current_organisation)
Je préfère ne pas le ranger dans un autre sous menu. Je vais le poser dans la liste pour l'instant.

2020-12-03 15:50 UTC, adipasquale requested changes
il y a un fichier de vue qui traine, et si tu mets un nouveau lien vers rdvs#index, il faut probablement mieux gerer le cas ou tu es connecté en tant qu'admin pour pas que tu en voies deux

2020-12-03 15:50 UTC, adipasquale commented on app/views/admin/rdv_by_lieux/index.html.slim
> +- content_for :title do
je pense que ce fichier est un relicat a supprimer

2020-12-03 15:50 UTC, adipasquale commented on app/views/layouts/_left_menu.html.slim
> +          class: ("active" if content_for(:menu_item) == "menu-rdvs-list") \
attention ce n'est pas correct,
aussi, si tu fais un lien hors du sous menu parametres, il faut gerer l'articulation entre les deux. la un agent va voir deux liens qui menent a la meme page, ce qui ne me semble pas terrible en UX. et il ne faut activer qu'un des deux liens quand il y est.

2020-12-03 15:50 UTC, adipasquale commented on spec/form_models/agent_rdv_search_form_spec.rb
> +describe AgentRdvSearchForm do
tres cool d'avoir rajouté une spec 👍

2020-12-03 15:55 UTC, yaf commented
Je pense qu'il y a un autre problème : Les RDV sont filtré par service. Un agent non admin et non secretariat je peux pas voir les RDV d'un autre service.
Il me reste à
- ajouter un filtre sur le calcul du nombre de RDV pour prendre en compte le service
- regarder comment ça réagi avec quelqu'un du secrétariat ou admin.

Je rebasule en draft.

2020-12-03 16:04 UTC, adipasquale commented
bonne remarque @yaf en effet il faut prendre ça en compte 👍

> ajouter un filtre sur le calcul du nombre de RDV pour prendre en compte le service

je pense qu'il faut filtrer via le policy_scope et ca devrait faire le job

2020-12-03 21:21 UTC, yaf commented
Bon, c'est très bizarre du coup quand on est pas du secretariat ou admin. Et ça pose bien la question de séparation de base...

Je crois que ça ira pour le moment. J'ai hate d'avoir un espace où les questions comme cette histoire de séparation pourront être discuté :)

2020-12-07 08:08 UTC, adipasquale commented
👋 tu me diras si tu veux que je re-jette un oeil @yaf

2020-12-07 09:00 UTC, yaf commented
Pour moi c'est bon. J'ai peut-être oublié un truc ou deux ?

Merci de regarder à nouveau !

2020-12-07 09:12 UTC, adipasquale approved these changes
👍 testé sur la review app ça a l'air de bien se comporter avec les policy scopes.

Je noterais bien quelques améliorations à faire d'ici pas trop trop longtemps cependant : 

- changer l'icône du nouvel item de menu à gauche pour qu'il soit différent de celui de la liste de RDV (cf https://fontawesome.com/icons?d=gallery)
- pour les agents non admins, cacher les liens vers les pages lieux#edit et lieux#new . pour l'instant ils vont voir ces liens mais quand ils cliquent ca dit "pas le droit"

2020-12-07 09:14 UTC, yaf commented
ça me semble une bonne idée oui. Je note ces deux points.

Merci !

2020-12-07 09:18 UTC, merged