Feature/hide social fields
betagouv/rdv-solidarites.fr pull request #998
Opened 2020-12-10 08:24 UTC by adipasquale

https://trello.com/c/P1A5StGb/1026-rgpd-filtrer-les-champs-demand%C3%A9s-pour-la-prise-dun-rdv-en-fonction-du-service

# Screenshots

## Tunnel de prise de RDV usagers :

<img width="700" alt="users" src="https://user-images.githubusercontent.com/883348/101740400-0b753400-3ac9-11eb-9c7c-8fdd6ee64488.png">

## Tunnel de prise de RDV admin :

<img width="1623" alt="admin" src="https://user-images.githubusercontent.com/883348/101740381-06b08000-3ac9-11eb-9ff5-e3abf8bbc22d.png">

J'ai rajouté un texte explicatif; j'anticipe que ça ne plaise pas à tout le monde ! 

## détails d'implem

Les pages d'édition et de création d'usager sont inchangés (côté admin et usager)

J'ai mis la responsabilité de savoir quels champs vont pour quels services dans une méthode du modèle parce que j'anticipe qu'on va nous demander des exceptions.

J'ai aussi déjà inclus deux services plutôt qu'un avec un check des noms qui contiennent "social" (case insensitive)

en prod : 
```
irb(main):002:0> Service.pluck(:name).each { puts _1 }; nil
Secrétariat
PMI (Protection Maternelle Infantile)
Service social
CPEF (Centre de planification et d'éducation familiale)
EHPAD
Autonomie
Direction Départementale des Territoires et de la Mer
Démarches juridiques
Service psychologie
SAPHA (Service Senior Ainé Personne Handicapée et Aidant)
Aide Sociale à l’Enfance
Mission insertion
PMI - Centre de Planification Familiale
```

2020-12-10 12:56 UTC, yaf requested changes
J'ai l'impression que ça ne fonctionne pas dans tout les cas.
Peut-être que les admin et le secrétariat sont des cas particulier, mais je vois toujours ces champs quand je suis un agent de PMI

![Capture d’écran de 2020-12-10 13-51-06](https://user-images.githubusercontent.com/42057/101775244-76396600-3aef-11eb-9209-fcd9b721b951.png)
![Capture d’écran de 2020-12-10 13-50-54](https://user-images.githubusercontent.com/42057/101775247-776a9300-3aef-11eb-96c9-5f0f7981cecd.png)

2020-12-10 12:56 UTC, yaf commented on app/controllers/admin/users_controller.rb
> +    @service = Service.find(params[:service_id]) if params[:service_id].present?
J'imaginais que ça pourrait être déduit de l'agent connecté. Pourquoi passer par un paramètre ?

2020-12-10 12:56 UTC, yaf commented on app/controllers/admin/users_controller.rb
> +    @service = Service.find(params[:service_id]) if params[:service_id].present?
et/ou par rapport au motif

2020-12-10 12:57 UTC, yaf commented
Merci d'avoir pensé à mettre un message.

Ce que j'imagine à terme, c'est que le fait de voir ou pas ces champs soit lié à un paramétrage.

2020-12-10 15:49 UTC, adipasquale commented
@yaf comme je vais être absent à partir de ce soir, je te laisse décider si tu souhaites retirer le comportement sur la partie tunnel de RDV admin , ou demander aux référentes ou déployer tel quel, merci !

2020-12-14 08:23 UTC, yaf commented
Je préfère être consistant et afficher les champs de la même manière sur tout les formulaires coté agent.

Nous pourrons reprendre le faire de masquer ces champs (ou plutôt d'avoir la liste des champs à afficher) quand on traitera des accès usager par service... peut-être.

2020-12-21 10:43 UTC, adipasquale commented
okay @yaf j'ai revert le code de la partie admin

2020-12-21 11:01 UTC, merged